### ISSUE TITLE
Menus don't acknowledge $stateParams

### ISSUE THREAD

**Issue by mikepc** [meanjs/mean#1003]
I can't pass the $stateParams into the state of the menu.. I tried injecting it all the way up to where the the addMenuItem function is declared but for some reason it just won't accept the stateparams.  Any ideas?

**Comment by ilanbiala** [comment]
@mikepc can you provide some code and describe this a little more clearly?

**Comment by mleanos** [comment]
@mikepc Feel free to re-open if you still have this issue, and would like to share more details on what you're experiencing.
