### ISSUE TITLE
Eslint dependency

### ISSUE THREAD

**Issue by jloveland** [meanjs/mean#1005]
I was seeing an error in my editor after installing a linter plugin for eslint referring to the fact that I didn't have eslint installed locally. I resolved by installing eslint globally, but I was curious if we should add this to our devDependencies?

```json
"devDependencies": {
  "eslint": "^1.7.1",
```

**Comment by codydaig** [comment]
@jloveland Just curious, what editor are you using?

**Comment by ilanbiala** [comment]
@jloveland what do you mean by a linter plugin?

**Comment by jloveland** [comment]
I am using the Atom editor. I am also using this linter plugin:
https://atom.io/packages/linter-eslint

**Comment by ilanbiala** [comment]
> linter-eslint will look for a version of eslint local to your project and use it if it's available. If none is found it will fall back to the version it ships with.

I don't think we need to include it as a dependency right now, but we probably should for when npm 3.x comes around (I think it removes peerDependencies).

**Comment by jloveland** [comment]
@ilanbiala sounds good, I will close.
