### ISSUE TITLE
MongoDB SCRAM-SHA-1 authentication failed for on mean-dev fro client 127.0.0.1;

### ISSUE THREAD

**Issue by wang3g** [meanjs/mean#1010]
Hi, I just cloned and installed a fresh MEAN.js from Github into my brand new iMac mini. Everything went well until the server starts running, I got the following error message:

Running "concurrent:default" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    Running "watch" task
    Waiting...
    [nodemon] v1.3.8
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: server.js config/**/*.js modules/*/server/**/*.js
    [nodemon] starting `node --debug server.js`
    Debugger listening on port 5858
   
    Could not connect to MongoDB!
    { [MongoError: Authentication failed.]
      name: 'MongoError',
      message: 'Authentication failed.',
      ok: 0,
      code: 18,
      errmsg: 'Authentication failed.' }

On MongoDB terminal, I can see the following error message:
2015-10-20T14:16:30.437+1100 I NETWORK  [initandlisten] connection accepted from 127.0.0.1:56532 #55 (5 connections now open)
2015-10-20T14:16:30.448+1100 I ACCESS   [conn51] SCRAM-SHA-1 authentication failed for  on mean-dev from client 127.0.0.1 ; BadValue Incorrect SCRAM-SHA-1 user name: n=
2015-10-20T14:16:30.449+1100 I ACCESS   [conn52] SCRAM-SHA-1 authentication failed for  on mean-dev from client 127.0.0.1 ; BadValue Incorrect SCRAM-SHA-1 user name: n=
2015-10-20T14:16:30.449+1100 I ACCESS   [conn53] SCRAM-SHA-1 authentication failed for  on mean-dev from client 127.0.0.1 ; BadValue Incorrect SCRAM-SHA-1 user name: n=
2015-10-20T14:16:30.450+1100 I ACCESS   [conn54] SCRAM-SHA-1 authentication failed for  on mean-dev from client 127.0.0.1 ; BadValue Incorrect SCRAM-SHA-1 user name: n=
2015-10-20T14:16:30.450+1100 I ACCESS   [conn55] SCRAM-SHA-1 authentication failed for  on mean-dev from client 127.0.0.1 ; BadValue Incorrect SCRAM-SHA-1 user name: n=

Below are some relevant info:
1) "mongoose": "^4.0.6",
2) "connect-mongo": "~0.8.1",
3) MongoDB version: 3.0.7, installed as per https://docs.mongodb.org/manual/tutorial/install-mongodb-on-os-x/
4) OS:  OS X Yosemite 10.10.5
5) node: v4.2.1

Did I miss anything? Please help. Thanks in advance.
Jack

**Comment by mleanos** [comment]
@wang3g Could be related to https://github.com/meanjs/mean/pull/1009

Try setting mongoose to version 4.1.11 by updating your *package.json* to use `"mongoose": "4.1.11"`. If that does indeed fix the issue for you, please report it back to the above PR & it will further confirm the fix.

**Comment by wang3g** [comment]
Thank you soooo much! The problem is gone after updating mongoose to 4.1.11.

**Comment by fellyralph** [comment]
I have the same problem am using mean.js,how can I update mongoose to 4.1.11?
do we have to only modify package.json? changind 4.0.6 to 4.1.11

**Comment by wang3g** [comment]
What I did is
npm install mongoose@4.1.11 --save.
That is it.

**Comment by fellyralph** [comment]
@wang3g  thnks a lot ,it worked!!

**Comment by wang3g** [comment]
Good to hear.

**Comment by withlovee** [comment]
had the same problem. fixed with "mongoose": "4.1.11" thanks!

**Comment by joops** [comment]
For the benefit of anybody else coming across this I had the same issue running mongoose v4.2.1 after a npm update.

In my case downgrading via npm install mongoose@4.1.11 --save also fixed the problem - many thanks to @wang3g!

**Comment by YaTaras** [comment]
updating mongoose to v4.1.11 helped me too. Thanks!

**Comment by mleanos** [comment]
@wang3g @withlovee @YaTaras @fellyralph FYI, Mongoose version 4.2.3 introduced a fix to this issue. This project was updated to use this version, in this commit https://github.com/meanjs/mean/commit/09bc727fdff3fe098e767bfc421724fd7bd8afe6

I haven't experienced any issues with this the Authentication after this version upgrade. It seems stable to me. I'd recommend bumping to this version, as it introduced other fixes, and enhancements as well.
