### ISSUE TITLE
Yo Sub generator tries to create brand new project

### ISSUE THREAD

**Issue by Dave3of5** [meanjs/mean#1013]
When running yo meanjs:crud-module test I get the prompt for creating a new project.

I'm using the meanjs yo sub generator from http://meanjs.org/generator.html#crud-module

I also used yo to create the project in the first place.

**Comment by codydaig** [comment]
This is a generator issue, so post it in that repo. There's already on open issue for this over there. 

However, the sub generators arnt fully built for the new generator yet.

**Comment by Dave3of5** [comment]
Sorry the url I posted sent me back here O-o. Any ideas what the repo is for that generator?

**Comment by codydaig** [comment]
https://github.com/meanjs/generator-meanjs
