### ISSUE TITLE
How to integrate ES6 with this project?

### ISSUE THREAD

**Issue by lvarayut** [meanjs/mean#1017]
First of all, thanks for the great generator. It looks very good for me. I would like to use this generator with ES6. Would it be possible to do so? Is there a ES6 option that I could choose when using yeoman?

**Comment by codydaig** [comment]
@lvarayut On the server side, there is no official support for ES6, however, the master branch is the only branch that's the closest to working for Node 4. If you use that branch and Node 4, then you can use ES6 features.

**Comment by lvarayut** [comment]
Thanks @codydaig. I'll give it a try!

**Comment by vko-online** [comment]
This is not totally true, project needs gulpfile/gruntfile adjustments
