### ISSUE TITLE
gyp ERR! during install

### ISSUE THREAD

**Issue by mahlu** [meanjs/mean#1018]
mahlu@ubuntu:~/Desktop/meanjsMaster$ npm install
    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN install Couldn't install optional dependency: Unsupported

    > bufferutil@1.2.1 install /home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil
    > node-gyp rebuild

    make: Entering directory `/home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil/build'
      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
    make: g++: Command not found
    make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 127
    make: Leaving directory `/home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.19.0-25-generic
    gyp ERR! command "/home/mahlu/.nvm/versions/node/v4.2.1/bin/node" "/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil
    gyp ERR! node -v v4.2.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
    npm WARN install:bufferutil@1.2.1 Exit status 1

    > utf-8-validate@1.2.1 install /home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate
    > node-gyp rebuild

    make: Entering directory `/home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate/build'
      CXX(target) Release/obj.target/validation/src/validation.o
    make: g++: Command not found
    make: *** [Release/obj.target/validation/src/validation.o] Error 127
    make: Leaving directory `/home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.19.0-25-generic
    gyp ERR! command "/home/mahlu/.nvm/versions/node/v4.2.1/bin/node" "/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate
    gyp ERR! node -v v4.2.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
    npm WARN install:utf-8-validate@1.2.1 Exit status 1

    > meanjs@0.4.1 postinstall /home/mahlu/Desktop/meanjsMaster
    > bower install --config.interactive=false

**Comment by mahlu** [comment]
I get the same error also after updating g++

**Comment by ilanbiala** [comment]
@mahlu post the package install errors separately on their respective repos. This isn't a MEAN problem as far as I can tell.

**Comment by codydaig** [comment]
https://github.com/npm/npm/issues/9204

It has worked for some people to uninstall node gyp and reinstall. What OS are you running?

**Comment by mahlu** [comment]
I am on Ubuntu 14.04 LTS 64-bit
Testing against  node v4.2.1 (npm v3.3.10) via nvm.
node-gyp v3.0.3

I have all the correct dependencies installed as instructed by node-gyp: (python, C/C++ compiler, make). I tried uninstalling and reinstalling node gyp but nothing is changing.
The odd thing is this is happening only when I try to npm install meanjs.

I tried to remove the node_modules folder and run npm install again and then tried against node v0.12.7.
Here are the logs:

## using v4.2.1 (npm v3.3.10)

mahlu@ubuntu:~/Desktop/meanjsMaster$ npm install
    npm WARN install Couldn't install optional dependency: Unsupported
    npm WARN install Couldn't install optional dependency: Unsupported

    > bufferutil@1.2.1 install /home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil
    > node-gyp rebuild

    make: Entering directory `/home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil/build'
      CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
    /home/mahlu/Desktop/meanjsMaster/node_modules/.bin/touch: 1: /home/mahlu/Desktop/meanjsMaster/node_modules/.bin/touch: Syntax error: "(" unexpected
    make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 2
    make: Leaving directory `/home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.19.0-31-generic
    gyp ERR! command "/home/mahlu/.nvm/versions/node/v4.2.1/bin/node" "/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/mahlu/Desktop/meanjsMaster/node_modules/bufferutil
    gyp ERR! node -v v4.2.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
    npm WARN install:bufferutil@1.2.1 Exit status 1

    > kerberos@0.0.16 install /home/mahlu/Desktop/meanjsMaster/node_modules/kerberos
    > node-gyp rebuild

    make: Entering directory `/home/mahlu/Desktop/meanjsMaster/node_modules/kerberos/build'
      CXX(target) Release/obj.target/kerberos/lib/kerberos.o
    /home/mahlu/Desktop/meanjsMaster/node_modules/.bin/touch: 1: /home/mahlu/Desktop/meanjsMaster/node_modules/.bin/touch: Syntax error: "(" unexpected
    make: *** [Release/obj.target/kerberos/lib/kerberos.o] Error 2
    make: Leaving directory `/home/mahlu/Desktop/meanjsMaster/node_modules/kerberos/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.19.0-31-generic
    gyp ERR! command "/home/mahlu/.nvm/versions/node/v4.2.1/bin/node" "/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/mahlu/Desktop/meanjsMaster/node_modules/kerberos
    gyp ERR! node -v v4.2.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    npm WARN install:kerberos@0.0.16 kerberos@0.0.16 install: `node-gyp rebuild`
    npm WARN install:kerberos@0.0.16 Exit status 1

    > utf-8-validate@1.2.1 install /home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate
    > node-gyp rebuild

    make: Entering directory `/home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate/build'
      CXX(target) Release/obj.target/validation/src/validation.o
    /home/mahlu/Desktop/meanjsMaster/node_modules/.bin/touch: 1: /home/mahlu/Desktop/meanjsMaster/node_modules/.bin/touch: Syntax error: "(" unexpected
    make: *** [Release/obj.target/validation/src/validation.o] Error 2
    make: Leaving directory `/home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
    gyp ERR! stack     at emitTwo (events.js:87:13)
    gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
    gyp ERR! System Linux 3.19.0-31-generic
    gyp ERR! command "/home/mahlu/.nvm/versions/node/v4.2.1/bin/node" "/home/mahlu/.nvm/versions/node/v4.2.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/mahlu/Desktop/meanjsMaster/node_modules/utf-8-validate
    gyp ERR! node -v v4.2.1
    gyp ERR! node-gyp -v v3.0.3
    gyp ERR! not ok 
    npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
    npm WARN install:utf-8-validate@1.2.1 Exit status 1

    > meanjs@0.4.1 postinstall /home/mahlu/Desktop/meanjsMaster
    > bower install --config.interactive=false

## And now against node v0.12.7 (npm v2.11.3)
**working as expected...**
Only a few warnings which are not a concern right now...

## Let's try with node v4.1.2 (npm v2.14.4)
**Working!**

In the end it looks like my issue is only with node v4.2.1 (npm v3.3.10)

**Comment by codydaig** [comment]
@mahlu Interesting. I'm going to try to duplicate on a Ubuntu 14.04 server myself. Thanks for the report back and glad you got it working.

**Comment by tmilar** [comment]
Had this same problem, node version v4.4.0 , npm 3.8.2

Then installed g++
 `sudo apt-get install g++`

And worked like a charm! :)

**Comment by cloudzombie** [comment]
Don't close this, it still helps people.

**Comment by thalesfsp** [comment]
Don't close this, I'm still having this problem!
