### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#1021]
Anyone opposed to deprecating `forever` in favor of `PM2`?

**Comment by ilanbiala** [comment]
Let's do it!

**Comment by mleanos** [comment]
:+1:

**Comment by lovellfelix** [comment]
+1

**Comment by ilanbiala** [comment]
Just to give us some idea of where we want it, @codydaig depending on how easy it is we may do it in 0.5.0 or a further release.

**Comment by lirantal** [comment]
:+1: definitely

**Comment by gustavodemari** [comment]
:+1:

**Comment by ilanbiala** [comment]
Is anyone willing to take this up in a PR for 0.5.0?

**Comment by lirantal** [comment]
Isn't that more of a deployment config rather than part of the framework?
It's not like we have something runner Forever (the only reference to it is Heruku's Procfile).

What did you have in mind with regards to the PM2 as part of 0.5.0?

**Comment by ilanbiala** [comment]
@lirantal we have a forever task in grunt and gulp for development/production.

**Comment by lirantal** [comment]
@ilanbiala I searched there but I couldn't find it. Where you possibly referring to the generator repo and not the main codebase? Otherwise give me a link.

**Comment by codydaig** [comment]
@ilanbiala I thought we used nodemon for grunt and gulp tasks.

**Comment by ilanbiala** [comment]
Sorry yeah nodemon, but anyway it's some kind of server reloading task. We're using forever in the Procfile.

**Comment by lirantal** [comment]
So is this kind of enhancement even valid? `nodemon` is used when you do development so it can monitor if the server needs to be reloaded and such, it's not really used in production.

And we don't use forever, again that's on the procfile which relates to heroku - again not really project standard for mean.js users.

Usually production users setup pm2 and such as part of their servers setup/build/etc.
I don't see how we fit it into the project

**Comment by ilanbiala** [comment]
@lirantal nodemon, forever, and pm2 should all be usable in production. Setting that up for users would probably be helpful.

**Comment by lirantal** [comment]
IMO the current gruntfile with nodemon starting there with debug mode too is quite  bizarre as normally production nodejs apps won't be running like that.

I do agree that we want to enable users to run nodejs in production mode, and I'm supporting pm2 but there's more to it than just configuring a gruntfile - for example installing pm2.

**Comment by mleanos** [comment]
We can't really account for the many scenarios that exist for deployments. Some users may want to use pm2, and others may want to use something else that suits their needs.

I think the general philosophy with this project has been to create a robust framework, that users can build upon. We shouldn't get too opinionated when things fall outside the scope of the workings of the application itself; which I think this definitely falls outside that scope.

**Comment by lirantal** [comment]
I agree with you, it's what I've been trying to explain. But, I do think there's a place to adopt the good tools, just like we are attempting to slowly replace grunt for gulp, then moving to pm2 is the same movement going on.

And I think it doesn't end in adding pm2 as part of the gruntfile or whatever, it also means some documentation about how to run the app with pm2.

**Comment by mleanos** [comment]
I agree that adding documentation on using pm2 with meanjs would be enough. I don't think it needs to be added as a core feature/tool. Especially, since the only place *forever* is being used is in the *Procfile*, which is used in some deployment environments; for instance Heroku (not sure if any others use it).

**Comment by lirantal** [comment]
Closing this one as I don't think we really need to do anything else here.
PM2 documentation just as anything else is beyond the scope of the project IMO.

**Comment by jpca999** [comment]
so what command do i have to give to run the app via pm2  ( in prod version i.e it should minify the stuff before it run )  ?
