### ISSUE TITLE
Module vs state

### ISSUE THREAD

**Issue by dbelieves** [meanjs/mean#1024]
Hi,

i am a beginner at MEAN.JS. I am a bit confused about few of the things.

Case: i want to create a page which can be opened at url [xxxx.com/post-requirement]
the contents of this page will store data to DB on submit

which thing should i follow:
1) create a module by the name 'post-requirement'
or
2) create a state using ui-router

the second case is easy but because i am working in the 'core' module, the boilerplate did not provide model files from where i can store info into mongodb and i dont how to create them.

please suggest.

**Comment by ilanbiala** [comment]
Please post this on Gitter as this is a question rather than a bug/feature request.

**Comment by dbelieves** [comment]
no room for meanjs on Gitter ?
where do i post ?

**Comment by manpikingillz** [comment]
Post on StackOverflow

On 10/28/15, dbelieves <notifications@github.com> wrote:
> no room for meanjs on Gitter ?
> where do i post ?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/meanjs/mean/issues/1024#issuecomment-151869336


-- 
Twesigomwe Gilbert
Software Engineer
Bsc. Computer Engineering

**Comment by ilanbiala** [comment]
https://gitter.im/meanjs/mean
