### ISSUE TITLE
Object pagination

### ISSUE THREAD

**Issue by 0xNacho** [meanjs/mean#1048]
Hi there.

Is there any pagination system implemented when listing entities?

Thanks!

**Comment by sparshy** [comment]
Yes when admin is viewing all users.

**Comment by 0xNacho** [comment]
Yes, but this pagination is not optimized.
I mean, imagine you have 100.000.00 articles in your MongoDB. By using this pagination, it will request 100.000.000 objects at once.

From my point of view, pagination should load X objects every time you press an index button

**Comment by mleanos** [comment]
@0xNacho You're right. If you need to paginate on a large amount of data, you'll have to take it server-side. You need a route that can fetch the data you want, based on the state of your pagination. 

This is a good discussion. I agree with the recommendation that you should have some sort of criteria, like a date filter, other than you're pagination parameters.

http://stackoverflow.com/a/23640287/2228227

**Comment by lirantal** [comment]
Indeed a good topic.
@mleanos  I'd say we should look into refactoring our code for server-side pagination too.

**Comment by 0xNacho** [comment]
Cool!

**Comment by mleanos** [comment]
@lirantal Sounds like a good idea. I'll take a look at it, after 0.4.2 is released.

**Comment by lirantal** [comment]
Grea!

On Mon, Nov 9, 2015 at 10:43 AM, Michael Leanos <notifications@github.com>
wrote:

> @lirantal <https://github.com/lirantal> Sounds like a good idea. I'll
> take a look at it, after 0.4.2 is released.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/1048#issuecomment-154998036>.
>



-- 
--
Sincerely, Liran Tal

Author
<http://www.amazon.com/Agile-Software-Development-HP-Manager/dp/1484210352/>of
Agile Software Development with HP Agile Manager
Founder and Lead Developer of daloRADIUS <http://www.daloradius.com/>
Blogging at http://www.enginx.com, and tweeting at @liran_tal
<https://twitter.com/liran_tal>

**Comment by 0xNacho** [comment]
How is it going? some progress with this?

what is the release this feature will be added in?

**Comment by sparshy** [comment]
You can use the mongoose-paginate plugin for mongoose, its very simple to integrate, I have done the same. Here is a link to it [mongoose-paginate](https://github.com/edwardhotchkiss/mongoose-paginate)

**Comment by mleanos** [comment]
@sparshy The mongoose-paginate looks promising. However, it only works with Node >= 4.2. We're not quite there yet. I'm planning on looking at some alternatives, and if there's a simple implementation without adding any dependencies.

Does anyone have any suggestions?

**Comment by mleanos** [comment]
@0xNacho Have a look at the PR referenced here. WDYT?

If others could also give feedback on this feature, that would be very helpful.

Key considerations with our server-side paging implementation:
- What we want out of this feature
- Capabilities
- Any special considerations as they pertain to the framework
- Potential pitfalls & possible solutions
- What aspects of the current PR do we like/don't-like

**Comment by 0xNacho** [comment]
Nice work @mleanos !

Two suggestions: 
* What about indexing `createdAt` field on `articles` collection? This should increase read performance.
* Could we avoid the use of `populate` in this case? Avoiding joins in MongoDB we drastically increase performance. Since we only need the `displayName` property, this could be added to the `articles`collection too (and obviusly maintained with possible user updates).

**Comment by mleanos** [comment]
@0xNacho Good feedback. 

I'll look at adding an index for `created`.

As for the `displayName`. Yes, it's editable. Anytime a User updates their profile, the `displayName` field is set to their `firstName` & `lastName`. Avoiding the use of `populate()` in this case would require a bit of changes, and I'm not even sure there would be a viable alternate solution. It could be that we'd do something funky, like fetching each Article's User info after the list has been *resolved*; basically when the Article is loaded in the UI. I'm not sure that would be a wise option.

**Comment by lirantal** [comment]
Closing issue.
