### ISSUE TITLE
Enhancement: Add the ability to add external links to menu service

### ISSUE THREAD

**Issue by eshaham** [meanjs/mean#105]
I couldn't find any way of adding external links to Menus service.
I need this to link to my tumblr blog (blog.mydomain.com) from the main menu.

I thought I might be able to do this by adding another state to my UI Router configuration, but apparently that's not possible.

For the time being, I ended up hard-coding an `<li>` element to the menu's `<ul>` element.

**Comment by lirantal** [comment]
Old issue, closing.
