### ISSUE TITLE
Add a signout route to aid in testing/privacy

### ISSUE THREAD

**Issue by 0x24a537r9** [meanjs/mean#1051]
As far as I can tell, mean.js does not provide a route for signing *out* of an application. While nice for privacy reasons, it's really crucial for testing user-based logic.

**Comment by lirantal** [comment]
@0x24a537r9 there is a signout controller in `users.authentication.server.controller.js` along with a signout route at `/api/auth/signout/`

**Comment by 0x24a537r9** [comment]
Ah, cool, thanks.
