### ISSUE TITLE
"ReferenceError: Promise is not defined" when database seeding is turned on

### ISSUE THREAD

**Issue by zymplsi** [meanjs/mean#1056]
I got this error running the master branch with *MONGO_SEED=true*.
Looks like seed.js or elsewhere is missing `var Promise = require('promise')` but I am not sure where to properly place this code.

**Comment by codydaig** [comment]
@zymplsi What version of node are you running? `Promise` is built into most versions of node.

**Comment by zymplsi** [comment]
I built using the Dockerfile which is pulling 'FROM node:0.10'. You stated in another thread that node 4 is not fully supported. Should I pull from node:0.12 instead?

**Comment by zymplsi** [comment]
node 0.12 has built-in Promises, so I edited the Dockerfile to `FROM node:0.12` and the error goes away when **MONGO_SEED** is set to **true**.

**Comment by ilanbiala** [comment]
@codydaig @zymplsi can we either have a PR fix that or make that change to master for 0.4.2?

**Comment by codydaig** [comment]
@ilanbiala @zymplsi  #1058
