### ISSUE TITLE
How to get and set session 

### ISSUE THREAD

**Issue by quanphan** [meanjs/mean#1059]
Can you help me how to get and set session in mean project 

Thanks

**Comment by lirantal** [comment]
@quanphan can you be more elaborate?

**Comment by 0xNacho** [comment]
I think he is referring to how to get the user session in the back-end.

**Comment by lirantal** [comment]
In that case then it's available in the `req.session` property.
@quanphan you can refer to https://github.com/expressjs/session if you need more info
