### ISSUE TITLE
When run gulp, an error TypeError: plugins.eslint is not a function

### ISSUE THREAD

**Issue by SharkIng** [meanjs/mean#1060]
What is that mean?

**Comment by lirantal** [comment]
@SharkIng did you run `npm install` before to make sure all module are accounted for?

**Comment by SharkIng** [comment]
yeah, npm install without any error, however, when I try to do gulp, it still ask me to install some dependency library again. After I install all the requirement. it give me this error..


BTW, is this not support Node.JS 5? since When i first use 5 and it give me some error so i switch to lower version.

**Comment by lirantal** [comment]
We don't support Node 5 officially, no.
Only recently we've made sure our build pass on NodeJS v4.

**Comment by SharkIng** [comment]
Thanks Lirantai, I am going to try it again with frash provision vagrant and Node 4

I'll let you know if I fall into another problem.

**Comment by codydaig** [comment]
@SharkIng Did downgrading to Node 4 solve your issues?

**Comment by SharkIng** [comment]
@codydaig Thanks for helping. Yes, I install Node v0.12.7 on my new vagrant and it solve the problem. However it still running into some other issues when/after i ran npm install. But none of that are criditcal and I can easlly solve those. So everything is fine now. I am still trying it to see if I can get raid of any issue when Installing MEAN.js, but I think none of those are your problem. It has to be some bug with my development environment.
