### ISSUE TITLE
Grunt Tasks

### ISSUE THREAD

**Issue by ubreddy** [meanjs/mean#1066]
Is it possible to have additional grunt tasks for the following ?

* connect, prism : to make front end work even when backed is offline and for mocking/ recording
* wiredep : wire dependency injection
* html2js : for converting html templates to one js file
* concat : concat js, css files including dependencies
* cdnify : for public bower libraries that get served to browser
* autoprefixer : for custom css files
* filerev : for overcoming browser cache... (not sure if livereload solves this.)
* imagemin / minify : for images

**Comment by lirantal** [comment]
@ubreddy we are trying to move out of  grunt and into gulp, but anyway all of your enhancements are valid and you're welcome to suggest relevant PRs.

**Comment by lirantal** [comment]
Closing issue.
