### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by xacaxulu** [meanjs/mean#1067]
Linux ip-10-45-214-83 4.1.10-17.31.amzn1.x86_64 #1 SMP Sat Oct 24 01:31:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

From master branch on clean ec2 instance with a clean Docker install, a `docker build .` errors out here indefinitely:

Step 8 : RUN npm install
 ---> Running in 069ae3a8b94e
npm WARN package.json meanjs@0.4.2 No README data
npm WARN peerDependencies The peer dependency istanbul@0.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

**Comment by ilanbiala** [comment]
So far I don't see any error, is there more to the stack?

**Comment by xacaxulu** [comment]
That's where it hangs. So far I've made it about 50 minutes in and it's stuck there. I'm not sure how long a docker build should take for this project.

**Comment by codydaig** [comment]
Currently Investigating this issue.

**Comment by xacaxulu** [comment]
@codydaig Thank you. Just to clarify, it is an Amazon Linux AMI and the stack trace has now increased.

npm WARN package.json meanjs@0.4.2 No README data
npm WARN peerDependencies The peer dependency istanbul@0.x.x included from grunt-mocha-istanbul will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! fetch failed https://registry.npmjs.org/utf8/-/utf8-2.1.0.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed https://registry.npmjs.org/after/-/after-0.8.1.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed https://registry.npmjs.org/arraybuffer.slice/-/arraybuffer.slice-0.0.6.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed https://registry.npmjs.org/blob/-/blob-0.0.4.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up
npm ERR! fetch failed https://registry.npmjs.org/base64-arraybuffer/-/base64-arraybuffer-0.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: socket hang up

**Comment by ilanbiala** [comment]
@xacaxulu have you tried configuring the proxy/other connection settings?

**Comment by codydaig** [comment]
@ilanbiala I'm getting the same hang locally as well. Still Investigating further.

**Comment by simison** [comment]
Just tested this and works fine here.

**Comment by mikepc** [comment]
This is definitely a network problem, I believe you've set up the Amazon image behind a VPC that has outbound firewall rules configured.

**Comment by gztitan** [comment]
I meeting same issue too, anyone can help? thanks.

**Comment by simison** [comment]
Sometimes if your network changes, Docker machine doesn't pick up new connection. `docker-machine restart default` (where default is the machine name) would help to that.

**Comment by lirantal** [comment]
Guys, I'm working on updating the Dockerfile appropriately and will need a week or so to wrap things up.

I've actually been working on setting up a docker MEAN.JS compatible setup as well here for the last few days.

@codydaig do you mind if I take this issue as I've already done major progress there?

**Comment by simison** [comment]
@lirantal Cool, I was also learning to use Docker with MEAN setup recently. Collected my studying so far here; https://github.com/simison/docker-nodejs-dev-boilerplate

**Comment by codydaig** [comment]
@lirantal All yours. I was unable to get it working.

**Comment by lirantal** [comment]
The plan is to setup the docker environment so that it's more suitable for a development workflow where you can share files with the host, and so on.
I'll push a new `Dockerfile` and `docker-compose.yml` soon enough to get some feedback.
