### ISSUE TITLE
How to edit mutiple id's in a list of a module

### ISSUE THREAD

**Issue by rohitkumarvinay** [meanjs/mean#1071]
I have a boolean in one of my modules, how do i edit all in the list to true at one go?

**Comment by mleanos** [comment]
These were the first two results when I searched Google with: "angularjs select all checkboxes"

http://jsfiddle.net/deeptechtons/TKVH6/
http://stackoverflow.com/a/27452286/2228227

Either solution should be enough for you to go off of.

**Comment by rohitkumarvinay** [comment]
I Could do so on the angular side, how i save it in the backend?

**Comment by lirantal** [comment]
There isn't such API open by default so you either add your own route and
logic to handle it or you can send a batch of requests, one for each record
ID.
