### ISSUE TITLE
Using both ESLint and JSHint

### ISSUE THREAD

**Issue by feimosi** [meanjs/mean#1072]
Is it a good idea to keep both: ESLint and JSHint in the project? It'll print many duplicate linting errors to the console. Also ESLint haven't been attached to the gulp watchers. And lastly, as an enhancement, there's a great eslint-plugin-angular for linting Angular apps.
Referencing #990

**Comment by lirantal** [comment]
@feimosi do you want to submit a PR to clean it up and add the angular eslint plugin?

**Comment by feimosi** [comment]
@lirantal sure, no problem. Should get rid of JSHint completely?

**Comment by lirantal** [comment]
If jshint is redundant then yes obviously remove it in favor of eslint.

**Comment by codydaig** [comment]
:+1:

**Comment by ilanbiala** [comment]
I think the specific duplicates are just some rules we have in both places. I'm not sure if JSHint is has all the features JSHint has and more though, so that will need to be checked if we want to remove JSHint.

**Comment by feimosi** [comment]
That's the point, ESLint offers the same functionality and even more, so there's no point in using two linting tools. AFAIK it's closely compatible with JSHint, so most of the rules should be there. We just need to do the migration from `.jshintrc` to `.eslintrc`. Preferably also add new rules, including code style, but that may need an additional discussion. 
Also I think it wouldn't be a bad idea to use the 'extending config' feature from ESLint and use someone else's config as the base e.g. well-known Airbnb rules.
What do you say?

**Comment by ilanbiala** [comment]
@feimosi If it doesn't throw errors, that sounds good to me. Otherwise, we'll need to just discuss any changes extending an existing config.

**Comment by lirantal** [comment]
@feimosi we're waiting on that PR from you... :-)
