### ISSUE TITLE
Meanjs seems to scaffold out but with a warning about 'eslint'

### ISSUE THREAD

**Issue by Syferus** [meanjs/mean#1073]
Running Node 0.12 and NPM 2.11.3

My app appears to scaffold without errors but when I try to use grunt to actually run it I get this error:

Running "env:dev" (env) task
Warning: Task "eslint" not found. Use --force to continue.

If I force it it works, after adding two missing packages, 'file-stream-rotator' and 'generate-password' haven't a clue what that was about and it may well be unrelated to the above issue) but I'm unsure how to fix the eslint task not found problem - can I remove it from the grunt file or is there a way to fix it?

**Comment by codydaig** [comment]
@Syferus Is this still an issue?

**Comment by lirantal** [comment]
Closing this old issue down.
