### ISSUE TITLE
Errors from oAuth not passed back to UI

### ISSUE THREAD

**Issue by kokokenada** [meanjs/mean#1074]
The oauthCallback on the server: (modules\users\server\controllers\users\users.authentication.server.controller.js)

    passport.authenticate(strategy, function (err, user, redirectURL) {
    if (err) {
            return res.redirect('/authentication/signin?err=' + encodeURIComponent(errorHandler.getErrorMessage(err)));

tries to pass on the error message with the query string.

However, in the client (modules\users\client\controllers\authentication.client.controller.js)

    // Get an eventual error defined in the URL query string:
    $scope.error = $location.search().err;

there is no sign of the error and the error goes unreported.

An easy error condition to replicate, is creating a user with an email address 'X' and then login with facebook with a user a facebook user also with the address of 'X'.  The server sees the correct error, the client reports nothing.  Errors could also be caused by discrepancies in the Facebook configuration. 

As well as passing the error message back to the user, should the error be logged? If so, is there a better way than console.log()?

**Comment by lirantal** [comment]
@kokokenada , @mleanos unless you wish to propose a PR I'll close this issue.
