### ISSUE TITLE
0.4.x 

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#1077]
Since it seems that 0.5 is going to have some big changes which will require discussion, I created a 0.4.x branch too support bug fixes that come up. @lirantal @ilanbiala @mleanos @jloveland

**Comment by mleanos** [comment]
SGTM! THanks!

**Comment by ilanbiala** [comment]
@codydaig @lirantal did we plan on supporting previous releases? I remember having a discussion about this, and IIRC I thought we would just fix bugs as they come along and release them with the next release. Obviously it's not ideal to push bugs to 0.5.0 so people may experience other changes, but I'm not sure we want to mess with the added complexity of that, because then we have to start resolving conflicts across versions and branches.

**Comment by lirantal** [comment]
Sure though I'm not sure we can easily support back-porting bug fixes (from developer's capacity/resource I mean)

**Comment by codydaig** [comment]
What does it hurt too have the branch there? I'm not saying too dedicate resources too it, but if a bug fix comes up and someone submits a PR for it to the 0.4.x branch, what does it hurt?

**Comment by mleanos** [comment]
I think it will be useful for debugging, and rolling out bug fixes.

With 0.5.0 having a bit more complex development, I'd rather verify/troubleshoot issues on a separate 0.4.x branch.

**Comment by ilanbiala** [comment]
@mleanos and @codydaig I don't disagree with you, but we also have to think about how we handle having those bug fixes in 0.4.x and in master, and what happens with the 0.4.x branch once we decide to stop releasing fixes. Also, how do we decide when? Based on a timeframe, or when the next major release comes out, or something else. I'm open to it, but what I'm looking for is a clear plan of how we are going to go about it that everyone is comfortable with and wouldn't impose too much additional burden on the contributors.

**Comment by codydaig** [comment]
As soon as 0.5 releases, we stop supporting 0.4. As for bug fixes, the 0.4 branch will just accept PRs. If it's something that needs too go into 0.4 and master, then I think there should be 2 PRs.

**Comment by ilanbiala** [comment]
We can try it out. @lirantal any suggestions, or do you want to try what @codydaig mentioned?

**Comment by lirantal** [comment]
we can give it a go. I'm not against, just saying what you did - we are essentially with limited time.
