### ISSUE TITLE
Cluster Help

### ISSUE THREAD

**Issue by mikepc** [meanjs/mean#1084]
Trying to get the cluster module to work with MEANJS, and I keep getting EADDRINUSE.

Has anyone gotten cluster to work with this repo, and if so where do I need to make my isMaster check and then have the forked process listen? It wants to start the whole server up on each fork I'm sure.

This is a really big deal for me, if anyone could help I'd greatly appreciate it.

**Comment by mikepc** [comment]
This is my starting point (server.js)

'use strict';

/**
 * Module dependencies.
 */

var cluster = require('cluster');

// Code to run if we're in the master process
if (cluster.isMaster) {

    // Count the machine's CPUs
    var cpuCount = require('os').cpus().length;

    // Create a worker for each CPU
    for (var i = 0; i < cpuCount; i += 1) {
        cluster.fork();
    }

// Code to run if we're in a worker process
} else {
	var app = require('./config/lib/app');
	var server = app.start();
}

**Comment by mikepc** [comment]
Actually for now I'm just going to spin up multiple docker containers and use a redis server, I really don't want to muck around in the guts of the app too much at this stage.

**Comment by codydaig** [comment]
@mikepc Try running it with PM2's native cluster feature. It's supposed to be able to handle apps like this in cluster mode (I think).

**Comment by codydaig** [comment]
@mikepc Closing this issue. Feel free to reopen if your still stuck.
