### ISSUE TITLE
Use NPM+Browserify/Webpack and remove Bower?

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1087]
(Topic was: "Move Bower modules out from /public/")

It's a slight security issue.

Now Bower libs end up to `/public/lib/**/*` and thus are open to public from the server.

I'd like to be in full control what my server is publishing. This way we might accidentally publish malicious JS _at the same domain_, so we aren't protected from XSS attacks via this.

Related to #1078

**Comment by codydaig** [comment]
@simison What's your proposed fix while still using bower?

**Comment by simison** [comment]
I don't have anything I can suggest as a best practise, but I guess it boils down into:
- symlinking (very error prone)
- bundling needed files into one js also at development (already done at production)
- keeping them under public only for dev and cleaning the folder out for prod
- using `npm main-bower-files`

**Comment by simison** [comment]
...or another way is to push non-Bower way such as NPM+Browserify, but that's another discussion.

**Comment by lirantal** [comment]
a lot of frameworks make `grunt build` create a really production-ready snapshot of the project, such as uglyfing, minifying, etc, but most importantly it creates a `dist/` directory such as:
```
dist/
dist/public
dist/server
package.json
```

which makes this `dist/` directory deployable: you can just copy that to a remote server, run npm install for the modules, and start the server.

what do you think?

**Comment by lirantal** [comment]
@simison if that sounds like a good idea, how about taking this for a PR?

**Comment by codydaig** [comment]
@lirantal @simison :+1:

**Comment by trainerbill** [comment]
I use wiredep in one of my projects and love it.

https://github.com/taptapship/wiredep

Automatically reads the bower file and inserts into the layout page.  So you would just have to move the bower directory and put 2 pieces of code onto the layout.html page.

**Comment by trainerbill** [comment]
@lirantal @codydaig @simison I think this would be pretty easy.  Move the Bower directory out of public, wiredep(), move the files to pubilc/lib, use gulp-inject to layout.html.  I wouldn't want to do this for grunt as well so when is the official move to Gulp?  Doing this would bring breaking changes to using grunt as we would be removing all of the bower packages out of the assets files as well.

**Comment by codydaig** [comment]
@trainerbill I just submitted a PR for the removal of grunt to start discussion around what all needs to be done to officially remove grunt. I think the plan is to complete the migration before 0.5.0. 

I'm indifferent on how we go about this. @simison Are you interested in submitting the PR as discussed earlier?

**Comment by lirantal** [comment]
@trainerbill @simison would you guys like to push further on the wiredep/dist directory build for production environments?

**Comment by trainerbill** [comment]
I think it would be good for ng1, but worthless if you are going to move to ng2 anytime soon.

**Comment by simison** [comment]
I've been looking into this today after I run into some hassle _again_ because of Bower. I really feel like getting finally rid of Bower completely and using something more modern such as [Browserify](http://browserify.org/).

- Use only one package management
- Things don't break so easily when requiring outdated versions
- Safer, no more exposing all the lib files publicly

Just it seems that it would need quite a bit restructuring angular modules/directives/etc around `require()` syntax.

Anyone got experience working with Browserify+Angular? Great examples?

**Comment by lirantal** [comment]
@simison I'm wondering if it's better to work on webpack instead because that seems to be the de-facto for frontend packing these days. I'm concerned we'll just pick browserify which isn't that 2016 and need to refactor all the work again.

**Comment by simison** [comment]
Oh yea totally, I'm not that invested to Browserify-idea. :-) I'll check out Webpack, thanks for pointing that out. Hard to keep up with all these tools!

**Comment by lirantal** [comment]
Javascript Fatigue :)

**Comment by simison** [comment]
I like this a lot: http://angular-tips.com/blog/2015/06/using-angular-1-dot-x-with-es6-and-webpack/

@lirantal This should probably not be for 0.5.0 milestone...

**Comment by lirantal** [comment]
Indeed.

**Comment by lirantal** [comment]
@simison I've been playing around with angular-cli, building a very simple app with it. I think it can make a good resource for our next mean.js revamp with angular2.

Have you had a chance to experiment with ng2 yet?
cc @codydaig @mleanos

**Comment by codydaig** [comment]
I've played around with Angular 2 a little bit, but need to dive deeper. The big question for me is ES6 or typescript? Most angular docs are in Typescript but not plain Javascript.

**Comment by lirantal** [comment]
@codydaig Typescript without a doubt. All the generators are geared towards TS.

**Comment by duncanawerbuck** [comment]
@codydaig @lirantal What's your overall feeling on the likelihood that mean.js will move to Angular 2 in the next 12 months?

I suspect there are many developers new to Angular who will likely only consider Angular 2 solutions.

For me personally, I'm really struggling with whether I should divide my focus between 1 and 2, or just focus on 2.

I'm competent with 1.x, but 2 is simpler and arguably better in all respects (except for the initial webpack or SystemJS initial setup, which can be super scary for beginners).

Just considering the capability of angular-cli and support for observables with rx.js, 2.x has surely got to be the way forward in the long term. What are your thoughts?

**Comment by duncanawerbuck** [comment]
Sorry, just saw https://github.com/meanjs/mean/issues/1666

Pls disregard last comment.

**Comment by simison** [comment]
I think this will come naturally with more fresh ES6/Angular2 codebase.
