### ISSUE TITLE
Serving images from 'public/images' folder does not work

### ISSUE THREAD

**Issue by onemenny** [meanjs/mean#109]
Serving images from 'public/images' folder does not work. 
only after changing express.js to 

``` javascript
    // Setting the app router and static folder
    app.use(express.static(path.resolve('./public')));
    app.use('/public', express.static(path.resolve('./public'))); //<--new line added
```

**Comment by anggigenialdi** [comment]
> Serving images from 'public/images' folder does not work.
> only after changing express.js to
> 
> ```js
>     // Setting the app router and static folder
>     app.use(express.static(path.resolve('./public')));
>     app.use('/public', express.static(path.resolve('./public'))); //<--new line added
> ```

thanks, it works for me
