### ISSUE TITLE
mongolab+meanjs

### ISSUE THREAD

**Issue by skatch** [meanjs/mean#1092]
Hi, I just cloned and installed a fresh MEAN.js .Everything went well until I wanted to connect to mongolab, I got the following error message:
Could not connect to MongoDB!
    { [MongoError: Authentication failed.]
      name: 'MongoError',
      message: 'Authentication failed.',
      ok: 0,
      code: 18,
      errmsg: 'Authentication failed.' }

I am connected with the shell to my mongolab database.
my code in the development.js file : 
module.exports = {
  db: {
    uri: process.env.MONGOHQ_URL || process.env.MONGOLAB_URI || 'mongodb://usera:passa@ds053191.mongolab.com:53194/basename' + (process.env.DB_1_PORT_27017_TCP_ADDR || 'localhost') + '/mean-dev',
    options: {
      user: '',
      pass: ''
    },

Thank you in advance

**Comment by lirantal** [comment]
@skatch  It's not a good idea to share your credentials online on the web so you might want to change these details (even if it's open for localhost only, etc).

Secondly, obviously there's an authentication problem - can you check the hostname, port, username and password you provided are indeed ok? also, please style your code paste so it is readable properly.

**Comment by mleanos** [comment]
@skatch It looks like your concatenating your MongoLab URI with `localhost` & `/mean-dev`.. so your URI would end up in this format...

`mongodb://user:pass@ds0000.mongolab.com:10000/basenamelocalhost/mean-dev`

Try setting a environment variable for your mongolab URI. You can set it at the command line, like this.. `SET MONGOLAB_URI=yourmongolaburi` and then running the application with Gulp/Grunt

**Comment by mleanos** [comment]
Closing, since the OP hasn't responded for quite some time, and the issue seems pretty clear.
