### ISSUE TITLE
Subdomain

### ISSUE THREAD

**Issue by GiankOtarola** [meanjs/mean#1094]
I try to search in the web the possible of create two different projects with the mean js stack, one of them it will be the like www.mysite.com and the second project I want to be a subdomain, like subdomain.mystie.com. But I dont know how I can configure the projects to work like that.

Any idea for help me?

**Comment by codydaig** [comment]
Assuming you want these too be two different apps, you need to clone the repo twice into two different directories, and run these on different ports, and have a load balancer like Nginx to distinguish the two incoming hosts and direct the traffic accordingly.

**Comment by GiankOtarola** [comment]
@codydaig Thanks for the answer, it helps me a lot !

**Comment by codydaig** [comment]
@GiankOtarola Glad I could help!
