### ISSUE TITLE
 Deep subfolders are not included automatically in the index for public/modules/**/**/**/*.js

### ISSUE THREAD

**Issue by estvmachine** [meanjs/mean#1099]
Hi how i can do for make the routine can detect more deep for javascript files in public?.

I got something like this  and its not recognizing:
```javascript
public/modules/users/directives/Authorization/auth.js
```
but recongnize : 
```javascript
public/modules/users/directives/auth.js
```

**Comment by mleanos** [comment]
It looks like you're using an older version of MEANJS; pre 0.4.0.

Try changing this line 
https://github.com/meanjs/mean/blob/v0.3.3/config/env/all.js#L64 to `'public/modules/**/*.js',`

**Comment by estvmachine** [comment]
Thanks!
