### ISSUE TITLE
How to run on https ?

### ISSUE THREAD

**Issue by surendrakumar1992** [meanjs/mean#1111]
Hello Everyone,
I want to try run server js on secure port. I want that every request come on http redirect it https.
Thanks in advance

**Comment by lirantal** [comment]
Hi @surendrakumar1992,

The README clearly explains this: https://github.com/meanjs/mean#running-with-tls-ssl

**Comment by surendrakumar1992** [comment]
hii @lirantal  Thanks for quick response.
I follow this stop but when i trying to access domain.com with http or https, but it's not working. What i have to set environment variable development or  production.

**Comment by lirantal** [comment]
Following READMEs and instructions is a vital part, so please do so. If you find the README lacking then let us know, but all the information is there.

* How are you running your node app? did you go into the relevant `config/env/*` file and toggled the `secure` flag on?
* Did you access the actual port for SSL per the app configuration?
* Can you show us the app startup logs?

**Comment by surendrakumar1992** [comment]
Yes I am updating env like 

secure: {
    ssl: true,
    privateKey: './config/sslcerts/key.pem',
    certificate: './config/sslcerts/cert.pem'
  },

I am sharing command window 

![image](https://cloud.githubusercontent.com/assets/12594740/11913084/1a2c9fb8-a67e-11e5-946c-889509df8ad9.png)

**Comment by lirantal** [comment]
which version of MEAN.JS project are you running?
how are you trying to access the app? because you set port 80, then you
should try https://server-host:80 to force SSL connection on port 80 rather
then 443 by default.


On Sat, Dec 19, 2015 at 3:00 PM, surendrakumar1992 <notifications@github.com
> wrote:

> Yes I am updating env like
>
> secure: {
> ssl: true,
> privateKey: './config/sslcerts/key.pem',
> certificate: './config/sslcerts/cert.pem'
> },
>
> I am sharing command window
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/12594740/11913084/1a2c9fb8-a67e-11e5-946c-889509df8ad9.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/1111#issuecomment-165982643>.
>



-- 
--
Sincerely, Liran Tal

Author
<http://www.amazon.com/Agile-Software-Development-HP-Manager/dp/1484210352/>of
Agile Software Development with HP Agile Manager
Founder and Lead Developer of daloRADIUS <http://www.daloradius.com/>
Blogging at http://www.enginx.com, and tweeting at @liran_tal
<https://twitter.com/liran_tal>

**Comment by surendrakumar1992** [comment]
Okay Now 443 working. If some one access domain.com then what will happen?

**Comment by lirantal** [comment]
you tell me... the app is deployed on your network, I've no idea how you set it up.
did you put a load balancer before the app? if you don't have http forwarding to https then no server will respond on port 80.

**Comment by surendrakumar1992** [comment]
Hii @lirantal ..
I not used any load balancer . I am new with this. I put my code on server and start server on 443 so right now it's working fine with https but not respond with http. Can you please help me?

Thanks in advance @lirantal  :)

**Comment by surendrakumar1992** [comment]
@lirantal  please reply

**Comment by lirantal** [comment]
@surendrakumar1992 you can't expect that if you bind a service to just port 443 it will also bind to port 80, right? if you want to enable port 80 then you need some kind of load balancer device/software that will "proxy" the traffic from port 443 to port 80 and not require SSL.
