### ISSUE TITLE
Meanjs modules (discussion)

### ISSUE THREAD

**Issue by vaucouleur** [meanjs/mean#1112]
It's a discussion entry. I could have missed it, but to the best of my knowledge, this was not addressed explicitly elsewhere, or at least not recently.

Like many, I think that it is a *good* thing to keep meanjs relatively small, and focused on infrastructure aspects ("framework aspects", so to say). I'm very happy with the existing framework (with the exception of the permissions system: IMHO, roles/views associations are not enough for real-life large SPA applications, but it's another debate).

So, a small kernel is good, and it seems to be the consensus. On the other hand, there is also a need to avoid duplicated efforts with respect to commonly needed "extra-functionalities". Hence, modules.  Modules are good: they can be external to the core project, they can compete with each other (in a healthy way), etc.

(Related) Questions:

- Why is there so few meanjs modules ?
- What can be done to address this ?
- Is it due to the project (files/directories) layout ?
- Would adopting another module/component system help ?
- Any modules out-there that are simply missing from the documentation page http://meanjs.org/modules.html ?

**Comment by lirantal** [comment]
Hi @vaucouleur,

I appreciate the discussion, thanks for jumping in.

The reason behind the modules system being so "light" is that MEAN.js really aims at being a framework, and just that. Adding more modules out of the box is ok, but I believe it misses the point where the project itself aims for minimalist and high quality project and not as-many-as-you-can-get modules offering.

This is one of the biggest differences between MEAN.io and MEAN.js - the former aims to be a platform, extensible, pluggable, core API, etc, much like Wordpress or Drupal in Node.js, while MEAN.js aims to be really, very humbly, *just* a framework.

**Comment by vaucouleur** [comment]
@lirantal Thanks for the frank reply.

To me, modules are actually a way to keep the framework minimalist. For example, the "Users Admin" code could be an external module: code that is maintained in an external repository. Hence, it becomes someone else responsibility, and you can focus on the core kernel. There is already quite a lot of support for modules in meanjs, but to the best of my knowledge, those "modules" cannot be deployed and shared independently.

Using all those technologies (angular services/views, npm/bower, etc.).. using all those best practices (proper code dependencies, clean REST interfaces, etc.).. using all those great things that can **enable code reuse**... and at the same time not being able to share or pull a "Users Admin" module.. It feels unfortunate. It feels like we're back to the 90's, merging code around while listening to Bon Jovi. What have we learned ?! :)

I don't want to beat a dead horse. I guess you already made up your mind, you did it your way. I also appreciate that you want to limit the scope of this project and I'm super grateful for the good work that has been done !
