### ISSUE TITLE
Using controllerAs syntax

### ISSUE THREAD

**Issue by iamvanja** [meanjs/mean#1113]
This syntax is recommended as best practices and it actually makes it much easier when it comes to scopes within multiple parent/child directives.
I understand directives with such complexity are beyond the scope of this project, but it might be worth considering using it since the changes are somewhat minimal and it helps developers new to ng to get faster up to speed with the framework.

**Comment by mg1075** [comment]
@iamvanja - f.y.i. - see discussion here:
https://github.com/meanjs/mean/pull/874

**Comment by iamvanja** [comment]
Ah, sorry I missed that. Thanks
