### ISSUE TITLE
angular2.X will be out,the project will be no easy!

### ISSUE THREAD

**Issue by xiaoyang2022** [meanjs/mean#1123]
angular2.X will be out,the project will be no easy!

**Comment by sparshy** [comment]
agree with you i @xiaoyang2022

**Comment by lirantal** [comment]
what is there to agree with?
@xiaoyang2022  I don't understand what you were trying to say.
Do you know when will Angular2 be officially released? 
What will be "no easy"?

It would help if you could actually engage in a valuable discussion and not just comment half a sentence.

**Comment by sparshy** [comment]
@lirantal angular2 beta is out. if u go out n try it they redesigned from base. For starters i dont think it has controllers. Syntax for everything is changed ng-repeat etc.. Say goodbye to $'s there are no $ in angular2. No doubt switching to angular2 will be tough. saw a talk , a guy from angular team mentions if you want to make transition easy, start using directives much.

**Comment by mleanos** [comment]
@sparshy It will be a huge upgrade to move to Angular 2. It's not something that we'll be able to get to anytime soon. I think we're a few major releases away. 

With that said, we're putting a lot of effort into making the framework more modular, and in accordance with best practices; including our use of Angular. As we work toward that goal, we will get closer to having a framework that will be easier to upgrade. 

Any, and all, help is appreciated with these efforts. I haven't read it yet, but there's a good guide for preparing your Angular app for upgrade; I think our adoption of John Papa's Angular styles is a great example of what we can do.

**Comment by mleanos** [comment]
Edit: a few **minor** releases away ;)

**Comment by lirantal** [comment]
@sparshy I don't need an explanation about Angular2, but thanks.
Are you interested in actually helping our here with moving to Angular2 or you only care about commenting? :)

**Comment by xiaoyang2022** [comment]
angular2.X will be easy than 1.x.   because of angular2.x is sported OPP with processed that has a class and more!

**Comment by lirantal** [comment]
Great. Thank you.

**Comment by aralroca** [comment]
Check this: https://github.com/datatypevoid/ng2-mean-webpack

**Comment by mushroomlb** [comment]
is means support angularjs2+?
