### ISSUE TITLE
Gruntfile not being linted

### ISSUE THREAD

**Issue by JulianLaval** [meanjs/mean#1125]
Hi there,

As it stands, the Gruntfile makes use of the Lodash `union` method to specify the ESLint `target`:

`_.union(defaultAssets.server.gruntConfig, defaultAssets.server.allJS, defaultAssets.client.js, testAssets.tests.server, testAssets.tests.client, testAssets.tests.e2e)`

This method only operates on arrays, however, and so the `gruntConfig` property in the default assets  (a string) isn't being added to this union.

May I suggest changing the field in `config/assets/default.js` from `gruntConfig: 'Gruntfile.js'` to `gruntConfig: ['Gruntfile.js']` so that it may be linted as expected?

Happy to submit a PR!

**Comment by codydaig** [comment]
@JulianLaval Go ahead and submit a PR and we'll review!

**Comment by mleanos** [comment]
The proposed fix looks right to me. Thanks.
