### ISSUE TITLE
outdated node-inspector version error -- Failed at the v8-debug@0.4.6 install script 'node-pre-gyp

### ISSUE THREAD

**Issue by keithics** [meanjs/mean#1132]
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
	npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.6
	npm WARN iskwelahan@0.0.1 No repository field.
	npm WARN iskwelahan@0.0.1 No license field.
	npm ERR! Linux 3.19.0-41-generic
	npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
	npm ERR! node v5.4.0
	npm ERR! npm  v3.5.3
	npm ERR! code ELIFECYCLE

	npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the v8-debug package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-pre-gyp install --fallback-to-build
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs v8-debug
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls v8-debug
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /home/user/app/npm-debug.log	

simple fix: change `"grunt-node-inspector": "~0.1.3",` to   `"grunt-node-inspector": ">=0.2.0",`

**Comment by ilanbiala** [comment]
@keithics officially we don't support Node v5 yet, so YMMV when using that version.

**Comment by codydaig** [comment]
@keithics The tests fail on v5. There are some things that need to be done to the framework to be v5 compatible. Not sure exactly what that is yet, but it's on our radar. Your welcome to submit a PR to make those changes!
