### ISSUE TITLE
Alternate MongoDB service for bluemix 

### ISSUE THREAD

**Issue by LadwaAditya** [meanjs/mean#1133]
Is there any alternate way to use mongodb service to deploy the app on bluemix ?

**Comment by codydaig** [comment]
@ryanjbaxter

**Comment by ryanjbaxter** [comment]
@LadwaAditya There are a couple of other options for MongoDB on Bluemix. You can look into using the MongoDB service by Compose.io.  The other option is to go off to MongoLabs and create and account and DB there.  Then create what is called a [user provided service](https://docs.cloudfoundry.org/devguide/services/user-provided.html) containing the URL and credentials to the DB.  I guess technically you can use and MongoDB you want as long as the app can connect to it.  

In either case you need to make sure the entry in VCAP_SERVICES matches what is there when you use the experimental MongoDB service or else the logic in the MEAN app won't find the correct URL and credentials.

**Comment by LadwaAditya** [comment]
@ryanjbaxter Thank you. Will look into it
