### ISSUE TITLE
Nodemon watching 73k+ files - might cause high cpu usage

### ISSUE THREAD

**Issue by mleanos** [meanjs/mean#1140]
When I start the application using Grunt, I receive a message that nodemon is watching over 73k files..

![nodemon-watching-large-amount-of-files](https://cloud.githubusercontent.com/assets/5613734/12366685/8250edba-bb91-11e5-9109-b4d7cf8cf3f1.PNG)

I couldn't find any reason why the watch task should be watching so many files. I double checked all the asset paths in *config/assets/default*. The only directory in the project that has a large amount of files is *node_modules*, which isn't being watched.

Can anyone else confirm this behavior? None of the node packages have changes, other than a couple introduced in recent commits; which shouldn't have any affect over grunt watch.

One other point of confusion is that in *node_modules* there are only about 59k files. That means that the watch is picking up an additional 14k files somewhere. The project doesn't have that many files. It's almost as if the watch is duplicating the amount of files somehow.

**Comment by mleanos** [comment]
Can anyone reproduce this?

BTW, I don't have any such issues with Gulp. I know that we're not looking to *support* Grunt any longer, but this issue should still garner some attention. If it's truly an issue (not just my environment), then it could be a bigger issue at play somewhere.

I don't remember this happening until recently, and the key packages involved haven't been updated for quite some time.

@ilanbiala @codydaig I think this can be labeled as a bug. If nobody can reproduce then we'll close eventually. But the label is helpful.

**Comment by codydaig** [comment]
@mleanos I am unable to duplicate this.
