### ISSUE TITLE
Eslint not erroring out.

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#1141]
As discussed in #1139. Eslint is not throwing errors on the build even though there was errors.

**Comment by lirantal** [comment]
@codydaig this can be closed, right? That #1139 is merged now.

**Comment by lirantal** [comment]
@codydaig when there are eslint errors the livereload just reload the web again, right? I think it's a nodemon/gulp sequence setup because the eslint process does seem to stop there when the an error is found.

Would you like to still tackle this one?
