### ISSUE TITLE
update to angular-bootstrap 1.0

### ISSUE THREAD

**Issue by trendzetter** [meanjs/mean#1142]
Angular-bootstrap 1.0 is out. Would it be desirable for you to update? I created a patch:
https://gist.github.com/trendzetter/c1e7be8bd3e41404fd49

**Comment by codydaig** [comment]
@trendzetter Submit a PR for discussion!

**Comment by trainerbill** [comment]
https://github.com/meanjs/mean/issues/1168

Thoughts?
