### ISSUE TITLE
Define controller mappings in anguar state machine to reduce coupling 

### ISSUE THREAD

**Issue by farajfarook** [meanjs/mean#1148]
To reduce the dependency coupling in between the views and controllers, I believe the better design would be to use the angular state machine to have the mapping of controller towards the view.

*example*
rather than this `<section ng-controller="SettingsController">`
we should use

      .state('settings', {
            url: '/settings',
            templateUrl: 'modules/users/client/views/settings/settings.client.view.html',
            controller: 'SettingsController'
      }

I'm using meanjs to on my project and this is something I did to all the states. It comes handy when i have to use the same view with different controllers. Just a suggestion though.

**Comment by mleanos** [comment]
We're already doing this.. 
https://github.com/meanjs/mean/blob/master/modules/articles/client/config/articles.client.routes.js

Also..
https://github.com/meanjs/mean/blob/master/modules/articles/client/controllers/articles.client.controller.js
https://github.com/meanjs/mean/blob/master/modules/articles/client/views/view-article.client.view.html

I believe the plan is to migrate the Users module, over to the new Angular style-guide. It just hasn't been done yet. That might be a conversation to start.

**Comment by farajfarook** [comment]
Great :+1: . I will create some pull requests when the time permits.

**Comment by mleanos** [comment]
This has been addressed with #1208. Closing this issue. 

@farajfarook Let us know if have any more input/suggestions on this. Thanks.
