### ISSUE TITLE
 Warning - You need to have Ruby and Sass installed and in your PATH for this task to work

### ISSUE THREAD

**Issue by finid** [meanjs/mean#1151]
I recognize that there's a similar issue that appears to have been resolved. But that was [issue 880 on Ubuntu](https://github.com/meanjs/mean/issues/880). This time it's on CentOS 7 and happens when I run `grunt` or `sudo grunt` from a project.

I have Ruby and Sass installed, and in my path, because `echo $PATH` gives:

```
/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/finid/.local/bin:/home/finid/bin
```
And `which ruby` says:

```
/usr/bin/ruby
```

While `which sass` gives:

```
/usr/local/bin/sass
```
What else do I need to do?

**Comment by codydaig** [comment]
What's the error message?

**Comment by finid** [comment]
Here's the full output:

```
Warning: 
You need to have Ruby and Sass installed and in your PATH for this task to work.
More info: https://github.com/gruntjs/grunt-contrib-sass
 Used --force, continuing.
```

**Comment by ilanbiala** [comment]
Are you able to run `ruby` and `sass` from the command line?

**Comment by finid** [comment]
Unfortunately, no, which is strange, because `which ruby` returns the expected result. Same for Sass. For both, I only get a blinking cursor.

Any clues why?

**Comment by ilanbiala** [comment]
Try adding --help after to just get output and not input.

**Comment by finid** [comment]
Ok, I got it now. I got the usage output, so I know I can run both `ruby` and `sass` from the command line.
But the original issue still remains.

**Comment by ilanbiala** [comment]
What's the error itself?

**Comment by finid** [comment]
Well, adding **--help** just prints the usage instructions. Where you expecting an error?

**Comment by ilanbiala** [comment]
Sorry, I meant the actual issue that you're posting about. It seems like this was just a dependency issue.

**Comment by finid** [comment]
Ok, the issue has been fixed. With Ruby and Sass installed, I edited `/etc/sudoers` and modified the line that reads:

```
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
```

To include `/usr/local/bin`, which is the directory path to the Ruby and Sass commands, so that it reads:

```
Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
```
