### ISSUE TITLE
Sign in not working

### ISSUE THREAD

**Issue by rishabh1403** [meanjs/mean#1152]
every time i click the button login , my console shows unknown strategy  local error

**Comment by mleanos** [comment]
What version of meanjs are you using?

**Comment by rishabh1403** [comment]
i am using meanjs 0.4.2 , my os ubuntu 15.10 , node v0.12.7 , mongodb 2.6.9

**Comment by mleanos** [comment]
can you share a screenshot of the console error?

**Comment by rishabh1403** [comment]
![screenshot_2016-01-19_16-29-47](https://cloud.githubusercontent.com/assets/10906358/12445024/029b9ffc-bf88-11e5-9e44-2d30427ab4c1.png)

**Comment by mleanos** [comment]
Can you make sure you have all the necessary NPM modules installed?
```bash
npm install
```
Do you have the *local.js* file in this directory?

**Comment by rishabh1403** [comment]
yes i did npm install many times , i even downloaded it again and did npm install , but still same error

**Comment by ilanbiala** [comment]
Do you have this on GitHub so we can see the project and what it looks like?

**Comment by rishabh1403** [comment]
fixed it , thanks for all your help , somehow my local.js was renamed to locl.js 
Thanks for your help :)
