### ISSUE TITLE
Minifying third party files

### ISSUE THREAD

**Issue by Joe312341** [meanjs/mean#1153]
Hello,

I was wondering what the best approach to minifying all the third party js and css files is.

I tried this approach: https://blog.dylants.com/2014/11/19/bundling-production-assets-for-mean-js/
but Heroku threw an error on the third party minified js file.

Any help is appreciated
Thank you

**Comment by sparshy** [comment]
concat: {
			js:{
				options: {
					  separator: ';\n',
					  stripBanners: true
				},
				src: [src files],
				dest: 'public/dist/vendor.js'
			}

		}

try this.... seprator : ';\n' is important

**Comment by Joe312341** [comment]
Thanks, after testing some more I was able to get it working
