### ISSUE TITLE
Can't access authentication.user._id

### ISSUE THREAD

**Issue by Eswan** [meanjs/mean#1157]
Hello, (and sorry for bad english)

I can access to authentication.user._id when i log in, but if i refresh the page, the _id become undefined.
For example, if i log in and go to the article example module, i can edit / remove the article. If i refresh the page, i can't anymore.
Is it normal ?

Should i use an older meanjs version ?

Thank you

**Comment by mleanos** [comment]
We recently removed the `_id` field from the client-side object that's stored in $window. This was done in an effort to make the framework more secure, and the thwart xss attacks.

If you need to retrieve the user data, and access it from the client-side, there's an route `/api/users/me` that you can query to get the currently logged in user. I would be cautious as to where/how you use the User data on the client. Be mindful of any security considerations.

**Comment by Eswan** [comment]
Ok thank you for your answer, closing the issue.
