### ISSUE TITLE
build admin panel

### ISSUE THREAD

**Issue by markstock7** [meanjs/mean#1158]
if i want to build a admin panel, where should i put this files, /modules/admin  ?

**Comment by vaucouleur** [comment]
@markstock7 I guess it depends on whether you want to create an admin panel for "all things" or just for a single "kind of objects". For example, in the current trunk version the "users admin" code is inside the "users" module -- which a perfectly reasonable choice since it's just there to edit/delete/etc users, and only users. Now, if I were to create an "admin panel" for "all things" (users, articles, etc.), I would create a dedicated module for this.

**Comment by markstock7** [comment]
so，i can creat a module admin，and include folder admin/user，admin/articles，admin/user/client，admin/user/server？


发自我的 iPad

**Comment by vaucouleur** [comment]
@markstock7 You can use the generator to get started with your own module. Alternatively, you can copy the structure of the existing Article module (and adapt the code, obviously).  You could start with a simple module, make sure it's working, and then modify it little-by-little, add tests, etc.

**Comment by mleanos** [comment]
Personally, I prefer to keep my admin features in the modules that I want to administer. For instance, if I wanted to have admin views for Articles, I'd put the admin module there; just like the Users module is setup. 

If you want an admin panel, you could create a module that acts as a Admin dashboard. However, any features that interact with my data beyond mere reporting, I would put them in their respective modules. 

I prefer how this strategy works in terms of architecture, and SOC. If wanted to remove the Articles module, I could just delete the folder & remove any references that other modules, navigation, and configs that might exist for it.

**Comment by mleanos** [comment]
@markstock7 Did this discussion help you decide which option is best for you? Unless you still need clarification on how the Admin feature is implemented in the framework, I think this can be closed.

**Comment by markstock7** [comment]
@mleanos sorry about that. i did help me to figure out a way to do it. thanks so much

**Comment by mleanos** [comment]
Great, glad it helped :) 

What was your solution?
