### ISSUE TITLE
multiple articles at the same time.

### ISSUE THREAD

**Issue by rohitkumarvinay** [meanjs/mean#1162]
How do i create multiple articles at the same time?anyway i can create two or three articles in a single form.?

**Comment by vaucouleur** [comment]
@rohitkumarvinay  This question might be a bit out of the scope of the MEAN.JS project, since it's more of a "general question" about angular etc.   There is many different ways to achieve this by modifying the existing code. Feel free to stop by Gitter to chat about this.

**Comment by mleanos** [comment]
Closing this for now, since it's not really a question about this framework.

@rohitkumarvinay Feel free to re-open, if you run into any limitations in implementing this that is specific to MEAN.JS.
