### ISSUE TITLE
Tests Failing because of Coverage

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#1164]
On recent PRs, coverage is staying the same (0% change), and yet it's still being marked as failing. Do we know what's going on? Did a setting get changed?

@lirantal @ilanbiala ?

**Comment by ilanbiala** [comment]
@codydaig nothing changed that I am aware of, but I made it so instead of blank for "COVERAGE DECREASE THRESHOLD FOR FAILURE", it is now 0.1%, which may avoid the errors we are seeing.

**Comment by codydaig** [comment]
@ilanbiala That seems to be working. Thanks!
