### ISSUE TITLE
Dependency Audit

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#1166]
Per the conversation in #1165. We should do a dependency audit and ensure that all dependencies are `~` to help keep dependencies from bringing in breaking changes.

**Comment by ilanbiala** [comment]
@codydaig do you want to make a PR that switches all dependencies to `~` and I'll take a quick look at it before merging?

**Comment by codydaig** [comment]
@ilanbiala I will tonight when I'm on my personal computer. I don't have my work laptop set-up for mean.js development. I created this as a reminder.

**Comment by ilanbiala** [comment]
:+1:
