### ISSUE TITLE
(discussion) Move from Bootstrap to Angular Material design

### ISSUE THREAD

**Issue by trainerbill** [meanjs/mean#1168]
Anyone worked with this project?

https://material.angularjs.org/latest/

Looks pretty sweet and is supported by Google with native angular directives.  We could drop bootstrap and angular ui bootstrap.

**Comment by trainerbill** [comment]
Forgot to tag some peeps.

@ilanbiala @codydaig @mleanos @lirantal @rhutchison

**Comment by ilanbiala** [comment]
Yep, I've worked with it. Moving UI frameworks isn't really something we are prioritizing now, as most people use MEAN for its backend setup, config, and authentication over its UI.

**Comment by trainerbill** [comment]
@ilanbiala Fair enough.  However I would like to use it in my project so would a PR to update core to use material design be welcome?  It is waaayy more visually appealing than Bootstrap and has native angular directives.  We can leave bootstrap in until the submodules are updated as well which will take more time.  That way we can have smaller PR's and different milestones.  If we want to move to this UI in the future I would rather just do part of it now.  Thoughts?

**Comment by siteshackinc** [comment]
I'd be interesting in helping out. Perhaps I could create a branch for this to happen and help maintain it?

**Comment by trainerbill** [comment]
@siteshackinc Awesome!  Lets do it and see what happens.  I will start a branch and you can pull it and PR to it.

**Comment by siteshackinc** [comment]
@trainerbill I have created the repository already https://github.com/siteshackinc/material-meanjs I will begin uploading a material base locally to it today. Will need to have someone start with a readme, giving credit to current meanjs to keep everyone happy as well as contributors

**Comment by trainerbill** [comment]
@siteshackinc I would rather not fork the project.  From the sounds of it @ilanbiala may be on board, so why don't we just work to get it merged here before making a fork?

**Comment by siteshackinc** [comment]
@trainerbill sounds good. Whatever works best for all of us. My current base of meanjs is way ahead of current meanjs master with enhancements and features as well as dependencies that are up2date and current.

**Comment by trainerbill** [comment]
@siteshackinc Understood.  I took a peek at your fork.  You should submit issues and PR's when you do things like this to enhance the project.  Forking is kind of a last resort.  We could sure use more people contributing with ideas like these.

**Comment by siteshackinc** [comment]
@trainerbill I hear ya :) I've been updating mean with my private app I am building (can find the weblink in my profile) and updating some my enhancement/features with my forked copy

**Comment by trainerbill** [comment]
@siteshackinc Yeah I went down that route too, but its a pain...  So when I have things that I want in my app, like JWT authentication/Material Design/etc, I like to post a discussion topic to see if it would be welcome in the main app.  If so then I PR it to Mean.  I am actually working towards getting all my updates in my private application into Mean as I think it will benefit it as a whole.  My goal is to make it so I can pull in mean updates without effecting my app.  Its a long process, but worth it in the long run as you usually get good collaboration and think of ways to do things that you normally wouldn't

**Comment by trainerbill** [comment]
@siteshackinc Can you join the gitter chat so we can discuss?

https://gitter.im/meanjs/mean

**Comment by siteshackinc** [comment]
@trainerbill ok I am there :)

**Comment by ilanbiala** [comment]
For clarification, I'm not in favor of putting effort into switching UI frameworks at this time. I think our effort is better prioritized to more functionality and a better framework overall than one that looks nicer but does the same thing.

**Comment by mg1075** [comment]
There was already a lengthy discussion on this issue here:
https://github.com/meanjs/mean/issues/369

**Comment by trainerbill** [comment]
@ilanbiala Understood, but I am going to use Material Design in my project and it is easier for me to put it into MEAN first if it is welcomed.  I just don't want to do the work and have it blocked for some reason.  In the trhead @mg1075 linked you seemed to favor Material Design, but put it on the back burner.  I am saying I will do the work, if you would approve it.

**Comment by mg1075** [comment]
@trainerbill - If you read the last set of comments after the discussion was closed, the sentiment was more yes, ngMaterial is a super cool piece of work, but it is an extremely opinionated way to go about building - or rather, _designing_ - your application. 

To quote @mleanos:
> This project [MEAN.JS] isn't trying to solve UI/UX problems; it's strength lies in the back-end, and architecture.

It probably would be cool if the MEAN.JS generator was such that you could opt-in or opt-out of using ngMaterial. _Forcing_ it on users, though, seems harsh.

**Comment by trainerbill** [comment]
@mg1075 understood.  But we currently force bootstrap so its basically the same thing.  I really don't care either way.  I can run with a fork using material design, I just wanted to see if the community wanted to move in that direction, and if so then I would start moving the UX in MEAN.

**Comment by mg1075** [comment]
@trainerbill Indeed, bootstrap is forced on users. From the perspective of styling an app, though, bootstrap allows a lot of freedom in the approaches you can take, while material design is a little more, "there are your options - like it or leave it". That is why I do not see them being equivalent.

**Comment by marianoqueirel** [comment]
@ilanbiala 's Right!

**Comment by mleanos** [comment]
+1 on what Ilan has been saying. There's no reason to add Material Design to this framework. The idea sounded good to me at first, but I don't see the value. 

@trainerbill It sounds like you're main concern is keeping your project in line with upstream. If so, this is my experience.. I have a project based off this framework, that I've added Material Design to. I keep my project pretty closely synced with the latest release (and at some point pull in *master*). I don't have merge conflicts very often, and when I do they are basic; most of the time it's with one of the `assets` files.

**Comment by trendzetter** [comment]
me too, I admit I am heavily invested in bootstrap but its too early to drop it in favor of the next thing. It's still uncertain if material design will reach the same level of popularity as bootstrap soon.

**Comment by codydaig** [comment]
Sounds like the overall verdict is keeping bootstrap. 

Thanks for the discussion everyone! :-D
