### ISSUE TITLE
Auth broken in view-article view, preventing edit/remove

### ISSUE THREAD

**Issue by 0x24a537r9** [meanjs/mean#1172]
I know nothing about the innards of MEAN.js's auth scheme, but on a fresh git clone, if I create a new Article with a standard sign-up (i.e. non-oauth test user), I get redirected to the view page but it has no edit/remove buttons. I inserted {{vm.authentication.user._id}} == {{vm.article.user._id}} into the DOM to debug, and despite being logged in (as evidenced by the upper-right menu item and my ability to create new articles with vm.article.user._id properly set) vm.authentication.user._id is an empty string.

I'm not sure the extent of this issue--whether it affects other views, only affects certain types of users, or has other unobserved consequences, but it definitely _used_ to work and doesn't now.

Thoughts?

**Comment by mleanos** [comment]
#1149

**Comment by 0x24a537r9** [comment]
Ah! Thank you very much! Feel free to mark this as a duplicate of issue #1146 .
