### ISSUE TITLE
(discussion) UI-Router nested states/views

### ISSUE THREAD

**Issue by trainerbill** [meanjs/mean#1179]
https://github.com/angular-ui/ui-router/wiki/Nested-States-&-Nested-Views

Any thoughts on moving to nested views?  I use it in my application and it works wonders.I have a couple ui-views in the server layout

ui-view="header"
ui-view="hero"
ui-view="main"
ui-view="footer"

Then my submodules target the views and inject different layouts.  I think it makes the application more modular and you don't have to update core files.

**Comment by ilanbiala** [comment]
I'm fine with this (I think), but can you give an example gist of one of the views and how it would look?

**Comment by mleanos** [comment]
This sounds like a good idea to me too. However, I'd like to see an example as well, and know the impact to the rest of application.

**Comment by trendzetter** [comment]
I would also be interested to use that. I have been wrangling and duplicating to work with 1 serverlayout which could be more elegantly done by using several nested views.

**Comment by trainerbill** [comment]
https://github.com/meanjs/mean/pull/1183
