### ISSUE TITLE
Multiple users can register with the same email address with default app

### ISSUE THREAD

**Issue by crewshin** [meanjs/mean#118]
While registering users with a default app, it's possible to register multiple users with the same email address. It does however check if the username exists and prompts the user to change.

**Comment by ilanbiala** [comment]
@crewshin identities and providers are being discussed in #337. @crewshin you may want to subscribe to that issue and chip in with your 2c.

**Comment by SOSANA** [comment]
Any updates?

**Comment by ilanbiala** [comment]
@SOSANA the plan is to handle that through #343, which needs to be merged into 0.4.0 rather than master. @sielay needs to create a new PR for 0.4.0 to avoid having lots of merge issues later on.

**Comment by codydaig** [comment]
Since this moved to #343, and #343 was closed, can we close this issue?

**Comment by lirantal** [comment]
@codydaig #343 is closed until we get that PR against 0.4.0 so maybe we leave this thread open still.

**Comment by codydaig** [comment]
I believe this is taken care of now in #439

**Comment by lirantal** [comment]
right, I'll close this @crewshin unless you spot any other problems with the fix in the latest 0.4.0 branch then you're welcome to re-open.
