### ISSUE TITLE
Is "app" folder gone?

### ISSUE THREAD

**Issue by giovapanasiti** [meanjs/mean#1182]
Hi, I cloned the repo for a project i'm studying but I cant find the "app" folder anymore so I follow install instructions and run localhost:3000 but instead that have a demo page I just have a white page with nothing inside. How can I recreate the app folder?

I'm following this course but I'm stucked without this information!

**Comment by lirantal** [comment]
That's right, it has been deprecated when we released v0.4

**Comment by giovapanasiti** [comment]
Thank you for the answer! So at the moment I cannot have any demo front end when I install it. Is there any way to obtain the same result?

**Comment by lirantal** [comment]
Of course there is a demo frontend, only the directory structure has been updated.
Go ahead and clone the repo, follow the README for instructions.

**Comment by giovapanasiti** [comment]
So I finished the readme but still the page it's only white without any frontend. Am i doing some mistake?

**Comment by lirantal** [comment]
Yes, you're missing a step, or you're not really running the server.
Can you show us some debug output?

**Comment by giovapanasiti** [comment]
this is the terminal output:
`$ grunt
Running "env:dev" (env) task

Running "sass:dist" (sass) task

Running "less:dist" (less) task

Running "jshint:all" (jshint) task
>> 115 files lint free.

Running "eslint:target" (eslint) task


Running "csslint:all" (csslint) task
>> 3 files lint free.

Running "mkdir:upload" task

Running "copy:localConfig" (copy) task


Running "concurrent:default" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    [nodemon] 1.8.1
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: gruntfile.js modules/*/server/views/*.html server.js config/**/*.js modules/*/server/**/*.js modules/*/server/config/*.js
    [nodemon] starting `node --debug server.js`
    Running "watch" task
    Waiting...
    Debugger listening on port 5858
    
    
    --
    MEAN.JS - Development Environment
    
    Environment:     development
    Server:          http://0.0.0.0:3000
    Database:        mongodb://localhost/mean-dev
    App version:     0.4.2
    MEAN.JS version: 0.4.2
    --
`

**Comment by lirantal** [comment]
and what do you get when you open the browser for port 3000?
did you also run bower install?

**Comment by trainerbill** [comment]
bet he did not bower install

**Comment by giovapanasiti** [comment]
right guys, sorry I can see only now how stupid I am. Sorry again about this :(

**Comment by trainerbill** [comment]
@giovapanasiti can you close out the issue if it is resolved then?
