### ISSUE TITLE
Changing the page title and description

### ISSUE THREAD

**Issue by etiennetatur** [meanjs/mean#1185]
Hello,

It seems that the title and description of the pages are set within the Express configuration. How would you recommend to update it from the client for History, tab name and SEO purpose ?

Any insight will be greatly appreciated !

**Comment by itelo** [comment]
please check [#1186] (https://github.com/meanjs/mean/pull/1186)

**Comment by etiennetatur** [comment]
It worked perfectly and it is a really pretty way to handle it ! 
I re-used another directive to handle the SEO description in a similar way.

Thanks !
