### ISSUE TITLE
(discussion) Gulp Strip Debug

### ISSUE THREAD

**Issue by trainerbill** [meanjs/mean#1187]
Thoughts on using:

https://www.npmjs.com/package/gulp-strip-debug

Would be nice to have some debug statements in the code base. Like on controller instatiation do

console.log('ArticlesController::Init', vm);

Then let gulp strip them on production/test build. Obviously we wouldn't allow all console.logs in PR's, but having strategic ones would save a bunch of time IMO

Thoughts?

**Comment by trainerbill** [comment]
@mleanos I know you are working a lot with gulp

**Comment by mleanos** [comment]
I vote no for this... 

I don't feel like there's a need for persistent `console.log`'s throughout the framework. We log certain things logging to the console, for important server status. For instance, when the server starts, seed is complete, certificate, and some others. I think those are sufficient for us and users can add whatever may fit their needs. I can see this type of thing getting out of hand, and allowing for lazily leaving log's all around.

**Comment by codydaig** [comment]
I would say no to this as well. I'd rather come up with a logging option that can be enabled/disabled depending on the env other than console.logs() that get stripped.

**Comment by trainerbill** [comment]
@codydaig Problem with that is you have to have if statements everywhere, even in production code.  This would be a much cleaner approach with zero performance impact IMO.

**Comment by ilanbiala** [comment]
Yeah, this seems a little pushy on logging when we can really handle that in a better way by using logs properly.

**Comment by codydaig** [comment]
Looks like the overall consensus is no on this, but in favor of a logging alternative.
