### ISSUE TITLE
How to access users view pages?

### ISSUE THREAD

**Issue by ChrisMaher** [meanjs/mean#1193]
I see the user admin --> edit, list and view pages but i have no idea how to access them. 

Is there more to becoming an admin than editing the role in Mongodb to admin?

Thanks

**Comment by mleanos** [comment]
@ChrisMaher Merely adding `admin` to the User's `roles` array should do the trick; the actual collection in your database, not the mongdb instance.

If you have already tried adding the *role* and still can't access the Admin module.. 
Are you working off a fresh clone? Is it possible that the admin module client routes aren't setup with the `admin` role?

**Comment by ChrisMaher** [comment]
Im using MEAN 0.4 if that makes a difference. This is what im working on https://github.com/ChrisMaher/mean-dev-0.4

**Comment by mleanos** [comment]
that repo looks correct to me. Have you verified that the User you're logged in with has the `admin` Role? Try console logging `Authentication.user.roles` on the client-side.

**Comment by ChrisMaher** [comment]
Is this enough?

From Mongo

```
 "roles": [
        "admin"
    ],
```

From Batarang

roles: 
[ admin, user ]

**Comment by mleanos** [comment]
If that's what your User's data looks like, then it should allow access to the Admin module. What is the behavior you're seeing? Any console/server errors?

I don't have time right now, but I'll try to pull down your branch later & test locally.

**Comment by ChrisMaher** [comment]
It just says page not found with a warning if i visit http://localhost:3000/users. 

Would this happen if i wasnt admin and visited the page as a regular user or does it indicate the route is messed up?

**Comment by mleanos** [comment]
Try `localhost:3000/admin/users`

**Comment by mleanos** [comment]
Also, `localhost:3000/api/users` should return a list of users in json format. That is the server-side route; it's only accessible to Admin's.

**Comment by ChrisMaher** [comment]
Im actually an idiot. 

Yeah that brings up a list of users alright.

Thank you very much. Couldnt find anything about it anywhere and the routes seem to just say /users

**Comment by mleanos** [comment]
Is the Admin menu not showing up in the topbar?

**Comment by ChrisMaher** [comment]
Nope. probably something i changed with that to be honest. Ill manually add a link myself again. 

Thanks for the help.

**Comment by mleanos** [comment]
@ChrisMaher I think this can be closed.

**Comment by ChrisMaher** [comment]
Absolutely.
