### ISSUE TITLE
Enhancement: Whitelist-xor-Blacklist the user object fields (do not do both)

### ISSUE THREAD

**Issue by vaucouleur** [meanjs/mean#1195]
- Sometimes in the code, we **blacklist** some user's fields. Like password that get excluded:
https://github.com/meanjs/mean/blob/959d03c31edbf8a865eb73000f3cba58cbb89868/modules/users/server/config/users.server.config.js#L24

- Sometimes in the code, we **whitelist** some user's fields. Like in the renderIndex method:
https://github.com/meanjs/mean/blob/6658774569d5718411b0766a226f45fa13b5b7b6/modules/core/server/controllers/core.server.controller.js#L12

Doing both is a source of confusion. People will get bitten when adding fields to the user object.

I suggest using either whitelisting or blacklisting -- but not both.

@lirantal @codydaig @mleanos @trainerbill

**Comment by codydaig** [comment]
Is your proposal to then remove additional fields that shouldn't be sent to the client instead of only including the ones that you want sent?

**Comment by vaucouleur** [comment]
@codydaig Either blacklisting or blacklisting is fine by me. If I had to make a choice, it would be blacklisting. That's my first bullet point above: what we are already doing with password etc. The safeUserObject is whitelisting. Again, any option is fine, we just have to be consistent, I guess. If someone has a strong opinion about this, I'd love to read it.

**Comment by lirantal** [comment]
@vaucouleur why do you find it so confusing?

**Comment by vaucouleur** [comment]
@lirantal As far as I know, we have 3 occurrences where we remove the password and the salt fields (blacklisting), and one instance where we explicitly list fields (whitelisting). Those are two very different approaches being mixed (not consistent). A newcomer who is adding a field to the user object is likely to miss the fact that the renderIndex function must be amended.

**Comment by trainerbill** [comment]
The renderIndex portion can be completely removed if the JWT PR goes in.  It uses a blacklist on the passport-jwt kind of like the deserialize:

https://github.com/meanjs/mean/blob/959d03c31edbf8a865eb73000f3cba58cbb89868/modules/users/server/config/users.server.config.js#L24

The only other places you should ever work with user is when doing a populate, you have to remember to remove password and salt.  If someone could figure out how to do this in mongoose for only .populate that would be awesome.  The only time the password/salt is needed is in the authentication piece which uses findOne

https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/local.js#L17

If we could find a way to do a mongoose post hook on user.find to remove salt and password in all other cases that would be awesome.

```js
schema.post('find', function(result) {
  delete result.password;
  delete result.salt;
});
```

Maybe if you did a direct mongoDB find only in the passport local strategy to get the complete object and then implemented a mongoose user.find post hook to remove the password/salt it should work?

**Comment by vaucouleur** [comment]
@trainerbill Good points. I just got an idea that might solve this elegantly (including the populate issue). I will prototype it to check whether it works.

**Comment by lirantal** [comment]
@vaucouleur great, waiting for your PR :)

**Comment by lirantal** [comment]
@vaucouleur if you're still hunger for this then any chance for a PR?

**Comment by vaucouleur** [comment]
@lirantal @codydaig I don't think it was perceived as a real issue by the community; no consensus. So I'll simply close it.

**Comment by simison** [comment]
We're actually facing this issue and having real trouble not having a white listing as a service.

We'll implement this eventually anyway at our site, thanks for food for thought everyone here.

Feel free to follow https://github.com/Trustroots/trustroots/issues/402
