### ISSUE TITLE
Disabling mongodb connection

### ISSUE THREAD

**Issue by 1nfinite** [meanjs/mean#1201]
I am using meanjs 0.4.2 as a template for development. However, our site will not be accessing database directly. Is there any configuration to disable connection to mongodb?

**Comment by lirantal** [comment]
@1nfinite is it actually failing to run if mongodb is not present?
If so, you can try to hack the `app.js` file to ignore the mongodb connection attempt: https://github.com/meanjs/mean/blob/master/config/lib/app.js

I'm not sure this is a common case that would constitute an actual configuration field control over mongodb.
