### ISSUE TITLE
Working with subdomains

### ISSUE THREAD

**Issue by dbelieves** [meanjs/mean#1211]
I want to create a subdomain in the meanjs app.
main : example.com
subdomain: team.example.com
subdomain: dashboard.example.com

where team and dashboards are modules in meanjs.
how do i do this ?

**Comment by lirantal** [comment]
this really ties down to your URL route handling (whether server-side or client-side).
some references to check are https://www.npmjs.com/package/express-subdomain and angular's ui-router setup

**Comment by dbelieves** [comment]
@lirantal , i have no idea how to manipulate the code from your given references.
can you elaborate more on this.
its really urgent for me.

**Comment by lirantal** [comment]
there's no built in support in MEAN.JS for subdomain routines but you can go ahead and check the code examples on https://github.com/bmullan91/express-subdomain
