### ISSUE TITLE
0.5.x branch

### ISSUE THREAD

**Issue by usta** [meanjs/mean#1219]
Hello, isn't it much better if project creates a 0.5.x branch so node 0.12 support can drop in this
branch and we can implement things in this branch.And whenever it is ready we can merge 0.5.x to master

**Comment by usta** [comment]
@ilanbiala @lirantal @codydaig Any comments ?

**Comment by codydaig** [comment]
If someone submits a PR to drop Node 0.12 support, that can be discussed. But the PR should only remove 0.12 support. Along with this, documentation on the website will need to be updated. 

There's a 0.4.x branch that can accept bug fixes into 0.4, but the master branch is the work going on for 0.5.

**Comment by lirantal** [comment]
@ilanbiala @codydaig  FWIW on 0.12 - official support for that will be dropped by end of year 2016 but we're still not there and I don't see any rush for removing it.

It's not like we're using any special ES6 features or whatever (unless you had something going and I missed it)

**Comment by ilanbiala** [comment]
@lirantal some libraries have already dropped support for 0.12, and very few people who set up MEAN run it against 0.12, most issues I have seen ask about Node 5 support. Honestly, being able to use some ES6 features as well would be nice.

**Comment by usta** [comment]
I'm not an expert but i think we hit a bug about promises or consts support because of a module we try to upgrade.  I don't remember which one

**Comment by lirantal** [comment]
I'm definitely fine if we have something concrete that we want to add and do and 0.12 would be a problem, then let's drop it. But otherwise, just to drop it for the sake of dropping it serves no purpose.
That's all I'm saying.

**Comment by ilanbiala** [comment]
No it definitely benefits to upgrade as we can use newer dependencies. I think this issue can be closed as @codydaig already answered the question.
