### ISSUE TITLE
Default profile image link tampered after page refresh

### ISSUE THREAD

**Issue by 1nfinite** [meanjs/mean#1220]
I am referring to MeanJs v0.4.2. The default user profile image in header and change profile picture seems to be broken after page refresh or opening in new tab.

Profile image link before page refresh. It appears that character entities conversion appears at somewhere.

> modules/users/client/img/profile/default.png

Profile image link after page refresh or opening a new browser tab:

> modules&amp;#x2F;users&amp;#x2F;client&amp;#x2F;img&amp;#x2F;profile&amp;#x2F;default.png

**Comment by vaucouleur** [comment]
https://github.com/meanjs/mean/commit/f88f28e0358060a4523fc5397f357f38171e8b0b#diff-faf81ce8496d16181a82eadc3e44bbf5
