### ISSUE TITLE
Production server - code security, binaries  ?

### ISSUE THREAD

**Issue by dpranav007** [meanjs/mean#1222]
please correct me ,if i am missing out something.

while deploying the code on a server , what steps do i need to take if the attacker has physical access to the server (hard drive of the server) 
are there any solutions that allow me to deploy binaries , and works full proof.

any help would be appretiated.thank you

**Comment by vaucouleur** [comment]
@dpranav007 what about hiring ex-marines to move him out of the server room ?

**Comment by dpranav007** [comment]
can someone help out please?

**Comment by simison** [comment]
@dpranav007 Try [StackOverflow](https://stackoverflow.com/), this repository is for tech issues related to Meanjs.
