### ISSUE TITLE
Add Pull Request Template

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1225]
Basically just move https://github.com/meanjs/mean/blob/master/CONTRIBUTING.md#commit-message-guidelines to a file called `PULL_REQUEST_TEMPLATE`.

https://github.com/blog/2111-issue-and-pull-request-templates
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

(Sorry, no time here for a PR)

**Comment by lirantal** [comment]
I'll add this tomorrow, thanks for the info @simison 
Looks like that open letter helped :)

**Comment by simison** [comment]
@lirantal What open letter? :-)

**Comment by lirantal** [comment]
I can't believe you missed it!
https://github.com/dear-github/dear-github

You should start following me on LinkedIn/Twitter :)

**Comment by simison** [comment]
Ah ye this one! — I indeed did see (and sign) it, I just had forgotten the exact contents of it. Thanks for reminding!
