### ISSUE TITLE
Deployement on Cloud Foundry

### ISSUE THREAD

**Issue by maelfosso** [meanjs/mean#1229]
Hi everybody,

Please I am a new developper and I have a lot of question about PaaS. The only thing I know it's that it's good when you don't have much money.
My questions are :

- Is it free ? How much does it cost ?

- Where is my database (mongodb) ? Does Cloud Foundry take it in account when I deploy ?

- After deploying, on what must I be concentrated except the development of my application ? Should I care about the server or everything else around it ?

Thanks.

**Comment by lirantal** [comment]
@maelfosso we have no idea what you're talking about.
Sounds like you really need to figure out from yourself what you want with Cloudfoundry.

1. What is free exactly? cloudfoundry? I don't know, go to their website support and ask.
2. Ask Cloudfoundry
3. You should care if your account hosting is able to deal with the traffic along with so many more requirements (security, monitoring, etc)
