### ISSUE TITLE
file name: /modules/core/client/directives/show-errors.client.directives.js

### ISSUE THREAD

**Issue by mg1075** [meanjs/mean#1233]
**show-errors.client.directives.js**
vs.
**show-errors.client.directive.js**

Shouldn't the name of this file be **show-errors.client.directive.js** to keep consistent with convention?

https://github.com/meanjs/mean/blob/5105eb12fee789548f21eb08dd0f6242af51d601/modules/core/client/directives/show-errors.client.directives.js

**Comment by Wuntenn** [comment]
I had a similar question a few days ago: 

[https://gitter.im/meanjs/mean?at=56c1df26d9c5a252408f8fc9]

Maybe because it's better to submit a pull request for these kinds of small changes. It would be good to know.

**Comment by lirantal** [comment]
definitely, just go ahead and submit a PR.

**Comment by mleanos** [comment]
@mg1075 @Wuntenn @sujeethk
