### ISSUE TITLE
protractor issues in latest version

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#1234]
@ilanbiala your advise on the following?
after running `grunt test` everything passes except the protractor tests
I cloned a fresh meanjs repo and ran `npm install`

these are the errors:
```bash
Running "protractor:e2e" (protractor) task
webdriver-manager path: /lirantal-meanjs/node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager
Updating selenium standalone
downloading https://selenium-release.storage.googleapis.com/2.47/selenium-server-standalone-2.47.1.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.19/chromedriver_linux64.zip...
chromedriver_2.19.zip downloaded to /lirantal-meanjs/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/chromedriver_2.19.zip
selenium-server-standalone-2.47.1.jar downloaded to /lirantal-meanjs/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/selenium-server-standalone-2.47.1.jar
Starting selenium standalone server...
[launcher] Running 1 instances of WebDriver
Selenium standalone server started at http://10.0.2.15:43309/wd/hub

/lirantal-meanjs/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/atoms/error.js:108
  var template = new Error(this.message);
                 ^
UnknownError: unknown error: Chrome version must be >= 43.0.2357.0
  (Driver info: chromedriver=2.19.346067 (6abd8652f8bc7a1d825962003ac88ec6a37a82f1),platform=Linux 3.13.0-27-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 9.17 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'localserver', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-27-generic', java.version: '1.7.0_65'
Driver info: org.openqa.selenium.chrome.ChromeDriver
```

**Comment by ilanbiala** [comment]
@lirantal I don't think I've ever seen that error. Can you try `npm cache clean`, delete `node_modules`, and run `npm install` again?

**Comment by lirantal** [comment]
@ilanbiala I'll try but like I said I started by cloning an entirely new fresh copy of the repo and doing `npm install`.

Any chance you could do the same and see if it happens? maybe it's related to how new packages get installed or whatever.

**Comment by ilanbiala** [comment]
I haven't seen this issue with the last few testing PRs I've done, so I don't think this is a universal issue.

**Comment by mleanos** [comment]
@lirantal I just cloned a fresh version of the repo (master), and didn't have any problems with running `grunt test`; The protractor tests passed.

I had weird issues with Protractor last week, but I ended up doing `npm cache clean` and deleting all the node_modules packages. Then did `npm install` again & everything worked fine. My guess would be the Cached version of grunt-protractor; they may have released a patch in the day or two after I first ran into my issue. Although, my error was quite different. The message about the Chrome version seems weird to me too.

**Comment by lirantal** [comment]
@mleanos which versions of node, npm, and OS are you running?

**Comment by mleanos** [comment]
Windows 7
`node --version v0.12.7`
`npm --version 2.11.3`

**Comment by lirantal** [comment]
I'll close for now as I'm unable to reproduce.
