### ISSUE TITLE
Recommendation: Replacing grunt-contrib-sass with grunt-sass

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#1237]
The `grunt-sass` module (https://github.com/sindresorhus/grunt-sass) doesn't require ruby installed to compile CSS files to SASS and as such we gain:
1. Faster compilation time due to a C++ extension
2. Lowering our dependencies/pre-requisites count and not requiring anyone to install ruby

What do you think?

**Comment by codydaig** [comment]
Is there a gulp equivalent?

**Comment by ilanbiala** [comment]
gulp-sass already uses node-sass.

**Comment by lirantal** [comment]
Right, was about to say that :)
I'll work on a PR for that so we can align it and remove dependencies for ruby.

**Comment by ilanbiala** [comment]
Why are we doing grunt development though, we are deprecating grunt...

**Comment by lirantal** [comment]
I don't think deprecating grunt will happen tomorrow and there is obviously some target users of MEAN.JS using grunt still so why not?
