### ISSUE TITLE
Dropdown menu of the navbar is not working on AngularJs 1.5?

### ISSUE THREAD

**Issue by taobataoma** [meanjs/mean#1243]
I create project with MEAN.js 0.4，all is OK
when is upgrade AngularJs to 1.5，the dropdown menu is can not open，need i change some code?

**Comment by ilanbiala** [comment]
@taobataoma are there any errors? @trendzetter @usta any ideas?

**Comment by taobataoma** [comment]
oh,sorry,this err is not on AngularJs1.5，It is on angular-bootstrap@1.2.*
today, I first upgrade AngularJs & resource & animate to v1.5 , all is ok,
when i upgrade the angular-bootstrap to v1.2, ok,this error is showing,
the dropdown menu can not open, tooltip can not show, popover can not show, etc.

**Comment by ilanbiala** [comment]
@taobataoma can the issue be closed?

**Comment by usta** [comment]
@ilanbiala we didn't used 1.2.1 in #1207  but it was working perfect. And until we merge #1207 we will get same false positive issue reports. i wrote @trendzetter about make a little test with 1.2.1 and if it won't have any other problems we need to merge that #1207 .

**Comment by trendzetter** [comment]
@taobataoma You need to clone the latest master, not 0.4. Or you can update the bootstrap directives yourself: dropdown-toggle -> **uib-**dropdown-toggle (the same for other angular bootstrap directives)
https://github.com/angular-ui/bootstrap/wiki/Migration-guide-for-prefixes

**Comment by trendzetter** [comment]
@usta will give 1.2.1 a try, I don't expact to find anything new. This issue is because in 0.4 the directives were not yet migrated to the new angular bootstrap directives.

**Comment by usta** [comment]
@trendzetter i guess same but it will be nice to have at least the PR is be a little more uptodate whenever we merge it

**Comment by trendzetter** [comment]
It wasn't yet included as the release is now just 4 days old

**Comment by taobataoma** [comment]
ok, i already replace directives with prefix uib-*，it`s work fine,thanks.
