### ISSUE TITLE
running the app does not work

### ISSUE THREAD

**Issue by anterokarttunen** [meanjs/mean#1244]
Yesterday "grunt" command was working ok. Today I moved the project sources into another folder.

Now it does not work anymore.

Using grunt --force works since tests are ignored..

What could be the issue? 

`$ grunt
Running "env:dev" (env) task

Running "sass:dist" (sass) task

Running "less:dist" (less) task

Running "jshint:all" (jshint) task

      1 |'use strict';
         ^ Use the function form of "use strict".
      6 |var _ = require('lodash'),
                 ^ 'require' is not defined.
      7 |  defaultAssets = require('./config/assets/default'),
                           ^ 'require' is not defined.
      8 |  testAssets = require('./config/assets/test'),
                        ^ 'require' is not defined.
      9 |  testConfig = require('./config/env/test'),
                        ^ 'require' is not defined.
     10 |  fs = require('fs'),
                ^ 'require' is not defined.
     11 |  path = require('path');
                  ^ 'require' is not defined.
     13 |module.exports = function (grunt) {
         ^ 'module' is not defined.
    232 |    require('coveralls').handleInput(lcovFileContents, function(err) {
             ^ 'require' is not defined.
    241 |  require('load-grunt-tasks')(grunt);
           ^ 'require' is not defined.
    249 |    grunt.file.mkdir(path.normalize(__dirname + '/modules/users/client/img/profile/uploads'));
                                             ^ '__dirname' is not defined.
    260 |    var mongoose = require('./config/lib/mongoose.js');`

**Comment by lirantal** [comment]
@anterokarttunen what exactly did you move?
what other updates have you made?
which version of MEAN.JS are you working with?

**Comment by anterokarttunen** [comment]
ex
`mv /users/antsa/meanproject /users/antsa/antsaproject`

Project was generated yesterday using MeanJS Yo Generator http://meanjs.org/generator.html
meanjs version: 0.5.0-Beta
I also generated some modules (took time to find correct ones since documentation is out of date)

Seems that grunt test execution gets corrupted somehow

**Comment by trendzetter** [comment]
does it work using gulp?
did you run npm install before grunt?

**Comment by anterokarttunen** [comment]
@trendzetter Haa, with gulp command I was able to find the root cause. It provided better message. Checked from history and had done silly mv command:
`mv /users/antsa/meanproject/* /users/antsa/some-cloned-repo`

of course it did not copy files that started with .

After copying rest of the .xxxx files - it was working ok. Daymn grunt didn't show good enough error message :D

Thanks peeps ^_^

**Comment by lirantal** [comment]
@anterokarttunen what message did gulp tell at you when that happens?

**Comment by anterokarttunen** [comment]
@lirantal I think it was saying that either .csslintrc or .eslintrc was missing

**Comment by lirantal** [comment]
Ok, thanks!

**Comment by anterokarttunen** [comment]
You can try it out by moving all hidden files & exexuting grunt / gulp command.

However I don't think this case happens very often since this is a human mistake :) Its like trying to run node without installing it :D



Lähetetty Samsung-laitteesta


-------- Alkuperäinen viesti --------
Lähettäjä: Liran Tal <notifications@github.com>
Päivämäärä: 3.3.2016 12.30 (GMT+02:00)
Saaja: meanjs/mean <mean@noreply.github.com>
Kopio: Antero Karttunen <antero.karttunen@jaspartners.com>
Aihe: Re: [mean] running the app does not work (#1244)


Ok, thanks!

-
