### ISSUE TITLE
Issue running tests, selenium-webdriver

### ISSUE THREAD

**Issue by trendzetter** [meanjs/mean#1247]
I am running ubuntu 15.10 but when doing a fresh clone and npm install I am getting:

> [launcher] Process exited with error code 1
> /mean/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
>   goog.global.setTimeout(function() { throw exception; }, 0);
>                                       ^
> 
> Error: Server terminated early with status 1
>     at Error (native)
>     at /mean/node_modules/selenium-webdriver/remote/index.js:204:18
>     at promise.ControlFlow.runInFrame_ (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
>     at goog.defineClass.notify (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
>     at promise.Promise.notify_ (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
>     at Array.forEach (native)
>     at promise.Promise.notifyAll_ (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
>     at goog.async.run.processWorkQueue (/mean/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
>     at process._tickCallback (node.js:406:9)
> E2E Tests failed

The tests run fine on a recent fork I created:
https://github.com/trendzetter/mean

**Comment by trendzetter** [comment]
I suspect some dependency was upgraded providing selenium-driver during this commit:
https://github.com/meanjs/mean/commit/1c143ae24adb5a5e3e5576d1691935121ad9030f#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by trendzetter** [comment]
chrome version 48.0.2564.116 (64-bit)

**Comment by ilanbiala** [comment]
@trendzetter try doing `npm cache clean`, removing `node_modules`, and doing `npm install`.

**Comment by trendzetter** [comment]
I just did a full cleanup. Still getting this:

>     ✓ should be able to change profile picture if signed in (54ms)
>     ✓ should not be able to change profile picture if attach a picture with a different field name (42ms)
> 
> 
>   107 passing (4s)
> 
> Disconnected from MongoDB.
> [19:22:38] Finished 'mocha' after 4.37 s
> [19:22:38] Finished 'test:server' after 7.93 s
> [19:22:38] Starting 'karma'...
> 03 03 2016 19:22:38.341:INFO [karma]: Karma v0.13.21 server started at http://localhost:9876/
> 03 03 2016 19:22:38.346:INFO [launcher]: Starting browser PhantomJS
> 03 03 2016 19:22:38.577:INFO [PhantomJS 2.1.1 (Linux 0.0.0)]: Connected on socket /#pvnObPnDTCwkmcvQAAAA with id 69220441
> PhantomJS 2.1.1 (Linux 0.0.0): Executed 140 of 141 (skipped 1) SUCCESS (1.946 secs / 2.072 secs)
> [19:22:40] Finished 'karma' after 2.74 s
> [19:22:40] Starting 'nodemon'...
> [19:22:40] Finished 'nodemon' after 34 ms
> [19:22:40] Starting 'webdriver_update'...
> [19:22:40] [nodemon] 1.9.1
> [19:22:40] [nodemon] to restart at any time, enter `rs`
> [19:22:40] [nodemon] watching: modules/*/server/views/*.html server.js config/**/*.js modules/*/server/**/*.js modules/*/server/config/*.js
> [19:22:40] [nodemon] starting `node --debug server.js`
> Debugger listening on port 5858
> selenium standalone is up to date.
> chromedriver is up to date.
> [19:22:41] Finished 'webdriver_update' after 258 ms
> [19:22:41] Starting 'protractor'...
> [19:22:41] Finished 'protractor' after 741 μs
> [19:22:41] Finished 'test' after 11 s
> 
> 
> Starting selenium standalone server...
> [launcher] Running 1 instances of WebDriver
> [launcher] Process exited with error code 1
> /mean/node_modules/selenium-webdriver/lib/goog/async/nexttick.js:41
>   goog.global.setTimeout(function() { throw exception; }, 0);
>                                       ^
> 
> Error: Server terminated early with status 1
>     at Error (native)
>     at /mean/node_modules/selenium-webdriver/remote/index.js:204:18
>     at promise.ControlFlow.runInFrame_ (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
>     at goog.defineClass.notify (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
>     at promise.Promise.notify_ (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
>     at Array.forEach (native)
>     at promise.Promise.notifyAll_ (/mean/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
>     at goog.async.run.processWorkQueue (/mean/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
>     at process._tickCallback (node.js:406:9)
> E2E Tests failed
>

**Comment by ilanbiala** [comment]
https://travis-ci.org/meanjs/mean/jobs/113216745#L1969 doesn't seem like Travis is having this issue. I'm not even sure why the server terminates early to be honest..

**Comment by QiyuLi** [comment]
Did you install java on your system?

**Comment by trendzetter** [comment]
https://github.com/meanjs/mean/pull/1213 There seem to be issues with some people but my guess is we might need a newer protractor with the latests of other dependencies.

**Comment by trendzetter** [comment]
java version "1.7.0_95"
OpenJDK Runtime Environment (IcedTea 2.6.4) (7u95-2.6.4-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)

Do I need Java?

**Comment by QiyuLi** [comment]
Selenium is a java program.

**Comment by trendzetter** [comment]
https://github.com/angular/protractor/issues/2638
```
// Protractor configuration
var config = {
  specs: ['modules/*/tests/e2e/*.js'],
  directConnect: true
};
```

**Comment by trendzetter** [comment]
Adding   directConnect: true in protractor.conf.js resolves the issue.

**Comment by jloveland** [comment]
I tried grunt and it runs e2e tests fine. Running with **gulp** gives me an error. To clarify @trendzetter, are you only seeing this issue with gulp?

**Comment by trendzetter** [comment]
I am no longer getting this error on a fresh clone today. Not sure what has changed.
