### ISSUE TITLE
Replace gulp-cssmin

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#1251]
Package `gulp-cssmin` at https://github.com/chilijung/gulp-cssmin seems un-maintained and old while other candidates are:
1. gulp-clean-css at https://www.npmjs.com/package/gulp-clean-css
2. gulp-csso at https://www.npmjs.com/package/gulp-csso/

**Comment by ecris87** [comment]
:+1: 

Both good choices, the CSS minification engine used by gulp-clean-css is slightly better according to this benchmark test: http://goalsmashers.github.io/css-minification-benchmark/ but gulp-csso is more popular.

And both work nicely with [gulp-sourcemaps](https://github.com/floridoo/gulp-sourcemaps), while gulp-cssmin does not.

**Comment by simison** [comment]
Some interesting discussion regarding this stuff:
https://github.com/gulpjs/plugins/issues/210
https://github.com/plus3network/gulp-less/pull/221

>the current flow by the gulp team is to use: https://github.com/postcss/gulp-postcss with a postcssnano plugin, or https://github.com/scniro/gulp-clean-css

**Comment by scniro** [comment]
@ecris87 @simison `gulp-clean-css` should (hopefully) be regaining popularity. Within the last month I took ownership of this project, which was previously [gulp-minify-css](https://www.npmjs.com/package/gulp-minify-css). The OP and repository have since vanished, but remains a very popular package on npm with a deprecation warning.

**Comment by lirantal** [comment]
So it's definitely `gulp-csso` as it is much more popular and common through the ecosystem.
With regards to `gulp-postcss` I'm seeing that it is even higher in popularity but overall in the same area so doesn't seem like there's any clear winner there.

**Comment by simison** [comment]
@lirantal, although, `post-css` is already in meanjs via `gulp-autoprefixer`:
https://github.com/meanjs/mean/blob/master/package.json#L91
https://github.com/sindresorhus/gulp-autoprefixer/blob/master/package.json#L24

**Comment by lirantal** [comment]
not sure if that's something to follow on or not.
