### ISSUE TITLE
AngularJS2

### ISSUE THREAD

**Issue by timokd** [meanjs/mean#1257]
Hello,
is it possible to create a meanja app with angularjs 2. If not can you tell me when this is planned?

Greetings

Timo

**Comment by lirantal** [comment]
Hi @timokd 

There is no such plan in motion at the moment for the MEAN.JS project to add this support.
However, we have just pushed some updates for Angualr 1.5.

**Comment by klemensz** [comment]
This will probably be a big change? I think Angular 2 is the future though.

**Comment by trendzetter** [comment]
For now that seems a bit uncertain how much adoption it will get in the short run. Maybe some projects will skip a version altogether?
