### ISSUE TITLE
Restructure: Use only npm commands

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1258]
What do you think about using only `npm` commands to operate the app? This came up at [Docker PR](https://github.com/meanjs/mean/pull/1249#issuecomment-194789888).

**Pros:**
- Being able to control Gulp, Grunt and Bower versions. NPM `scripts` section uses locally installed versions of packages, not globally. Running `gulp` command directly will require globally installed version. Gulp is soon getting a major version bump, I'm not sure how that will affects things in the future.
- [Prerequisites](https://github.com/meanjs/mean#prerequisites) section would be significantly simpler due no more requiring global cli packages. Actually with correct `prestart` script the whole install process would be pretty much just: 
  - 1. Install node+npm+mongo, 
  - 2. Run `npm start`. :-)
- It looks nice when the whole app operates with one command instead of mixture of `gulp`, `npm`, `sh` and `bower`:
  - `npm install`
  - `npm update`
  - `npm start`
  - `npm test`
  - `npm run test:server`
  - `npm run test:client`
  - `npm run test:e2e`
  - `npm run build` (for production build)
  - `npm run generate-ssl-certs` (would run a task: `"generate-ssl-certs": "./scripts/generate-ssl-certs.sh"`)
- Allows adding pre/post tasks. Current [bower postinstall task](https://github.com/meanjs/mean/blob/master/package.json#L20) is a good example. E.g.:
  - `"prestart": "if [ ! -d node_modules ]; then npm install --quiet; fi"`
  - `  "postinstall": "bower install --allow-root --config.interactive=false && bower prune --allow-root --config.interactive=false"`
- If tooling ever changes again (like now Grunt=>Gulp), commands won't. Might be npm will replace Bower in the future.

**Cons:**
- Will hide Gulp implementation a little bit, which might be bad for people's understanding how things work.
- Breaking change

This with assumption that Grunt task runner is getting deprecated, since that kinda complicates this a bit.

Further reading: https://docs.npmjs.com/misc/scripts

**Comment by lirantal** [comment]
Sounds good, and great summary @simison.
@meanjs/core ?

**Comment by codydaig** [comment]
Sounds good to me.

**Comment by ilanbiala** [comment]
SGTM.

**Comment by mleanos** [comment]
This sounds like a good idea. I'm not sure I understand all the implications though.

I think I'm clear on the application/server tasks. However, what happens to the other Gulp tasks that we've added. For instance, `gulp wiredep`, the `gulp watch`'s, etc. Will we still have those integrated into the application? Will we have to add scripts like `npm run wiredep`?

Overall, this seems like a really good move for the framework. Having a more controlled environment will help us as developers, and our users will be able to get up & running a lot easier.

Definitely a +1 :)

**Comment by lirantal** [comment]
@simison would you like to propose the PR?

**Comment by trendzetter** [comment]
really cool!

**Comment by simison** [comment]
Sooo.. as it turns out, I'm not sure if I trust the concept of NPM scripts after stumbling upon this:

https://blog.liftsecurity.io/2015/01/27/a-malicious-module-on-npm

>Earlier this week a package called `rimrafall` was published to npm. This package had a preinstall hook that executed the command `rm -rf /*`. It was created on 01/26/2015 at 15:28 and immediately posted to Hacker News and then it was unpublished from the registry by npm at 17:06 – giving it a lifespan of less than two hours.

While NPM scripts are convenient, I would totally understand someone doing this in their system:
```
npm config set ignore-scripts true
```

More http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability

That all said, I still think there should be one command to rule 'em all, instead of a mixed bag of `gulp`, `npm`, `sh` and `bower`...

A bit mixed feelings about this right now...

**Comment by lirantal** [comment]
Security concerns are understood but I'm not sure they are valid in this case as this is a framework and not just some library that you 'npm install'.

**Comment by simison** [comment]
@lirantal True.

Pushed initial example for discussion: https://github.com/meanjs/mean/pull/1296

**Comment by Wuntenn** [comment]
I've heard good things about this approach. 

https://medium.freecodecamp.com/why-i-left-gulp-and-grunt-for-npm-scripts-3d6853dd22b8#.vzzmwa9n4

I like having the mixed bag myself. Gives more options. Like grunt allows the `--force` to make sure that warnings don't stop the compile/build - This is good for when I don't want to spend time picking away at tabbing etc. I've not found a way to bypass warnings with gulp. Also I've had issues sometimes where livereload crashes and doesn't want to work again for whatever reason. At those times I hop from grunt to gulp and don't worry about closing the environment/OS.

Up to you guys though - looks cleaner!

**Comment by codydaig** [comment]
@lirantal I merged the PR. Do you want this open as a reference still, or shall we close?

**Comment by lirantal** [comment]
We can close it, I'll open another one to handle the remaining parts.
Thanks @codydaig !
