### ISSUE TITLE
User Id Missing

### ISSUE THREAD

**Issue by jagadeeshthegeek** [meanjs/mean#1262]
**user._id**  is not mapped. when you refresh the page. 
It makes problem while checking, Article-Created-Owner-id and Logged-In-user-id is same. (Edit Article -Access)

**Solution:** (_id has to be added)

https://github.com/meanjs/mean/blob/master/modules/core/server/controllers/core.server.controller.js

 ```
  safeUserObject = {
      _id: validator.escape(req.user._id),
      displayName: validator.escape(req.user.displayName),
      provider: validator.escape(req.user.provider),
      username: validator.escape(req.user.username),
      created: req.user.created.toString(),
      roles: req.user.roles,
      profileImageURL: req.user.profileImageURL,
      email: validator.escape(req.user.email),
      lastName: validator.escape(req.user.lastName),
      firstName: validator.escape(req.user.firstName),
      additionalProvidersData: req.user.additionalProvidersData
    };
```

**Comment by lirantal** [comment]
@codydaig can you take a look?

**Comment by mleanos** [comment]
@jagadeeshthegeek what version of meanjs are you running? We fixed an issue with that. Can you check the most recent version in master?

**Comment by jagadeeshthegeek** [comment]
@mleanos I am referring the master code.

https://github.com/meanjs/mean/blob/master/modules/core/server/controllers/core.server.controller.js

**Comment by mleanos** [comment]
Can you explain what the exact issue is, and where it's occurring?

See this PR: https://github.com/meanjs/mean/pull/1149

In particular we added the logic to handle the missing `_id` field.

https://github.com/meanjs/mean/blob/master/modules/articles/client/views/view-article.client.view.html#L5
https://github.com/meanjs/mean/blob/master/modules/articles/server/controllers/articles.server.controller.js#L38

Does this not work for you?

**Comment by jagadeeshthegeek** [comment]
@mleanos Actually I got it from Yeoman Generator and it was like this. I think the latest might work.

**view-article.client.view.html**  --My Code look like this
```

 <div class="pull-right" ng-show="authentication.user._id == article.user._id">
    <a class="btn btn-primary" ui-sref="articles.edit({articleId: article._id})">
      <i class="glyphicon glyphicon-edit"></i>
    </a>
    <a class="btn btn-primary" ng-click="remove();">
      <i class="glyphicon glyphicon-trash"></i>
    </a>
  </div>
```

`article.isCurrentUserOwner`  --I feel this **work around is not required** if u follow the below line change. Otherwise we have to do handle that in each new module read/view page.

Just add this `_id` line in **core.server.controller.js**, everywhere you will be getting the user._id

```
exports.renderIndex = function (req, res) {

  var safeUserObject = null;
  if (req.user) {
    safeUserObject = {
      _id: validator.escape(req.user._id),
      displayName: validator.escape(req.user.displayName),
      provider: validator.escape(req.user.provider),
      username: validator.escape(req.user.username),
      created: req.user.created.toString(),
      roles: req.user.roles,
      profileImageURL: req.user.profileImageURL,
      email: validator.escape(req.user.email),
      lastName: validator.escape(req.user.lastName),
      firstName: validator.escape(req.user.firstName),
      additionalProvidersData: req.user.additionalProvidersData
    };
  }

  res.render('modules/core/server/views/index', {
    user: safeUserObject
  });
};
```

**Comment by jolacaleb** [comment]
validator shows an error when I use req.user._id as a parameter.
```
validator deprecated you tried to validate a object but this library (validator.js)
 validates strings only. Please update your code as this will be an error soon.
```

So I changed the code as below:
```javascript
_id: validator.escape(req.user._id.toString()), // validator deprecated.
// _id: validator.escape(req.user._id + '') also works.
```

I think validator think '_id' field as a kind of object.

I'm using meanjs v.0.5.0 beta.
Any opinion?

**Comment by lirantal** [comment]
@codydaig could you take a look? and figure out also what is that deprecation notice from the module?

**Comment by mleanos** [comment]
I want to note that we've removed the `_id` field from the `safeUserObject`. Also, instead of using `_id`, you can use `id`; you wouldn't need to use `.toString()` in that case.

@jolacaleb Where do you see the deprecation message?

**Comment by jolacaleb** [comment]
Sorry for late response. I've been so busy to work on other stuff and I completely forgot this issue..

After the server starts running, the deprecation message shows up when I connect to localhost:3000 in development mode. I didn't test it in production mode, and it's a server-side message.

and as @lirantal mentioned, I changed '._id' to '.id,' and no deprecation message shows up and am able to use id field in Authentication service.

**Comment by Xyroid** [comment]
I read [this blog](http://zklinger2000.github.io/blog/2016/03/11/customize-user-model-means). It recommends to not add userId in `safeUserObject`, since once anyone has this value, any request authorized to that User would be available, like updating the password and email, thus, taking over their account.

So what could be best strategy to keep userId or token on client side?

**Comment by ilanbiala** [comment]
@mleanos can this issue be closed?

**Comment by lirantal** [comment]
@jagadeeshthegeek @mleanos I don't see anything broken with the functionality of articles even when the _id field is missing. Do open up the thread if there's an issue we miss.
