### ISSUE TITLE
`bower install` yields "Unable to find a suitable version for angular"

### ISSUE THREAD

**Issue by 0x24a537r9** [meanjs/mean#1267]
On a fresh git pull of the current HEAD, running `bower install` fails to find a "suitable version for angular":

Unable to find a suitable version for angular, please choose one:
    1) angular#~1.2.11 which resolved to 1.2.29 and is required by angular-file-upload#1.1.5
    2) angular#^1.1.5 which resolved to 1.3.17 and is required by angular-file-upload#2.2.0
    3) angular#^1.0.8 which resolved to 1.3.17 and is required by angular-ui-router#0.2.18
    4) angular#1.3.17 which resolved to 1.3.17 and is required by angular-messages#1.3.17
    5) angular#1.3.18 which resolved to 1.3.18 and is required by angular-animate#1.3.18
    6) angular#1.5.0 which resolved to 1.5.0 and is required by angular-animate#1.5.0, angular-messages#1.5.0, angular-mocks#1.5.0, angular-resource#1.5.0
    7) angular#>=1.4.0 which resolved to 1.5.0 and is required by angular-bootstrap#1.2.4
    8) angular#>=1.3.0 which resolved to 1.5.0 and is required by angular-bootstrap#0.13.4
    9) angular#>= 1.0.8 which resolved to 1.5.0 and is required by angular-ui-router#0.2.15
    10) angular#~1.5.0 which resolved to 1.5.0 and is required by meanjs
    11) angular#>= 1.0.2 which resolved to 1.5.0 and is required by angular-ui-utils#3777381cf2

I think this is a result of @trendzetter 's commit 500d1a6, which may have introduced some ambiguity. I'm not sure how to actually fix this issue, but I feel like this should not be happening.

**Comment by ilanbiala** [comment]
@0x24a537r9 please try using the latest code from master, your dependency versions seem out of date.
