### ISSUE TITLE
Remove in Article -> Add callback

### ISSUE THREAD

**Issue by marianoqueirel** [meanjs/mean#1274]
> mean/modules/articles/client/controllers/articles.client.controller.js

```
function remove() {
  if ($window.confirm('Are you sure you want to delete?')) {
    vm.article.$remove($state.go('articles.list'));
}
```
I think it would be better to do as follow: 

```
function remove() {
  if ($window.confirm('Are you sure you want to delete?')) {
    vm.article.$remove(function (){
      $state.go('articles.list'));
    });
}
```
In Order to do so with a callback, and so it en the next digest.

**Comment by ilanbiala** [comment]
@marianoqueirel there should actually be error handling as well. Can you make a PR so we can fix this code a bit?

**Comment by jamviking** [comment]
This patch actually fixes a bug in 0.5 where the list still displays the deleted record after deletion.

I have not observed the bug in 0.4.2.

**Comment by ilanbiala** [comment]
@marianoqueirel can you make a PR with your code with @jamviking's typo fix?

**Comment by marianoqueirel** [comment]
sure! @ilanbiala, I'm going to do, and Make my first PR.

**Comment by xiandalisay** [comment]
I'm also experiencing this issue. I deal with images associated with the article

**Comment by lirantal** [comment]
@xiandalisay , @marianoqueirel will you open a PR please to fix this?

**Comment by lirantal** [comment]
@ilanbiala @xiandalisay @marianoqueirel one of you would like to open a PR for this fix?
@hyperreality or you? :)

**Comment by hyperreality** [comment]
@lirantal Sure, I'll take a look at it sometime in the next few days.
