### ISSUE TITLE
On small screen devices (width less than 767px), the expanded navbar covers the main page content.

### ISSUE THREAD

**Issue by generalgmt** [meanjs/mean#1275]
Steps: 
1. Reduce the screen size to 767px orr . 
2. click on the collapsible button to expand the nav bar.
 After this, you will see the expanded nav bar covering the content section as shown in the images bellow:
<img width="395" alt="screen shot 2016-03-19 at 3 21 26 pm" src="https://cloud.githubusercontent.com/assets/7859083/13899409/b4ca3240-eded-11e5-83e1-8a3308ac23be.png">

It will be great experience to have an enhancement to the boiler plate that keeps the main page visible as users dropdown the menu instead of covering the main page. This change overall gives a better User Experience.

**Comment by generalgmt** [comment]
After adding a position attribute of "relative" here is how it will look like:
<img width="806" alt="screen shot 2016-03-19 at 4 16 54 pm" src="https://cloud.githubusercontent.com/assets/7859083/13899418/0c433ecc-edee-11e5-8c14-7091c8a7b910.png">

**Comment by ilanbiala** [comment]
@mleanos have you noticed this? @generalgmt we aren't really building a UI framework so this isn't a top priority, but if this fix causes no other issues then I'm fine merging it in.

**Comment by lirantal** [comment]
Obviously if this fixes a UI issue we should go for it.

**Comment by d3dc** [comment]
How is this different from the bootstrap class _navbar-static-top_ ?

**Comment by trendzetter** [comment]
I think this is interesting, I am having some issues with navigation too and I want to return to as close as possible to the mainstream bootstrap way of things.

**Comment by ilanbiala** [comment]
@trendzetter does navbar-fixed-top fix this issue?

**Comment by generalgmt** [comment]
@d3dc, yeah that is exactly what navbar-static-top does. Thanks for pointing that out.

**Comment by trendzetter** [comment]
@ilanbiala it does solve the issue in the title + I just checked if my application works with navbar-static-top and it is compatible. I suggest to remove the relative-header, probably I am not the only one having gui issues as a result.

**Comment by ilanbiala** [comment]
@trendzetter can you make a PR for that?
