### ISSUE TITLE
My think at backend

### ISSUE THREAD

**Issue by incNick** [meanjs/mean#1277]
Some pseudocode below, I think you can know what is my think.
```
var policy = {
    invokeRolesPolicies: function(){},
    isAllowed: function(req, res, next){
        var thePolicy = false;
        if (req.model) {
            if (req.model.policy) {
                thePolicy = req.model.policy;
            } else {
                thePolicy = require('default.restful.policy.js');
            }
            thePolicy.invokeRolesPolicies();
            retuen thePolicy.isAllowed(req, res, next);
        }
        return next();
    }
};
var RESTController= {
    this.save = function(req, res){...};
    this.delete= function(req, res){...};
    this.read = function(req, res){...};
    this.list = function(req, res){...};
    this.loadModel = function(req, res, next, modelName){
        req.model = moogoose.model(modelName);
        next();
    };
    this.loadData = function(req, res, next, dataId){
        req.data = req.model.findById(dataId);
        next();
    };
}
app
    .route('/rest/:model')
    .all(policy.isAllowed)
    .get(RESTController.list)
    .post(RESTController.save)
;
app
    .route('/rest/:model/:id')
    .all(policy.isAllowed)
    .get(RESTController.read)
    .put(RESTController.save)
    .delete(RESTController.delete)
;
app.param('model', RESTController.loadModel);
app.param('id', RESTController.loadData);
```
so, for backend of article, we only need 2 files:
1- articles/server/models/articles.server.model.js
2- articles/server/policies/articles.server.policy.js
and may can move above 2 files to same directory, like
model.policy = require('./policy.js');

**Comment by Berkmann18** [comment]
This issue lacks in information about what you're trying to do, what are/is the issue(s) you're facing, what have you tried to do to solve the problem.

**Comment by trendzetter** [comment]
Your suggestion is not clear. Are you suggesting meanjs should use less files? Why?

**Comment by Wuntenn** [comment]
It looks like @incNick wants to reduce the articles files to
- articles.server.policy.js; (which I assume is his pseudo code above which inlines the routes, controller and policy files into a file called... articles.server.policy.js)** 
- articles/server/models/articles.server.model (which I assume remains as is)

@incNick: This might be a refactor that will work for you to create a simple app. You could even put everything in one file, however this goes backward from MeanJS's current modular composition/philosophy.

**Comment by lirantal** [comment]
No clarity as to the issue on this thread, closing.
