### ISSUE TITLE
eslint is making annoying remarks when if and else declare same variable name

### ISSUE THREAD

**Issue by trendzetter** [meanjs/mean#1278]
I don't think this is needed. Nor for style nor because it is an error in javascript. It's just annoying having to rename your variables or look at the buzz on screen and use --force 

> line 164, col 20, 'i' is already defined.

**Comment by trendzetter** [comment]
example code:
```
function(){
for (var i = 0; i < someArray.length; i++) {
   ...
}

for (var i = 1; i < moreArray.length; i++) {
  ...
}
}
```

**Comment by rhutchison** [comment]
```javascript
function(){
  var i;

  for (i = 0; i < someArray.length; i++) {
    ...
  }

  for (i = 1; i < moreArray.length; i++) {
    ...
  }
}
```

**Comment by trendzetter** [comment]
@rhutchison that is indeed suppressing the message but still, not needed according to best practices, I would even recommend against putting the variable in a higher scope.

**Comment by Dollab** [comment]
The variable is not being put in a higher scope. It is already in this
scope (
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for#Parameters).
This is precisely the reason why it is bad practice to declare it twice.
The better practice I think is to use different loop variable names when
using two loops in the same function.

**Comment by ilanbiala** [comment]
@trendzetter which code (line numbers in files) specifically?

**Comment by trendzetter** [comment]
@Dollab I didn't know that about the for variables. Could it be specific to javascript?
It's also giving me the same warning on something like this:
if(form.vm.check){
  var car = form.vm.field2;
  ...
} else {
  var car = form.vm.field1;
  ...
}
Is this also already added to the higher scope?

@ilanbiala I encounter this using the meanjs framework to develop my own app.

**Comment by Dollab** [comment]
Yes. It is specific to js. There are no block scopes apart from try/catch
statements, only global and function scopes.

**Comment by lirantal** [comment]
I think @Dollab provided the correct answers here, we can close this Ilan.
