### ISSUE TITLE
UNMET PEER DEPENDANCY

### ISSUE THREAD

**Issue by truthstands** [meanjs/mean#1280]
When I run, `npm install --save yelp`. I get the following results:

`UNMET PEER DEPENDENCY eslint-plugin-react@^4.0.0 ├── generator-angular@0.15.1 extraneous └── UNMET PEER DEPENDENCY generator-karma@>=0.9.0`

What is the best way to resolve this? Is there another easy way to setup Yelp OAuth?

**Comment by ilanbiala** [comment]
`npm install yelp`? This doesn't seem related to our code.
