### ISSUE TITLE
replace 'swig' package with a proper solution

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#1286]
We use the 'swig' package (https://github.com/paularmstrong/swig) for server side templates rendering but this package has been abandoned by it's maintainer and also includes a vulnerability that must be fixed yet no releases area available for it. 

![image](https://cloud.githubusercontent.com/assets/316371/14117090/ada89b22-f5eb-11e5-8c9b-cfac45a5abca.png)

I'm open to recommendations for a proper replacement.

**Comment by simison** [comment]
Author recommends https://mozilla.github.io/nunjucks/

**Comment by simison** [comment]
Some reading:
- https://strongloop.com/strongblog/compare-javascript-templates-jade-mustache-dust/
- They seem to be using [Liquid](https://shopify.github.io/liquid/) for Express docs.

**Comment by AttilaSATAN** [comment]
Nunjucks is a good and solid alternative

**Comment by simison** [comment]
This article recommends Nunjucks: https://medium.com/@andy.neale/nunjucks-a-javascript-template-engine-7731d23eb8cc#.r4pk2ao30

Seems to be good for a boilerplate since it has potential for more complex stuff but it's still fairly simple and in this case quite similar to good ol' Swig.

**Comment by lirantal** [comment]
Cool I'll take a look. Thanks @simison

**Comment by ilanbiala** [comment]
Nunjucks looks fine to me.

**Comment by simison** [comment]
@hyperreality wrote https://github.com/meanjs/mean/issues/1440#issuecomment-241260324:

>It's hard to make the call. As far as features go they're both fantastic. Nunjucks is more actively maintained but Handlebars is getting about 20 times the amount of downloads according to NPM, and I've seen Handlebars used way more in the wild. If nothing else, there is probably more info about Handlebars out there and users are more likely to be comfortable using it.
>
>This may be a [Buridan's ass](https://en.wikipedia.org/wiki/Buridan%27s_ass) situation where both choices are equally as good and the worst thing is being stuck in the state of indecision and not choosing either.

**Comment by Ankur-Marwaha** [comment]
See if we can go with handlebars ( easy to learn, widely used ) and still if in the future we had to switch to some other templating engine it would not be that hard of a job. Lets get the solution ASAP.

**Comment by lirantal** [comment]
Indeed, working on it.

**Comment by lirantal** [comment]
Hey guys,
Check out the new handlebars template system in PR #1461 

cc @simison @Ankur-Marwaha @hyperreality @ilanbiala

**Comment by ilanbiala** [comment]
LGTM.
