### ISSUE TITLE
docker-compose error while building form Dockerfile 

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1291]
Ubuntu image error shown at image below

![screen shot 2559-04-04 at 12 22 58](https://cloud.githubusercontent.com/assets/1640817/14238887/258ca2b4-fa60-11e5-9367-27ca959ccf84.png)

I move form mean.io and docker is work fine so I have a question about meanjs: Why not Dockefile use ubuntu image if it use nodejs stand alone like https://github.com/linnovate/mean/blob/master/Dockerfile it is better way?

**Comment by lirantal** [comment]
@avatarr looks like an ubuntu image related error, or possibly you're unable to resolve?
An Ubuntu image is more standard and close to how you would be developing locally or what you will be deploying to production, and also you can easily install whatever extra dev tools/libraries you will need so it makes more sense to me.

**Comment by avatarr** [comment]
Thank for reply so I will retry to use other version of ubuntu
