### ISSUE TITLE
Running an AngularJS App in Production

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1294]
Two things from https://docs.angularjs.org/guide/production

- [ ] Disabling Debug Data
- [x] Strict DI Mode

Thoughts how to implement these?

**Comment by codydaig** [comment]
I think to disable debug data, we have to somehow load config into the client side. This is something that has come up a lot, but has not been implemented. 

However, I think we can do the strict DI mode with the index.html template in swig.

**Comment by pgrodrigues** [comment]
I opened a [similar issue](https://github.com/meanjs/mean/issues/903) a few months ago.

**Comment by lirantal** [comment]
Will you guys work on a PR for this, sounds like a good idea.

**Comment by lirantal** [comment]
@simison you handled in the recent PR #1457  the debug data. What about the ng-strict-di? how do we handle that?
