### ISSUE TITLE
fresh clone, then gulp and I get "SyntaxError: Use of const in strict mode."

### ISSUE THREAD

**Issue by ervine13** [meanjs/mean#1295]
Just 15 minutes ago,

1. I cloned
2. ran NPM install
3. ran gulp 

then I got the following error

/Users/ErvinEbalo/workspace/project_mealBuilder/mealBuilder/node_modules/connect-mongo/src/index.js:3
const Promise = require('bluebird');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

I do something wrong?

**Comment by lirantal** [comment]
You are probably running a version of nodejs which we don't support.
Which node version do you have installed?

**Comment by ervine13** [comment]
thanks, @lirantal. that was it. silly me.

**Comment by simison** [comment]
@lirantal is https://github.com/meanjs/mean/blob/master/package.json#L14-L15 up to date?

**Comment by lirantal** [comment]
actually no, nodejs engine there should be v4, npm v2
