### ISSUE TITLE
Should gulp test:server:watch default to "onlyChanged"?

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1297]
This:
```
gulp test:server:watch --onlyChanged
```
...should really be default when hitting that test-watch task (`gulp test:server:watch`).

Are there situations when you'd want to run all the tests when changing something at a single test file? Wouldn't it be enough to run all the tests only at the end of development manually?

Thoughts?

**Comment by mleanos** [comment]
I think defaulting to only running a changed test is a good idea. I don't really see a need to run all tests again, after changing a single test file.

**Comment by ilanbiala** [comment]
SGTM.

**Comment by mleanos** [comment]
@simison I'll submit a PR for this change, since I introduced this task.
