### ISSUE TITLE
generators regenerate the whole project

### ISSUE THREAD

**Issue by c-rodrigo** [meanjs/mean#13]
I'm trying to generate a crud-module (on windows) and yo generator tries to re generate the whole project
![mean](https://cloud.githubusercontent.com/assets/1656288/2625936/35327136-bdb2-11e3-8981-7f06427a2a2c.PNG)

**Comment by rahil051** [comment]
@amoshaviv @c-rodrigo  but the issue wasnt fixed for me while using
sudo npm update -g generator-meanjs

I am on a Ubuntu 14.04 machine, and the generator-meanjs version I am using is 0.4.1 (I think this is the latest one)
the meanjs I have installed from yo generator is 0.4.1 (latest mean.js) and my yo version is 1.4.8

But still when trying to create a module inside my meanjs directory, it's generating the entire project ?

**Comment by lirantal** [comment]
@rahil051 this one is quite an old discussion.
Just a clarification, the generator for the latest version (v0.4) doesn't support sub-generators like the older one. We are working on getting those on-board but their not there yet.
