### ISSUE TITLE
[Question] Which framework should I use for the module management/system to use MEAN.js

### ISSUE THREAD

**Issue by Berkmann18** [meanjs/mean#1307]
Hello I want to get into full stack web development so after making some research on frameworks (for web dev. obviously), I saw that the MEAN.JS (not the .io one) stack (MongoDB+Express.js+Angular 2+Node.js) was the way to go especially as I'm more oriented Front-End so DHTML (HTML+CSS+JS) over PHP&MySQL and that I'm not used to the LAMP stack (Linux+Apache+MySQL+PHP).

The ick is that there's several frameworks/libraries which take care of the module management/system:
-RequireJS (AMD)
-CommonJS (used by Node.js)
-SystemJS (used by Angular here: https://github.com/gocardless/angularjs-style-guide#third-party-dependencies)
-Browserify.js
-Webpack
And ES6 (official name ECMAScript 2016 aka JavaScript v6) has it's own module management/system

So I'm confused wether to stick with just ES6 (for the module management/system) or go for one of those frameworks to complete the MEAN stack.

What are the pros and cons of each of them and which one would have the best pro/con ration regarding their use with MEAN.js and what would you recommend.
Thanks in advance :).

Also (if that may help you understand why I'm asking all of this), I'm going to learn ES6, Bootstrap and probably jQuery despite: 
    -not being recommended by Angular developpers and that: http://dancancro.com/meanio_vs_meanjs.html
    -I have own library that does mostly of what jQuery does (with a lot of other stuff too)

**Comment by Wuntenn** [comment]
If you look in the config directory, you will see that the files are required() using Node.js (CommonJS), however you should be able use what suits you.

You'll probably have to do your own research on which is better than what - it will be different for each dev.

In Meanjs there's already a system in place to require the modules that you want and it works automatically if you follow the folder conventions. Look inside: [https://github.com/meanjs/mean/tree/master/config/assets](https://github.com/meanjs/mean/tree/master/config/assets)
to get a feel for what's needed.
