### ISSUE TITLE
Installation Script has errors

### ISSUE THREAD

**Issue by iakcaoglu** [meanjs/mean#1310]
Hi, 
I am looking for a good alternative to develop a nodejs app and MEAN.js seem to be a good starting point for me. But when I tried to intall in li,nuz and windows I get Errors and Deprecated packages. These should be updated somehow? The log file is attached.
Thanks,
[npm-debug.log.txt](https://github.com/meanjs/mean/files/217009/npm-debug.log.txt)

**Comment by simison** [comment]
>162525 verbose stack Error: meanjs@0.4.2 postinstall: `bower install --config.interactive=false`

Does running `bower install` directly work for you?

**Comment by iakcaoglu** [comment]
No it gives the following error.
"bower ENOGIT git is not installed or not in the PATH"

**Comment by simison** [comment]
There's your problem. :-)

Install `git` and try again https://git-scm.com/downloads

**Comment by ilanbiala** [comment]
@iakcaoglu fixed?

**Comment by iakcaoglu** [comment]
Installed GIT, Then needed python 2.7. I also installed it.
After all steps it is fixed.

**Comment by ilanbiala** [comment]
@iakcaoglu why did you need Python 2.7?
