### ISSUE TITLE
Should all js be bundled when deployed to Heroku?

### ISSUE THREAD

**Issue by ChrisMaher** [meanjs/mean#1311]
I have a problem with a site that loads slowly and after asking on Stackoverflow everyone said that there is far too many js files

There is 71.

What i noticed is that its loading all the non third party js files seperately. Is this wrong? i.e routes, views etc.

Heres the URL.

http://saveme.ie/

**Comment by ilanbiala** [comment]
You can concatenate those files and see if that helps.

**Comment by ChrisMaher** [comment]
Well then my question is how do i bundle them?

**Comment by ilanbiala** [comment]
Check out gulp-concat and see if concatenating into 1 script will load faster.

**Comment by simison** [comment]
@Ilanbala Gulpfile should actually have a `build` task that's suitable for production env.

**Comment by simison** [comment]
Confusing...

[Build task](https://github.com/meanjs/mean/blob/master/gulpfile.js#L365-L367):
```javascript
// Lint project files and minify them into two production files.
gulp.task('build', function (done) {
  runSequence('env:dev', 'wiredep:prod', 'lint', ['uglify', 'cssmin'], done);
});
```
Odd to see both `env:dev` and `wiredep:prod`?

[Wiredep task](https://github.com/meanjs/mean/blob/master/gulpfile.js#L200-L206) 
...isn't used anywhere. Was this meant for development?

**Comment by ilanbiala** [comment]
prod I think uses minified files.

**Comment by simison** [comment]
@ilanbiala `prod` task also runs the app, so it's not really suitable for _building_ the prod version.

**Comment by ilanbiala** [comment]
Sorry, I meant wiredep:prod uses the minified files for wiredep.

**Comment by ChrisMaher** [comment]
On HEROKU you need to go to env vars in settings and add

NODE_ENV production

Then use grunt build before deploying to Heroku.

Cuts loading time to about 1/5th on my site.

**Comment by ilanbiala** [comment]
@ChrisMaher can you make a PR to add that to our documentation for Heroku?

**Comment by lirantal** [comment]
@ilanbiala I think we actually need a better production build maybe?
