### ISSUE TITLE
browserSync support with gulp

### ISSUE THREAD

**Issue by nikitpatel24** [meanjs/mean#1313]
I am trying to add browser sync instead of livereload.
But i am getting a Cannot get error.
Can it be resolved.
It would be nice to integrate Browser-sync with the new update

`

`
[gulpfile.txt](https://github.com/meanjs/mean/files/221640/gulpfile.txt)

**Comment by simison** [comment]
What's the reasoning using BrowserSync instead of Livereload?

**Comment by nikitpatel24** [comment]
BrowserSync uses connect under the hood.

It has support for all the 'live-reload' features (it was specifically built as a replacement).

It has greater browser support (right back to IE7)

The middleware for injecting scripts is all included, it 'just works'

It has port-resolution built in so there's no need for hard-harded ports in the gulpfile.

Supports streams for better file injecting/reloading
It has 'ghost mode' that will synchronize clicks, scroll & form input.

It uses socket.io which provides real time update like using ng-model with no reloads.

**Comment by ilanbiala** [comment]
Is there anything that it specifically does better than Livereload?

**Comment by lirantal** [comment]
@nikitpatel24 you're welcome to open a PR enhancement.
