### ISSUE TITLE
Errors due to some chages

### ISSUE THREAD

**Issue by sparshy** [meanjs/mean#1319]
https://github.com/meanjs/mean/blob/master/modules/users/client/controllers/settings/edit-profile.client.controller.js#L8

the controller should inject `UsersService` instead of `Users`

https://github.com/meanjs/mean/blob/master/modules/users/client/controllers/settings/manage-social-accounts.client.controller.js#L20

user is on `vm` instead of $scope

**Comment by trendzetter** [comment]
bug. would you be willing to create a PR?

**Comment by pgrodrigues** [comment]
The first one was already addressed via this [PR](https://github.com/meanjs/mean/pull/1283/commits).
The second I'm not sure.

**Comment by lirantal** [comment]
Seems fixed as well, closing.
@sparshy let me know if you think there's a fix that should go in order.
