### ISSUE TITLE
Angular Version?

### ISSUE THREAD

**Issue by suhailameen46** [meanjs/mean#1321]
which version of angular does it use?

and why does `$ yo meanjs:angular-module <module-name>` does not work?

**Comment by simison** [comment]
This should probably be under https://github.com/meanjs/generator-meanjs

**Comment by ilanbiala** [comment]
Angular 1.5 will be used for MEAN 0.5.0.

**Comment by Caoimhin89** [comment]
I'm new to Meanjs. Can Angular 2 be safely used with the current version?

**Comment by codydaig** [comment]
@Caoimhin89 If you were to strip out all the frontend code and replace it with Angular 2 it will work, but just swapping them will cause things to break.
