### ISSUE TITLE
Setting up HTTP/2

### ISSUE THREAD

**Issue by aralroca** [meanjs/mean#1323]
Just I read this article and I thought that maybe setting up **HTTP/2** in Mean.JS is a good idea:

* **Article:** https://surma.link/things/h2setup/

What do you think?

**Comment by aralroca** [comment]
**What is HTTP/2?**: http://codeahoy.com/2016/04/23/what-is-http2/

**Comment by Berkmann18** [comment]
Yeah, it's definitely a good idea.

**Comment by lirantal** [comment]
It is but HTTP/2 isn't yet supported as part of ExpressJS so I guess we'll wait with that.

**Comment by aralroca** [comment]
**http2** provides an API similar to Node’s standard HTTP server.

    var fs = require('fs');
    var http2 = require('http2');
    var options = {
      key: fs.readFileSync('/path/to/server.key'),
      cert: fs.readFileSync('/path/to/server.cert')
    };
    http2.createServer(options, function(request, response) {
      response.end('Hello world!');
    }).listen(8080);

**Comment by lirantal** [comment]
We can discuss it later when Express actually supports this. As long as it doesn't and we don't intend to move out of Express this isn't relevant.
Thanks anyway for enlightning us @aralroca!
