### ISSUE TITLE
App not showing up on localhost:3000 and the Requests Logs in   "version": "0.3.3"

### ISSUE THREAD

**Issue by prasad47** [meanjs/mean#1324]
Hi Guys,

I have meanjs version 0.3.3 . When i used command **grunt** .Server started but finally it is not showing the message  "server started with **localhost:3030/** " and keep on showing **waiting .....** Please find the attachment for the clear view of my issue 
Unfortunately we cannot able to upgrade to another meanjs versions currently .
Uploading Screen shot of problem . 
 
![f293226e-0bd7-11e6-8feb-8ec81b1c2693](https://cloud.githubusercontent.com/assets/6585745/14820739/81dfc960-0be5-11e6-8ed8-309058496820.jpg)

I am Having grunt-nodemon 0.3.0(not changed) .i cannot see whats is happening to debug or Understand the responses of requests etc :-(.

Could you Guys Please Suggest How to see the responses of localhost etc

**Comment by ilanbiala** [comment]
We don't support Mean 0.3.3 anymore, we'll be releasing 0.5.0 in the near future if you would like to start looking at the code in the master branch.

**Comment by prasad47** [comment]
node server.js worked like magic . Sure thanks for the help .
