### ISSUE TITLE
Installation issue : error

### ISSUE THREAD

**Issue by younesherlock** [meanjs/mean#1325]
Hello,

I got the following error while installing meanjs : 

> 21246 error System Linux 3.19.0-32-generic
> 21247 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "--dev"
> 21248 error cwd /home/vendetta/Documents/Projects/meanjs
> 21249 error node -v v0.10.25
> 21250 error npm -v 1.3.10
> 21251 error path /root/tmp/npm-7543-feYMQKua/1461705437899-0.33092925092205405/package/.npmignore
> 21252 error fstream_path /root/tmp/npm-7543-feYMQKua/1461705437899-0.33092925092205405/package/.npmignore
> 21253 error fstream_type File
> 21254 error fstream_class FileWriter
> 21255 error fstream_finish_call utimes
> 21256 error code ENOENT
> 21257 error errno 34
> 21258 error fstream_stack /usr/lib/nodejs/fstream/lib/writer.js:305:19
> 21258 error fstream_stack Object.oncomplete (fs.js:107:15)
> 21259 verbose exit [ 34, true ]

Do you have any idea of how I may solve this ?

**Comment by ilanbiala** [comment]
You can't use Node 0.10, try using Node 4.

**Comment by lirantal** [comment]
Thanks @ilanbiala
