### ISSUE TITLE
Issue with 'Application Generator'

### ISSUE THREAD

**Issue by coolshul** [meanjs/mean#1330]
Hello,

Sorry if this is a duplicate issue. I am new to the MEAN arena. And have been scratching my head over the below errors with no success yet:

Steps I executed:
1. Installed node (v4.4.3) (success)
2. Installed mongodb (v3.0.2) (success)
3. Updated npm (to v3.8.8) (success)
4. Installed bower (v1.7.9) (success)
5. Installed grunt-cli (v1.2.0) (success)
6. Install yo (v1.7.0) (success)
7. Install generator-meanjs (success)
8. $ yo mean js
_
This is the step where I get the following errors:_

1 warning and 10 errors generated.
make: *** [Release/obj.target/debug/src/debug.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/.../Finances/Finances/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/.../Finances/Finances/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/.../Finances/Finances/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node" "--module_name=debug" "--module_path=/.../Finances/Finances/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64"
gyp ERR! cwd /.../Finances/Finances/node_modules/v8-debug
gyp ERR! node -v v4.4.3
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /.../Finances/Finances/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/.../Finances/Finances/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/.../Finances/Finances/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/.../Finances/Finances/node_modules/v8-debug/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:827:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "/usr/local/bin/node" "/.../Finances/Finances/node_modules/v8-debug/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /.../Finances/Finances/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 
npm WARN mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! Darwin 14.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.8
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /.../Finances/Finances/npm-debug.log

    at ChildProcess.exithandler (child_process.js:213:12)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:477:12)

Not sure, what is going wrong. Would appreciate help on this issue.

Thanks,
Harshul

**Comment by csharpee** [comment]
I am also new to MEAN - If this helps, try checking out




‪♯‎Light‬ ‪♯‎Love‬ ♯Unity‬ - Charles B <http://www.sharpetronics.com>.
Sharpe
-------------
 Prepare For Change Network:    Intel <http://2012portal.blogspot.com/> *|*
News <http://www.theeventchronicle.com/> *|* Reference
<http://www.eventreference.org/> *|* Collaborate
<http://www.prepareforchange.net/> *|* Connect <http://coeo.cc/>
    *Twitter:*       C♯ <https://twitter.com/wodanzu>     *    Facebook:
 * C♯ <https://www.facebook.com/WodAnZu>

**Comment by csharpee** [comment]
install Python 2.7.x
install Microsoft Visual Studio C++ 2012 Express
Run NPM update
$ npm update -g



‪♯‎Light‬ ‪♯‎Love‬ ♯Unity‬ - Charles B <http://www.sharpetronics.com>.
Sharpe
-------------
 Prepare For Change Network:    Intel <http://2012portal.blogspot.com/> *|*
News <http://www.theeventchronicle.com/> *|* Reference
<http://www.eventreference.org/> *|* Collaborate
<http://www.prepareforchange.net/> *|* Connect <http://coeo.cc/>
    *Twitter:*       C♯ <https://twitter.com/wodanzu>     *    Facebook:
 * C♯ <https://www.facebook.com/WodAnZu>

**Comment by coolshul** [comment]
Thanks @csharpee for your quick reply. 
I see that I am running the latest stable version of npm. Would installing Python & updating still make a difference? 

Thanks,
Harshul

**Comment by csharpee** [comment]
If you are using node-gyp,, this uses python and could be causing the
errors for out of date.

See requirements here: hhttps://github.com/nodejs/node-gyp#installation



‪♯‎Light‬ ‪♯‎Love‬ ♯Unity‬ - Charles B <http://www.sharpetronics.com>.
Sharpe
-------------
 Prepare For Change Network:    Intel <http://2012portal.blogspot.com/> *|*
News <http://www.theeventchronicle.com/> *|* Reference
<http://www.eventreference.org/> *|* Collaborate
<http://www.prepareforchange.net/> *|* Connect <http://coeo.cc/>
    *Twitter:*       C♯ <https://twitter.com/wodanzu>     *    Facebook:
 * C♯ <https://www.facebook.com/WodAnZu>

**Comment by csharpee** [comment]
@coolshul, I just tested out your install and it worked for me, so it must
be something related to your environment / setup.

Let me know if the python was the issue.



‪♯‎Light‬ ‪♯‎Love‬ ♯Unity‬ - Charles B <http://www.sharpetronics.com>.
Sharpe
-------------
 Prepare For Change Network:    Intel <http://2012portal.blogspot.com/> *|*
News <http://www.theeventchronicle.com/> *|* Reference
<http://www.eventreference.org/> *|* Collaborate
<http://www.prepareforchange.net/> *|* Connect <http://coeo.cc/>
    *Twitter:*       C♯ <https://twitter.com/wodanzu>     *    Facebook:
 * C♯ <https://www.facebook.com/WodAnZu>

**Comment by csharpee** [comment]
Also, step 8 should have no spaces between the 'meanjs' - with a space,
this only installed node modules, rather than the application.

See this link: http://meanjs.org/generator.html#application



‪♯‎Light‬ ‪♯‎Love‬ ♯Unity‬ - Charles B <http://www.sharpetronics.com>.
Sharpe
-------------
 Prepare For Change Network:    Intel <http://2012portal.blogspot.com/> *|*
News <http://www.theeventchronicle.com/> *|* Reference
<http://www.eventreference.org/> *|* Collaborate
<http://www.prepareforchange.net/> *|* Connect <http://coeo.cc/>
    *Twitter:*       C♯ <https://twitter.com/wodanzu>     *    Facebook:
 * C♯ <https://www.facebook.com/WodAnZu>

**Comment by coolshul** [comment]
Thanks @csharpee. Tried installing Python 2.7. No luck yet! :(

**Comment by simison** [comment]
@coolshul everything else listed at https://github.com/nodejs/node-gyp#installation done?

**Comment by coolshul** [comment]
On it.

**Comment by coolshul** [comment]
Thanks a bunch @csharpee & @simison for your time. 

I did:

1. npm install -g node-gyp

2. I have Python (v2.7)

3. I have 'gcc' 
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.1.0

4. I have 'make' (GNU Make 3.81)

Still same set of errors. Do I need to generate binding.gyp file manually?

Thanks,
Harshul

**Comment by genru** [comment]
same problem. I use Mac with Xcode7.3.1, python 2.7.10

> node-pre-gyp ERR! node -v v4.4.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.27
node-pre-gyp ERR! not ok 

is my node version is incompatible?

**Comment by socialatm** [comment]
:( Windows just isn't worth the bother. Even with virtualbox it's a pain. I'm setting up a Ubuntu box now.

**Comment by lirantal** [comment]
@coolshul , @socialatm hopes this goes well on Ubuntu :)
