### ISSUE TITLE
Typo in page-title.client.directives.js

### ISSUE THREAD

**Issue by aanev** [meanjs/mean#1332]
Line 11 in "mean/modules/core/client/directives/page-title.client.directives.js" is 

retrict: 'A',

and should be

restrict: 'A',

**Comment by ilanbiala** [comment]
@aanev can you submit a PR?

**Comment by lirantal** [comment]
@aanev you created a PR in your own repo (https://github.com/aanev/mean/pull/1) but you actually need to make the PR for the code change to the meanjs repo so that @ilanbiala can help you merge it.
