### ISSUE TITLE
Safari Error : truncate angular.js

### ISSUE THREAD

**Issue by patouche7519** [meanjs/mean#1333]
Hi guys,
Not sure that the error is global or related to my development environment (OSX, Node 4.4.2) but the master meanjs doesn't work in Safari, it works in Chrome or Firefox

Safari truncate angular.js in the master release
Error message: SyntaxError: Unexpected End of script (angular.js)

**Safari**: Version 9.1 (11601.5.17.1)
**MEANJS**: master

**How to reproduce the error:**
- download the .zip from the master meanjs in github
- npm install
- gulp default

Open localhost in Safari

**Comment by patouche7519** [comment]
FYI, the bug is introduce by angularJS 1.5.5. It works nice with 1.5.4 and older 1.5.x versions

**Comment by Wuntenn** [comment]
Why did you close this? (Maybe it's something we need to fix or warn against)

**Comment by lirantal** [comment]
I don't have a Mac so I can't test this.
@Wuntenn can you test and follow up on this?

**Comment by patouche7519** [comment]
Hi
Understand, I reopen it. I resolved by downgrade my angularjs version in the npm file.
And I know magic doesn't exist but after a few days and works on my website, I modified the npm file to the angularJS 1.5.5 and did a npm update and It works. I have no idea why.

I'm actually in vacation but if you need more informations, ping me, I'll do my best to reply.

**Comment by codydaig** [comment]
I cloned the repo down, ran npm install, and went to the page in Safari and no issues. I am using node v5. However, your right in that it might be a bug with angular 1.5.5 because I'm pretty sure it installed 1.5.7 for me.

**Comment by Wuntenn** [comment]
Sorry guys, I've been a bit fried over the past few days. Not sure why I didn't just test it when I left the comment.

I just did the steps above and it ran first time for me

**Comment by lirantal** [comment]
Great thanks @codydaig and @Wuntenn

**Comment by codydaig** [comment]
@Wuntenn No worries!
