### ISSUE TITLE
How to solve MEAN stack User is not logged in error?

### ISSUE THREAD

**Issue by useralive003** [meanjs/mean#1345]
I have installed MEAN.JS and i am using only server side code .i am not using front end angular code .

I am using different servers. for frontend(client side) i am maintaining one serve, for backend(server side) i am using MEAN.JS .

Signup and Signin is working fine but when i create article i am getting error

"User is not logged in" how can i solve this .please some one help me out.

Routes:

Below My MEAN.JS routes for Article

app.route('/articles')       
    .get(users.requiresLogin,articles.list)
    .post(users.requiresLogin,articles.create);

controller:

exports.create = function(req, res) {

    var article = new Article(req.body);
    article.user = req.body._id;
    article.save(function(err) {
        if (err) {
            return res.status(400).send({
                message: errorHandler.getErrorMessage(err)
            });
        } else {
            res.json(article);
        }
    });
};
Middleware Code :

/**
 * Require login routing middleware
 */
exports.requiresLogin = function(req, res, next) {
    //console.log(req.body.id);

    if (!req.isAuthenticated()) {
        return res.status(401).send({
            message: 'User is not logged in'
        });
    }

    next();

};

My Front end Code

<!DOCTYPE html>
<html>
<head>
<script type="text/javascript" src="http://code.angularjs.org/angular-1.0.1.js"></script>
</head>
<body ng-app="myApp">
  <div ng-controller="MyCtrl"><br><br>
  <input type="text" ng-model="title"><br><br><br>
  <input type="text" ng-model="content"><br><br><br>
  <input type="button" ng-click="submit()" value="submit">
</div>
<script type='text/javascript'>//<![CDATA[

var myApp = angular.module('myApp',[]);
function MyCtrl($scope,$http) {
    $scope.submit = function()
    {
        var article= {

            title: $scope.title,
            content: $scope.content,

        };

    $http.post('http://192.168.1.6:3000/articles', article).success(function (response) {

        console.log(response);

      }).error(function (response) {
        $scope.error = response.message;
        console.log(response.message);
      });

    }
}

</script>

</body>

</html>

i think middleware problem how can i solve this pls help me out i am new to this fullstack

**Comment by eliavmaman** [comment]
Can u please post the code in layout.server.html the user binding part?

**Comment by useralive003** [comment]
signuphtml

**Comment by useralive003** [comment]
myApp.controller('ArticleCtrl', function ($scope,$http) {
$scope.create = function()
{
var credentials = {};
                    credentials = {
                        "title": $scope.title,
                       "content": $scope.content,
                    }
					console.log(credentials);
					$http.post('http://192.168.1.4:3000/articles', credentials).success(function(data, status, headers, config, response) {
					console.log(data);
					});
					console.log(credentials);
}
});

**Comment by lirantal** [comment]
@useralive003 StackOverflow is probably a better place for these questions so I'm closing this issue, but anyone who may have the answer is welcome to reply back on this thread regardless.
