### ISSUE TITLE
Error while starting up from docker file

### ISSUE THREAD

**Issue by prasadh13** [meanjs/mean#1346]
Hello,

I am trying to setup docker and MEANJS. I installed docker and docker-compose and have the latest MEANJS commit.

When I run docer-compose build I get this error - 

`npm info lifecycle ms@0.7.1~install: ms@0.7.1
npm info lifecycle debug@2.2.0~install: debug@2.2.0
npm info lifecycle vary@1.1.0~install: vary@1.1.0
npm info lifecycle methods@1.1.1~install: methods@1.1.1
npm info lifecycle mime@1.2.11~install: mime@1.2.11
npm info lifecycle form-data@0.0.10~install: form-data@0.0.10
npm info lifecycle mime-db@1.12.0~install: mime-db@1.12.0
npm info lifecycle mime-types@2.0.14~install: mime-types@2.0.14
npm info lifecycle form-data@0.2.0~install: form-data@0.2.0
npm info lifecycle minimatch@3.0.0~install: minimatch@3.0.0
npm info lifecycle minimist@0.0.10~install: minimist@0.0.10
npm info lifecycle minimist@0.0.8~install: minimist@0.0.8
npm info lifecycle mkdirp@0.5.0~install: mkdirp@0.5.0
npm info lifecycle grunt-mocha-test@0.12.7~install: grunt-mocha-test@0.12.7
npm info lifecycle utile@0.1.7~install: utile@0.1.7
npm info lifecycle mkpath@0.1.0~install: mkpath@0.1.0
npm info lifecycle isarray@1.0.0~install: isarray@1.0.0
npm info lifecycle isarray@1.0.0~install: isarray@1.0.0
npm info lifecycle ms@0.1.0~install: ms@0.1.0
npm info lifecycle mout@0.9.1~install: mout@0.9.1
npm info lifecycle mpath@0.1.1~install: mpath@0.1.1
npm info lifecycle mpromise@0.4.3~install: mpromise@0.4.3
npm info lifecycle ms@0.7.1~install: ms@0.7.1
npm info lifecycle debug@2.2.0~install: debug@2.2.0
npm info lifecycle ms@0.7.0~install: ms@0.7.0
npm info lifecycle debug@2.1.3~install: debug@2.1.3
npm info lifecycle finalhandler@0.3.3~install: finalhandler@0.3.3
npm info lifecycle muri@1.1.0~install: muri@1.1.0
npm info lifecycle mute-stream@0.0.4~install: mute-stream@0.0.4
npm info lifecycle nan@1.8.4~install: nan@1.8.4
npm info lifecycle kerberos@0.0.11~install: kerberos@0.0.11

> kerberos@0.0.11 install /home/mean/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

ERROR: Service 'web' failed to build: The command '/bin/sh -c npm install' returned a non-zero code: 1
`

Can someone explain to me why is this happening? And point me in the right direction to resolve it?

Thanks

**Comment by socialatm** [comment]
Looks like a compiler error. Are you on Windows?

**Comment by codydaig** [comment]
@prasadh13 Can you provide more information about your dev environment?

**Comment by lirantal** [comment]
@prasadh13 looks indeed like a generic issue when trying to install npm packages. Could be so many reasons: package not found, compiling issues (i.e related to node-gyp on windows), proxy/networking problem, and so on.

If you still have this problem please try to provide a more detailed problem description (such as running `npm install -d` when building the container)
