### ISSUE TITLE
【mabye a bug】master branch create crud-module by yoeman, gulp eslint throws lots of errors.

### ISSUE THREAD

**Issue by yalishizhude** [meanjs/mean#1348]
windows 10

1. `yo meanjs`, I choose the master branch to create project.
2. `yo meanjs:crud-module`, I create a new module.
3. `gulp eslint`. I run the command,errors occurs~
maybe threre is something wrong with **.eslintrc.js**?
![Uploading Unnamed QQ Screenshot20160524180425.png…]()

**Comment by OneOfTheWorld** [comment]
yo meanjs still use the previous stable version to generate the template, but for this latest version something changed, such as "Menus" service changed to "menuService", you may be need to noticed that.

**Comment by lirantal** [comment]
cc @codydaig

**Comment by codydaig** [comment]
@yalishizhude Sorry for the delay. This bug should be resolved here: https://github.com/meanjs/generator-meanjs/pull/219. 

This PR is open to bump and release the next version, however, we're hitting a snag with the build system. Once I get travis working again, it will be released to npm. https://github.com/meanjs/generator-meanjs/pull/237
