### ISSUE TITLE
MongoDB secure connection with certificates

### ISSUE THREAD

**Issue by pasket** [meanjs/mean#1349]
We have found some errors with the data types in mongodb connections using certificates. Finally, we have solved:

1. Updating mongoose to:
"mongoose": "^4.4.16",

2. We have configured our secure connection like this:

'use strict';
var fs = require('fs');
...
...
db: { 
     uri: process.env.MONGOHQ_URL || process.env.MONGOLAB_URI || 
'mongodb://172.16.1.66/mycollection', 
     options: { 
         user: 'avalverde', 
         pass: 'mypass...', 
         server: { 
             ssl: true, 
             sslValidate: false, 
             sslKey: 
                    fs.readFileSync('./config/sslcerts/mongoose/metabox-key.pem'), 
             sslCert: 
                   fs.readFileSync('./config/sslcerts/mongoose/metabox-cert.pem'), 
             sslCA: fs.readFileSync('./config/sslcerts/mongoose/ca.pem') 
        } 
    }, 
...
...

3. Finally, we had to edit config/lib/mongoose.js because the buffer of the certificates weren't Uint8Array as expected. We added the following lines.

  if ( config.db.options && config.db.options.server ) {
        config.db.options.server.sslCert = new Uint8Array(config.db.options.server.sslCert);
        config.db.options.server.sslKey  = new Uint8Array(config.db.options.server.sslKey);
  }

  var db = mongoose.connect(config.db.uri..................

**Comment by lirantal** [comment]
Hi @pasket,

Would you like to submit a PR for this enhancement?

**Comment by pasket** [comment]
Yes. Thank you.

**Comment by lirantal** [comment]
@pasket we can't wait... :)
are you on it or do you need some help?

**Comment by ilanbiala** [comment]
@pasket if you open a PR, we'll review it and help tidy up any loose ends. Any work that you have would help us wrap this up.
