### ISSUE TITLE
Server can't run

### ISSUE THREAD

**Issue by hoangphucvu** [meanjs/mean#1351]
When I type `grunt` everything seem perfect but I had waiting for 30 minute and still not see anything message show that I can access to port 3000.I'm using `MEAN.JS 0.3.3 ` 

[Here](http://prntscr.com/b9heb3) is what I get

**Comment by Wuntenn** [comment]
Hi @hoangphucvu, I just looked at you linked image. It looks like you're not using MeanJS at all. You're probably best of re-tracing the book or looking at the book publishers site for published errata or forums.

**Comment by lirantal** [comment]
@Wuntenn how can you tell if he is using MEAN.JS or not?

Anyway, @hoangphucvu version 0.3.3 is quite old, you should really get up to date with the latest version in `master` branch, being a beta 0.5 version

**Comment by Wuntenn** [comment]
On the screenshot If you look at the directory he's operating out of "AngularJS/Chap5". Looks like a tutorial or a book. I doubt that someone includes the whole meanjs project in their angular folder.

Also this project has usually reports 111-113-files lint free and his reported around 50.

**Comment by lirantal** [comment]
It could be snippets of code examples from @amoshaviv's MEAN Web Development book: https://www.packtpub.com/web-development/mean-web-development

**Comment by Wuntenn** [comment]
True - I'm not sure if Amos still supports the repo: https://github.com/amoshaviv/mean-web-development/tree/09e066bc63c50f136320707d1901558b9ab2c33d
