### ISSUE TITLE
[test] Can't get connection with socket 

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1352]
When I use "grunt test" I got this message "ChatController when user logged in should make sure socket is connected FAILED"

Any suggestion ??

**Comment by ilanbiala** [comment]
@avatarr did you manage to fix this?

**Comment by mleanos** [comment]
I just ran `grunt test` on the latest *master* branch and didn't encounter any issues. This could have been a bug/issue that has been fixed.

**Comment by ilanbiala** [comment]
@mleanos can this be closed?

**Comment by avatarr** [comment]
So sorry for late reply I fixed
