### ISSUE TITLE
Making Topbar into sidebar

### ISSUE THREAD

**Issue by NavneetKaur9** [meanjs/mean#1358]
How can i remove topbar and instead add the same menus into sidebar.
Also, if i want to introduce my own css style where should it be added?

**Comment by javo01** [comment]
Hi, the css should go in the respective folder "/module/module_name/css"  and it will be automatically added.

and for the sidebar just change the html structure of the navbar for the one that you need to use for sidebar but keep the angular parts.

**Comment by NavneetKaur9** [comment]
thanks Javo01

**Comment by NavneetKaur9** [comment]
When i inspect Elements in the browser i cant see the html,how am i gonna do that?

**Comment by javo01** [comment]
what elements are you looking for?

the elements for the topbar are in the file --> "/modules/core/client/views/header.client.view.html"

**Comment by ilanbiala** [comment]
This is more style and less about the framework itself, so I'm going to close this.
