### ISSUE TITLE
Documentation for Pivotal Web Services

### ISSUE THREAD

**Issue by bencmbrook** [meanjs/mean#1364]
When deploying to Cloud Foundry, in the step for creating the Mongo service
`$ cf create-service mongolab sandbox mean-mongo`
should be
`*$ cf create-service mlab sandbox mean-mongo`

**Comment by bencmbrook** [comment]
Also the production env file

**Comment by lirantal** [comment]
@bencmbrook would you like to open a PR for this?

**Comment by lirantal** [comment]
FYI @bencmbrook  You don't need to close it manually, the PR will close it when it gets merged.

**Comment by bencmbrook** [comment]
@lirantal oh cool, didn't know that
