### ISSUE TITLE
what about use redis with mongo?

### ISSUE THREAD

**Issue by itelo** [meanjs/mean#1365]

**Comment by lirantal** [comment]
What about it?

**Comment by itelo** [comment]
redis works better than mongo for frequently requests, so what about use redis to articles?

And acoording with this [article](https://www.sitepoint.com/caching-a-mongodb-database-with-redis/), we could put the cache with redis too.

**Comment by ilanbiala** [comment]
@itelo redis is in memory, not disk, so if you restart the system and don't handle it properly then you will lose the data. Redis isn't the best solution, it's better for sessions and other caching things than storing important data.
