### ISSUE TITLE
CRUD

### ISSUE THREAD

**Issue by batosai85** [meanjs/mean#1367]
Hey guys, 
im having some major issue with updating data. Can create, display data, delete , but when im using update   only first property of any document is updated.

any suggestion?

tnx

**Comment by itelo** [comment]
@batosai85 which data?

**Comment by codydaig** [comment]
@batosai85 Any update here?

**Comment by batosai85** [comment]
Not so far, same problem , can't update any data

**Comment by codydaig** [comment]
Can you elaborate on what you mean by can't update any data? Are you getting any error messages? What code are you using to try to update data? What version of meanjs are you running? Any steps you can give us to reproduce the issue?

**Comment by batosai85** [comment]
It is latest version of MEAN. It is code similiar like one  in articles folder, with some more form fields. Everything is  working except that  i  can't update data via put verb(can create, delete, read). No error in console so far.  I will try to do it from scratch again , and will let you know what happend.

**Comment by lirantal** [comment]
@batosai85 please let us know how it ended up. whether you found a fix/solution or noticed a really problem with the framework.

For now I'm closing but you're welcome to re-open if you see fit.
