### ISSUE TITLE
Mocha exploded!  Error: Unsupported Node version: 6.2.0

### ISSUE THREAD

**Issue by dylike** [meanjs/mean#1373]
I'm using win10 to build my meanjs app, everything goes to be okay, and when i type `grunt`, i do see everything okay at `localhost:3000`, but when i run `grunt test`, there is somthing wrong.

`Running "mochaTest:src" (mochaTest) task`
`>> Mocha exploded!`
`>> Error: Unsupported Node version: 6.2.0`

so, is anybody see the same error, and appreciate a lot to help me fix it?

**Comment by simison** [comment]
It's not exactly supported yet: https://github.com/meanjs/mean/blob/master/.travis.yml#L15-L17

...but if you figure out how to fix that, pull requests are welcome. ;-)

**Comment by iamchathu** [comment]
Updating mock-fs to 3.12.0, fix this issue.
