### ISSUE TITLE
e2e testing with protractor not waiting authentication finish 

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1375]
I have modified authentication controller and client a bit, Then my code e2e2 test at below 
`    it('Should report valid username and password', function() {
      browser.get('http://localhost:3001/authentication/signin');
      element(by.model('vm.credentials.username')).sendKeys(user2.username);
      element(by.model('vm.credentials.password')).sendKeys(user2.password);
      element(by.css('button[type=submit]')).click();
      expect(browser.getCurrentUrl()).toEqual('http://localhost:3001/');
    });`

When protractor click on button is not waiting authentication finish before expect() , So got error like: 
` 1) Users E2E Tests: Signin Validation Should report valid username and password
   Message:
     Expected 'http://localhost:3001/authentication/signin' to equal 'http://localhost:3001/'.
`

I copy code form original and change parameter to mind, What step I missed  

Ps. When e2e testing I use grunt-mongoimport to import mockup data to database  it is possible make my project has failed?

**Comment by ilanbiala** [comment]
@avatarr do you still have this issue?

**Comment by lirantal** [comment]
@avatarr I'm closing for now due to no response.
If you are still having issues/want to propose a fix please re-open with more details.
