### ISSUE TITLE
Using "Format Code" in Visual Studio Code bug in IIFEs

### ISSUE THREAD

**Issue by water42** [meanjs/mean#1377]
When I use this option, it adds a space in `}());` such that it becomes `} ());` which throws an ESLint error. Is this a VSCode quirk or something to do with the editor config?

Changing .editorconfig does change the "Format Code" (Alt shift f) results.

**Comment by codydaig** [comment]
I'm not sure if there is an editorconfig setting to configure that, but I would say that is a Visual Studio quirk.
