### ISSUE TITLE
what about update all code to es6?

### ISSUE THREAD

**Issue by itelo** [meanjs/mean#1378]

**Comment by lirantal** [comment]
Hey @itelo 

It's unlikely that we will get to that anytime soon, although if you were hoping to actually contribute to that effort then by all means this is welcome.

**Comment by water42** [comment]
@lirantal how you recommend going about this in terms of submitting pull requests, etc? personally I think meanjs would be an amazing resource if it had branches maintained using the current Angular 1 style, Angular 1 ES6 style, and Angular 2 style.

**Comment by codydaig** [comment]
@water42 We don't have the development power to maintain that many branches. If this is soemthing that people want, I would recommend an initial PR that runs babel from a src folder into a build folder. Then submit PRs refactoring bits of code vs the entire project.

**Comment by lirantal** [comment]
As @codydaig said - we simply don't have the resources as maintainers to review everything and the PR queue is already quite full.

@water42 I definitely join you in your observation of going Angular2 + ES6 in MEAN.JS will be an amazing shift and a fun journey but we can't really distribute too much resource there. We can take it PR at a time, starting possibly with the Angular side maybe.

**Comment by lirantal** [comment]
@water42 if you're still up for helping the project we can start with some PRs :)
