### ISSUE TITLE
Stable Versión

### ISSUE THREAD

**Issue by marianoqueirel** [meanjs/mean#1380]
Hello Everybody, 

First of all Thanks to everybody who made this great work. I'm from Argentina, sory for my poor english. 

For me it is very useful, And I would ask: 

1) Would You have idea when the stable version will be?
2? You Advise me start a new project with this version? 
3? I need to start inmediately one project, what do you recommend? Angular Full Stack generator? 

Many Thanks! ! !

**Comment by lirantal** [comment]
HI @marianoqueirel,

Thanks for your feedback.

You can definitely go with the current version. We are always improving and enhancing the project so there will always be changes.

**Comment by codydaig** [comment]
@marianoqueirel Did that help? If so, can we close this issue?

**Comment by marianoqueirel** [comment]
@codydaig 
I would start my project today.
I wonder if I should start with the 0.4 or the 0.5-Beta.

Obviously I want to start with the 0.5-Beta, with the current branch master, and my question is: Do you recommend I start a project with the current master branch? I prefer that.

Thank you!!

**Comment by ilanbiala** [comment]
I would use the latest tagged release, which is 0.4.2, if you want fully reliable code for a large project. However, 0.5 will bring quite a few big changes, so definitely use that for your next project if it's ready.
