### ISSUE TITLE
Can't run application with grunt after generating application from yo

### ISSUE THREAD

**Issue by ntlzz93** [meanjs/mean#1381]
I installed global nodejs, npm , mongodb ,bower , grunt. I create an application from yo but I can't run application with grunt. I followed these step from offical meanjs website :

```
ntlzz@DESKTOP-3D7GVU0 MINGW32 ~/Desktop
$ yo meanjs
You're using the official MEAN.JS generator.
? What mean.js version would you like to generate? (Use arrow keys)
? What mean.js version would you like to generate? 0.4.2
0.4.2
? In which folder would you like the project to be generated? This can be chang
? In which folder would you like the project to be generated? This can be chang
Cloning the MEAN repo.......
? What would you like to call your application? (MEAN)
? What would you like to call your application? MEAN
? How would you describe your application? Full-Stack JavaScript with MongoDB,
? How would you describe your application in comma seperated key words? MongoDB
? What is your company/author name? loint
? What is your company/author name? loint
? Would you like to generate the article example CRUD module? (Y/n) y
? Would you like to generate the article example CRUD module? Yes
? Would you like to generate the chat example module? (Y/n) n
? Would you like to generate the chat example module? No
Running npm install for you....
This may take a couple minutes.

------------------------------------------
Your MEAN.js application is ready!

To Get Started, run the following command:

cd mean && grunt

Happy Hacking!
------------------------------------------

ntlzz@DESKTOP-3D7GVU0 MINGW32 ~/Desktop
$ cd mean

ntlzz@DESKTOP-3D7GVU0 MINGW32 ~/Desktop/mean ((0.4.2))
$ grunt
Running "env:dev" (env) task

Running "sass:dist" (sass) task

```
> Warning:
> You need to have Ruby and Sass installed and in your PATH for this task to work.
> More info: https://github.com/gruntjs/grunt-contrib-sass
>  Use --force to continue.
> 
> Aborted due to warnings.

**Comment by ntlzz93** [comment]
grunt --force can work !! but how to fix warning?

**Comment by codydaig** [comment]
@ntlzz93 Looks like you need Ruby installed!

**Comment by lirantal** [comment]
Hi @ntlzz93 , as @codydaig pointed out you simply needed a few tools on your system as requirement to use mean.js.

We've actually removed this dependency just recently so you might not need this anymore if you will be using the latest `master` branch version of MEAN.JS. Otherwise, you can still use the 0.4.2 version with the generator but remember to install ruby and the required gem as follows:
1. Download and install Ruby: https://www.ruby-lang.org/en/documentation/installation/
2. Install the `sass` gem:
```bash
$ gem install sass
```
