### ISSUE TITLE
jshint failed when move project to another folder

### ISSUE THREAD

**Issue by TAMMENY** [meanjs/mean#1386]
system: Ubuntu 14.04 LTS
npm: v3.9.6
nodejs: v4.4.5
meanjs: v0.4.2
When move the project to another folder and run grunt the following errors were encountered:
`modules/users/tests/client/authentication.client.controller.tests.js
      1 |'use strict';
         ^ Use the function form of "use strict".
      5 |  describe('AuthenticationController', function () {
           ^ 'describe' is not defined.
     14 |    beforeEach(function () {
             ^ 'beforeEach' is not defined.
     15 |      jasmine.addMatchers({
               ^ 'jasmine' is not defined.
     20 |                pass: angular.equals(actual, expected)
                               ^ 'angular' is not defined.
     29 |    beforeEach(module(ApplicationConfiguration.applicationModuleName));
             ^ 'beforeEach' is not defined.
     29 |    beforeEach(module(ApplicationConfiguration.applicationModuleName));
                        ^ 'module' is not defined.
     29 |    beforeEach(module(ApplicationConfiguration.applicationModuleName));
                               ^ 'ApplicationConfiguration' is not defined.
     31 |    describe('Logged out user', function () {
             ^ 'describe' is not defined.
     35 |      beforeEach(inject(function ($controller, $rootScope, $location, $stateParams, _$httpBackend_) {
               ^ 'beforeEach' is not defined.
     35 |      beforeEach(inject(function ($controller, $rootScope, $location, $stateParams, _$httpBackend_) {
                          ^ 'inject' is not defined.
     50 |      describe('$scope.signin()', function () {
               ^ 'describe' is not defined.
     51 |        it('should login with a correct user and password', function () {
                 ^ 'it' is not defined.
     59 |          expect(scope.authentication.user).toEqual('Fred');
                   ^ 'expect' is not defined.
     60 |          expect($location.url()).toEqual('/');
                   ^ 'expect' is not defined.
     63 |        it('should be redirected to previous state after successful login',
                 ^ 'it' is not defined.
     64 |          inject(function (_$state_) {
                   ^ 'inject' is not defined.
     74 |            spyOn($state, 'transitionTo');
                     ^ 'spyOn' is not defined.
     75 |            spyOn($state, 'go');
                     ^ 'spyOn' is not defined.
     84 |            expect($state.go).toHaveBeenCalled();
                     ^ 'expect' is not defined.
     85 |            expect($state.go).toHaveBeenCalledWith($state.previous.state.name, $state.previous.params);
                     ^ 'expect' is not defined.
     89 |        it('should fail to log in with nothing', function () {
                 ^ 'it' is not defined.
     99 |          expect(scope.error).toEqual('Missing credentials');
                   ^ 'expect' is not defined.
    102 |        it('should fail to log in with wrong credentials', function () {
                 ^ 'it' is not defined.
    116 |          expect(scope.error).toEqual('Unknown user');
                   ^ 'expect' is not defined.
    120 |      describe('$scope.signup()', function () {
               ^ 'describe' is not defined.
    121 |        it('should register with correct data', function () {
                 ^ 'it' is not defined.
    130 |          expect(scope.authentication.user).toBe('Fred');
                   ^ 'expect' is not defined.
    131 |          expect(scope.error).toEqual(null);
                   ^ 'expect' is not defined.
    132 |          expect($location.url()).toBe('/');
                   ^ 'expect' is not defined.
    135 |        it('should fail to register with duplicate Username', function () {
                 ^ 'it' is not defined.
    145 |          expect(scope.error).toBe('Username already exists');
                   ^ 'expect' is not defined.
    150 |    describe('Logged in user', function () {
             ^ 'describe' is not defined.
    151 |      beforeEach(inject(function ($controller, $rootScope, $location, _Authentication_) {
               ^ 'beforeEach' is not defined.
    151 |      beforeEach(inject(function ($controller, $rootScope, $location, _Authentication_) {
                          ^ 'inject' is not defined.
    155 |        $location.path = jasmine.createSpy().and.returnValue(true);
                                  ^ 'jasmine' is not defined.
    168 |      it('should be redirected to home', function () {
               ^ 'it' is not defined.
    169 |        expect($location.path).toHaveBeenCalledWith('/');
                 ^ 'expect' is not defined.
`

**Comment by TAMMENY** [comment]
I'm sorry I missed the hidden files.

**Comment by codydaig** [comment]
No worries! Thanks for reporting back!! :-D
