### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by aikorei** [meanjs/mean#1387]
Hi. Hobby developer and first time poster here. I'm struggling to get Google Analytics to work on my recently deployed site (I got it working on an older deployment of MEANJS, but through custom implementation). I see, however, that we have the beginnings of getting this working:

**/config/env/default.js**
```
module.exports = {
  app: {
    title: 'MEAN.JS',
    description: 'Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js',
    keywords: 'mongodb, express, angularjs, node.js, mongoose, passport',
    googleAnalyticsTrackingID: process.env.GOOGLE_ANALYTICS_TRACKING_ID || 'GOOGLE_ANALYTICS_TRACKING_ID' // <-- Here
  },
```

**/config/lib/express.js**
```
/**
 * Initialize local variables
 */
module.exports.initLocalVariables = function (app) {
  // Setting application local variables
  app.locals.title = config.app.title;
  app.locals.description = config.app.description;
  if (config.secure && config.secure.ssl === true) {
    app.locals.secure = config.secure.ssl;
  }
  app.locals.keywords = config.app.keywords;
  app.locals.googleAnalyticsTrackingID = config.app.googleAnalyticsTrackingID; // <-- Here
  app.locals.facebookAppId = config.facebook.clientID;
  app.locals.jsFiles = config.files.client.js;
  app.locals.cssFiles = config.files.client.css;
  app.locals.livereload = config.livereload;
  app.locals.logo = config.logo;
  app.locals.favicon = config.favicon;

  // Passing the request url to environment locals
  app.use(function (req, res, next) {
    res.locals.host = req.protocol + '://' + req.hostname;
    res.locals.url = req.protocol + '://' + req.headers.host + req.originalUrl;
    next();
  });
};
```

However, this app.local variable doesn't appear anywhere in `/modules/core/server/views/layout.server.view.html` where I would expect it.

In my own testing, I tried adding the Google Analytics script in two places, without success. First, I added it to a custom footer file that I made which is included in `layout.server.view.html`, and secondly to the `layout.server.view.html` file itself (just before the closing `</head>` tag). Both without luck.

**layout.server.view.html**
```
<!DOCTYPE html>
<html lang="en">
<head>
  ...
  <!-- Meta stuff here -->
  ...

  <!-- Other stuff here, e.g. CSS files -->
  ...

</head>

<body class="ng-cloak">
  <header ng-include="'/modules/core/client/views/header.client.view.html'" class="navbar navbar-fixed-top navbar-default"></header>
  <section class="content">
    <section class="container">
      {% block content %}{% endblock %}
    </section>
  </section>
  <footer ng-include="'/modules/core/client/views/footer.client.view.html'" class="footer-section"></footer>

...
<!-- Other stuff here, e.g. JS files -->
...

  <!-- Google Analytics Script -->
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', '{{googleAnalyticsTrackingID}}', 'auto');
    ga('send', 'pageview');

  </script>
</body>

</html>
```

Note that I've verified that my `{{googleAnalyticsTrackingID}}` is populating the correct tracking ID value in my page when it loads. Note also that in my custom footer file, I loaded the tracking ID directly in the script (not the `{{googleAnalyticsTrackingID}}` variable). In neither case is my Google Analytics account registering hits to the page.

I'm using MEANJS 0.5.0 on a CentOS server, and I can't see any issues. If anyone leads me in the right direction, and I can get it working, I'm happy to create (my first ever) pull request and submit a fix.

I've really enjoyed developing with MEANJS. All around nice work, everyone.

**Comment by aikorei** [comment]
Well, apparently 2 days wasn't long enough. In the third day, data finally started showing up in my Google Analytics account from adding the GA script to the `layout.server.view.html` file as noted above.

**Comment by lirantal** [comment]
Great, thanks for updating @aikorei

**Comment by aikorei** [comment]
@lirantal I just realized - if I'm only loading the GA script on `layout.server.view.html`, it seems it's only going to capture the initial page loaded, but I'm guessing the GA script won't get trigger with Angular state changes. Is that assumption correct? If so, it seems we're going to need to integrate GA more deeply into the Angular files, right?

**Comment by IdanCo** [comment]
@aikorei you're right, loading the GA script in your index file will only trigger a single page view, and ignore all internal routing.

To solve this issue you can do one of two things -
1. Trigger a page view manually each time a successful routing occures.
2. Alternatively, and much easier, you can add the aglulartics module to your project and enjoy many other benefits it offers. You can get it here - http://angulartics.github.io/

**Comment by lirantal** [comment]
Thanks @IdanCo.
@aikorei we're good?

**Comment by aikorei** [comment]
Thanks for the suggestion, @IdanCo. I just implemented angulartics. Will give it a few days to see if it works as expected. For now, though, I'll close the issue so no one loses any sleep over it. ;)

**Comment by ohadcn** [comment]
may I ask why the code above isn't in `layout.server.view.html` by default? or at least in `  {% if %}` block?
