### ISSUE TITLE
Virtual Hosts

### ISSUE THREAD

**Issue by costasT** [meanjs/mean#1391]
I am trying to setup vhosts using express-vhost. However, there is a problem with the paths. This is mainly because paths are currently relative to the node app - when vhost is used there is a single 'parent' app which becomes the root directory of the app. One possible solution to this is to use __dirname instead of process.cwd() and use it throughout the config directory.

**Comment by ilanbiala** [comment]
@costasT can you propose some code that would fix this in a PR?

**Comment by lirantal** [comment]
@costasT if you're up for proposing a fix/enhancement to enable this for other users we will welcome it gladly.
