### ISSUE TITLE
Server logs/logger

### ISSUE THREAD

**Issue by freemind-** [meanjs/mean#1396]
Hi guys,

Whats the recommended way to log errors in the backend? I'm using the 0.4.2 tag and I dont see any built-in mechanism to log such information. Thanks for your help!
Mathieu

**Comment by codydaig** [comment]
@freemind- The framework uses morgan, and morgan can be defined to log to a file. https://github.com/expressjs/morgan#write-logs-to-a-file

**Comment by freemind-** [comment]
Well I will cherry pick this commit,

feat(logs): replacing unmaintained and vulnerable file-stream-rotator package with winston log facility (#1334)

it will allow me to use logger with defined level in the same file :+1:

**Comment by codydaig** [comment]
There ya go!

**Comment by lirantal** [comment]
@freemind- very cool, glad to see you adopting it! :)

**Comment by freemind-** [comment]
@lirantal I embrace it! Thank you so much guys!!
