### ISSUE TITLE
Bug: Remove gulp-wiredep dependency

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#1398]
`nsp` reports `gulp-wiredep` as problematic due to dependencies which are out of date and are subject to RegEx attacks. That plugin is anyway another `leftpad` so we really need to take it out of our build system in gulp.

![image](https://cloud.githubusercontent.com/assets/316371/16853712/3d764a32-4a16-11e6-8197-3f31aa310b67.png)

**Comment by lirantal** [comment]
A couple of suggestions for the upcoming PR:
1. Use the native `wiredep` library that is compatible with gulp's stream system
2. Use `gulp-inject`

**Comment by shanavas786** [comment]
`nsp` reports lot more.

            | Regular Expression Denial of Service                  
------------|-------------------------------------------------------
 Name       | minimatch                                             
 Installed  | 2.0.10                                                
 Vulnerable | <=3.0.1                                               
 Patched    | >=3.0.2                                               
 Path       | meanjs@0.5.0-beta > forever@0.15.2 > forever-monitor… 
 More Info  | https://nodesecurity.io/advisories/118                
            |                                                       

            | Regular Expression Denial of Service                 
------------|-------------------------------------------------------
 Name       | minimatch                                             
 Installed  | 2.0.10                                                
 Vulnerable | <=3.0.1                                               
 Patched    | >=3.0.2                                               
 Path       | meanjs@0.5.0-beta > gulp-wiredep@0.0.0 > wiredep@2.2… 
 More Info  | https://nodesecurity.io/advisories/118                

            | Regular Expression Denial of Service                
------------|-------------------------------------------------------
 Name       | minimatch                                             
 Installed  | 0.3.0                                                 
 Vulnerable | <=3.0.1                                               
 Patched    | >=3.0.2                                               
 Path       | meanjs@0.5.0-beta > mocha@2.5.3 > glob@3.2.11 > mini… 
 More Info  | https://nodesecurity.io/advisories/118                

            | DoS due to excessively large websocket message 
------------|-------------------------------------------------------
 Name       | ws                                                    
 Installed  | 1.1.0                                                 
 Vulnerable | <=1.1.0                                               
 Patched    | >=1.1.1                                               
 Path       | meanjs@0.5.0-beta > socket.io@1.4.8 > engine.io@1.6.… 
 More Info  | https://nodesecurity.io/advisories/120                

            | Regular Expression Denial of Service                 
------------|-------------------------------------------------------
 Name       | negotiator                                            
 Installed  | 0.4.9                                                 
 Vulnerable | <= 0.6.0                                              
 Patched    | >= 0.6.1                                              
 Path       | meanjs@0.5.0-beta > socket.io@1.4.8 > engine.io@1.6.… 
 More Info  | https://nodesecurity.io/advisories/106                

            | DoS due to excessively large websocket message       
------------|-------------------------------------------------------
 Name       | ws                                                    
 Installed  | 1.0.1                                                 
 Vulnerable | <=1.1.0                                               
 Patched    | >=1.1.1                                               
 Path       | meanjs@0.5.0-beta > socket.io@1.4.8 > socket.io-clie… 
 More Info  | https://nodesecurity.io/advisories/120                

            | Regular Expression Denial of Service             
------------|---------------------------------------------------
 Name       | uglify-js                                         
 Installed  | 2.4.24                                            
 Vulnerable | <2.6.0                                            
 Patched    | >=2.6.0                                           
 Path       | meanjs@0.5.0-beta > swig@1.4.2 > uglify-js@2.4.24 
 More Info  | https://nodesecurity.io/advisories/48

**Comment by lirantal** [comment]
Indeed. There are some issues I already opened in the past regarding `swig`, and `file-stream-rotator`.  Let's focus on the wiredep dependency in this PR.
