### ISSUE TITLE
No ES6 support?

### ISSUE THREAD

**Issue by r-chandra-1** [meanjs/mean#1403]
Fails to run right out of the box. Connect-mongo is a dependency this project has and it uses 'const' and 'let'. The grunt command throws exception. How to fix this issue?

**Comment by r-chandra-1** [comment]
I used the fallback approach of switching to 'connect-mongo/es5'. But would like to know how to run the app with ES6 as well.

**Comment by codydaig** [comment]
@r-chandra-1 The mean.js repo does not currently support ES6. There's a lot of groundwork that must be laid for it to work. It's something we have plans for in the future, but not currently a top priority.

**Comment by lirantal** [comment]
@r-chandra-1 I'm closing this issue but if you'd like to offer help with adding some ES6 support do let us know and let's review together what it requires and how to approach it.
