### ISSUE TITLE
Unlink old(previous) profile images

### ISSUE THREAD

**Issue by aanev** [meanjs/mean#1415]
Currently old profile images are not unlinked upon change and remain on disk. If a user changes his/her profile image frequently that can lead to disk space leakage.

**Comment by mleanos** [comment]
This is something that has crossed my mind as well.

I think we have a couple options:
1) Remove previous profile image after successful upload
OR
2) Overwrite existing profile image, using the same file name

The latter may be a less complicated implementation, but could have security implications when we're using the same file name over long periods of time (or for the lifetime of the profile image). However, this is just a profile image that isn't a private asset.

**Comment by aanev** [comment]
IMHO both options are fine. However, I think the first one will be easier to implement and with less changes to existing code. Something like that:
1. Save reference to the old file.
2. Upload new one.
3. In the upload callback update the db with the new file name and fs.unlink the old one if it's different from the default image.

**Comment by mleanos** [comment]
Your proposed solution is fine, and would work. Most likely requiring just 4 lines of code in [this method](https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.profile.server.controller.js#L59). However, I'd like to see this done in a more configurable manner, and the actual deletion abstracted away from the User's profile server controller. Whether or not to delete, or overwrite, the existing profile picture seems to be more of a business requirement that may vary among this framework's users.

**Comment by lirantal** [comment]
@aanev good catch.

I think we should simplify this, whether we overwrite an existing file name, or create a new one, both are ok. Is anyone getting a PR proposed?

**Comment by mleanos** [comment]
@aanev Would you like to submit a PR for this?

If we opted for overwriting the existing file by using the same name, we wouldn't have a need to update the database. I fiddled around with this idea, and wasn't able to change the file name before upload. I'm not sure if this is a limitation of angular-file-upload on the client-side, or with our implementation of it. The solution in [this comment](https://github.com/nervgh/angular-file-upload/issues/138#issuecomment-100448780) didn't work for me. We could always remove the old file, and rename the new one on the server-side after the successful upload; we wouldn't need to update the database in this case either. Just food for thought :)

Either option we go with, we can keep it simple as @lirantal suggested.

**Comment by lirantal** [comment]
Tested and it looks good.
Thanks @aanev  and @mleanos
