### ISSUE TITLE
Mobile Rest Full API

### ISSUE THREAD

**Issue by Usman-Asghar** [meanjs/mean#1430]
Hello,

I want to use your MEAN Stack for my Mobile as a REST Full API, So can you please guide me how i can call different URL's from my Mobile end. I try to call but i get this error at Mobile end "User is not authorized". Please let me know as soon as possible.

**Comment by hyperreality** [comment]
Please post the contents of your module's /server/policies/*.server.policy.js and /server/routes/*.server.routes.js, it is most likely that they are not set up correctly.

**Comment by Usman-Asghar** [comment]
Here are my contents of "/*.server.policy.js"
'use strict';

/**
 * Module dependencies
 */
var acl = require('acl');

// Using the memory backend
acl = new acl(new acl.memoryBackend());

/**
 * Invoke Articles Permissions
 */
exports.invokeRolesPolicies = function() {
  acl.allow([{
    roles: ['admin'],
    allows: [{
      resources: '/api/articles',
      permissions: '*'
    }, {
      resources: '/api/articles/:articleId',
      permissions: '*'
    }]
  }, {
    roles: ['user'],
    allows: [{
      resources: '/api/articles',
      permissions: ['get', 'post']
    }, {
      resources: '/api/articles/:articleId',
      permissions: '*'
    }]
  }, {
    roles: ['guest'],
    allows: [{
      resources: '/api/articles',
      permissions: ['get']
    }, {
      resources: '/api/articles/:articleId',
      permissions: ['get']
    }]
  }]);
};

/**
 * Check If Articles Policy Allows
 */
exports.isAllowed = function(req, res, next) {
  var roles = (req.user) ? req.user.dataValues.roles : ['guest'];
  // If an article is being processed and the current user created it then allow any manipulation
  if (req.article && req.user && req.article.User && req.article.User.id === req.user.id) {
    return next();
  }

  // Check for user roles
  acl.areAnyRolesAllowed(roles, req.route.path, req.method.toLowerCase(), function(err, isAllowed) {
    if (err) {
      // An authorization error occurred
      return res.status(500).send('Unexpected authorization error');
    } else {
      if (isAllowed) {
        // Access granted! Invoke next middleware
        return next();
      } else {
        return res.status(403).json({
          message: 'User is not authorized'
        });
      }
    }
  });
};

and "/*.server.routes.js"

'use strict';

/**
 * Module dependencies
 */
var articlesPolicy = require('../policies/articles.server.policy'),
  articles = require('../controllers/articles.server.controller');

module.exports = function(app) {
  // Articles collection routes
  app.route('/api/articles').all(articlesPolicy.isAllowed)
    .get(articles.list)
    .post(articles.create);

  // Single article routes
  app.route('/api/articles/:articleId').all(articlesPolicy.isAllowed)
    .get(articles.read)
    .put(articles.update)
    .delete(articles.delete);
};

**Comment by hyperreality** [comment]
Please use code tags to format your code.

It all looks good to me, apart from that you're missing the line which binds the articleId parameter to a function: `app.param('articleId', articles.articleByID);
`
What exactly are you trying to do? Are you logged into your app on your mobile device?

**Comment by Usman-Asghar** [comment]
Hello hyperreality,

I am just trying to implement API for my Android application. So i just hit URL from REST Client and it returns me the error. 

In web pages its working fine.

**Comment by mleanos** [comment]
@Usman-Asghar From your policy configuration, it appears that you should be able to access the articles/ & articles/{articleId} routes without any authentication. Are these routes causing the issue for you?

Are you able to verify that you don't have a user in the request (`req.user` should be null or undefined). If you have `req.user`, and an empty array for `req.user.roles`, then you will see this behavior.

**Comment by Usman-Asghar** [comment]
When i send a request from REST client then did not have any req.user defined. So what i can do in that case. in other words how i can MEAN Stack for my android API

**Comment by simison** [comment]
@Usman-Asghar you'll have to pass your session cookie with each http request. You get it first once you send user credentials to login. Then, if you get `403: User is not authorized` when doing API requests, just ask user to login again, get new session id, and continue from where you left.

**Comment by Usman-Asghar** [comment]
@simison Thank You so much. Can you also please let me know how i can add default users during setup like. Defined in in development.js file.

**Comment by simison** [comment]
@Usman-Asghar See https://github.com/meanjs/mean#running-with-user-seed

**Comment by Usman-Asghar** [comment]
Trying with that but not working :( 

Got this error at cmd

'MONGO_SEED' is not recognized as an internal or external command,
operable program or batch file.

**Comment by simison** [comment]
You might need to add `SET MONGO_SEED....` if you're on Windows. http://superuser.com/questions/212150/how-to-set-env-variable-in-windows-cmd-line

**Comment by Usman-Asghar** [comment]
@simison Can you please also let me know how can i achieve email verification for new users sign up?

**Comment by lirantal** [comment]
@Usman-Asghar please take it in StackOverflow or the gitter channel. I'm closing this comment but regardless if @simison or @mleanos would like they can keep up the discussion here.

**Comment by ebastidas** [comment]
@Usman-Asghar check out this post http://stackoverflow.com/questions/30630862/angular-authentication-using-passport-for-ionic-app
