### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by ChrisHuntCal** [meanjs/mean#1436]
Hi Guys,

Quick question (hopefully) around clustering.  Looking at the Heroku documentation, they recommend that all apps implement clustering:
https://devcenter.heroku.com/articles/node-concurrency

Creating a WEB_CONCURRENCY variable to use  process.env.WEB_CONCURRENCY or a local value is easy enough.  We then need to provide throng with the start function.  

I am assuming that the start function we would use is module.exports.start in config/lib/app.js.  We would then replace the:
var server = app.start(); in config/lib/app.js

with:
throng(app.start, {
  workers: WEB_CONCURRENCY,
  lifetime: Infinity
});

The final file would look something like:

```
'use strict';

/**
 * Module dependencies.
 */
var app = require('./config/lib/app'),
  throng = require('throng');

var WEB_CONCURRENCY = process.env.WEB_CONCURRENCY || 1;

//var server = app.start();
throng(app.start, {
  workers: WEB_CONCURRENCY,
  lifetime: Infinity
});
```

Does that sound right?  Can you guys make any recommendations?  Are we going to need that server object to have been created here?

Thanks!

**Comment by ChrisHuntCal** [comment]
Or, should throng be wrapping the app.listen() function inside module.exports.start.  So something like:

```
module.exports.start = function start(callback) {
  var _this = this;
  var WEB_CONCURRENCY = process.env.WEB_CONCURRENCY || 2;

  _this.init(function (app, db, config) {

    throng(WEB_CONCURRENCY, startApp);

    function startApp() {
      // Start the app by listening on <port>
      app.listen(config.port, function () {

        // Logging initialization
        console.log('--');
        console.log(chalk.green(config.app.title));
        console.log(chalk.green('Environment:\t\t\t' + process.env.NODE_ENV));
        console.log(chalk.green('Port:\t\t\t\t' + config.port));
        console.log(chalk.green('Database:\t\t\t\t' + config.db.uri));
        if (process.env.NODE_ENV === 'secure') {
          console.log(chalk.green('HTTPs:\t\t\t\ton'));
        }
        console.log(chalk.green('App version:\t\t\t' + config.meanjs.version));
        if (config.meanjs['meanjs-version'])
          console.log(chalk.green('MEAN.JS version:\t\t\t' + config.meanjs['meanjs-version']));
        console.log('--');

        if (callback) callback(app, db, config);
      });
    }

  });

};
```

**Comment by lirantal** [comment]
No idea here. I haven't used clustering like that and not with Heroku either so I can't comment.
Maybe one of the @meanjs/contributors knows better to answer you.

Small tip: I do use pm2 for app clustering and load balancing, not sure if that's available on heroku but it greatly helps and eases it.
