### ISSUE TITLE
Fatal error: spawn cmd ENOENT

### ISSUE THREAD

**Issue by Ankur-Marwaha** [meanjs/mean#1439]
After successfully generating app, I am trying to run grunt and here is the error that I am getting.

No idea what should i do, Already tried the following :
* Verify the npm folder exists at the following location C:\Users\My-UserName\AppData\Roaming\npm
* Try to run npm cache clean
* Add C:\Windows\System32\ to the PATH Environment variable

````
E:\akshay\torrent\Architecture of the MEAN Stack (OReilly 2015)\yo mean\final\fnl>grunt
Running "env:dev" (env) task

Running "sass:dist" (sass) task

Running "less:dist" (less) task

Running "jshint:all" (jshint) task
>> 89 files lint free.

Running "eslint:target" (eslint) task

Running "csslint:all" (csslint) task
>> 2 files lint free.

Running "mkdir:upload" task

Running "copy:localConfig" (copy) task


Running "concurrent:default" (concurrent) task
    Running "nodemon:dev" (nodemon) task
    [nodemon] 1.10.2
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: server.js config/**/*.js modules/*/server/**/*.js
    [nodemon] starting `node --debug server.js`
    Running "watch" task
    Fatal error: spawn cmd ENOENT
    Waiting...
Warning:  Use --force to continue.

Aborted due to warnings.
````

**Comment by Ankur-Marwaha** [comment]
changing the way question was visible. adding code to properly formatted.

**Comment by mleanos** [comment]
Have you tried starting the application with Gulp (`gulp default`), instead of Grunt?

If Gulp works, then we can look at why Grunt might be doing this.

**Comment by Ankur-Marwaha** [comment]
No,Now I tried but it is not installed with meanjs.

```
E:\akshay\torrent\Architecture of the MEAN Stack (OReilly 2015)\yo mean\final\fnl>gulp
'gulp' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by Ankur-Marwaha** [comment]
Sorry for wasting your time,
Its resolved, there was an error in the env path at my end.
