### ISSUE TITLE
Why does meanjs still use swig as https://github.com/paularmstrong/swig not suggest using it ?

### ISSUE THREAD

**Issue by Ankur-Marwaha** [meanjs/mean#1440]
Why does meanjs still use swig as https://github.com/paularmstrong/swig not suggest using it ?

Is there any alternative that i can use so that files that have use swig works fine as well ?

**Comment by hyperreality** [comment]
Good point, it hasn't received an update in 2 years.

Could EJS be a possible alternative? https://github.com/mde/ejs . As far as I can see making the switch shouldn't be too painful.

**Comment by hyperreality** [comment]
Also has at least one serious issue which Lirantal tried to chase down: https://github.com/paularmstrong/swig/pull/649

**Comment by lirantal** [comment]
Indeed.
We're considering to replace it with either nunjacks or handlebars.

**Comment by lirantal** [comment]
@hyperreality I think ejs doesn't support nested templates, does it?

**Comment by hyperreality** [comment]
Yeah, as far as I'm aware out of the box EJS  doesn't support blocks (reusing parts of templates across different files). I've been looking at handlebars and think it's a much better choice for MEAN.js in any case.

**Comment by lirantal** [comment]
Do you have a pro/con for handlebars vs nunjucks?

**Comment by lirantal** [comment]
My bad, accidentally closed it :)

**Comment by hyperreality** [comment]
It's hard to make the call. As far as features go they're both fantastic. Nunjucks is more actively maintained but Handlebars is getting about 20 times the amount of downloads according to NPM, and I've seen Handlebars used way more in the wild. If nothing else, there is probably more info about Handlebars out there and users are more likely to be comfortable using it.

This may be a [Buridan's ass](https://en.wikipedia.org/wiki/Buridan%27s_ass) situation where both choices are equally as good and the worst thing is being stuck in the state of indecision and not choosing either.

**Comment by Ankur-Marwaha** [comment]
I wish the templating engine is changed very soon (may be handlebars), as I am new to meanjs and changing the template engine will be a pain in the ass. 
Wishes do come true, right ?

**Comment by lirantal** [comment]
Wishes do come true :)

**Comment by simison** [comment]
I would be safe to close this and continue at #1286 ?

**Comment by Ankur-Marwaha** [comment]
i prefer to keep it open, if you don't mind until the issue is resolved. As i am receiving email notifications from this.

**Comment by Ankur-Marwaha** [comment]
i prefer to keep it open, if you don't mind until the issue is resolved. As i am receiving email notifications from this.

**Comment by hyperreality** [comment]
@Ankur-Marwaha you can go to issue #1286 and press Subscribe on the right to receive notifications there. It helps because we don't need several Github issues for the same problem.
