### ISSUE TITLE
why specify core and !core in config.server.routes

### ISSUE THREAD

**Issue by danoz-direct** [meanjs/mean#1444]
Hi there, 

Just a question to help clarify my understanding if you will.

Inside ./config/assets/default.js there the following property

`routes: ['modules/!(core)/server/routes/**/*.js', 'modules/core/server/routes/**/*.js'],`

Q: why specify two values for this, i.e. `core` and `!core` when they look like they essentially resolve to the same path pattern, i.e. `modules/*/server/routes/**/*.js` ?

**Comment by hyperreality** [comment]
The key lies in a function in the `config/lib/express.js` file:

`module.exports.initModulesServerRoutes = function (app) {
  // Globbing routing files
  config.files.server.routes.forEach(function (routePath) {
    require(path.resolve(routePath))(app);
  });
};`

The idea with having the core routes occupy the final place in the array is that they are added to the routing table last. Error handling is done in `core.server.routes.js` and routing should 'fall through' to the errors. I'm not sure how much it really matters in this app though given the way that the routing is handled, things should still work even if the routes are out of order.

**Comment by danoz-direct** [comment]
Makes perfect sense, thanks for pointing that out.
