### ISSUE TITLE
Why meanjs uses grunt and gulp both, as both does the same task ?

### ISSUE THREAD

**Issue by Ankur-Marwaha** [meanjs/mean#1445]
Both does the same task with a difference in the way they achieve it, one uses streams and other doesn't.
Its kind of an question, I don't know if i should ask it here or somewhere else ?

**Comment by lirantal** [comment]
We are deprecating Grunt in favor of Gulp. Currently both are left there to make sure that users who relied on Grunt can still use it at this point.
