### ISSUE TITLE
Add mean-seo to core

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1446]
Should `mean-seo` be merged with the core? It's not terribly a lot of code and seems like a core feature anyway.

Currently it's not getting much [attention][1] and has some very outdated [dependencies][2].

[1]: https://github.com/meanjs/mean-seo/pulls
[2]: https://snyk.io/test/github/meanjs/mean-seo/

**Comment by hyperreality** [comment]
Is it even necessary any more? As Google state in [their docs](https://developers.google.com/webmasters/ajax-crawling/docs/specification), AJAX crawling was deprecated in October 2015. As far as I'm aware `mean-seo`'s functionality is now completely outmoded.

**Comment by simison** [comment]
Seems so, thanks!

More reading; https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html
