### ISSUE TITLE
Purpose and use of showStackError in module /config/lib/express.js

### ISSUE THREAD

**Issue by danoz-direct** [meanjs/mean#1447]
Hi folks,

A query regarding a setting in module [config/lib/express.js](https://github.com/meanjs/mean/blob/master/config/lib/express.js)...

Inside the function `initMiddleware` there is the following call:

`app.set('showStackError', true);`

What is the intent behind this? I suspect it is related to whether or not to show full stack traces in the client response on error, however I am puzzled as to how/where this is used. I ask this question for the following reasons:

1. this setting doesn't appear to be used/read anywhere else in the app. i.e. a [search here in the github repository for the setting `showStackError`](https://github.com/meanjs/mean/search?utf8=%E2%9C%93&q=showStackError) returns only a single result, i.e. where it is set. I understand from this that it is probably not intended to be 'used' by the app but rather by the express module internally;

2. according to the express API doc, [`app.set(name, value)`](http://expressjs.com/en/4x/api.html#app.set) assigns setting `name` to `value`, where `name` is one of the properties from the [app settings table](http://expressjs.com/en/4x/api.html#app.settings.table). However, I note that `showStackError` isn't listed in said app settings table.

I must admit, I am still learning and understanding the meanjs project so please forgive me in advance if I have misunderstood something.

Thanks for your time reading and considering this question.

Sincerely,
Dan

**Comment by lirantal** [comment]
@danoz-direct it's an old one indeed that doesn't exist anymore.
Can you submit a PR to remove both this one and the other jsonp option that you noted in the other issue?

**Comment by mleanos** [comment]
Resolved with #1463
