### ISSUE TITLE
Purpose and use of 'jsonp callback' setting in module /config/lib/express.js 

### ISSUE THREAD

**Issue by danoz-direct** [meanjs/mean#1448]
Hi everyone, 

This is a similar question to #1447 

A query regarding a setting in module [config/lib/express.js](https://github.com/meanjs/mean/blob/master/config/lib/express.js)...

Inside the function `initMiddleware` there is the following call:

` app.enable('jsonp callback');`

What is the intent behind this? By the looks of it, it is related to whether or not the app enables jsonp callback support, however I am puzzled as to how/where this is used. Is it deprecated? Or, perhaps, is the [express API doc](http://expressjs.com/en/4x/api.html) missing this? I ask this question for the following reasons:

1. this setting doesn't appear to be used/read anywhere else in the app. i.e. a [search here in the github repository for the setting `jsonp callback`](https://github.com/meanjs/mean/search?utf8=%E2%9C%93&q=jsonp+callback&type=Code) returns only a single result, i.e. where it is set. I understand from this that it is probably not intended to be 'used' by the app but rather by the express module internally;

2. according to the express API doc, [`app.enable(name)`](http://expressjs.com/en/4x/api.html#app.enable) sets the Boolean setting `name` to true, where `name` is one of the properties from the [app settings table](http://expressjs.com/en/4x/api.html#app.settings.table). However, I note that `jsonp callback` isn't listed in said app settings table.

Thanks for your time reading and considering this question.

Sincerely,
Dan

**Comment by lirantal** [comment]
@danoz-direct thanks for bringing this up.
I don't think it's required anymore but the option does exist, if you look at the settings table you pointed (http://expressjs.com/en/4x/api.html#app.settings.table) then it's there with a default 'callback' handler if the `name` is not specified.

**Comment by mleanos** [comment]
Resolved with #1463
