### ISSUE TITLE
multiple server layout supported?

### ISSUE THREAD

**Issue by genru** [meanjs/mean#1451]
I am trying to apply different layout for certain pages like login page, but after many attempt, I realized it's not easy to do.

I had tried route login url to new render function, but because some other routing issues stop it work.

```
   app.route('/').get(core.index);
   app.route('/authentication/*').get(core.renderLogin);
```

are there any way can do that?

**Comment by lirantal** [comment]
It's possible with swig but you need to create a new base layout and then render it properly.
In any way we're switching out of Swig and into `handlebars` probably, so look it up in their documentation and a fix will be coming soon to MEAN.JS to implement `handlebars`.

**Comment by genru** [comment]
Thanks for your quick response.
I don't think it's a layout problem, it's a routing issue. New server layout has no chance to be triggered. Current mean app is a sort of one-page app, multiple layout is hard to implement, there are a lot of routing  need to modify.

Handlebars would not help.

**Comment by genru** [comment]
Thanks for your quick response.
I don't think it's a layout problem, it's a routing issue. New server layout has no chance to be triggered. Current mean app is a sort of one-page app, multiple layout is hard to implement, there are a lot of routing  need to modify.

Handlebars would not help.

**Comment by lirantal** [comment]
@genru could you please explain why and suggest an example code to fix it?

**Comment by genru** [comment]
@lirantal I could not, I am not a nodejs or angular expert. what I found is this is a routing issue, as a said this framework perfect for a one-page app, because there is only one server layout.

I tried added new url route for login in core.server.route.js
```
app.route('/').get(core.index);
app.route('/authentication/*').get(core.renderLogin);
```

and new render function in core.server.controller.js
```
exports.renderLogin = function (req, res) {
  logger.trace('auth template renderred');
  res.render('modules/core/server/views/auth', {
    user: req.user || null
  });
};
```
created new layout named `auth.server.view.html` in views folder.
this new layout can be rendered when I access localhost:3000/authentication/signin directly, but not work when I access by clicking login link from menu bar, a login form with default layout instead.

it seems angular routing handled this request, express route had no chance to work.

**Comment by lirantal** [comment]
@genru please check out the new handlebars implementation - you can specify what is the parent layout for a view to render from. This way, in specific routes you can render a view that implements another layout than the default.

Let me know if this helps or still misses the point.

**Comment by mleanos** [comment]
Closing since the provided answer should help solve the problem.

@genru Feel free to re-open if needed.

**Comment by genru** [comment]
@mleanos @lirantal thank you for your discuss. after tons of google work, i found this is an actual "how to navigate to outside of angular app" question, not a routing matter.

finally i get a resolution here, http://stackoverflow.com/questions/16144619/how-do-i-navigate-away-from-an-angular-app

it perfectly resolved my problem. if you want to trigger server routing to render another server layout, just simply set `target='_self'` in A tag like
```
<a target='_self' href="/authentication/signin"><span>Login(server)</span></a>
```
hope this can save other developers who is struggling in similar issues. 

thanks for your all help.

**Comment by nlaycock** [comment]
Once you have logged out, and I gather you have a new template to use for logging in. But how did you set the new template once logged in?
