### ISSUE TITLE
Authentication fails 80% of time.

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1452]
I downloaded the fully working example of mean stack, but in 80% of the cases the login wont work, authentication/signin returns me server error.

in the grunt command lines, i do get:

```
    - -
        GET /modules/users/client/services/authentication.client.service.js 304 7.311 ms - -
        GET /modules/users/client/services/password-validator.client.service.js 304 17.815 ms - -
        GET /modules/users/client/services/users.client.service.js 304 7.199 ms - -
        GET /modules/core/client/views/header.client.view.html 304 1.300 ms - -
        GET /modules/core/client/views/404.client.view.html 304 1.051 ms - -
        GET /modules/users/client/views/authentication/authentication.client.view.html 304 2.172 ms - -
        GET /modules/users/client/views/authentication/signin.client.view.html 304 5.555 ms - -

```
but for some reason, it wont show?

result:

```
        Server Error
      Oops! Something went wrong...


```
EDIT1:

it seems like the view only shows when i drop my database for some reason?
and when i create a account, and wait abit, it wont work again?

**Comment by lirantal** [comment]
@frkwhiteangel no idea what you are referring to.
Where did you download the MEAN app from? which version? can you show a complete debug log of the application startup and the error you are getting?

**Comment by mleanos** [comment]
Closing for now since there hasn't been any response for some time. Also, this doesn't seem like an issue with the project itself.
