### ISSUE TITLE
Problem with documentation

### ISSUE THREAD

**Issue by jrodenbostel** [meanjs/mean#1464]
I just wanted to mention the docs on your home page say that the AngularJS Test Sub-Generator should be called with 

```
yo meanjs:angular-test <controller-name>
```
but the installed generator says it should be:
```
yo meanjs:angular-tests
```

Same seems to be true for the Express equivalent.  I did not see a way to help update this.

Thanks!

**Comment by lirantal** [comment]
@codydaig care to take a look?

**Comment by lirantal** [comment]
Thanks @jrodenbostel 
Fixed in PR: https://github.com/meanjs/meanjs.github.io/pull/13
