### ISSUE TITLE
Considering move of view cache setting

### ISSUE THREAD

**Issue by danoz-direct** [meanjs/mean#1470]
Hi there,

Have just been looking at the following block inside [mean/config/lib/express.js](https://github.com/meanjs/mean/blob/master/config/lib/express.js)

```
  // Environment dependent middleware
  if (process.env.NODE_ENV === 'development') {
    // Disable views cache
    app.set('view cache', false);
  } else if (process.env.NODE_ENV === 'production') {
    app.locals.cache = 'memory';
}
```
Presently, that block is sitting inside the function `initMiddleware`.

Given that block is not technically middleware but rather more related to express system settings, I was considering submitting a PR to move that block out into another function. i.e. to improve maintainability/understanding. For example, I was considering moving it into the other nearby function `initViewEngine`. 

What does everyone think? Would this be logical? Useful? Not really?

It's a tiny/semantic thing I know, so just thought I'd discuss first before jumping in.

**Comment by danoz-direct** [comment]
Oh, and also, was wondering about the line...

`app.locals.cache = 'memory';`

This might need to be updated based on the [Express API doc](http://expressjs.com/en/4x/api.html#app.render) where they say...

> The local variable `cache` is reserved for enabling view cache. Set it to true, if you want to cache view during development; view caching is enabled in production by default.

**Comment by lirantal** [comment]
@danoz-direct hi! :)
sounds like a good idea, although the only other question is whether it was put where it is now due to priority. As you know, the order in which middleware is called in ExpressJS has a significance.

I think that else expression can be removed indeed.

Thanks for helping out

**Comment by danoz-direct** [comment]
Hi @lirantal  :v: 

Understood. Hmm, so even though the call to `app.set('view cache', false);` isn't technically middleware but rather a configuration of one of the [express application settings](http://expressjs.com/en/api.html#app.set), perhaps it is being set at that point for a reason? That is what you are asking?

I'll keep researching and will try to find out a few things first before proceeding further. I'll aim to find out answers to the following two questions:

1. Does the order in which [express application settings](http://expressjs.com/en/api.html#app.set) get configured matter in relation to the order of middleware? i.e. We know that the order of express middleware matters, but is it also the case that the order of express settings matters in that context?

2. Is there a specific reason why you would need to turn off the express view cache in DEV via the call `app.set('view cache', false);` prior to (i.e. in sequence before) enabling the following middleware: body-parser, method-override, cookie-parser and then connect-flash?

Give me a little while and I'll drop back in to let you know what I find out (unless you or someone else here beats me to it).

**Comment by simison** [comment]
BTW in ExpressJS view cache is enabled by default in production and off in development mode.

http://expressjs.com/en/api.html

**Comment by danoz-direct** [comment]
http://expressjs.com/en/api.html#app.set


> view cache
> Boolean
> 
> Enables view template compilation caching.
> NOTE: Sub-apps will not inherit the value of this setting in production (when `NODE_ENV` is "production").
> 
>   true in production, otherwise **undefined**.

**Comment by simison** [comment]
Also:

> the contents do not cache, just the compiled template function 

Anyway, seems like the whole thing can be removed and it wouldn't change anything.

**Comment by danoz-direct** [comment]
https://github.com/expressjs/express/issues/542

Cool, thanks @simison :+1: 

That answers Q2.

I've got an open question over on the Express repo, will let you know what I hear back.

**Comment by lirantal** [comment]
Great, keep it moving :)

**Comment by danoz-direct** [comment]
@lirantal 

Apologies, I'm getting all sorts of errors when trying to get MeanJS set up on a clean [Vagrant ](https://www.vagrantup.com/)([Scotch Box](https://box.scotch.io/)) machine and running `npm install`.

I've tried a quick investigation myself to see what is happening to no avail yet...

Hence, there might be a bit of delay with me being able to make the changes I've mentioned here and submitting them up in a PR.

**Comment by lirantal** [comment]
@danoz-direct no problems.
what about spinning up the docker instance?

**Comment by simison** [comment]
@danoz-direct `NPM install` tends to fail on Vagrant due symlink issues. Add `-–no-bin-link` or use [sympm).](https://github.com/ezekg/sympm).

**Comment by danoz-direct** [comment]
Thanks @lirantal & @simison, 

The errors more relate to protractor/selenium and the E2E tests. The first thing I want to do is ensure that I can get meanjs installed and running on a clean machine with all tests passing. 

Minor oversight on my behalf, I spun up a VM that didn't have the necessary dependencies for protractor/selenium (i.e. openJDK, chrome, etc.)

@lirantal, I'll have a go at spinning up a [Vagrant/Docker](https://www.vagrantup.com/docs/docker/basics.html) instance as per your suggestion. BTW - I really appreciate the tip, thanks.

**Comment by lirantal** [comment]
@danoz-direct I personally use the project's Docker file/compose setup to develop locally, it's a breeze because you don't have to install anything as dependency.

1. Clone the project
2. Make sure you have the basic tools like docker, git, etc installed on your OS (hopefully Linux based)
3. cd into the project and run `docker-compose up -d` which will take some time to build the image for you 

then it's ready, you can work with your favorite IDE to update the source code and it will reflect in real-time updating of the running mean.js instance.

**Comment by mleanos** [comment]
Closing this since it appears the original question has been answered.

@danoz-direct Feel free to re-open if this is still an outstanding issue. Otherwise, you can open a new issue for your Docker problems.
