### ISSUE TITLE
Redirect if not logged in

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1475]
Is there a way to redirect a user if not logged in into the login view?

**Comment by lirantal** [comment]
@simison , @mleanos ?

**Comment by simison** [comment]
Suppose you should modify this somehow:

https://github.com/meanjs/mean/blob/8da372519a4f7894966835904ab7bd28368922ea/modules/core/client/config/core.client.route-filter.js#L18

...tho it looks like it's already doing something like that using `roles` from route configs (e.g. https://github.com/meanjs/mean/blob/master/modules/chat/client/config/chat.client.routes.js#L18)

**Comment by hyperreality** [comment]
Fixed #1496

Gotta hate Javascript sometimes ;)
