### ISSUE TITLE
Fix deprecated `$http.error()` and `$http.success()`

### ISSUE THREAD

**Issue by simison** [meanjs/mean#1479]
https://docs.angularjs.org/api/ng/service/$http

>The `$http` legacy promise methods `success` and `error` have been deprecated. Use the standard `then` method instead. If [`$httpProvider.useLegacyPromiseExtensions`](https://docs.angularjs.org/api/ng/provider/$httpProvider#useLegacyPromiseExtensions) is set to false then these methods will throw [`$http/legacy`](https://docs.angularjs.org/error/$http/legacy) error.

Used at least here:
- https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/client/controllers/settings/change-password.client.controller.js
- https://github.com/meanjs/mean/blob/c95bd7d1cb0c6e651f82b2b4cfa4e937d4dcf154/modules/users/client/controllers/settings/manage-social-accounts.client.controller.js
- https://github.com/meanjs/mean/blob/59e6daa63d65798886e446fc7696b6331c9e3aba/modules/users/client/controllers/authentication.client.controller.js

**Comment by simison** [comment]
Happy if someone else would have the time to do a PR. :P

**Comment by mleanos** [comment]
I'm on it! This has been in the back of my mind for a while. Thanks Mikael.

**Comment by simison** [comment]
@mleanos you might wanna have a look at this: 
* https://github.com/Trustroots/trustroots/blob/master/gulpfile.js#L198-L208
* https://github.com/Trustroots/trustroots/blob/master/.eslintrc-angular.js#L22
 — it's a eslint gulp task for Angular stuff only.
