### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1483]
any idea when the new release is comming? since its 90% done.

**Comment by lirantal** [comment]
Yep, a few more PRs to merge and we're good.

**Comment by frkwhiteangel** [comment]
So 1 month?

Im really wanting for update to update the rendered view

Den tirsdag 6. september 2016 skrev Liran Tal <notifications@github.com>
følgende:

**Comment by lirantal** [comment]
I think we can release within a few weeks already in September.

**Comment by frkwhiteangel** [comment]
Great!

Could you already spoon feed how it's supposed to work regarding update
variables in the rendered view from results in a modules controller ?

Den tirsdag 6. september 2016 skrev Liran Tal <notifications@github.com>
følgende:

**Comment by lirantal** [comment]
You mean with regards to the handlebars update?
Exactly the same. Take a look at the main layout file in the core module's server views directory.

**Comment by frkwhiteangel** [comment]
I mean the update where you can change variables that loaded in the render,
outside the U.K.-view with info loaded in a ui-view controller if you know
what I mean

Den tirsdag 6. september 2016 skrev Liran Tal <notifications@github.com>
følgende:

**Comment by frkwhiteangel** [comment]
Ment ui-view *

Den tirsdag 6. september 2016 skrev Malin Pedersen <
frk.malin.pedersen@gmail.com> følgende:

**Comment by simison** [comment]
This was the same questions as #1473 I suppose. I still don't understand what are you exactly asking, though. :-/ Mind elaborating a bit more?

**Comment by frkwhiteangel** [comment]
Why did you add it to the milestone then ?

Anyway, you remember that the view is rendered one time in the core, right
with the view?
And then the view is creating the U.i-view where all the info comes on
router change, right ?

I'm in need for a way, to update variables I'm using in the rendered view,
with info from one of the modules controller.

Let's say I'm in the rendered view that the core sever is rendering have a
variable called user,

And in the U.i-view have a controller with new information, that I need to
update it to the user variable outside of the ui-view. How will I do that?
How can I make those changes ? The rootscope won't work.

Den tirsdag 6. september 2016 skrev Mikael Korpela <notifications@github.com>
følgende:

**Comment by simison** [comment]
I see. You can access those variables from template (e.g. `var user = ...`) using `$window`, e.g. `$window.user`.

**Comment by frkwhiteangel** [comment]
May I update the variable using window too?

Any other ways?

How could I for example make a query that would run to update it no matter
of what module I'm visiting?

Den tirsdag 6. september 2016 skrev Mikael Korpela <notifications@github.com>
følgende:

**Comment by frkwhiteangel** [comment]
i tried to update $window.user.cash to 20, but the site wont relfect the
changes.

2016-09-06 17:58 GMT+02:00 Malin Pedersen <frk.malin.pedersen@gmail.com>:

**Comment by simison** [comment]
Yeah sorry, forgot to mention that `$window.user` is already accessible trough a service called `Authentication`. So require it for your controller [like this](https://github.com/meanjs/mean/blob/master/modules/users/client/controllers/password.client.controller.js#L8-L10) and then set `Authentication.user.cash = 20;`. If you want to reflect that at the current controller's scope, you need to expose that user like this `vm.user = Authentication.user;`

**Comment by frkwhiteangel** [comment]
So If i set audentication.user.cash IT Would be reflected in The rendered
view where i USE {{ user.cash }} ?


Den tirsdag 6. september 2016 skrev Mikael Korpela <notifications@github.com>
følgende:

**Comment by simison** [comment]
Just play around and check how it's done at controllers here: https://github.com/meanjs/mean/tree/master/modules/users/client/controllers ;-)

**Comment by frkwhiteangel** [comment]
hi again. tried audentication.user.cash = 20, but that wont be reflected
right away on the rendered view. any idea how to make it work?

2016-09-06 19:43 GMT+02:00 Malin Pedersen <frk.malin.pedersen@gmail.com>:

**Comment by lirantal** [comment]
The template variable that gets rendered in the view comes from express. Whatever you may set it to from the client side later on will obviously get re-written and back to whatever it was set to in a new page load.

I'm also a bit confused as to what you're trying to ask exactly.

**Comment by frkwhiteangel** [comment]
my core / server file:

  ```
 res.render('modules/core/server/views/index', {
      user: safeUserObject,
    });
```

http://prntscr.com/cex7l1 is how my site looks.
everything in white there, is the different ui-view, while the black areas, is the rendered one.


inside the ui-view,  i want to update where the layout says " Penger : 100000465 kr ", so i would like it to change the amount of penger, in this case:

>         ```
<p class="header-item"><span style="cursor: pointer;"><b>Penger
		:</b> {{ parseInt(user.cash) }}  kr</span></p>
```


so i would for example like it to call the Authentication and update the cash user variable to a value, and i want it reflected in the layout that i screened above.

did that make it better to understand?

**Comment by simison** [comment]
You need to first tell the backend that the new user model should be saved to the database, like this: https://github.com/meanjs/mean/blob/master/modules/users/client/controllers/settings/edit-profile.client.controller.js

**Comment by frkwhiteangel** [comment]
Im intrested to know how I can reflect it right away in the site because
it's triggered from client .


I could take a longer discussion with you if you want .

Another question : is it easy to broadcast server sided to the client ? To
be more specific , to broadcast with socket within a function ( from a
server sides factory )?

Den tirsdag 6. september 2016 skrev Mikael Korpela <notifications@github.com>
følgende:

**Comment by frkwhiteangel** [comment]
I'm in no need to update server sides regarding my first question , only to
reflect it client sided with results from a module controller , without the
need to actually reload the page.

Den tirsdag 6. september 2016 skrev Malin Pedersen <
frk.malin.pedersen@gmail.com> følgende:

**Comment by simison** [comment]
Then this:

>If you want to reflect that at the current controller's scope, you need to expose that user like this `vm.user = Authentication.user;` 

Or just `vm.user.cash = 20;` — if you don't have to save that to the DB, then that's enough.

...and some studying how Angular's scopes work: https://docs.angularjs.org/guide/scope ;-)

**Comment by frkwhiteangel** [comment]
I want to reflect it wise versa . I want to reflect it FROM the controller
to the rendered view, that for now have to be forced with a reload .

Isn't it possible to make a core controller to run on the rendered view to
the changes would be reflected in the rendered view right away? Or some
solution ?

Den tirsdag 6. september 2016 skrev Mikael Korpela <notifications@github.com>
følgende:

**Comment by frkwhiteangel** [comment]
If You GOT What i mean

**Comment by mleanos** [comment]
@frkwhiteangel Have you solved this issue yet? 

It's hard to tell exactly what you're trying to accomplish. However, from what I gather, you can do what @simison suggested:

> Then this:

>    If you want to reflect that at the current controller's scope, you need to expose that user like this vm.user = Authentication.user;

> Or just vm.user.cash = 20; — if you don't have to save that to the DB, then that's enough.

> ...and some studying how Angular's scopes work: https://docs.angularjs.org/guide/scope ;-)

Also, from your example using `{{ parseInt(user.cash) }} kr` you don't need to parse your value. If you need to do that, then just do it in the controller or add a filter to do it. Using the `parseInt()` function will disable the two-way binding on your UI element. So using just `{{ user.cash }} kr` will suffice.

**Comment by mleanos** [comment]
Closing since this doesn't seem to be an issue, and the answers are sufficient to address the question.
