### ISSUE TITLE
Writing tests for socket server

### ISSUE THREAD

**Issue by shanavas786** [meanjs/mean#1484]
How to write socket io server test cases.

this is what I tried and failed.

```
  express = require(path.resolve('./config/lib/express')),
  config = require(path.resolve('./config/config')),
  io = require('socket.io-client');
```

in before hook
```
    var app = express.init(mongoose);
    socketUrl = 'http://' + config.host + ':' + config.port;
```
and test
```
      this.timeout(20000);

      socket = io.connect(socketUrl, {
        transports: ['websocket'],
        'force new connection': true
      });
      socket.on('connect', function () {
        console.log(1);
      });

      socket.on('disconnect', function () {
        console.log(2);
        done();
      });
      socket.disconnect();
```

Test just times out with no console output. Am I missing something ?

EDIT
----------
added
```
app.listen(config.port, config.host);
```
in before hook. no effect.

**Comment by shanavas786** [comment]
Fixed it.
with `app.listen` and moving `socket.disconnect` to callback of connect event, it worked.

**Comment by mleanos** [comment]
Can you share your overall solution for testing SocketIO? This is a server test right?

**Comment by mleanos** [comment]
@shanavas786 See the work done here, that wasn't merged in. We were waiting for a version of the socketio package to be released/added-to-npm.

https://github.com/meanjs/mean/pull/865

Do you think you could help out with this effort? I completely lost track of that PR, so I haven't done any more work on it.

**Comment by shanavas786** [comment]
@mleanos 
Here is a basic test case [gist](https://gist.github.com/shanavas786/c8243b150ec742dbd8b75f660ae6a355) written for our project which doesn't use express session (RESTful).

> Do you think you could help out with this effort? I completely lost track of that PR, so I haven't done any more work on it.

Sure :). I thought about it when I saw empty [chat.socket.tests.js](https://github.com/meanjs/mean/blob/master/modules/chat/tests/server/chat.socket.tests.js).
But I am afraid if I get enough spare time for next two weeks.
