### ISSUE TITLE
Haven't debug yet, however social login buttons don't work on mobile browers.

### ISSUE THREAD

**Issue by Valm1980** [meanjs/mean#1492]
They render fine, however attempting to click on them in Firefox/Chrome on mobile devices don't seem to redirect. Work fine in regular desktop browsers.

On Android Kitkat / No Adblockers which sometimes interferes with img/buttons which contains social names.

**Comment by lirantal** [comment]
cc @hyperreality

**Comment by hyperreality** [comment]
Hi @Valm1980, this is something which I think got fixed recently, I can't reproduce it on either Android or iPhone using the latest build.

However in the meantime I did discover that the social buttons don't display nicely on the tiny screen of the iPhone, @lirantal do you have any objection to cutting them down to 80% size? I think they are too large on desktop also.

**Comment by Valm1980** [comment]
I can confirm it is working with latest git clone from source.

**Comment by mleanos** [comment]
@hyperreality Feel free to submit a PR. It sounds like a small cosmetic change, and just as long as it looks good, and works, I'm sure we'll merge it right in :)

**Comment by lirantal** [comment]
@hyperreality https://github.com/meanjs/mean/pull/1499 fixes this, right?

**Comment by hyperreality** [comment]
@lirantal The issue was already fixed, #1499 just adds further improvements

**Comment by lirantal** [comment]
Thanks :+1:

**Comment by mleanos** [comment]
@lirantal I think this can be closed.
