### ISSUE TITLE
Save method not adding user

### ISSUE THREAD

**Issue by richjava** [meanjs/mean#1497]
I recently added a new CRUD module (called "projects") to my app using Yeoman and needed to add a line (see below) in the projects.client.controller save method to get CRUD functionality to work as expected. Is there something I'm missing?

```
function save(isValid) {
      if (!isValid) {
        $scope.$broadcast('show-errors-check-validity', 'vm.form.projectForm');
        return false;
      }
      vm.project.user = vm.authentication.user._id; //<-- I added this line and it works
      // TODO: move create/update logic to service
      if (vm.project._id) {
        vm.project.$update(successCallback, errorCallback);
      } else {
        vm.project.$save(successCallback, errorCallback);
      }
```

**Comment by mleanos** [comment]
You should be setting `project.user` in your server controller. I'm surprised that your `project` didn't save without the referenced User. Perhaps it's a required field?

**Comment by richjava** [comment]
My mistake. I had commented out the setting of the user in the server controller because I was getting a "Cast to ObjectId failed for value "[object Object]" at path "_id"" error for some reason, but it seems fine now. Thanks!
