### ISSUE TITLE
Header controller doesn't update params after sign-in

### ISSUE THREAD

**Issue by hyperreality** [meanjs/mean#1502]
This may be related to this super old issue #187.

The issue concerns adding parameters to the dropdown account menu. In my case I wanted a dynamic link to a user's profile. 

The problem: after sign-in, params placed in `header.client.view.html` will point to the correct places, but param properties in the account menu object created from `core.client.menus.js` will not be updated. This is because the [header controller](https://github.com/meanjs/mean/blob/master/modules/core/client/controllers/header.client.controller.js) is not refreshed on state change, only on page reload. 

The issue could be fixed by adding an updater to vm.accountMenu [here](https://github.com/meanjs/mean/blob/master/modules/core/client/controllers/header.client.controller.js#L23) but this is just a performance impact, which although minor, is totally unnecessary. Personally I don't see what the account menu config adds to the app, you end up with a bunch of angular watchers in the header watching stuff that doesn't change. I'll be hard-coding my menu choices into `header.client.view.html` to avoid headaches like this. And I want to begin a discussion on the value of the account menu.

**Comment by acenter2507** [comment]
This issue is solved ?

**Comment by acenter2507** [comment]
I'm tried to resolve it and my code is below.
**authentication.client.controller.js**
`function onUserSigninSuccess(response) {`
     ` // If successful we assign the response to the global user model`
      `vm.authentication.user = response;`
      `Notification.info({ message: 'Welcome ' + response.firstName });`
      `$rootScope.$emit('loginSuccess'); // Push a notif to Header controller`
      `// And redirect to the previous or home page`
      `$state.go($state.previous.state.name || 'home', $state.previous.params);`
   ` }`
**header.client.controller.js**
`function HeaderController($rootScope, $scope, $state, Authentication, menuService) {`
`  var vm = this;`
`  init();`
`  function init() {`
`    vm.user = Authentication.user;`
`    vm.isLogged = (vm.user);`
`  }`
`$rootScope.$on('loginSuccess', () => {`
`  init();`
`});`
Hope it's useful.

**Comment by simison** [comment]
This should be implemented precisely as @acenter2507 describes. Here is more information about $emit/$broadcast/$on: https://stackoverflow.com/a/37717690/1984644

**Comment by mleanos** [comment]
I'm not following what the issue is. After the user is logged in,  doesn't the header update based on `Authentication.user`? Also, when the user updates their profile,  the header updates as well. 

Can someone explain a use case?

If the issue is just adding a dynamic menu item,  wouldn't using something like `menuService.addMenuItem` work?

I think using `$broadcast/$emit` would work,  but I've also used Socket events to notify the HeaderController.

**Comment by simison** [comment]
![image](https://user-images.githubusercontent.com/87168/28663496-34d4ce2e-72c6-11e7-8b72-7ac7eee37c91.png)

So header might have content which depends on info from other Services/Factories like `Authentication` service.

Header controller is listening changes only on its own scope, so you have to notify it about updates outside the scope.

Example of [broadcasting](https://github.com/Trustroots/trustroots/blob/34e9dbc4e6043df25dafd1d613325b8c9dbbbc23/modules/users/client/controllers/confirm-email.client.controller.js#L46-L47
):
```js
Authentication.user = response.data.user;
$rootScope.$broadcast('userUpdated');
```

Example of [listening](https://github.com/Trustroots/trustroots/blob/master/modules/core/client/controllers/app.client.controller.js#L143-L145):
```js
$scope.$on('userUpdated', function() {
  vm.user = Authentication.user;
});
```

What exactly has to be emited/broadcasted depends so much on app that it doesn't make sense to implement this as a feature to Mean.js and as far as I can remember there isn't anything in Mean.js header controller that would need updating?

> I think using $broadcast/$emit would work, but I've also used Socket events to notify the HeaderController.

That's a good idea as well.
