### ISSUE TITLE
Error handling for articles

### ISSUE THREAD

**Issue by hyperreality** [meanjs/mean#1504]
Invalid articles currently go to a blank page, rather than the correct error page. The 400 or 404 errors are sent from the server, they're just not dealt with on the client-side. I don't have the time to fix it up and test it now but I think the below is a start, in `articles.client.routes.js` (or perhaps it should go into the controller although I don't think the controller is ever reached if there's an error). Paging @mleanos

    function getArticle($stateParams, ArticlesService) {
      return ArticlesService.get({
        articleId: $stateParams.articleId
      }).$promise.then(function(data) {
        return data;
      }, function(error) {
        console.log(error);
      }) 
    }

**Comment by mleanos** [comment]
We're already returning a 404 from the server when an [Article isn't found](https://github.com/meanjs/mean/blob/master/modules/articles/server/controllers/articles.server.controller.js#L110). So we just need to add a 404 handler [here](https://github.com/meanjs/mean/blob/master/modules/core/client/services/interceptors/auth-interceptor.client.service.js) to send the user to a 404 view. So this should only involve the client-side addition of $http interceptors for 400 & 404.

I don't know what happened to this PR: https://github.com/meanjs/mean/pull/1052. But it looks like it will solve this issue.

**Comment by hyperreality** [comment]
Indeed, that appears to do the trick. However, that approach does have a couple of issues.
 
1. The error message is generic, as opposed to preserving the "Article not found" error message sent from the server.
2. The back button breaks - the previous page just sends you directly back to the error state.
