### ISSUE TITLE
config.domain Vs. config.app.domain

### ISSUE THREAD

**Issue by 19r3ka** [meanjs/mean#1506]
Hi all, 

Going through the code, these lines kinda bugged me: 

`var validateDomainIsSet = function (config) {
  if (!config.app.domain) {
    console.log(chalk.red('+ Important warning: config.domain is empty. It should be set to the fully qualified domain of the app.'));
  }
};`

is `domain` a key on the nested app object? Because judging by the following **important warning**, it is a key on the main config object. Even in config/env/default.js, it is set on the top-level object:

`app: {
    title: 'MEAN.JS',
    description: 'Full-Stack JavaScript with MongoDB, Express, AngularJS, and Node.js',
    keywords: 'mongodb, express, angularjs, node.js, mongoose, passport',
    googleAnalyticsTrackingID: process.env.GOOGLE_ANALYTICS_TRACKING_ID || 'GOOGLE_ANALYTICS_TRACKING_ID'
  },
  port: process.env.PORT || 3000,
  host: process.env.HOST || '0.0.0.0',
  // DOMAIN config should be set to the fully qualified application accessible
  // URL. For example: https://www.myapp.com (including port if required).
  domain: process.env.DOMAIN,`

I still think I'm the one mistaking here so please correct me, I am still learning the MEAN stack.

**Comment by hyperreality** [comment]
Looks like a bug, submit a PR :)

**Comment by sujeethk** [comment]
This is a quickfix. @19r3ka are you opening a PR?

**Comment by mleanos** [comment]
@sujeethk Feel free to open a PR to fix this, since this should be pretty quick.
