### ISSUE TITLE
Failed at the meanjs@0.5.0-beta start script

### ISSUE THREAD

**Issue by et-taousy** [meanjs/mean#1507]
hi there i followed all steps but i get some errors when i come to start npm:
`npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! meanjs@0.5.0-beta start: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the meanjs@0.5.0-beta start script 'gulp'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the meanjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs meanjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls meanjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/share/nginx/html/www.vipco.fr/npm-debug.log
`

**Comment by hyperreality** [comment]
Try running Gulp directly `gulp` in the project and look at the error message.

It could be caused by the fact that you're using a super up-to-date node version and one of the gulp dependencies doesn't support it yet.

**Comment by et-taousy** [comment]
Node version : 6.4.0
Npm vercion : 3.10.3

when i'm running gulp i got this issue :

`[06:02:50] Using gulpfile /usr/share/nginx/html/www.vipco.fr/gulpfile.js
[06:02:50] Starting 'default'...
[06:02:50] Starting 'env:dev'...
[06:02:50] Finished 'env:dev' after 135 μs
[06:02:50] Starting 'copyLocalEnvConfig'...
[06:02:50] Starting 'makeUploadsDir'...
[06:02:50] Finished 'makeUploadsDir' after 303 μs
[06:02:50] Finished 'copyLocalEnvConfig' after 20 ms
[06:02:50] Starting 'lint'...
[06:02:50] Starting 'less'...
[06:02:51] Finished 'less' after 624 ms
[06:02:51] Starting 'sass'...
[06:02:51] Finished 'sass' after 26 ms
[06:02:51] Starting 'csslint'...
[06:02:51] Starting 'eslint'...
/usr/share/nginx/html/www.vipco.fr/node_modules/rcloader/index.js:39
        if (err) throw err;
                 ^

Error: ENOENT: no such file or directory, open '.csslintrc'
  at Error (native)
`

**Comment by hyperreality** [comment]
It might be that your UNIX permissions aren't set up correctly because you are running things straight out of /usr/

Try running the project out of your home directory instead.

**Comment by lirantal** [comment]
Are you sure you have cloned the repository properly? make sure you run `npm install` again and indeed check your permissions correctly.

**Comment by mleanos** [comment]
Closing this for now, since we haven't heard feedback. This is most likely an environment issue & not an issue with the project itself.
