### ISSUE TITLE
Include asset versioning

### ISSUE THREAD

**Issue by Xyroid** [meanjs/mean#1509]
Since MEAN app depend heavily on Javascript files, it would be better if assets like CSS, JS and image files are versioned if they are changed. It helps it busting cache issues. In ASP.NET bundling provide minification and versioning. I was searching the same for MEAN and reached to [gulp-rev](https://github.com/sindresorhus/gulp-rev) npm module. But I am new to MEAN and I find it hard to integrate. If any one has used then please guide me for it. I also request to integrate it MEANJS itself.

**Comment by lirantal** [comment]
Hi @Xyroid 

That's a great idea and that plugin should be exactly what we need.
If you're able to figure out how to write this in our `gulpfile.js` configuration then I'd be happy to see a PR opened.

**Comment by Xyroid** [comment]
Hi @lirantal I am not able to figure out regarding integrating gulp-rev npm module because I am still learning MEAN. I also don't use gulp too much. If MEANJS team can do something, that'll be awesome.
