### ISSUE TITLE
"Gulp build" removes assets from production.js

### ISSUE THREAD

**Issue by Eswan** [meanjs/mean#1515]
(Sorry for my english)

I just finished my Mean.JS application and i try to pull it in production mode on my web server.

When i try to run "grunt prod" or "gulp prod", it removes some assets from my production.js and default.js files like jquery.js or bootstrap.js before build, so my website doesn't work properly.

Thanks for help

**Comment by lirantal** [comment]
@Eswan we're deprecating Grunt for Gulp so can you please describe the problem better with sharing the code you've added that gets removed?

**Comment by Eswan** [comment]
Here is my production.js asset file before i run "gulp prod" command : http://hpics.li/f8feeaf

Then after i run this command : http://hpics.li/07f8dec

As you can see, theses two lines has been removed from js assets : 
'public/lib/jquery/dist/jquery.min.js',
'public/lib/bootstrap/dist/js/bootstrap.min.js',

jQuery and Bootstrap aren't include in application.min.js so i have multiples error like "$ not defined..."

Here gulpfile.js code : http://hpics.li/e72d3bb, maybe this part is the origin of my problem ?

Thanks

**Comment by Eswan** [comment]
I just resolved my problem by adding bootstrap and jquery in "overrides" attribute in bower.json

**Comment by lirantal** [comment]
Thanks for the update @Eswan

**Comment by joonas-yoon** [comment]
@Eswan i have same problem :(
can i get your `bower.json` ?

**Comment by joonas-yoon** [comment]
Thanks! solved my problem.
here is "overrides" in my bower.json

```json
  "overrides": {
    "bootstrap": {
      "main": [
        "less/!(variables).less",
        "dist/fonts/*",
        "dist/js/*",
        "dist/css/bootstrap.css",
        "dist/css/bootstrap-theme.css",
        "less/bootstrap.less"
      ]
    },
    "jquery": {
      "main": [
        "dist/*.js"
      ]
    }
  },
```

thanks
