### ISSUE TITLE
Multiple Coveralls notifications

### ISSUE THREAD

**Issue by hyperreality** [meanjs/mean#1520]
Could it be caused by the fact that we are not doing this? https://coveralls.zendesk.com/hc/en-us/articles/203484329-Parallel-Build-Webhook And multiple builds are sending their results to Coveralls.

We'd also need to update node-coveralls to a newer version, current version is 2.11.13, we have 2.11.6 which was before support for parallel builds was added.

**Comment by lirantal** [comment]
@hyperreality can you open a PR for the coveralls version?

**Comment by lirantal** [comment]
Can you also include the travis setup as they provide? seems like we need to put a token there and I remember there's a way to build with secret parameters

**Comment by hyperreality** [comment]
@lirantal Apologies, I anticipate being very busy for the next few weeks, can't look at this right now.

**Comment by codydaig** [comment]
Just throwing this out there: Can we disable comments all together? I find them very annoying since it's already displayed in the CI portion.

**Comment by hyperreality** [comment]
Good call, it's just a quick fix in the Coveralls settings.

**Comment by codydaig** [comment]
@lirantal Is this something that you can do or give @mleanos and/or I access to do?

**Comment by lirantal** [comment]
I disabled the comments.
I think coveralls allows only project admins to configure these settings. I didn't drill in but this is what it looks like.
