### ISSUE TITLE
ENOENT: .csslintrc

### ISSUE THREAD

**Issue by Wats0ns** [meanjs/mean#1527]
Getting the `Error: ENOENT: no such file or directory, open '.csslintrc'` when doing an `npm install`

**Comment by sujeethk** [comment]
@Wats0ns do you see a .csslintrc file in your project folder?

**Comment by sujeethk** [comment]
I just did a fresh install using the master and got a clean install with no ERRs. are you still seeing issue, if so what is your node, npm and meanjs version? If not this issue can be closed.

**Comment by Wats0ns** [comment]
No, I don't see the .csslinrc in my project folder :/

**Comment by sujeethk** [comment]
@Wats0ns well there lies the issue :). You could probably try a fresh clone from the master. Or simply download the .csslintrc file and put it on your project folder and see if it works
