### ISSUE TITLE
SEO issue - Dynamic titles

### ISSUE THREAD

**Issue by Eswan** [meanjs/mean#1528]
Hello everyone,

I have problem concerning SEO on my website : https://www.google.fr/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:goldnord.fr&filter=0

Google doesn't care about the title mark, it takes description meta for results titles.

Here is a page : https://goldnord.fr/vendre-mon-or/treflaouenan

As you can see, my title is generated by angularjs with page-title directive from mean.js

How could i solve my problem ?
Should i use a tool like prerender.io ?

Thanks.

**Comment by hyperreality** [comment]
It would be nice if you gave some information about why you closed this issue... did you find a solution to your problem?

**Comment by Eswan** [comment]
Unfortunately i didn't solve m'y problem but i did some changes on my website and i dont use page-title anymore, i use rootscope with a simple title variable. Still doesn't work i dont know why...
Google refuses to take the generated title.

**Comment by dansundy** [comment]
I have found the same thing.

According to issue #1446 Google should be able to crawl the JS but I haven't found that to be true.

I think using [prerender.io](https://prerender.io/) or [mean-seo](https://www.npmjs.com/package/mean-seo) is still the way to go.

I would be curious if others had a definitive answer on how SEO should be handled for MEAN.js post October 2015 (which is when Google released [this blog post](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html)).

**Comment by simison** [comment]
See also https://github.com/meanjs/mean-seo/issues/20

`mean-seo` isn't really maintained anymore and it [has some security issues](https://snyk.io/test/github/meanjs/mean-seo/)

**Comment by Eswan** [comment]
I solved my problem by using prerender.io, it seems Google isn't able to fully understand angular apps.
