### ISSUE TITLE
Trying to improve user experience on authentication

### ISSUE THREAD

**Issue by igorauad** [meanjs/mean#153]
I'm trying to adapt the authentication to my needs and somehow improve user experience. Given the various possibilities, I would like to share my thoughts and accept suggestions.

In the sequel, please note I`ve removed from my app providers that do not provide email information. In fact, I chose only **facebook**, **google** and **linkedIn**. In addition, assume the user is not yet logged in.

### Case 1: User registered via Provider (e.g. facebook), tries to sign in w/ email and password

In case the email is the same as the one provided by facebook, in my opinion the best user experience in this case would be to receive a message recommending to sign in with facebook (instead of simply saying the 'username or password is incorrect').

To do this, I added the following to the local strategy.

    if (user.provider !== 'local') {
        return done(null, false, {
            message: 'Please, sign in with ' + user.provider
        });
    }

In case the email is different, it is obviously impossible to detect the user has a registered facebook account. 

* * *
### Case 2: User registered “locally” tries to sign in w/ provider whose email is the same

In this case it would be a good experience for the user to authenticate into the same account. For this to work, I would add an email search query in “saveOAuthUserProfile()"

    // Email search query
    var emailSearchQuery = {
        email: providerUserProfile.email
    };

    // Define a search query to find existing user with current provider profile
    var searchQuery = {
        $or: [mainProviderSearchQuery, additionalProviderSearchQuery, emailSearchQuery]
    };

* * *
### Case 3: User registered “locally” tries to sign in w/ provider whose email is different

Given that the user is not logged in, there is nothing to be done in this case. This action would create another user account, which is bad, but unavoidable.

* * *

### Case 4:  User registered via Provider (e.g. facebook), tries to sign in w/ another provider (e.g Google) in which his email address is the same:

For this to work, given that the search query can now match by the email address, it is necessary to check if the provider is already configured, with practically the same code as if the user was trying to add the provider:

    // Check if user doesn't have that provider data already configured
	if (user.provider !== providerUserProfile.provider && (!user.additionalProvidersData || !user.additionalProvidersData[providerUserProfile.provider])) {
		// Add the provider data to the additional provider data field
		if (!user.additionalProvidersData) user.additionalProvidersData = {};
		user.additionalProvidersData[providerUserProfile.provider] = providerUserProfile.providerData;

		// Then tell mongoose that we've updated the additionalProvidersData field
		user.markModified('additionalProvidersData');

		// And save the user
		user.save(function(err) {
			return done(err, user);
		});
	} else {
		return done(err, user);
	}

* * *

### Case 5:  User registered locally with two different accounts (for any possible reason), tries to add in one of the two accounts a provider that was already registered in the other:

If a user does that, then one of the accounts would become unaccessible via the provider that is common to both accounts. Although this is a minor issue, I provided a solution in my app.

* * *

Regards

**Comment by ilanbiala** [comment]
@igorauad has this been resolved?

**Comment by igorauad** [comment]
@ilanbiala this discussion was not continued, so I guess you could close. Perhaps this could be further considered in #343
