### ISSUE TITLE
Socket emir inside functions

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1533]
Im using MEAN stack, with angularjs frontend, node backend.

Is it possible to make a socket emit call within some functions? im only intrested to emit data to the client side.

Or how pusher server sided is working, could that be done with socket too?

the client request is as follows server sided

    var bankfactory = require(path.resolve('./modules/articles/server/factory/user_factory.js'));
    
    
     app.post('/api/bank', function (req, res) {
    bankfactory.bank_inn(req.user._id,amount).then( function (bankresult) {
                    res.json(bankresult);
                });
    });

bankfactory:

        exports.bank_inn = bank_inn;
    
    
        function bank_inn(playerid,amount) {
        
    if (playerid == 1) {
    
    } else {
    
        // possible to make a emit call to the client here?
    //emit("newevent,datahere)
    }
        
        }

is it possible to make a socket emit within there?

**Comment by mleanos** [comment]
@frkwhiteangel See this discussion for insight, and options: https://github.com/meanjs/mean/issues/1114
