### ISSUE TITLE
On route change

### ISSUE THREAD

**Issue by frkwhiteangel** [meanjs/mean#1539]
Is Ir possible to detect route changes server sided ? I'm in need to do some database queries when the user is navigating to a new page / route.

**Comment by lirantal** [comment]
Depends. If the route changes is happening on client-side routes then you can use Angular's built in route mechanism to detect it. If it's a server-side route then there are multiple ways to approach them problem such as cookie storing information about current route, or checking the HTTP referer header, just to name a few quick ones.

**Comment by frkwhiteangel** [comment]
How Would i do IT client sided?

**Comment by frkwhiteangel** [comment]
@lirantal another question, How Would IT be to fall a function server sided on all post requests to the server ? Im looking for a way to log everything a user do

**Comment by mleanos** [comment]
@frkwhiteangel For the client-side you can add logic to one of these events: https://github.com/meanjs/mean/blob/master/modules/core/client/config/core.client.route-filter.js#L11-L12

For the server-side, you could add a middleware to your Express server.

I caution you to be careful to not put blocking, or resource heavy, operations that would be executed on every client-side route change, and/or API call.

**Comment by frkwhiteangel** [comment]
@mleanos Would a request to the server that logs the page visited and time into db, and for server sided to log all variables and buttons clicked be a wrong idea ? Or would it be heavy ?

**Comment by mleanos** [comment]
That's really hard for me to answer. It could depend on a lot of things. It might be more helpful for you to post this on StackOverflow.
