### ISSUE TITLE
Lingering Bluemix/Cloud-Foundry references

### ISSUE THREAD

**Issue by mleanos** [meanjs/mean#1540]
We [removed Bluemix](https://github.com/meanjs/mean/pull/1476), but we still have [the assets file](https://github.com/meanjs/mean/blob/master/config/assets/cloud-foundry.js), and [cfenv dependency](https://github.com/meanjs/mean/blob/master/package.json#L38).

I believe both can be removed. @codydaig Can you clarify that these weren't purposely left in place?

**Comment by codydaig** [comment]
They are good to remove! I just accidentally missed them.
