### ISSUE TITLE
how do i stop these error messages on terminal ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1550]
![image](https://cloud.githubusercontent.com/assets/1026325/19209222/d21a6970-8cd3-11e6-8993-f00064b0c030.png)

**Comment by lirantal** [comment]
That's the linting, it's purpose is to help you have a standard coding convention across the project. The point is to help you so I'm not sure why would you want to turn it off.

**Comment by hyperreality** [comment]
If you want to ignore particular rules, then edit the .eslintrc.js file.

If you really want to ignore linting altogether (but you probably shouldn't), then remove eslint from the gulp task that runs the app in gulpfile.js.

**Comment by jpca999** [comment]
lol - I know its linking - sometimes I just wanna get shit done and then wanna come back and correct the linting errors.   I was looking for on and off for this feature.

**Comment by trendzetter** [comment]
It's kind of oversensitive eslint. It's marking style "errors" as syntax errors with continues to be annoying. It should be capable of differentiating but it doesn't.
