### ISSUE TITLE
Discussion - package.json cleanup

### ISSUE THREAD

**Issue by sujeethk** [meanjs/mean#1569]
**Discussion:**
The below dependencies are listed but not used

```
file-stream-rotator (1)
jasmine-core (0)
mocha (33)
phantomjs-prebuilt (102)
```

The below dev-dependencies are listed but not used

```
eslint (127)
eslint-config-airbnb (1)
gulp-node-inspector (282)
gulp-util (94)
istanbul (59)
lcov-result-merger (93)
node-inspector (235)
```

Also `connect-flash (0)` is being used in the express.js file but what is using this flash? I do not see it being used anywhere other than the middleware initialized.

The numbers in brackets are a node count of the total recursive dependencies for those modules.

Am I missing something. Or Is there a reason why they cant be removed?

**Comment by sujeethk** [comment]
Also is Imagemin a necessary task? I see the task listed in gulpfile but the task is never called. But for this minification two dependencies are used-
```
gulp-imagemin (316)
imagemin-pngquant (284)
```

Is it worth having an unused imagemin task that is using these massive dependencies? Look at their dependency count, wow :)

**Comment by sujeethk** [comment]
reason i mentioned the dependency count is so we know how polluted the node_modules get while having unused dependencies. Also reducing those would speed up npm install time and reduce any errors/warns from unwanted dependencies. Like the eslint-config-airbnb which is currently causing npm ERR on the install step

**Comment by mleanos** [comment]
I don't have much insight into these particular dependencies. I'll take a look at them, and see if I can help.

>Also is Imagemin a necessary task? I see the task listed in gulpfile but the task is never called. But for this minification two dependencies are used-

Some tasks aren't used directly from within the framework. They're ran by developers using the framework. So for the `image-min` task, it's just there for someone to use during development/deployment.

**Comment by sujeethk** [comment]
lcov-result-merger is used in travis CI in the last step:
`$ node_modules/.bin/lcov-result-merger 'coverage/**/lcov.info' | node_modules/coveralls/bin/coveralls.js`

`eslint` and `eslint-config-airbnb` are required for `.eslintrc.js` but the extension `airbnb/legacy` is deprecated. Also, Airbnb seems to be focused on React, it would be better if we could find a different eslint config that focus on angular so we could elimiate the need for airbnb and react configs.

**Comment by simison** [comment]
@sujeethk I'm using this exact same setup but for Angular files I have additional `eslint:angular` task:
- https://github.com/Trustroots/trustroots/blob/master/.eslintrc-angular.js
- https://github.com/Trustroots/trustroots/blob/master/gulpfile.js#L201-L211

I think it would make sense to 
1) update to eslint 3.x, 
2) get rid of `eslint-config-airbnb`, 
3) set CI builds fail on linting errors

**Comment by simison** [comment]
I'll quickly check these trough and PR a cleanup.

[x] = keep

 [ ] file-stream-rotator (1)
Was already removed and replaced with winston.

[x] jasmine-core (0)
Removing throws warning:
> karma-jasmine@1.1.0 requires a peer of jasmine-core@* but none was installed.

[ ] mocha (33)
Installed already via `gulp-mocha`, can be removed

[ ] phantomjs-prebuilt (102)
Was already removed, we switched to Chrome for testing.

[ ] eslint (127)
Installed already via `gulp-eslint`, can be removed

- [ ] eslint-config-airbnb (1)
Can be removed it seems.

- [ ] gulp-node-inspector (282)
was already removed

- [ ] gulp-util (94)
Indeed seems not to be used.

- [ ] istanbul (59)
Installed already via `gulp-istanbul`, can be removed

- [ ] lcov-result-merger (93)
[Used only by Travis](https://github.com/meanjs/mean/blob/master/.travis.yml#L48) so I'll move installing this there as well.

- [ ] node-inspector (235)
was already removed

**Comment by lirantal** [comment]
Great summary @simison, thanks!
