### ISSUE TITLE
Grunt Build Deleting Assets

### ISSUE THREAD

**Issue by abumere** [meanjs/mean#1588]
I am working on trying to deploy my mean app to production. I understand that before doing that I need to run the 'grunt build' command to compile and minify the needed files. 

When running that command I noticed my app wouldn't run after. It turns out that the 'grunt build' command is actually modifying my /config/default.js and taking things out. 

Specifically it's removing any css references in client > lib > css that are URL's (I have urls to google fonts). It is also removing a reference to angular-jquery in client > lib> js 

Is this expected behavior?

**Comment by hyperreality** [comment]
We have stopped working on Grunt and have switched over to Gulp instead, please try using that.
