### ISSUE TITLE
unable to run using docker on ec2.  Got issues. 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1598]
npm ERR! Please include the following file with any support request:
npm ERR!     /home/mean/npm-debug.log
The command '/bin/sh -c npm install' returned a non-zero code: 228

![image](https://cloud.githubusercontent.com/assets/1026325/19736496/8452404c-9b7d-11e6-9178-548fcbd7a001.png)

Steps that I'm doing : 
I just sssh into the terminal and pull docker conatiner and i try to run it. 
please help.

**Comment by dalelotts** [comment]
Why such an old version of node? Perhaps that't part of the problem.

**Comment by jpca999** [comment]
lol  - i just run sudo - apt-get install.    should i run any specific node version ? which one ?

**Comment by jpca999** [comment]
what node version is recommended by mean js ?  Also how can i add it to my docker file so that it automatically install that version of node - can i do that ?

**Comment by dalelotts** [comment]
I _always_ use the latest LTS version of node - I think that's 6.9.1 at the moment.

Try running `apt-get update` before installing anything -  `apt-get update` downloads the package lists from the repositories and "updates" them to get information on the newest versions of packages and their dependencies.

**Comment by lirantal** [comment]
Maybe you have no space left to get the container working?
After all, npm install reports an error: `npm ERR! code ENOSPC`

**Comment by jpca999** [comment]
low space -  may be true since im using ec2 free versoin, but is there a way to optmize the space ?

**Comment by lirantal** [comment]
yeah I'll look into the space issue
