### ISSUE TITLE
Question: why uglify mangle option is disabled ?

### ISSUE THREAD

**Issue by shanavas786** [meanjs/mean#1599]
Enabling mangle reduces javascript file size by 10kb.

**Comment by simison** [comment]
It usually doesn't work well with Angular. Did you test if it worked?

**Comment by shanavas786** [comment]
Haven't tested comprehensively. But I think it should work properly as `ng-annotate` handles dependency resolution problems arise due to mangling.

**Comment by simison** [comment]
I tested and mangling worked just fine. Made a PR.
