### ISSUE TITLE
Add git version info

### ISSUE THREAD

**Issue by cdc-js** [meanjs/mean#1600]
Hi all,

Is it a good idea to put git information to footer or not? The goal is to assist us to know the exact version of our application easily. We can put for example git short commit id and latest git change date (e.g. xxxxxxx - dd mmm yyyy). 

Example of my code for getting this information are below:

```
exec = require('child_process').exec;
function _command (cmd, cb) {
  exec(cmd, { cwd: __dirname }, function (err, stdout, stderr) {
    cb(stdout.split('\n').join(''))
  })
};
module.exports.gitRev = function (cb) {
  return _command('git describe --always --tag', cb)
};
module.exports.gitDate = function (cb) {
  return _command('git log -1 --date=short --pretty=format:%cd', cb)
};
```

Thanks all

**Comment by abaka82** [comment]
Sorry, it is better if I am using my active github account. I am closing this and write a new one. Please see #1601
