### ISSUE TITLE
Add git information to frontend

### ISSUE THREAD

**Issue by abaka82** [meanjs/mean#1601]
Hi all,

Is it a good idea to put git information to frontend (i.e. footer) or not? The goal is to assist us to know the exact version of our application easily. We can put for example git short commit id and latest git change date (e.g. xxxxxxx - dd mmm yyyy).

Example of my code for getting this information are below:

```
exec = require('child_process').exec;
function _command (cmd, cb) {
  exec(cmd, { cwd: __dirname }, function (err, stdout, stderr) {
    cb(stdout.split('\n').join(''))
  })
};
module.exports.gitRev = function (cb) {
  return _command('git describe --always --tag', cb)
};
module.exports.gitDate = function (cb) {
  return _command('git log -1 --date=short --pretty=format:%cd', cb)
};
```
Thanks all

**Comment by lirantal** [comment]
From security perspective you wouldn't want to run system commands from the web

**Comment by dalelotts** [comment]
You have a version in your package.json - if your build/deploy process correctly increments the version and also tags the git repository with the version you will always know what is in production.

Consider fully automating the process similar to the way [semantic-release](https://github.com/semantic-release/semantic-release) does it for npm packages.
