### ISSUE TITLE
Inconsistent spacing before function parentheses

### ISSUE THREAD

**Issue by mleanos** [meanjs/mean#1605]
There are some places in the code-base that have spaces before function parentheses, and some that don't. I'm seeing changes to these in multiple PR's, that go either way (some are creating unnecessary diffs). We should enforce a linting rule in these cases for reasons of consistency.

One example: https://github.com/meanjs/mean/blob/master/modules/users/tests/e2e/users.e2e.tests.js#L411-L424

My personal preference is the same expressed in this comment: https://github.com/airbnb/javascript/issues/55#issuecomment-101360471

My proposal is to change [this eslint setting](https://github.com/meanjs/mean/blob/master/.eslintrc.js#L43) to

``` javascript
'space-before-function-paren': ['error', {
      'anonymous': 'always',
      'named': 'never',
      'asyncArrow': 'always'
    }]
```

http://eslint.org/docs/rules/space-before-function-paren#anonymous-always-named-never-asyncarrow-always

When testing this new setting, 242 instances where this rule is violated were reported by the linting task. This would be a big sweeping change, but worthwhile.

Anyone have thoughts on whether we want to implement my proposed change?

**Comment by simison** [comment]
Just tested: `eslint --fix` handles this really nicely.

**Comment by simison** [comment]
We just need last two items for [0.6.0](https://github.com/meanjs/mean/milestone/10) merged (or ignored and refactored later) and we can PR this change + publish 0.6.0. :-)
