### ISSUE TITLE
Issues with angular functions

### ISSUE THREAD

**Issue by JMon8** [meanjs/mean#1607]
I've followed the tutorial to getting the files on my server as well as having mongodb up an running. I'm just trying to test that the server is running by visiting the address. I'm seeing the requests, but when I open up developer tools to see whats going on, I get the following error a whole bunch:

> config.js:25 Uncaught ReferenceError: angular is not defined

I'm also seeing this error later, but I'm not sure if its related to the first set of errors

> Uncaught ReferenceError: owaspPasswordStrengthTest is not defined(…)

I haven't modified any of the files, so I'm not sure if i missed something

Thanks

**Comment by shanavas786** [comment]
Have you run `npm install` ?

**Comment by TheBlackPowerRanger** [comment]
Yea, I ran it in the project folder. If it helps, I'm running it on an Ubuntu 16.04 instance.

**Comment by JMon8** [comment]
I think I figured it out. Looks like I didn't update some files. Guess I just didnt understand how to connect angular to the backend set up.

Thanks!
