### ISSUE TITLE
after installing it with  "yo meanjs" why do i get the .git  file already in there ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1612]
![image](https://cloud.githubusercontent.com/assets/1026325/20076633/341b661a-a507-11e6-8e0c-cab038ac49e9.png)

**Comment by mleanos** [comment]
IIRC, this is due to the meanjs generator doing a `git clone` to build the framework.

This question is probably better suited for the issues at https://github.com/meanjs/generator-meanjs
