### ISSUE TITLE
Is there a build in provision for keeping the application running forever using forever/ supervisor ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1632]

**Comment by shanavas786** [comment]
I use [pm2](http://pm2.keymetrics.io/) and suggest it. Build has nothing to do with it. You can simply run `pm2 start server.js`
I think something similar applies for `forever/supervisor` also.

**Comment by jpca999** [comment]
@shanavas786  quick question:  So I'm using docker so that i can mimic the linux / ubuntu platform while developing on mac.   Do you recommend running docker on ec2   (ubuntu ) again and run the app via that  or i can just get the app files from git and run it there ?

**Comment by shanavas786** [comment]
I haven't used docker.
It seems adding 
```
CMD npm install -g pm2
CMD pm2 start server.js
```
to dockerfile would be enough.

https://hub.docker.com/r/meanjs/mean/ may help you

**Comment by jpca999** [comment]
I appreciate that

**Comment by jpca999** [comment]
Its easy just do 
After installing gulp both as global and local, 

sudo pm2 start gulp
