### ISSUE TITLE
Fatal error: Unable to find Gruntfile.

### ISSUE THREAD

**Issue by yinix** [meanjs/mean#1638]
Hi All,

I install the latest(master) meanjs by "yo meanjs" and then choose "master" version.
when I perform "grunte", I got the message "Fatal error: Unable to find Gruntfile.".
It seems that there missed gruntfile.js" under the root folder of master, or is there any change point about this?

Thanks

ZhangHui

**Comment by shanavas786** [comment]
grunt has been removed in favor of gulp.

**Comment by mleanos** [comment]
@yinix We have indeed removed Grunt from the project, and the `Gruntfile` no longer exists. However, this is a bug in the [MEANJS Generator project](https://github.com/meanjs/generator-meanjs). You're experiencing this because the generator is out of sync with the up-stream project.

**Comment by yinix** [comment]
@mleanos thanks a lot for your strong support, understood.
