### ISSUE TITLE
how to seed sample data into the mongo db ?

### ISSUE THREAD

**Issue by mrtinkz** [meanjs/mean#1642]
I tried to seed the sample data but looks like if the below command does anything.

` MONGO_SEED=true npm start`
```
'MONGO_SEED' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by sanathpathiraja** [comment]
In production.js
set 
seedDB: {
    seed: process.env.MONGO_SEED === 'true',

then
MONGO_SEED=true npm start:prod

if got problem 
use npm install gulp-sass --save-dev

**Comment by mrtinkz** [comment]
It's already configured that way, so should it work ?


  ```
seedDB: {
    seed: process.env.MONGO_SEED === 'true',
    options: {
      logResults: process.env.MONGO_SEED_LOG_RESULTS !== 'false',
      seedUser: {
        username: process.env.MONGO_SEED_USER_USERNAME || 'seeduser',
        provider: 'local',
        email: process.env.MONGO_SEED_USER_EMAIL || 'user@localhost.com',
        firstName: 'User',
        lastName: 'Local',
        displayName: 'User Local',
        roles: ['user']
      },
      seedAdmin: {
        username: process.env.MONGO_SEED_ADMIN_USERNAME || 'seedadmin',
        provider: 'local',
        email: process.env.MONGO_SEED_ADMIN_EMAIL || 'admin@localhost.com',
        firstName: 'Admin',
        lastName: 'Local',
        displayName: 'Admin Local',
        roles: ['user', 'admin']
      }
    }
  }
```

**Comment by mrtinkz** [comment]
Also, how does the gulp-sass relate to mongo seed ?

**Comment by sanathpathiraja** [comment]
What is the you got error.
if you run MONGO_SEED=true npm start:prod
follow the [https://github.com/meanjs/mean/blob/master/README.md#running-with-user-seed]

**Comment by mrtinkz** [comment]
I am running it in a command prompt and i get the below error.


```
'MONGO_SEED' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by sanathpathiraja** [comment]
try to,
clone master repo.
and run it.

**Comment by mrtinkz** [comment]
So it doesn't work on the code generated by yo generator ? It should all be same correct ? how would it be any difference ?

**Comment by sanathpathiraja** [comment]
I used clone master repo.
it's work for me.

**Comment by hyperreality** [comment]
Probably a problem with environment variables in windows

**Comment by mrtinkz** [comment]
Thanks, I figured it was a problem with the command prompt I am using, tried the same in cygwin and it worked.
