### ISSUE TITLE
What version of node/npm?

### ISSUE THREAD

**Issue by mycodeself** [meanjs/mean#1644]
Hi, im trying to get rid of my first meanjs application. Im using the yo generator and when the generator starts to build the application it always fail. I tried with node 7.1 and npm 3.9. What should i use for get successful start configuration ?

**Comment by codydaig** [comment]
Depends on the version of the generator. If your using the latest generator, I recommend using Node 4. I don't think Node 7 is officially supported by this project yet.

**Comment by mycodeself** [comment]
Thank for your reply @codydaig, if i dont use the generator what version of Node its supported?

**Comment by mleanos** [comment]
@mycodeself I'm running Node v6.6.0 and haven't encountered any issues with this project. Node 7 isn't fully supported yet, so you might run into issues. If you manage to get this project working with Node 7, would you report back on what issues you encountered, and how you solved them?

**Comment by codydaig** [comment]
@mycodeself Feel free to reopen if there's additional questions around this, otherwise i'm closing for now and considering it resolved.
