### ISSUE TITLE
How can I run my mean app so that another application can call the backend api (of mean) to perform CRUD operations (on mean app) ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1645]
Any help/ suggestions would be very helpful. 

I dont care abou the password authentication at this time..  

Both can be running on same machine  just different ports.

**Comment by shanavas786** [comment]
`request` module would be enough. If you want multiple services to function as a single application (microservices), you can use reverse proxy server like `nginx`

**Comment by codydaig** [comment]
What are you currently trying? Are you experiencing issues? The only thing I see stopping you is CORS, which is a simple fix.

**Comment by jpca999** [comment]
Haven't started on this yet, but soon.  
 hmmm I'm trying to figure out if ghost would be great for this new website It's not much just a simple webpage like  jaybuyhousesinmiami.com.  But eventually(soon)  i want to explode it to every city nationwide.   Trying to figure out what cms or whatever is good for this kind of website. 

Mostly it will contain blog, about us,  comments with facebook integration.  But later I wanna host property listings on it...

**Comment by codydaig** [comment]
So this framework is a framework set-up to be a boiler plate project. It is not set-up to be a CMS. For a CMS that you want to be able to expand on later, I'd recommend a PHP based one like Wordpress of Drupal. There really isn't a CMS in the node world that's proven to be expandable.
