### ISSUE TITLE
Return a json Postman

### ISSUE THREAD

**Issue by ennaimyassine** [meanjs/mean#1648]
I want to use mean.js in a mobile app, when I send a request to /authentication/signin in postman the response was "Cannot POST /authentication/signin"

**Comment by codydaig** [comment]
@ennaimyassine Because that route does not exist. The correct route is `/api/auth/signin`.

https://github.com/meanjs/mean/blob/master/modules/users/server/routes/auth.server.routes.js#L19

**Comment by ennaimyassine** [comment]
@codydaig thank you so much I understand now that's so helpful

**Comment by codydaig** [comment]
No Problem! Let us know if there's anything else!
