### ISSUE TITLE
CORS issue  :   AngularJS POST Fails: Response for preflight has invalid HTTP status code 404

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1651]
Hello guys,  so I've 2 applications running on ec2.   

First one is mainly used for calling services upon. 
Second one has the whole UI and it calls the other one for the data.  It runs okay for http READ operation but when i try to run UPDATE on the server  it gives me this error. 

Can someone please help me how to resolve this CORS issue in mean app ?

**Comment by codydaig** [comment]
@jpca999 This question has been answered here. https://github.com/meanjs/mean/issues/1609

**Comment by jpca999** [comment]
@codydaig  the Caller application is only Angular has no express/ node.   Is there any other way to resolve the CORS ?

**Comment by codydaig** [comment]
CORS has to be handled on the server side.

**Comment by jpca999** [comment]
got it working   http://stackoverflow.com/questions/40772050/how-do-i-setup-reverse-proxy-on-nginx-to-avoid-the-cors-issue-for-my-ionic-and-m

**Comment by codydaig** [comment]
Glad to hear it!
