### ISSUE TITLE
`npm install` error for Node v6.3+ due to "node-inspector" dev dependency in package.json

### ISSUE THREAD

**Issue by kimbaudi** [meanjs/mean#1652]
After cloning this repo, I executed `npm install` and got error. I am using node v7.2.0 and npm v4.0.2. I believe `npm install` error affects people using Node v6.3 or greater.

Here is the relevant snippet of `npm-debug.log`:
```
123423 error Darwin 16.1.0
123424 error argv "/Users/kimbaudi/.nvm/versions/node/v7.2.0/bin/node" "/Users/kimbaudi/.nvm/versions/node/v7.2.0/bin/npm" "install"
123425 error node v7.2.0
123426 error npm  v4.0.2
123427 error code ELIFECYCLE
123428 error v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
123428 error Exit status 1
123429 error Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
123429 error Make sure you have the latest version of node.js and npm installed.
123429 error If you do, this is most likely a problem with the v8-debug package,
123429 error not with npm itself.
123429 error Tell the author that this fails on your system:
123429 error     node-pre-gyp install --fallback-to-build
123429 error You can get information on how to open an issue for this project with:
123429 error     npm bugs v8-debug
123429 error Or if that isn't available, you can get their info via:
123429 error     npm owner ls v8-debug
123429 error There is likely additional logging output above.
123430 verbose exit [ 1, true ]
```

The issue is "node-inspector" dev dependency in `package.json` (https://github.com/node-inspector/v8-debug/issues/7).

I resolved this issue by simply removing `"node-inspector"` dev dependency from `package.json` and re-running `npm install`.

**Comment by codydaig** [comment]
Howdy! We don't currently support node v7. 

For future, you can always checkout our Travis.CI build page for what versions of node are currently working. Anything under allowed failures is versions we plan to support but are currently breaking the build. https://travis-ci.org/meanjs/mean
