### ISSUE TITLE
Show article from category mean.js

### ISSUE THREAD

**Issue by mskinho** [meanjs/mean#1663]
**Link Menu**

```
<a ui-sref="articles.list-nav({category: category.name})">
  {{ category.name }}</a>
```
**Route Client:**

```
.state('articles.list-nav', {
        url: '/:category/articles',
        templateUrl: 'modules/articles/views/list-articles-scategory.client.view.html',
        controller: 'ArticlesController'
      })
```
**List Article Category:**

`<a class="md-12-line" ng-repeat="article in getArticles(category.id) ">`
**Controller Client:**

```
$scope.getAticles = function(category){
             var result = [];
             for(var i = 0 ; i < $scope.articles.length ; i++){
                 if(category === $scope.articless[i].category){
                     result.push($scope.articles[i]);
                 }
             }
             console.log(category);
             return result;
         };
```
**I tried the other way:**

**Controller Client:**

` $scope.subCat = $stateParams.subcategoria;`
**List Article Category:**

`<a class="md-12-line" ng-repeat="article in article | Filter: {(category: category.id)} ">`
But not working anyway, can I help me?

**Comment by mleanos** [comment]
@mskinho I don't understand what last two examples you provided in your description.

However, the one thing that jumps out at me is the referencing of `category` in your view/template. Where are you setting this value in your Angular controller? You must retrieve it from the router using `$stateParams.category` and set it to a scope variable (e.g. `$scope.category = $stateParams.category;`.

In addition, it appears that *categories* reside in your Article data. The way that you're checking for equality in your `getArticles` method, is just checking the value of the category field in your Article schema. However, in your view you pass in `category.id` to this method; this would **only** work if your `category` scope variable is a populated data set (i.e. has the `id` property in this case), and in your `$scope.articles` variable the `category` field is just a reference to it's `id`.

If you could clarify some of this, that would help in understanding your issue.

**Comment by mskinho** [comment]
mleanos thanks for your help.
I'm using $scope.category = $stateParams.category;.
I not expained in the right way.
I need show article for each categoryID. 
Ex:
menu IT: all article from IT
menu marketing: All article from Marketing

Thanks for help.

**Comment by mleanos** [comment]
@mskinho What does the data in `$scope.articles[i].category`?

Is it just the Category ID? something like: `{ category: 'some-mongoose-id' ..}`
OR
Does it have the **populated** data of the Category?: `{ id: 'some-mongoose-id', name: 'some-category-name'.... }`

Can you describe how this is not working? Are you getting console errors? Or is it just not finding any articles for the provided Category?

**Comment by mskinho** [comment]
@mleanos  I using this method in: $scope.getAticles = function(category){
             var result = [];
             for(var i = 0 ; i < $scope.articles.length ; i++){
                 if(category === $scope.articless[i].category){
                     result.push($scope.articles[i]);
                 }
             }
             console.log(category);
             return result;
         };

Like menu dropdonw it's work this way, but for display in other page not work.
I get the list url normally, exemplo: http://127.0.0.1:3000/articles/content-marketing/articles
But not filter 'article' from category 'content-marketing'

**Comment by mskinho** [comment]
In this Git work https://github.com/K-M-B/mean.js-support-module/blob/master/modules/support/client/views/support.issues.client.view.htm <br/>
but of page for page not from menu link.

**Comment by mleanos** [comment]
> if(category === $scope.articless[i].category){

@mskinho In that line, in your example code, what is "category"? Is it the populated data of Category? Or is it the "_id" of Category? It appears that "category" that you are passing this `$scope.getArticle` method is the "_id".

Can you describe in more detail how it's not working? Do you see any console logs?

BTW: the repo link you provided in your last comment, doesn't work. It goes to a 404 page. It's most likely a private repo.

**Comment by mskinho** [comment]
Updte link https://github.com/K-M-B/mean.js-support-module/blob/master/modules/support/client/views/support.issues.client.view.html
I passed _id in category, in console log give category "Undefined"

**Comment by mskinho** [comment]
I find exemplo That works similarly that I need. http://plnkr.co/edit/yNOIlgBK2inFy1FkFsKk?p=preview
Só não consigo substituir '**_.find**'
