### ISSUE TITLE
POST http://localhost:3000/api/auth/signin 422 (Unprocessable Entity)

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1667]
I haven't dealt with authentication in a while but today when i needed to work upon it, i get this error. I wonder if someone has dealt with this issue ?

![image](https://cloud.githubusercontent.com/assets/1026325/20868359/c50e3a6e-ba27-11e6-873e-9b2cb862f060.png)

**Comment by mleanos** [comment]
@jpca999 That's most likely a validation error with the login

https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L58

If the passport local strategy authentication throws an error or can't authenticate, then you will see this status.

https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/local.js

**Comment by lirantal** [comment]
Indeed, as @mleanos pointed out it's a user/pass validation error and you're probably not sending the JSON in correctly.
