### ISSUE TITLE
Question: How do I use this framework without MongoDB or any database?

### ISSUE THREAD

**Issue by anandsinghkunwar** [meanjs/mean#1671]
I wanted to create a front end app, but use express for routing and was using MEAN.js in the backend in a ReST architecture. About the framework, I liked the all the configurations that have been done in the app and wanted to use it in my frontend as well. Is there an easy way to remove MongoDB from the framework and use it as a frontend only app.

**Comment by vaucouleur** [comment]
@anandsinghkunwar To the best of my knowledge there is no "easy way". You can always change the code to your liking, but you'll have to work quite a bit to get to your goal. As in: changing the model definitions, looking into the gulp script, making sure that authentication can work without a db, etc. Quite a lot of work. MEAN.JS is currently clearly dependent on mongodb, and is not trying to hide it, hence the acronym.

**Comment by anandsinghkunwar** [comment]
I thought so. Just wanted some outside advice. Thanks @vaucouleur
