### ISSUE TITLE
Forget password is not working,showing error like "Failure sending email" how do i solve this issue?

### ISSUE THREAD

**Issue by Maniselvam006** [meanjs/mean#1679]
Hi guys I am using MEAN stack in my application with AngularJS as my front-end.....my problem is if i forget the password i were enter the user name and submitted, but i got error like "Failure sending email" is there any solution to solve this....I'M new to meanjs... so please help to solve this issue....forgot password page is not working..... thanks...

**Comment by s0j0hn** [comment]
did you provide the good config for your mail server in config files ?

**Comment by Maniselvam006** [comment]
yes, can you please provide some examples to solve this  issue?.... for example:- how you have solve this issue in your meanjs app...?

**Comment by s0j0hn** [comment]
just add your mail server ip and port in config file. Don't remember witch  one

**Comment by vaucouleur** [comment]
@s0j0hn 

"Rename this file to local-NODE_ENV.js (i.e. local-development.js, or local-test.js) for having a local configuration variables that will not get commited and pushed to remote repositories. Use it for your API keys, passwords, etc."

https://github.com/meanjs/mean/blob/master/config/env/local.example.js#L3

```javascript
  mailer: {
    from: process.env.MAILER_FROM || 'MAILER_FROM',
    options: {
      service: process.env.MAILER_SERVICE_PROVIDER || 'MAILER_SERVICE_PROVIDER',
      auth: {
        user: process.env.MAILER_EMAIL_ID || 'MAILER_EMAIL_ID',
        pass: process.env.MAILER_PASSWORD || 'MAILER_PASSWORD'
      }
    }
  }
```
https://github.com/meanjs/mean/blob/master/config/env/development.js#L62

**Comment by Maniselvam006** [comment]
@s0j0hn, @vaucouleur , thanks for your answers, right now i have added my username and password in `config/env/development.js`  like following coding :-  
mailer: {
    from: process.env.MAILER_FROM || 'maniselvam006@gmail.com',
    options: {
      service: process.env.MAILER_SERVICE_PROVIDER || 'Gmail',
      auth: {
        user: process.env.MAILER_EMAIL_ID || 'maniselvam006@gmail.com',
        pass: process.env.MAILER_PASSWORD || 'ms9962867815'
      }
    }
  },

but again i got the error like "Failure sending email", so where i made the  mistake, and if anything else to add in my files?...

**Comment by vaucouleur** [comment]
@Maniselvam006 Using gmail for those kind of things might not be a good idea. But if you persist, check the following. Hope it helps.

- "Using Gmail": https://nodemailer.com/using-gmail/
- "OAuth2": http://nodemailer.com/2-0-0-beta/using-oauth2/
- "Google account gets suspended when...": http://stackoverflow.com/questions/39334899/google-account-gets-suspended-when-using-gmail-api-from-node-js-nodemailer

**Comment by hyperreality** [comment]
@Maniselvam006 I strongly suggest that you edit your comment to remove your password...

**Comment by simison** [comment]
Closing, @Maniselvam006 feel free to open again if you still have issues with this.

**Comment by Maniselvam006** [comment]
still i have a same issue, while using the portal in localhost the mail has sending to email id perfectly, after pushing into server like heroku platform error occurred like "Failure sending email" is there any final solution to solve this?
if have solution what i need to do and where and which of the page i need to modify, mentioning exact path would be better to understand... thanks
