### ISSUE TITLE
Content visible only by user who created

### ISSUE THREAD

**Issue by mskinho** [meanjs/mean#1698]
I need proctect content, visible only by user who created.
I try this, but give me error:
process.nextTick(function() { throw err; });
 Error: Route.get() requires callback functions but got a [object Undefined]

In router I using
users = require('../../../users/server/controllers/users.server.controller');
.get( users.requiresLogin, tickets.hasAuthorization, tickets.list)

In the controller:
exports.hasAuthorization = function(req, res, next) {
  if (req.ticket.creator.id !== req.user.id) {
  return res.status(403).send({
  message: 'User is not authorized'
  });
  }
  next();
  };

Someone can help me?
Regards
Santana, Marcos

**Comment by mleanos** [comment]
>Error: Route.get() requires callback functions but got a [object Undefined]

Usually means that one of the methods you provided in the route `.get` method doesn't exist. My recommendation for your requirement would be to use the ACL Policy to check this, and invoke the policy check on your route the same way that it's done in Articles.

https://github.com/meanjs/mean/blob/master/modules/articles/server/policies/articles.server.policy.js#L52

https://github.com/meanjs/mean/blob/master/modules/articles/server/routes/articles.server.routes.js#L16

NOTE: In your policy file, you wouldn't have your tickets.list route in the `allows` configuration.

**Comment by mskinho** [comment]
Tanks for help @mleanos , but give this error:
TypeError: Cannot read property 'creator' of undefined

**Comment by mskinho** [comment]
Solver problem, I used .find({user: req.user._id}).sort('-created') in my list controller.
Thanks for help.

Regards,
Santana, Marcos
