### ISSUE TITLE
Store Image/Video on MongoDB

### ISSUE THREAD

**Issue by Zacknero** [meanjs/mean#170]
Hello guys, I'm developing a project with MEANJS but would like to know how I can use Via The Express + Mongoose to save and upload images / video on MongoDB ?? 
If you can post the guides, videos or pieces of code that make these device operation. 
Thank you so much !!

**Comment by dancancro** [comment]
Adding [this](https://groups.google.com/forum/#!topic/meanjs/-ol3T11PbuU) related conversation I just saw in the Google group.

**Comment by lirantal** [comment]
You can use GFS (GridFS) to do that.
