### ISSUE TITLE
node-inspector as optionalDependencies 

### ISSUE THREAD

**Issue by prashanthmadi** [meanjs/mean#1700]
Build fails in azure web apps because of node-gyp issue. Is it possible to make `node-inspector` as optional dependency ?

**Comment by prashanthmadi** [comment]
If anyone is looking for deploying meanjs on azure web apps.

I made a fork of this at below link which works in azure web app. Fork might be temporary and would be deleted.
https://github.com/prashanthmadi/mean

1) nodemon doesn't work on azure web apps (It might not be a best practice to use nodemon for prod apps)
2) Lock nodejs version in package.json
3) make node-inspector as optionalDependencies (node-gyp failure issue)

**Comment by lirantal** [comment]
Thanks @prashanthmadi 
https://github.com/meanjs/mean/pull/1744 fixes the issue now, merged to master already.
