### ISSUE TITLE
Travis builds are failing on install of Protractor version that's incompatible with Node 4 & 5

### ISSUE THREAD

**Issue by mleanos** [meanjs/mean#1705]
Currently, the Travis CI builds are failing on Node 4 & 5, due to the latest version of Protractor being installed. Consequently, a version of the `webdriver-manager` package is installed that is incompatible with Node 4 & 5.

![image](https://cloud.githubusercontent.com/assets/5613734/22230412/3ad1fc0e-e192-11e6-8eaa-7bba7c990d01.png)

https://github.com/meanjs/mean/blob/master/.travis.yml#L35

We're not using Protractor directly in the project, since we're using `gulp-protractor`. The latter installs the expected version of Protractor, thus a compatible version of `webdriver-manager`.

I don't have much experience with Travis CI, and I'm not aware of a way of testing our `.travis.yml` configuration, short of committing to a PR.

Could we just change the referenced line in the Travis build config, to be `npm install gulp-protractor@">=3.0.0 <4.0.0"` to match our version of gulp-protractor? Moreover, why do we have to install Protractor at all, before the project's dev dependencies are installed?

@meanjs/contributors @simison @sujeethk @hyperreality

**Comment by lirantal** [comment]
@mleanos I don't remember the historical reasons for the travis.yml file but you can definitely open a PR with the suggested change and see how the build works.

**Comment by codydaig** [comment]
What @lirantal said. Go for the changes and hope for the best! I'd be curious to see if we don't need gulp-protractor directly in the travis.yml file. That would be the ideal situation.

**Comment by lirantal** [comment]
@mleanos  this PR for protractor basically sets up the build in travis so that we don't run E2E on unsupported versions like 4 & 5, and only for 6.9 and higher.
Reference: #1752
