### ISSUE TITLE
how to query mongoose with multiple query params ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1707]
Here is my mongo object : 
[ {},{}
{
	"_id" : ObjectId("588aa3ab9045439fdf1bb280"),
	"Bi_Weekly_P" : false,
	"Continue_P" : false,
	"CounterOffer" : "default",
	"Counter_P" : false,
	"DOM" : "default",
	"Grey_P" : false,
	"Later_P" : false,
	"Later_Today_P" : false,
	"Left_VM_P" : true,
	"dateAdded" : "default",
	"next_call_Date" : ISODate("2017-01-27T02:14:48.393Z"),
	"__v" : 1
}
]

I want to query for objects that has "Left_VM_P" : true,  as true. 

from angular this is how i call it.  

var Priority = 'Left_VM_P';    (  this priority can be chnaged as per user selection ) 
url = currentUrl+"/api/prioritySearch/"+Priority;

exports.prioritySearch = function(req, res, next, id) {
  // below query works 
  // Property.find({ Left_VM_P : 'true' }).exec(function(err, properties) {

// but i want below query to work coz i want to change the id parameter so I can modify each time what key is searched for 
  Property.find({id : 'true' }).exec(function(err, properties) {    

Here's the log on terminal on server side.
    value of  id =  Left_VM_P
   req.params  =  { Left_VM_P: 'Left_VM_P' }

Your help will be greatly appreciated.

**Comment by vaucouleur** [comment]
@jpca999 this is really not meanjs specific. You are crossing the line -- and you know it.

**Comment by mleanos** [comment]
I agree that this isn't MEANJS specific. Closing.

@jpca999 If you have a more focused issue, and it's relevant to this project, then feel free to re-organize your question & re-open.

Look into dynamically generating your query object that is passed into your mongoose Model's `find()` method. This can be done with a simple `switch` statement.
