### ISSUE TITLE
Our use of promises? 

### ISSUE THREAD

**Issue by abumere** [meanjs/mean#1708]
So I am using AWS on my web application and when referencing the API's documentation on promises it says "By default, the AWS SDK for JavaScript will check for a globally defined Promise function. If found, it adds the promise() method on AWS.Request objects. " 

So Im curious to know what version of Promise is used in MEANJS? (Bluebird etc)

Certain aws api commands don't execute and I suspect it's has to do with not having and Promise library but I just wanted to double verify

**Comment by mleanos** [comment]
AFAIK, we're only using the globally built-in Node.js promises.
