### ISSUE TITLE
how can i send an object from angular to backend to query multiple things in mongo db ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1709]

**Comment by mleanos** [comment]
You can send the object as querystring parameters with a GET request, or you can send it as the body (data) in a POST request. Personally, I prefer the latter.

**Comment by jpca999** [comment]
im making sendin username via the later styel you suggested, but how do i grab the user name in the properties.controller.server.js 

![image](https://cloud.githubusercontent.com/assets/1026325/22762901/cdb81702-ee2f-11e6-80b2-38a333122f8e.png)


exports.sendEmailTemplate = function(req, res, next, id) {
console.log( ' 359 - id =  ', id);

**Comment by jpca999** [comment]
I got it, working  with  req.body
