### ISSUE TITLE
Migrating Node and MEAN versions

### ISSUE THREAD

**Issue by Torone** [meanjs/mean#1713]
Hello,

I recently moved from Node version 4.x to 6.x and from meanjs 0.3.x to 0.4.2.
Everything was going ok until I started working with Users.
Basically none of my Users are able to sign in, after having investigated it a bit I found an error:

```
DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
```

So I updated it adding `sha1` as last parameter in the `hashPassword` method.

It removed the error but unfortunately not solved the User sign in issue, they are still unable to sign in. Watching at `this.password` and the result of the `crypto.pbkdf2Sync` within the `hashPassword` method I can see different results.

How can I solve this? Thanks

**Comment by andreafdaf** [comment]
Hi!

I had your same issue and solved it changing that function:
```
UserSchema.methods.hashPassword = function(password) {
  if (this.salt && password) {
    // UPDATE to nodejs v6: digest = 'sha1', encoding = 'binary' for compatibility
    // new defaults: digest = undefined, encoding = 'utf8'
    return crypto.pbkdf2Sync(password, new Buffer(this.salt, 'binary'), 10000, 64, 'sha1').toString('base64')
  } else {
    return password
  }
}
```

In my case this solved the problem :+1:

**Comment by Torone** [comment]
Hi, I tried all combination but never tried to add that `'binary'` there... Thank you very much it solved my issue! Cheers
