### ISSUE TITLE
Compatibility for NodeJS v6

### ISSUE THREAD

**Issue by iamchathu** [meanjs/mean#1714]
I have encounted few few errors running on nodeJs v6. Util now I needed to update 
gulp-protractor, 
mock-fs 
and some test files to make the project up and running.

What are the other things need to keep eye on if I'm going to working on this node version?

I'm using MeanJS 0.4.2

**Comment by lirantal** [comment]
Can you please test with the master branch with regards to v6 compat?

**Comment by iamchathu** [comment]
Seems errors have gone which I encounted earlier.

But there is a recurring warning in Karma Test.

```
WARN [web-server]: 404: /modules/core/client/views/404.client.view.html
```

**Comment by lirantal** [comment]
@iamchathu any other news you want to report on? if so I'll re-open.
