### ISSUE TITLE
how to make a class object being accessed by all the controllers in each module? 

### ISSUE THREAD

**Issue by helxsz** [meanjs/mean#1716]
My mean project has multiple modules, each module can share a common javascript class based on ES6 style, this class object is served as a gateway to access to some common services, for example coap service and mqtt service.

```
class gateway{
     
	get coapActuatorService(){
		return this._coapActor;
	}

	get mqttActuatorService(){
		return this._mqttActor;
	}
}
```

What I want to do is  the controllers in each module can use the gateway class instance to access to the common services, but I don't know how could I be able to code it, any ideas ?

**Comment by mleanos** [comment]
Have you tried the following? Then just use `require('path/to/services/gateway-service')` wherever you need it.

```javascript
module.exports = class gateway {....}
```
