### ISSUE TITLE
Project Structure of MEAN.JS 0.5

### ISSUE THREAD

**Issue by JoeLeeWu** [meanjs/mean#1717]
new in Learning MEAN.JS v0.5 recently,and want to figure out the project structure of it.
Kindly give me your advice.
Thanks a lot~

**Comment by vaucouleur** [comment]
@JoeLeeWu 

Some generic  advice:

1. read the documentation, and all the source code under "config"
2. read the source code for the article module (server side then client side)
3. Add your own module as an exercice.

... At that point you will know most of the basics of the structure... then:

4. read the user module
5. read the core module
6. read the gulpfile

At that point you will know most of the mechanics.

It's not that hard really, assuming that you know the javascript ecosystem.

Good luck !

**Comment by JoeLeeWu** [comment]
@vaucouleur Thanks a lot!

**Comment by mleanos** [comment]
Closing due to @vaucouleur's answer.
