### ISSUE TITLE
Running server in both https and http.

### ISSUE THREAD

**Issue by abhishekdgeek** [meanjs/mean#1718]
Hi Team,

I just configured my COMODO SSL and was able to run the instance on https in browser but not http has stopped working. Can you please let me know what is the desired setting to service both http and https at the same time.

PS - I am using pm2 for keeping the server running.

Thanks,
Abhishek Jain

**Comment by lirantal** [comment]
I think we can either run HTTP or HTTPs, not both.
It shouldn't be a tough configuration on `lib/socket.io` IIRC although I don't know why you would want to do it.

I would have Node.js run on HTTP on some high port and use a LB functionality to crunch the SSL connection.

**Comment by abhishekdgeek** [comment]
Yeah, that's what I did at end. I used nginx to proxy read on port 3000 but then I also had to change a little bit of code to get the IP addresses.

Thanks.

**Comment by simison** [comment]
> https in browser but not http has stopped working. 

You might want to redirect all `http` traffic to `https` btw. Would solve your problem as well. ;-)

**Comment by lirantal** [comment]
@simison possible, but it's a less secure way of doing things since a MITM can hijack your HTTP connection and redirect you elsewhere.

HTTPS's Strict Transport Security should help to minimize this
