### ISSUE TITLE
even with typing  rs   the server doesnt restart Error: listen EADDRINUSE :::5858

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1721]
Usually this problem gets resolved with system (current on mac)  restart, but i dont wanna do it every time.. Please any suggestions ?

![image](https://cloud.githubusercontent.com/assets/1026325/23181212/22f3ec16-f842-11e6-9174-212d3868bef7.png)

 I tried killing it but it doenst work

![image](https://cloud.githubusercontent.com/assets/1026325/23181445/0a468cb8-f843-11e6-8320-d81cd0ab9130.png)

**Comment by shanavas786** [comment]
5858 is port not pid

**Comment by jpca999** [comment]
Ok, how can I kill the port ?

**Comment by shanavas786** [comment]
pid is given in the line just above. 21672 in this case
you can kill that

**Comment by jpca999** [comment]
@shanavas786 

I killed the pid using sudo kill -9 pid  but still i get the same error, 


![image](https://cloud.githubusercontent.com/assets/1026325/24049675/1ce9ca06-0b03-11e7-8302-2cee512a61a0.png)

**Comment by lirantal** [comment]
@jpca999 I can't reproduce.
when running the default service (`npm start`), it works just fine:

![image](https://cloud.githubusercontent.com/assets/316371/24580947/95276708-171a-11e7-8046-3caa6a40c1ca.png)
