### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by JoeyAcc** [meanjs/mean#1726]
Hi,

Looking at both the project page and this GH repo, it seems like this is not an actively maintained project (anymore): 
- The most recent commit the repo has seen is from December last year
- The [project website for 0.4.x](https://meanjs.org/docs/0.4.x/) is the most recent version, but was last updated more than a year ago

I'd like to know, because basing a greenfield project on a dead one is a waste of time.

**Comment by vaucouleur** [comment]
@JoeyAcc 

I can't speak for the others, but as far as I am concerned: meanjs == "it just works".

Since "it just works", maybe, maybe, most of us are busy spending time in the Application layers, creating value for our respective business/companies.

There is also a roadmap that you can find by looking around a bit, with feedbacks from the community.

**Comment by davidtaylorjr** [comment]
@JoeyAcc There was a commit to the master branch in December so I would say ye it is still alive.

However, I don't think it supports Angular 2 so it is definitely behind.

**Comment by JoeyAcc** [comment]
It is exactly because there are no commits yet this year that I wasn't sure whether this project is alive or not.
That said, I'm quite happy to see the answer is affirmative.

**Comment by lirantal** [comment]
In another issue I stated that I am working on the next version of MEAN.JS in another repository of mine, where I'd be happy if people would be able to help out, especially on the frontend stack.

**Comment by davidtaylorjr** [comment]
What is the repository link?

**Comment by JoeyAcc** [comment]
@lirantal Will that be MEAN.js v0.6.0 (or something to that effect)? Or more like a 1.0?

**Comment by ptimich** [comment]
Take a look at MEAN.JS 1.0 Roadmap:  #1666 
Hopefully it will answer your questions.

**Comment by lirantal** [comment]
@JoeyAcc we already somewhat decided that MEAN.JS 0.x will continue to evolve with smaller updates/fixes on the current project structure, and the project re-haul will take place as a MEAN.JS v1 or something like that.
