### ISSUE TITLE
error with npm install

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1727]
I want to deploy to server production I just create server and run npm install, So I got error below

> npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated mongodb@2.0.49: Please upgrade to 2.2.19 or higher
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
[      ............] | fetchMetadata: verb cache add spec glob@~3.1.21
[      ............] | fetchMetadata: verb afterAdd /root/.npm/lodash._arraycopy/3.0.0/package/package.json written
[      ............] / fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/for-own
[      ............] \ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/got
[       ...........] \ fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/temporary
[       ...........] | fetchMetadata: verb cache add spec qs@2.4.2
[       ...........] | fetchMetadata: verb cache add spec optionator@^0.8.1
[       ...........] | fetchMetadata: verb cache add spec which@^1.1.1
[       ...........] - fetchMetadata: verb afterAdd /root/.npm/once/1.3.3/package/package.json written
[       ...........] | fetchMetadata: verb cache add spec graceful-fs@~2.0.0
[       ...........] - fetchMetadata: verb cache add spec graceful-fs@~2.0.0
Killed  ...........] / fetchMetadata: verb cache add spec graceful-fs@~2.0.0

Server information 
* 512 MB Memory / 20 GB Disk / SGP1 - Ubuntu 16.04.2 x64
* digitalocean 
* node v 6.10.0
* mean v0.4.2

How do I fix this problem thank in advance

**Comment by rogerlopz** [comment]
It may be your node version.
Have you tried another? Im running 6.3.1 with no problems.

**Comment by avatarr** [comment]
Not yet try anther version on my local machine I use v 6.9.2 (MAC OS)

**Comment by shanavas786** [comment]
I could see only warnings there which can be ignored. What is the error ?

**Comment by avatarr** [comment]
@shanavas786 The error is last line npm exist process

> Killed ...........] / fetchMetadata: verb cache add spec graceful-fs@~2.0.0

**Comment by avatarr** [comment]
I figure it out Cause by server memory is full

I will close this issues
