### ISSUE TITLE
Angular error

### ISSUE THREAD

**Issue by pgupta408** [meanjs/mean#1728]
Getting following error after Ubuntu-14.04 installation. Looks like some basic Angular installation bug. Any clue how to solve?

Uncaught ReferenceError: angular is not defined
    at config.js:25
    at config.js:36
(anonymous) @ config.js:25
(anonymous) @ config.js:36

init.js:5 Uncaught ReferenceError: angular is not defined
    at init.js:5
    at init.js:54
(anonymous) @ init.js:5
(anonymous) @ init.js:54

config.js:18 Uncaught ReferenceError: angular is not defined
    at Object.registerModule (config.js:18)
    at articles.client.module.js:4
    at articles.client.module.js:9
registerModule @ config.js:18
(anonymous) @ articles.client.module.js:4
(anonymous) @ articles.client.module.js:9

config.js:18 Uncaught ReferenceError: angular is not defined
    at Object.registerModule (config.js:18)
    at chat.client.module.js:4
    at chat.client.module.js:6
registerModule @ config.js:18
(anonymous) @ chat.client.module.js:4
(anonymous) @ chat.client.module.js:6

config.js:18 Uncaught ReferenceError: angular is not defined
    at Object.registerModule (config.js:18)
    at core.client.module.js:4
    at core.client.module.js:8
registerModule @ config.js:18
(anonymous) @ core.client.module.js:4
(anonymous) @ core.client.module.js:8

**Comment by pgupta408** [comment]
RESOLVED....

bower install was not started by NPM install process.. Refer documentation:
        Finally, when the install process is over, npm will initiate........

After I did bower install, thinks worked..

**Comment by getwebem** [comment]
I am getting the same problem but this only happens when i upload the app to github and then if i want to test it by cloning it and running grunt, i get this problem?
