### ISSUE TITLE
I have problem with login user and got another user login instead 

### ISSUE THREAD

**Issue by avatarr** [meanjs/mean#1729]
It 's strange case.For example, I use 2 username [admin_system, staff_shop] .I try to login to website with username "admin_system" but meanjs have been logged to "staff_shop" instead. This case shouldn't happen even throught  I was useing username and password  "admin_system"

Anyone havw this problem and How to do I fix it

Ps. I use meanjs v 0.4.2

Thanks in advance.

**Comment by vaucouleur** [comment]
@avatarr Are you using some kind of integrated password manager with your browser, that could interfere with your test ("auto-login") ? if you use another browser do you experience the same issue ? what browser were you using ? browser version and OS version as well please. Did you modify the meanjs source code or was it with a fresh meanjs install ? Thanks

**Comment by avatarr** [comment]
@vaucouleur First time I use Chrome and for sure then change to FF is the same, I just remove social login and use meanjs login system with username and password and remove owasp and not modify anything use original except I tell you 

Ps. on local on don't have any problem 
Ps2 I have other problem if you can tell my why please let me know. I create CRUD system and update one user then I request users list ( use find({}) ) the data in not change to latest  update and still get old data , I try to check on database is a fresh data but I have to wait about 1 min. data will change If you know please me with this case too.

Cllient Information: 
 * OS: OSX
 * Mac Air 
* Browser Chrome, FF, Safari 
Server Infomation 
 * Node v6
 * use nginx as proxy
 * use pm2 as development mode 
 * use "pm2 start server.js -i 3" 
 * OS ubuntu 16.04 
 * provider Digitalocean

**Comment by avatarr** [comment]
I can't finish this project because 2 problem I tole you please help me to find what happen I use many way to fix and try too much it doesn't work

**Comment by vaucouleur** [comment]
If you put a breakpoint at the line below, do you see the expected username and user object (as part of the result of the findOne query) ?

https://github.com/meanjs/mean/blob/e14088039748ba515e7de3f5a44ec20965337537/modules/users/server/config/strategies/local.js#L20

**Comment by lirantal** [comment]
@avatarr any other insights you can share? not enough to go on

**Comment by avatarr** [comment]
Sorry, I decided to other platform to finish my project, unfortunate I can't address problem.
