### ISSUE TITLE
i just create a new module using the yo , but it isn't pulling the data from mongo  

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1730]
am i missing anyting ?
fyi : commented lines work coz uses previous code. 

exports.list = function(req, res) {

  Rei.find().sort('-created').populate('user', 'displayName').exec(function(err,  re) {
  // Rei.find().populate('Rei').exec(function(err, rei) {
    if (err) {
      return res.status(400).send({
        message: errorHandler.getErrorMessage(err)
      });
    } else {
      console.log( '  reif  = ', reif);
      res.jsonp(reif);
    }
  });
};

// console.log('95-RSC--calling in rei list function'); 

//   Property.find().sort('-created').populate('user', 'displayName').exec(function(err, properties) {
//     if (err) {
//       return res.status(400).send({
//         message: errorHandler.getErrorMessage(err)
//       });
//     } else {
//       res.jsonp(properties);
//     }
//   });
// };

**Comment by mleanos** [comment]
Please provide more info here. Where is it failing? What are the results of your console logs?

Can you determine if the issue is client-side or server-side. Describe what your experiencing, as it will help us debug this with you.

**Comment by jpca999** [comment]
sure,

**Comment by jpca999** [comment]
if i change the line to following i.e get the data from users collection  it works good.
User.find().sort('-created').populate('user', 'displayName').exec(function(err,  reifaxes) {

so something wrong with data i guess

**Comment by jpca999** [comment]
If i try to pull the data from Articles collection  ( this is the default collection in the mongo, it works great, but it doenst work for the new module that i created. 

Article.find().populate('Reifax').exec(function(err, reifaxes) {

**Comment by lirantal** [comment]
@jpca999 so it' still an issue?

**Comment by jpca999** [comment]
Yes

**Comment by lirantal** [comment]
@jpca999 you're using the generator, right?
I'm afraid it's a different version from the current master branch of mean.js and I haven't been actively developing it either. Is it an option for you to move to just clone mean.js master repo?
