### ISSUE TITLE
gulp build only concatenates non-library files?

### ISSUE THREAD

**Issue by abumere** [meanjs/mean#1731]
Maybe I'm missing something but it seems like **gulp build** (the command we're supposed to run before running in prod) is only concatenating non-asset files. 

So anything defined in production.js  (stuff in public/lib) is not added to the application.min.js or application.min.css files that are eventually created? 

Is this normal behavior for the command or am I missing a step? 

I did a site speed test and noticed that I was still loading up separate asset files. You can see it here: [here](https://tools.pingdom.com/#!/1n06m/https://learningesan.herokuapp.com/)

I was under the impression the the application.js and application.css files would contain _all_ of my css/js along with the library files

**Comment by mleanos** [comment]
The Bower libraries are installed with the project's `postinstall` script.

See here: https://github.com/meanjs/mean/blob/master/package.json#L32

**Comment by abumere** [comment]
@mleanos So does that mean I should execute npm postinstall after running gulp build to get libraries included in the application.js file?

**Comment by mleanos** [comment]
You don't have to run `postinstall` because it automatically gets executed after NPM installs your package dependencies. Your deploy process should at the very least install your package dependencies. Otherwise, your application wouldn't be able to start without the necessary node libraries.

**Comment by lirantal** [comment]
@mleanos ?

**Comment by abumere** [comment]
@mleanos @lirantal I guess what I'm asking is if there is a process already designed that will contact, uglify etc all the asset js files similar to what is already done for the js files in the modules

**Comment by lirantal** [comment]
yeah, we don't build a bundle like you might be familiar with webpack and such.
Welcome to open a PR though.
