### ISSUE TITLE
Profile pic not loading in internet explorer.

### ISSUE THREAD

**Issue by abhishekdgeek** [meanjs/mean#1733]
Hi team,

I was testing the app in Internet Explorer 9 for my next production app and I found that profile pic doesn't load. I did some searches and found that image is not having any extension and node js is not setting the headers properly for IE to know whether that url is an image or not.

Thanks.

**Comment by lirantal** [comment]
@abhishekdgeek would you like to submit a PR to fix this?
I have no way of reproducing the IE9 bug.

Are you saying that the server doesn't respond with the correct headers for the image?

**Comment by abhishekdgeek** [comment]
@lirantal I didn't really fix it. Instead I kinda put a hack by setting content-type to image/jpeg without knowing actual content type as I was only uploading jpeg. Later I got to know about magic numbers but reading the file every time would be resource expensive in my case.

> Are you saying that the server doesn't respond with the correct headers for the image?
Yes. The headers are application/octet which IE doesn't understand.

Thanks.

**Comment by lirantal** [comment]
That's right.
The missing feature would be that after the upload is successful we don't only record the filepath for the picture but also metadata, such as the file mimetype and others. This way, you can use it to send it back to the client. 

It's a fairly easy process to do and you wouldn't need to hack it.
The relevant code is in https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.profile.server.controller.js#L96 where you'd also need to record other metadata you get from the file.
