### ISSUE TITLE
whenver i try to install a new copy it spits this error.   Error: Cannot find module 'ansi' 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1734]
![image](https://cloud.githubusercontent.com/assets/1026325/23928623/23f982fe-08f7-11e7-89c0-d075a2fc86de.png)

I tried installing it with npm install --save ansi 

I tried installing it with npm install --g ansi 

no change.

**Comment by lirantal** [comment]
@jpca999 provide more context please.
How is this related to MEAN.JS?

**Comment by jpca999** [comment]
@lirantal it happens when i change my node version from 4. to 6ish.  so resolved

**Comment by lirantal** [comment]
Ok, thanks.
