### ISSUE TITLE
while installing mean js  on node version 7.2.1   &  npm = 3.10.10     Unable to run meanjs. 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1735]
on mac

npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.4.6 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jay/code/delete/liberty/npm-debug.log
npm ERR! code 1

**Comment by PierreBrisorgueil** [comment]
Hello,

meanjs is in test for node v7, today it's only available for node 6.4 for the last realase

**Comment by lirantal** [comment]
thanks @jpca999 
this mainly happens due to the old node-inspector library which is now deprecated since 6.3 issued support for the internal debugger.

I already tested MEAN.JS locally with 7.7.4 and npm v4 and it works well with this dependency removed. I'll issue a PR tomorrow.

**Comment by lirantal** [comment]
FYI @jpca999  https://github.com/meanjs/mean/pull/1744 fixes the issue
