### ISSUE TITLE
MEAN.JS AngularJS - ng-repeat displaying blank rows

### ISSUE THREAD

**Issue by denGitHub** [meanjs/mean#1736]
I take any example with working ng-repeat.

For example this:

https://plnkr.co/edit/6IeQBH49Z3SoU817IbVk?p=preview

On PHP based site it is working. But on the latest MEAN.js it is displaying blank rows though it renders correct number of rows.

For more details
http://stackoverflow.com/questions/42855698/mean-js-angularjs-ng-repeat-displaying-blank-rows

**Comment by umairch** [comment]
Please share your code where you're using ng-repeat.
 Its very simple dude @denGitHub

**Comment by denGitHub** [comment]
Sure, right on the main page after deploying.
https://github.com/denGitHub/NodeAngular

**Comment by PierreBrisorgueil** [comment]
Hello, I took a look at your repo
you've edited the server layout, not the client side. Server side is for node, don"t know angular, you need tu put your code in client/view/home.client.view.html, with the angular part in client/contorllers/home.client.controller.js

**Comment by lirantal** [comment]
Please use Stackoverflow or other means of developers forum, closing.
