### ISSUE TITLE
Gruntfile.js missing

### ISSUE THREAD

**Issue by jellicoe** [meanjs/mean#1739]
there is no Gruntfile.js in the repo

**Comment by shanavas786** [comment]
Use `gulp`. Grunt is no longer supported by meanjs.

**Comment by umairch** [comment]
@shanavas786 will you please share the official link where team mean.js has mentioned that grunt is no longer supported. I want to update my knowledge

**Comment by shanavas786** [comment]
Its removed in this [commit](https://github.com/meanjs/mean/commit/83c7c47578dc3a0eb8df1678793c0ecfcb06ee62)

**Comment by jellicoe** [comment]
you need to remove references to grunt from the websites install
instructions

http://meanjs.org/docs/0.4.x/

**Comment by lirantal** [comment]
Thanks @jellicoe 

@codydaig how about we copy&paste the 0.4.2 to a 0.5.0 and set that as default for the docs, then we can just review the 0.5.0 and update it to remove stuff like the deprecated grunt?

**Comment by simison** [comment]
@lirantal this can be closed, seems to be done?

**Comment by lirantal** [comment]
Yes, thank you.
