### ISSUE TITLE
Not showing but return a download item in Tencent's QQ browser(Chrominum).

### ISSUE THREAD

**Issue by Rykka** [meanjs/mean#174]
When Opening a meanjs app, like the meanjs.herokuapp.com
it works as a blank page ,and return a `download` item which contains the page .

the source code of the blank page seems allright.
but no other info showed.

I know this is mainly the browser issue.

But  I can not track and found out why.

browser from: http://browser.qq.com/index_m.html

**Comment by ilanbiala** [comment]
@Rykka it seems like the browser has some issues, because in no other browser does this happen.

**Comment by ilanbiala** [comment]
@Rykka this seems to be a bug in that browser's implementation, because all commonly used browsers handle MEAN.js fine. In the future, please post on Stackoverflow or the forums before coming here.

**Comment by Rykka** [comment]
Ok, This Thing maybe I should post to Tencent's browser team.
