### ISSUE TITLE
how I can save several email templates for individual user via UI ?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1741]
It would be ver helpful to know if someone else has implemented a functionality like this, 

I want to give the users to have the ability to create their own email templates, and save them as templates, in each user's personal settings. 

Here's how it would look like 
![image](https://cloud.githubusercontent.com/assets/1026325/24340907/ce74f926-1283-11e7-89cb-3a35f5cdafda.png)

Following are the Issues I need help with :
1) Currently the implementation in the mean js is, we have to hard code/ write that each email template in the file, 
2) How i can implement the variables like {{username}}  {{agent_name}}

Thanks in advance :-)

**Comment by umairch** [comment]
@jpca999 Aren't  you using Swig Templates for this Purpose?

**Comment by jpca999** [comment]
No I wasn't.  I'll look into it.

**Comment by lirantal** [comment]
The swig templates library has been deprecating a long time ago already and as such we've also moved away from that in MEAN.JS.

**Comment by jpca999** [comment]
@lirantal so can you please recommends a solution for this kind of requirement ?

**Comment by lirantal** [comment]
It's beyond the scope of a framework itself which is why I closed it to begin with.
In a nutshell, I'd store the template into the database along with the variables, and then when processing the e-mail I'd replace the variables with their actual value (take good care here for security issues).

But again, this is entirely a system that needs to be built and designed and has nothing to do with the MEAN.JS project itself

**Comment by jpca999** [comment]
@lirantal    so the email with variable names work great but now i want to save the {{variables}} in the mongo. 

![image](https://cloud.githubusercontent.com/assets/1026325/25073265/e5d3f922-22b0-11e7-8e7a-de95c79d6b68.png)
Here the green marked variables are replaceable & I can chnage the content of inner html by putting the variable inside the <p> tag, but the issue is when i want to render variables inside the emailContent variable ?
Any ideas ?


In the below sample mongo object, I'm unable to dynamically replace the variable {{name}} with the content provided by the  res.render function
{
    "last_date_call": "-",
    "call_priority": "-",
    "financial": "Sale",
    "emailTemplate":"This is coming from mongodb sir  Dear name => {{name}}  is also coming from mongodb"
}

**Comment by lirantal** [comment]
So you're making a good progress and in the right direction.
Now that you have the variables as placeholders on the template saved inside the database, whenever you start processing e-mails and send them one by one then you simply do search/replace for `{{email}}` with the real user's email.
