### ISSUE TITLE
Angular is not defeined in 51 files.. Just seing blank page

### ISSUE THREAD

**Issue by mrbigwolf67** [meanjs/mean#1742]
Have tried installing bower several times Reading in other cases, but still having this problem.
need som advise..

**Comment by joooneyd** [comment]
Any resolution so far?

**Comment by PierreBrisorgueil** [comment]
Hello, I just tested for you, no problem on my side with a new installation. 

node 6.4 ? 

npm cache clean
bower cache clean
npm install

if 0 error but it doesn't work, try bower install after, check if you not have a conflict of package.

All libraries have been successfully downloaded to public / lib?

**Comment by lirantal** [comment]
@mrbigwolf67 please tell us how to reproduce and what you did exactly, including your OS details.
