### ISSUE TITLE
how to stop eslint errors on the terminal - changes in .eslintrc.json didnt work. 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1745]
![image](https://cloud.githubusercontent.com/assets/1026325/24591202/b7365ee4-17c9-11e7-8508-50ba91bf817b.png)

![image](https://cloud.githubusercontent.com/assets/1026325/24591206/c88cc516-17c9-11e7-94db-a86ebe5a356c.png)

**Comment by lirantal** [comment]
What do you mean how to stop it...?
You have a modified eslint setup which obviously isn't compatible with the way the code is structured.

So you either go with the project's guideline or you use your own but you'd have to change all the code style to make it pass.
