### ISSUE TITLE
npm install have issues on ubuntu  Not compatible with your operating system or architecture: fsevents@1.1.1

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1747]
![image](https://cloud.githubusercontent.com/assets/1026325/24728439/ccada6aa-1a27-11e7-9f6d-052d6f692f10.png)
![image](https://cloud.githubusercontent.com/assets/1026325/24728452/da76d040-1a27-11e7-8526-67a238f0794f.png)

it happens on node v = 4.5 also

whenever i try to install promise library , it fails. 

![image](https://cloud.githubusercontent.com/assets/1026325/24728615/b2f1b4f8-1a28-11e7-9ff2-de8deb2a5b0e.png)

**Comment by lirantal** [comment]
I see some warnings there, but is there an actual error/issue you face?

**Comment by PierreBrisorgueil** [comment]
same, no error for me, some of my team work on ubuntu, and no problems for us

**Comment by lirantal** [comment]
Ok, closing then.
Open it later if you do find anything.
