### ISSUE TITLE
travis failed on npm test for node > v6.4 

### ISSUE THREAD

**Issue by PierreBrisorgueil** [meanjs/mean#1748]
Fresh install with npm cache clean and bower cache clean

nvm install 6
nvm use 6
node ==> v6.10.2
npm cache clean
bower cache clean
npm install
npm test

<img width="892" alt="screen shot 2017-04-06 at 13 23 51" src="https://cloud.githubusercontent.com/assets/6069599/24752411/ff4e23ae-1acd-11e7-8fe6-6fae194f9fca.png">

<img width="924" alt="screen shot 2017-04-06 at 13 23 56" src="https://cloud.githubusercontent.com/assets/6069599/24752414/04b67e7c-1ace-11e7-985e-4b95bebed071.png">

<img width="839" alt="screen shot 2017-04-06 at 13 24 04" src="https://cloud.githubusercontent.com/assets/6069599/24752420/07b0169c-1ace-11e7-8b09-73f68224ae54.png">

this make travis failed because it use the last node 6, actually 6.10.2, no problem for 6.4 apparently

I'm actually have a look on this, i will make a PR if i can.

**Comment by lirantal** [comment]
@PierreBrisorgueil thanks for reporting.
I fixed it now with this PR: https://github.com/meanjs/mean/pull/1751

**Comment by PierreBrisorgueil** [comment]
@lirantal Thx ! I had started looking but not on mock-fs yet :)

I will try this, thank you !

**Comment by lirantal** [comment]
yeah took me an hour to get to mock-fs as well.
I thought at first this was something related to my Mac OS setup.

**Comment by PierreBrisorgueil** [comment]
ok for me & travis, thx :)
