### ISSUE TITLE
Moving to Node.js v6 and v7 support

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#1756]
To make it short - I'd like to stop supporting Node.js v4 and v5 and focus on v6 and v7.
Any strong reasons why that would be an issue?

Longer story:
* Multiple libraries simply don't support older than specific Node.js v6 versions (nodemailer and protractor to name a few)
* Maintaining the travis matrix and test setup for v4 and v5 is a pain
* Node.js v4 entered maintenance mode this April

**Comment by PierreBrisorgueil** [comment]
Done on our sub stack.

Possible to maintain two versions, to let the time to follow, but 4 is too restrictive ... And can cause to spend too much time to the developers ... not the priority for us in my opinion

**Comment by lirantal** [comment]
So I'll definitely upgrade our deps and project to Node v6.

**Comment by mleanos** [comment]
I've been running MEANJS on Node v6.6 for over 6 months, and haven't encountered any issues. In fact, most (if not all) npm issues have disappeared relating to Node 4 and previous versions.

Additionally, I've been running a MEANJS project on Node 7 for a short time. I haven't touched the project in a few weeks, but I don't recall any issues.

**Comment by lirantal** [comment]
It further strengthen my decision to move to 6.9 and above.

**Comment by simison** [comment]
Done!
