### ISSUE TITLE
weird page behavior:  doesnt stop loading until I hit stop button on browser. 

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1761]
![image](https://cloud.githubusercontent.com/assets/1026325/25054672/8542fea8-212c-11e7-802c-48fb18e036b3.png)

It doesnt call any resources in the terminal but. 

I just cloned the new codebase to check if it happens with just my app or with the new one too. 
It may be happening only in my system ( macbook ) , I wonder if someone else had same issue ?

**Comment by lirantal** [comment]
@jpca999 if you clone the master branch of this repo it still reproduces?

**Comment by jpca999** [comment]
on it, give me few.

**Comment by jpca999** [comment]
I re-cloned the whole thing and made sure that im on master. Yes, It still does the same weird thing.

**Comment by jpca999** [comment]
@lirantal  the issue is gone now. if it happens again, I'll let you know... Maybe my machine issue, I'll keep you posted.

**Comment by lirantal** [comment]
Thanks!
