### ISSUE TITLE
Error: Failed to lookup view  when run unit test

### ISSUE THREAD

**Issue by tridungle** [meanjs/mean#1765]
User CRUD tests
    ✓ should be able to register a new user (105ms)
    ✓ should be able to login successfully and logout successfully (67ms)
    ✓ should not be able to retrieve a list of users if not admin (51ms)
    ✓ should be able to retrieve a list of users if admin (62ms)
    ✓ should be able to get a single user details if admin (59ms)
    ✓ should be able to update a single user details if admin (61ms)
    ✓ should be able to delete a single user if admin (56ms)
    ✓ forgot password should return 400 for non-existent username
    ✓ forgot password should return 400 for no username provided
    ✓ forgot password should return 400 for non-local provider set for the user object
```
Error: Failed to lookup view "reset-password-email" in views directory "./"
    at EventEmitter.render (/private/var/www/restful-api/node_modules/express/lib/application.js:580:17)
    at ServerResponse.render (/private/var/www/restful-api/node_modules/express/lib/response.js:966:7)
    at async.waterfall.mailOptions.to (/private/var/www/restful-api/modules/users/server/controllers/users/users.password.server.controller.js:64:11)
    at nextTask (/private/var/www/restful-api/node_modules/async/dist/async.js:5210:14)
    at /private/var/www/restful-api/node_modules/async/dist/async.js:5204:13
    at apply (/private/var/www/restful-api/node_modules/async/dist/async.js:21:25)
    at /private/var/www/restful-api/node_modules/async/dist/async.js:56:12
    at /private/var/www/restful-api/node_modules/async/dist/async.js:944:16
    at /private/var/www/restful-api/modules/users/server/controllers/users/users.password.server.controller.js:48:15
    at /private/var/www/restful-api/node_modules/mongoose/lib/model.js:3720:16
    at /private/var/www/restful-api/node_modules/mongoose/lib/services/model/applyHooks.js:146:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by mleanos** [comment]
Which test is failing? Also, is this happening with the latest master branch?

**Comment by tridungle** [comment]
@mleanos:
I followed the yo generator documentation to create my application as shown bellow:
```
$ npm install -g yo
$ npm install -g generator-meanjs
$ yo meanjs
```
Then I select version 0.4.2 after that I run `grunt test` command

```$ grunt test```

**Comment by mleanos** [comment]
Do you encounter the same issue using `gulp test`?

Also, can you provide which test is throwing this exception?

**Comment by tridungle** [comment]
@mleanos : I'm not sure, I did not use `gulp test` and I just run `grunt test`  for default unit test which yo was generate.

**Comment by PierreBrisorgueil** [comment]
@mleanos the yo generator use the last master ? not for me, i'm wrong ? 

@tridungle you juste have to 

clone the repo
make an npm install
gulp test
gulp

the yo generator is not up to date, we need to inform of this in documentation

**Comment by lirantal** [comment]
what @PierreBrisorgueil said - use the master branch on this repo, not the yeoman generator as it is not up to date.

**Comment by mleanos** [comment]
@PierreBrisorgueil You are correct. The generator project isn't up to date with the latest master. However, @tridungle was installing the 0.4.2 version of MEANJS. This version shouldn't have these issues, unless it's a bug that actually exists in the code-base & not the generator.

@tridungle Do you see the [reset-password-email template](https://github.com/meanjs/mean/blob/master/modules/users/server/templates/reset-password-email.server.view.html) in your project, after generating from Yoeman?

I do want to point out that using the 0.5.0, or latest (*master*) version of the project is probably a better choice. There have been many improvements since 0.4.2.

**Comment by tridungle** [comment]
@mleanos : yes, the reset-password-email template is existed. I will trying to use the 0.5.0. 
Thank you!
