### ISSUE TITLE
How to update a angular $resource inside the meanstack / meanjs way of doing?

### ISSUE THREAD

**Issue by jpca999** [meanjs/mean#1766]
First, I know i can hack my way to make it work, but i want to make it work the way meanjs folks have done it. 

I have my front end written in ionic. I have a  user profile view, where user can update the contents of its profile data, like username first name, last name etc. 

I copy pasted the whole angular resource code to update the user profile as below as an angular service.

.factory('UsersService', function($resource , currentUrl) {
console.log( ' 470- S  $resource = ', $resource ); 
  console.log( ' 469- S  curerntUrl = ', currentUrl ); 
  // debugger; 
    var Users = $resource(currentUrl+'/api/users', {}, {
      update: {
        method: 'PUT'
      },
      updatePassword: {
        method: 'POST',
        url: '/api/users/password'
      },
      deleteProvider: {
        method: 'DELETE',
        url: '/api/users/accounts',
        params: {
          provider: '@provider'
        }
      },
      sendPasswordResetToken: {
        method: 'POST',
        url: '/api/auth/forgot'
      },
      resetPasswordWithToken: {
        method: 'POST',
        url: '/api/auth/reset/:token'
      },
      signup: {
        method: 'POST',
        url: '/api/auth/signup'
      },
      signin: {
        method: 'POST',
        url: '/api/auth/signin'
      }
    });

    angular.extend(Users, {
      changePassword: function (passwordDetails) {
        return this.updatePassword(passwordDetails).$promise;
      },
      removeSocialAccount: function (provider) {
        return this.deleteProvider({
          provider: provider // api expects provider as a querystring parameter
        }).$promise;
      },
      requestPasswordReset: function (credentials) {
        return this.sendPasswordResetToken(credentials).$promise;
      },
      resetPassword: function (token, passwordDetails) {
        return this.resetPasswordWithToken({
          token: token // api expects token as a parameter (i.e. /:token)
        }, passwordDetails).$promise;
      },
      userSignup: function (credentials) {
        return this.signup(credentials).$promise;
      },
      userSignin: function (credentials) {
        return this.signin(credentials).$promise;
      }
    });

    return Users;
  })
when user clicks on the update profle html, it calls this function in the controller,

  $scope.updateUserInfo = function(auser) {
        var user = new UsersService(auser);
    user.$update(function (response) {
console.log( ' success  response', response); 
});
      }, function (response) {
console.log( ' error response', response); 
      });

heres the issue, when i call it from my own front end code,

![image](https://cloud.githubusercontent.com/assets/1026325/25210806/aa42b654-254f-11e7-9838-7be5cc90f9dc.png)

I dont know where is this "m" coming from?
But when i call it from their localhost:3000 codebase, it works great.

![image](https://cloud.githubusercontent.com/assets/1026325/25210818/bc25cabe-254f-11e7-8ac8-c4734e087a67.png)

Over here its called $resource.

I think where im screwing up is, in the original its forming as a Resource object but mine code isn't. 

 $scope.updateUserInfo = function(auser) {
        var user = new UsersService(auser);
console.log( ' 2444  new UsersService = ', user ); 
Here it doesn't get instantiated as user = Resource object. 

![image](https://cloud.githubusercontent.com/assets/1026325/25213301/c7769408-255d-11e7-99b0-53e02becd155.png)

Kindly guide me how to fix it.

**Comment by mleanos** [comment]
It appears that your Angular $resource object is working correctly, as it is hitting the correct endpoint (`http://localhost:3000/api/users`). The error message you're seeing is coming from the server, due to the check for the logged in User. My guess is that you're not sending an auth token/cookie with the request from your Angular code.

**Comment by jpca999** [comment]
@mleanos My guess is that you're not sending an auth token/cookie with the request from your Angular code.   Your right I'm not, how do i make sure that its sending the auto cookie stuff ?

**Comment by mleanos** [comment]
I'm not familiar enough with Ionic, so I really can't say. Are you able to login from your Ionic front-end? If so, how does your front-end handle it?

I think this might be a little outside the scope of the project, and you should be able to search the web for better help. There's gotta be plenty of info that could help you.

**Comment by jpca999** [comment]
Are you able to login from your Ionic front-end? If so, how does your front-end handle it?

Yes, for logging  I use the same code thats implemented in angular, but I don't use the same cookie names, or key value pairs. 


I think this cookie authenticaion  is done in the meanjs  via this code. 

function EditProfileController($scope, $http, $location, UsersService, Authentication, Notification) {
    var vm = this;
    console.log('12 - vm  = ', vm); 
    vm.user = Authentication.user;

But i dont have this in my ionic.

**Comment by PierreBrisorgueil** [comment]
hello, sorry, no time to investigate .. i work with the jwt part today ..!

but like say @mleanos on every request you must set the cookie, i think it was a var like a sessionId in mean 0.5 ? 

just up the project mean from the master, and have a look on network transaction, you will be able to understand, try and reproduce same cookie on your own Ionic front after. 

You can do some search about ionic passport cookie authentication :)

**Comment by jpca999** [comment]
thanks but i moved on tho metor and react-native.
