### ISSUE TITLE
meanjs on ec2 is too slow

### ISSUE THREAD

**Issue by maelfosso** [meanjs/mean#1770]
Hi,

I deployed an application on EC2 but is too slow. The users wait up to 3 min to see the static home page.
Are there any way to solve this problem ?

Thanks !!!

**Comment by lirantal** [comment]
Maybe just the first page when assets are getting built but shouldn't happen more than that

**Comment by simison** [comment]
Closing.

@maelfosso if you have any news on this, let us know!
