### ISSUE TITLE
Potential forgot password security flaw

### ISSUE THREAD

**Issue by rdelhommer** [meanjs/mean#1771]
I'm pretty new to the MEAN stack and web development in general so sorry if this is a dumb question.

In the user password server controller, the forgot password url domain is set by using app.get('domain') however this is always undefined on my development environment ~~(I haven't checked my production environment yet)~~.

Just curious, how is this app setting set?  I searched the code and didn't see anything that explicitly sets the 'domain' setting.

**Comment by rdelhommer** [comment]
I was thinking this could be a potential security hole if someone spoofs the request's host header

**Comment by rdelhommer** [comment]
Wanted to provide some more details...

This setting was also undefined in my production.  I ended up adding the following line to my express setup file that fixed the issue.

```
app.set('domain', config.domain);
```

As seen in the code below, since `req.app.get('domain')` is always undefined, the domain of the forgot password url is always determined by the request's host header

```
var httpTransport = 'http://';
if (config.secure && config.secure.ssl === true) {
  httpTransport = 'https://';
}

var baseUrl = req.app.get('domain') || httpTransport + req.headers.host;

res.render(path.resolve('modules/users/server/templates/reset-password-email'), {
  name: user.displayName,
  appName: config.app.title,
  url: baseUrl + '/api/auth/reset/' + token
}, function (err, emailHTML) {
  done(err, emailHTML, user);
});
```

The security concern is that someone could bombard the server with forgot password requests with a spoofed host header and hope to get an email registered with the server.  The server would provide a valid password reset token, but the forgot password url would have a domain specified by the bad guy.  

These tokens could then be harvested if the links in email are clicked and used to change a user's password and compromise the user's account.  Not a huge hole since it only compromises individual accounts, but certainly something thats easy to fix.

That is unless I'm being an idiot and totally misunderstanding the code which is possible :)

**Comment by vaucouleur** [comment]
Assuming that your conf file is  well-defined:
https://github.com/meanjs/mean/blob/master/config/env/default.js#L17

..  then did you try to breakpoint at the following line, and check the domain ? Still undefined ?
https://github.com/meanjs/mean/blob/master/config/lib/express.js#L44

**Comment by rdelhommer** [comment]
Correct.  I only noticed the problem because of the [warning](https://github.com/meanjs/mean/blob/f53db0f2e24c5de67bc43566e1103cf7d53edf80/config/config.js#L75) that is printed when config.domain is not set.

app.local.domain is properly set to the value in config and is defined, but app.get('domain') returns undefined [here](https://github.com/meanjs/mean/blob/f53db0f2e24c5de67bc43566e1103cf7d53edf80/modules/users/server/controllers/users/users.password.server.controller.js#L64)

**Comment by vaucouleur** [comment]
@rdelhommer  @mleanos @lirantal I'm reproducing this issue on a fresh install.  Node v6.7.0; Express 4.15.3.

Please note that  while req.app.get('domain') is undefined, req.app.locals.domain is properly defined.

**Comment by mleanos** [comment]
> Correct. I only noticed the problem because of the warning that is printed when config.domain is not set.

👍 on the existence of this message 😸 

The bad reference to this config setting has been fixed with https://github.com/meanjs/mean/pull/1803/commits/422036b9e7d7c86758b44a648f3370c0fe9492a7

**Comment by mleanos** [comment]
Thanks @rdelhommer & @vaucouleur
