### ISSUE TITLE
Promisify test object creation/destruction

### ISSUE THREAD

**Issue by aanev** [meanjs/mean#1773]
I guess it might be a good idea to promisify object creation/destruction in the tests. For example:
 
```
 afterEach(function (done) {
    User.remove().exec(function () {
      Article.remove().exec(done);
    });
  });
```

can become:
```
  afterEach(function (done) {
    User.remove().exec()
      .then(Article.remove().exec())
      .then(done());
  });
```

This can simplify more complex test scenarios where multiple models are used.

**Comment by mleanos** [comment]
Good idea. A PR would be very welcome for your proposed changes. Thanks you.
