### ISSUE TITLE
Remove Swig Templating

### ISSUE THREAD

**Issue by daronjones** [meanjs/mean#1775]
Meanjs no longer uses swig as it has vulnerabilities and is no longer being maintained: 

See: https://github.com/paularmstrong/swig

Meanjs has opted to use handlebars which uses a similar syntax and is a fairly straight forward conversion, as it's only used to present the server side views: [`modules/core/server/views`](https://github.com/GrowSoftware/Project.AM.UX/tree/master/modules/core/server/views).

**Comment by lirantal** [comment]
But we did remove it... not sure what did you mean by this issue @daronjones?

**Comment by daronjones** [comment]
Lol! Sorry Liran.

I'm now working somewhere using MeanJS. This message was meant to be put on
our internal TODO. :D

**Comment by lirantal** [comment]
Cool no issues, I'm closing :)

**Comment by daronjones** [comment]
Are you on top of all the issues in Meanjs? I got snowed under way back.

**Comment by lirantal** [comment]
Been a bit busy but I did review quite a few items a few weeks back.
Would be great to have more active contributors onboard to help with the repo.

**Comment by daronjones** [comment]
Definitely, things have been a bit like a ghost-town recently. I was going to have a crack at some of the stuff I've not had time before to work on.
