### ISSUE TITLE
Error: ENOENT: no such file or directory, unlink './modules/users/client/img/profile/uploads/df9f321cf61c57c89c3e4d0a416e1093.jpg'

### ISSUE THREAD

**Issue by maelfosso** [meanjs/mean#1778]
Hi,

Please I always have this error
I don't know why

How could I solve it please ?

Thanks.

**Comment by vaucouleur** [comment]
@maelfosso When you change your profile picture, the current version of meanjs tries to delete the existing profile picture (pictures are not stored withing mongodb they are stored on the filesystem). 

https://github.com/meanjs/mean/blob/f53db0f2e24c5de67bc43566e1103cf7d53edf80/modules/users/server/controllers/users/users.profile.server.controller.js#L112

My guess is that, you played with meansjs, you modified some profile picture, then re-deployed meanjs  somewere else on your filesystem (or deleted altogether the previous install).. but you kept the existing mongodb database.. hence the exception when you are trying to change your profile picture.

**Comment by sagarora77** [comment]
Totally agree with @vaucouleur.
Its not an issue, its just a broken link which is left in MongoDB after you removed the project or reinstalled in a different directory as the resource is not present in the uploads directory.

**Comment by mleanos** [comment]
In the case of a missing file, or bad reference in the User's `profileImageUrl` field, we probably shouldn't throw an error and send it back to the user.

We should just log the error to the console in the case of when the file isn't found.

https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.profile.server.controller.js#L112

We can change the callback logic to something like:
```javascript
if (unlinkError) {
  console.log(unlinkError);
  if (unlinkError.code === 'ENOENT') {
    // NO NEED TO RETURN ERROR IN THIS CASE
    return resolve();
  }

  reject({
    message: 'Error occurred while deleting old profile picture'
  });
} else {
  resolve();
}
```
