### ISSUE TITLE
TypeError: EmployeesService.query is not a function at new EmployeesListController

### ISSUE THREAD

**Issue by Abdou00** [meanjs/mean#1783]
Hello everyone,
I have a meanjs app in which I have an employee module and a team module, I would like to integrate in each of these modules a drop-down list of employees for the team module and teams for the employee module. But then I have this error: TypeError: EmployeesService.query is not a function at new EmployeesListController. Does anyone have an idea or an indication as to what causes this error??
Here is my code:

    // modules/employees/server/controllers/employees.server.controller.js
    exports.list = function(req, res) {
     Employee.find().sort('-created').populate('user', 'displayName').exec(function(err, employees) {
     if (err) {
      return res.status(400).send({
        message: errorHandler.getErrorMessage(err)
       });
      } else {
       res.jsonp(employees);
      }
     });
    };
**My model:**

    // modules/employees/server/models/employees.server.model.js

    'use strict';
    var mongoose = require('mongoose'),
     Schema = mongoose.Schema;

    var EmployeeSchema = new Schema({
     lastname: {
       type: String,
       default: '',
       required: 'Remplissez le nom de l\'employé.',
       trim: true
     },
     firstname: {
      type: String,
      default: '',
      required: 'Remplissez le prénom de l\'employé.'
     },
     email: {
      type: String,
      default: '',
      required: 'Remplissez l\'email de l\'employé.'
     },
     team_name: {
      type: Schema.ObjectId,
      ref: 'Team'
     },
     created: {
      type: Date,
      default: Date.now
     },
     user: {
      type: Schema.ObjectId,
      ref: 'User'
     }
    });
    module.exports = mongoose.model('Employee', EmployeeSchema);

**My policies:**

    // modules/employees/server/policies/employees.server.policy.js
    'use strict';
    var acl = require('acl');
    acl = new acl(new acl.memoryBackend());

    exports.invokeRolesPolicies = function () {
     acl.allow([{
     roles: ['admin'],
     allows: [{
      resources: '/api/employees',
      permissions: '*'
     }, {
      resources: '/api/employees/:employeeId',
      permissions: '*'
     }, {
      resources: '/api/teams',
      permissions: '*'
     }, {
      resources: '/api/teams/:teamId',
      permissions: '*'
     }]
    }, {
    roles: ['user'],
    allows: [{
      resources: '/api/employees',
      permissions: ['get', 'post']
    }, {
      resources: '/api/employees/:employeeId',
      permissions: ['get']
    }, {
      resources: '/api/teams',
      permissions: ['get', 'post']
    }, {
      resources: '/api/teams/:teamId',
      permissions: ['get']
    }]
    }, {
    roles: ['guest'],
    allows: [{
      resources: '/api/employees',
      permissions: ['get']
    }, {
      resources: '/api/employees/:employeeId',
      permissions: ['get']
      }]
     }]);
    };

    exports.isAllowed = function (req, res, next) {
    var roles = (req.user) ? req.user.roles : ['guest'];
     if (req.employee && req.user && req.employee.user && req.employee.user.id === req.user.id) {
      return next();
    }

    acl.areAnyRolesAllowed(roles, req.route.path, req.method.toLowerCase(), function (err, isAllowed) {
     if (err) {
      return res.status(500).send('Unexpected authorization error');
     } else {
      if (isAllowed) {
        return next();
      } else {
        return res.status(403).json({
          message: 'User is not authorized'
        });
       }
      }
     });
    };

**My service:**

    // modules/employees/client/services/employees.client.service.js
    (function () {
      'use strict';
      angular
       .module('employees')
       .factory('EmployeesService', EmployeesService);

       EmployeesService.$inject = ['$resource'];

       function EmployeesService($resource) {
        return {
         employees: $resource('api/employees/:employeeId', {
          employeeId: '@_id'
         }, {
          update: {
           method: 'PUT'
         }
       }),
      teams: $resource('api/teams/teamId', {
        teamId: '@_id'
      }, {
        update: {
          method: 'PUT'
        }, params: {
          controllers: 'TeamsController'
        }
       })
      };
     }
    }());

**and my controller:**

    // modules/employees/client/controllers/employees.client.controller.js
    (function () {
     'use strict';
     angular
      .module('employees')
      .controller('EmployeesController', EmployeesController);

      EmployeesController.$inject = ['$scope', '$state', '$window', '$log', 'Authentication', 'employeeResolve'];

      function EmployeesController ($scope, $state, $window, $log, Authentication, employee) {
       var vm = this;
       vm.authentication = Authentication;
       vm.employee = employee;
       vm.error = null;
       vm.form = {};
       vm.remove = remove;
       vm.save = save;

       function remove() {
        if ($window.confirm('Are you sure you want to delete?')) {
         vm.employee.$remove($state.go('employees.list'));
       }
     }

     function save(isValid) {
      if (!isValid) {
       $scope.$broadcast('show-errors-check-validity', 'vm.form.employeeForm');
       return false;
     }

      if (vm.employee._id) {
        vm.employee.$update(successCallback, errorCallback);
      } else {
        vm.employee.$save(successCallback, errorCallback);
      }

      function successCallback(res) {
        $state.go('employees.view', {
          employeeId: res._id
        });
      }

      function errorCallback(res) {
        vm.error = res.data.message;
      }

       $scope.find = function () {
        $log.info('executing TeamsController.$scope.find');
        vm.team = Teams.query();
       };
      }
     }
    }());

    That's all I've done.

**Comment by mleanos** [comment]
What is `Teams` in `employees.client.controller`?

What does your EmployeeLIstController look like? My guess is that you're trying to get a list of employees with something like `EmployeesService.query()`, just as the error indicates. However, you're service isn't returning a `$resource` object (which would have a `.query()` method). Instead, your returning an object that has two properties that happen to be a `$resource` object. With that, you would need to call `EmployeesService.employees.query()`. 

I would recommend creating your Angular services just as the [Articles service](https://github.com/meanjs/mean/blob/master/modules/articles/client/services/articles.client.service.js#L11) is done. And I would highly recommend separating your Employees & Teams services into their own individual services.

**Comment by Abdou00** [comment]
Thanks for the answer, Teams in employee.client.controller is how I try to retrieve the Teams collection. As for the service I followed your advice and separated them. But despite all when I click on my select I have nothing. I would like to get a trick in this style: [https://stackoverflow.com/questions/33157769/mean-js-how-to-create-of-1-model-that-requires-another](url)

**Comment by mleanos** [comment]
Can you provide your modified code?

**Comment by Abdou00** [comment]
(function () {
     'use strict';

     angular
      .module('employees')
      .factory('EmployeesService', EmployeesService);

      EmployeesService.$inject = ['$resource', '$log'];

      function EmployeesService($resource, $log) {
       var Employee = $resource('/api/employees/:employeeId', {
        employeeId: '@_id'
       }, {
        update: {
         method: 'PUT'
        }
       });

       angular.extend(Employee.prototype, {
        createOrUpdate: function () {
         var employee = this;
         return createOrUpdate(employee);
       }
      });

      return Employee;

    function createOrUpdate(employee) {
      if (employee._id) {
        return employee.$update(onSuccess, onError);
      } else {
        return employee.$save(onSuccess, onError);
      }

      function onSuccess(employee) {
          var success = employee.data
      }

      function onError(errorResponse) {
        var error = errorResponse.data;
        handleError(error);
      }
     }

     function handleError(error) {
       $log.error(error);
      }
     }
    }());

**Comment by mleanos** [comment]
Your service looks good to me. How are you calling it (client controller, and/or angular route resolve?), and what is the html markup you're using for your select?

**Comment by Abdou00** [comment]
This is my routes file:

    'use strict';

    var path = require('path'),
     employeesPolicy = require('../policies/employees.server.policy'),
     teamsPolicy = require(path.resolve('../vlg-espaces-verts/modules/teams/server/policies/teams.server.policy')),
     employees = require('../controllers/employees.server.controller');
     teams = require(path.resolve('../vlg-espaces-verts/modules/teams/server/controllers/teams.server.controller'));

     module.exports = function(app) {

      app.route('/api/employees').all(employeesPolicy.isAllowed)
       .get(employees.list)
       .post(employees.create);

       app.route('/api/employees/:employeeId').all(employeesPolicy.isAllowed)
        .get(employees.read)
        .put(employees.update)
        .delete(employees.delete);
       
       app.route('/api/teams').all(teamsPolicy.isAllowed)
        .get(teams.list)
        .post(teams.create);

      app.route('/api/teams/:teamId').all(teamsPolicy.isAllowed)
       .get(teams.read)
       .put(teams.update)
       .delete(teams.delete);

      app.param('employeeId', employees.employeeByID);
    };

Here is my html markup:

    <select name="team" ng-model="vm.employee.team" id="team" class="form-control" ng-options="opt.id as opt.name for opt in employee" required></select>
