### ISSUE TITLE
Best usage : backend - frontend - both

### ISSUE THREAD

**Issue by maelfosso** [meanjs/mean#1796]
Hi,

Please I need your opinion about the good way to use this framework.
I'm working on a platform that need 

- a front-end side to explain the service to the visitor, 
- two backends side. one for employee and another one for connected user
- api side for Android and IOS

I'm trying to use one package for frontend and backend, but it very difficult because the design are completly different which makes the task very difficult
**Do you think It's good to build the frontend and backend with the same package ?**

I have already the frontend side but It take too much time to lunch. All the testers and users talk about that. The Api it's already working great with Android. So I wonder whether it is not a good idea to use it just for API and Backend and with regard to the frontend side, to use another tool/framework that will redirect the users after it signed. 
**What do you think please ?**

Thanks.

**Comment by simison** [comment]
Current meanjs isn't very flexible regarding this, but if you'd like to work on separating the backend from frontend, I'd invite you to work on meanjs.

https://github.com/meanjs/mean/issues/1849

I'll close this and let's continue in that other issue.
