### ISSUE TITLE
Socket event on login

### ISSUE THREAD

**Issue by smokeyblues** [meanjs/mean#1797]
I have several socket events running on my meanjs app where event emitters and listeners are working properly. But when I try to emit an event on user login, the listener doesn't respond. Any idea what the problem might be? I've tried putting the socket emitter in both the user service and the auth controller.

**Comment by smokeyblues** [comment]
I'm a moron. I got it to work through the home controller. I may have been over-thinking it a bit.

**Comment by simison** [comment]
:beers: happens :-)
