### ISSUE TITLE
error when run npm install

### ISSUE THREAD

**Issue by bi-kai** [meanjs/mean#1800]
error when run `npm install`, seems faild to install `phantomjs-prebuilt` module:
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\node\\anzhuang\\node.exe" "D:\\node\\anzhuang\\node_modules\\npm\\bin\\npm-cli.js" "i"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\node\www\test\test-meanjs\mean-master\npm-debug.log
```
what can i do then?

**Comment by mleanos** [comment]
It looks like you're on Windows. Make sure you have Ruby 2.7 installed and have it in your path.

If that doesn't work then you should be able to find a lot of useful info on the web for errors like this. Most likely, it's an environment issue with your setup; you might just need to install something additional.

**Comment by bi-kai** [comment]
@mleanos Thx for your answer, I'm using win7 in company, do you mean that meanjs is not friendly with windows? 
Besides, I also didn't install ruby, do you have a readme for all these step by step?

**Comment by simison** [comment]
@bi-kai https://rubyinstaller.org/

See also https://github.com/meanjs/mean/blob/master/README.md#prerequisites

**Comment by sagarora77** [comment]
@bi-kai Worked on MEANJS with Windows and below are the helpful official links-
You need to follow the steps @ https://github.com/meanjs/mean
If problem still persists, this page will help @ http://meanjs.org/docs.html

Hope you find it useful...

**Comment by simison** [comment]
Closing, @bi-kai let us know if you still have questions about this!
