### ISSUE TITLE
[$resource:badcfg] Error in resource configuration for action `get`. Expected response to contain an object but got an array

### ISSUE THREAD

**Issue by Abdou00** [meanjs/mean#1801]
Hello everyone, I have a problem to display the data of my item on the page employees.client.view.html, when I select an employee I arrive on the page but it is empty (blank page)??
Here my employe.client.service.js:

     (function () {
      'use strict';

     angular.module('employes').factory('EmployesService', EmployesService).controller('EmployesController', ['$scope', '$resource', '$http', function ($scope, $resource, $http) {
      $scope.employe = {};

      $scope.createEmploye = function() {
        $resource('/api/employes', null, {
          'save': {
            method: 'POST',
            isArray: false
          }
        })
        .save($scope.employe).$promise.then(
          function(result) {
            console.log(result);
          },

          function(response) {
            console.log(response);
          }
        );
      };
      /* -----------------------------------------------------------------------
                                      RESSOURCE TEAMS
      ------------------------------------------------------------------------ */
      $resource('/api/teams', null, {
        'get': {
          method: 'GET'
        }
      })
      .get().$promise.then(
        function(teams) {
          $scope.teams = teams;
        },

        function(response) {
          console.error(response);
        });
    }]);

    EmployesService.$inject = ['$resource'];

     function EmployesService($resource) {
      return $resource('/api/employes/:employeId', {
       employeId: '@_id'
      }, {
       update: {
        method: 'PUT'
      },
      query: {
        method: 'GET',
        isArray: true
      }
     });
    }
    }());

here my html:

    <section>
     <div class="page-header">
       <h1 ng-bind="vm.employe.name"></h1>
     </div>
     <div class="pull-right" ng-show="vm.employe.isCurrentUserOwner">
      <a class="btn btn-primary" ui-sref="employes.edit({ employeId: vm.employe._id })">
       <i class="glyphicon glyphicon-edit"></i>
      </a>
      <a class="btn btn-primary" ng-click="vm.remove()">
       <i class="glyphicon glyphicon-trash"></i>
      </a>
     </div>
     <small>
      <em class="text-muted">
        Posted on
        <span ng-bind="vm.employe.created | date:'mediumDate'"></span>
        by
         <span ng-if="vm.employe.user" ng-bind="vm.employe.user.displayName"></span>
         <span ng-if="!vm.employe.user">Deleted User</span>
      </em>
     </small>
     <p class="lead" ng-bind="employe.lastname"></p>
     <p class="lead" ng-bind="employe.firstname"></p>
     <p class="lead" ng-bind="employe.email"></p>
      <p class="lead" ng-bind="employe.team"></p>
      <p class="lead" ng-bind="employe.contract"></p>
      <p class="lead" ng-bind="employe.formation"></p>
    </section>

And here The message returned in my terminal:

      GET / api / employees / 594ce3877b8099601f4cffda 304 9.132 ms - -

And the one returned in the browser:
     [Resource, $ promise: Promise, $ resolved: true]
      Resource
       created: "2017-06-23T13: 37: 00.037Z"
       name: "Team 1"
       site: "La Coulée Verte"
       _id: "594cd9dd418f52f0d3b95e45"

**Comment by mleanos** [comment]
Try putting `isArray: true` in your Resource Teams `$resource` configuration.

```javascript
$resource('/api/teams', null, {
    'get': {
      method: 'GET',
      isArray: true
    }
  })
```

You could just use the `.query()` method of the `$resource`, which I believe defaults to expecting an Array. I also recommend mimicking the Articles client-side service implementation rather than have `$resource` service's used directly within your controllers.

To be certain I understand your issue, which service call is throwing this error? The console log for `/api/employees/:id` is different from the Resource you listed at the end of your post.

**Comment by Abdou00** [comment]
This is supposed to call the employee service and display data about the employee (name, first name, email, team, etc ...).

**Comment by mleanos** [comment]
Could you report back on if my suggested fix solves your problem?

Also, it would be helpful to know which of your client-side service calls is gwnerating this error.

**Comment by Abdou00** [comment]
I tried your suggestion but it did not solve the mistake. The error is generated by the team service call.

**Comment by Abdou00** [comment]
The problem is solved it was the query that it was missing. Thank you very much for your help and your availability :)
