### ISSUE TITLE
bootstrap theme css link not being loaded with other css

### ISSUE THREAD

**Issue by smokeyblues** [meanjs/mean#1806]
I added a custom bootstrap theme [readable] to my project that loads with other css files in the for loop on line 35 of the layout.server.view.html file when served locally but once I tried running it on my cloud server, the source code shows that my theme isn't included but all the other ones are. 

The theme's is living in the bootstrap/dist/css directory next to regular bootstrap and is included in the overrides.bootstrap.main array in the bower.json file. 

I'm having trouble figuring out how the bootstrap main css file is being included with all the others and how I might be able to throw my theme in there with it without hard coding it to the layout view.

Any help would be greatly appreciated!

**Comment by billyjov** [comment]
@smokeyblues I don't really understand what the issue is. But i think you can solve it by inserting or importing your dependencies here .

[config assets](https://github.com/meanjs/mean/blob/master/config/assets/default.js#L12)

**Comment by smokeyblues** [comment]
Thanks Billy. I'm still learning to speak developer lol. I have my dependency included there. That's how it is working locally. There seems to be some disconnect when I push it up to my droplet even though everything else is working. 

It looks like the public folder isn't including the lib directory in my repo that might be the problem. 

Yep! I just added the files to the server and that solved the problem.
