### ISSUE TITLE
where to put JS  files and API's DCNs for other modules like articles?

### ISSUE THREAD

**Issue by aniu** [meanjs/mean#1810]
I am new to meanjs and have a simple question. I create a new module for showing buildings on google maps on client htmls, but where to include the google map API's DCN and other javascript files? Thanks a lot!

**Comment by sagarora77** [comment]
You need to add your dependencies in config/assets/default.js for module-level dependencies. 
Or you can add project wide dependencies in core/client/app/config.js as **applicationModuleVendorDependencies**

Hope you find it helpful...

**Comment by simison** [comment]
@aniu feel free to re-open if you have further questions about this!
