### ISSUE TITLE
fail to get jason message req.body 

### ISSUE THREAD

**Issue by IEEE-z** [meanjs/mean#1823]
I wrote some code to accept messages sent by the client like this：
`app.route('/api/tk1/addcar').post(users.addcar);

module.exports.addcar= function(req,res) {
  console.log(req.body);
  res.json('ok');
}`
I use the ARC as a client and send a jason![2017-07-18 21 30 00](https://user-images.githubusercontent.com/26320443/28319607-ef73c82e-6c00-11e7-99e9-14606f618d67.png)
But the result is empty
![2017-07-18 21 38 40](https://user-images.githubusercontent.com/26320443/28319809-8497b564-6c01-11e7-9b14-8a556db8b9a3.png)
What's the problem of it?

**Comment by mleanos** [comment]
I don't know how ARC works, but the Raw Payload doesn't look like properly formatted JSON to me. 

Try
```javascript
{
  "name": "some name",
  "message": "hello message"
}
```

**Comment by lirantal** [comment]
your json response is also invalid: `res.json('ok')`
