### ISSUE TITLE
Socket.io private chat

### ISSUE THREAD

**Issue by fuzzzycoder** [meanjs/mean#1825]
I'm working private room chat. I have already done it with different structure. In boilerplate I'm unable do it. Can please anyone help me out by showing a simple private chat example?

**Comment by mleanos** [comment]
You can put each user into their own Socket room so you can send to an individual user. This is how I've done it in the past, not sure if it's the best way to handle this but it works pretty well.

To do this you will have to slightly modify the [Socket.IO config](https://github.com/meanjs/mean/blob/master/config/lib/socket.io.js#L98) here. Upon User authentication with the Socket.IO server, you can add a user to a room with: 

```javascript
// Create a room, and add the user who will be the only in that room
// Use a unique field such as username for the room name.
socket.join(socket.request.user.username, function (err) {
  // callback logic
});
```

And to send to a specific user (client) from a server-side Socket handler:
```javascript
// Send Socket event to specific room (username)
io.to(user.username).emit('some-event-name', data);
```

A while back I added a branch on my fork to demonstrate this with Socket.IO. See [this commit to that branch](https://github.com/mleanos/mean/commit/64c9bf42b985f87c94769cd4c09ed528b467d704) for a more detailed example. The branch is not up to date with the upstream *master* branch, so there may be slight differences in the code.

**Comment by simison** [comment]
I'll close this, @fuzzzycoder feel free to open if you still have questions about this!
