### ISSUE TITLE
Live meanjs link & admin role

### ISSUE THREAD

**Issue by adrivanrex** [meanjs/mean#1829]
Hello, 

can you setup a live meanjs link? and also I want to know how do I set the user as admin. 
Since, I want to create,delete articles.

**Comment by simison** [comment]
You can make any user admin by modifying user directly in MongoDB, just add `admin` to `roles` array:
```js
{
    ...
    "roles" : [ 
        "user", 
        "admin"
    ],
    ...
}
```

You can use [command line](https://docs.mongodb.com/manual/reference/mongo-shell/) or [Robomongo](https://robomongo.org/) to access your database.

Not sure what you mean by "_setup a live meanjs link_"?
