### ISSUE TITLE
Admin setup

### ISSUE THREAD

**Issue by divyashobana19** [meanjs/mean#1831]
Development site is working properly in localhost:3000.
Admin files are there in mean.zip folder.Is admin site is working?
If working,How i can view admin in website?

**Comment by simison** [comment]
You can access admin paths by authenticating with user which has `admin` in their `roles` array at the database.

At the header there should be "admin" section as configured here: https://github.com/meanjs/mean/blob/master/modules/articles/client/config/articles-admin.client.config.js

and from route configs for both backend and frontend you can see actual admin routes for the client and for the API.

**Comment by divyashobana19** [comment]
Like localhost:3000 for dev site,is there any url for admin?

**Comment by simison** [comment]
@divyashobana19 

1. modify your user after signing up, note roles:
```js
{
    ...
    "roles" : [ 
        "user", 
        "admin"
    ],
    ...
}
```

You can use [command line](https://docs.mongodb.com/manual/reference/mongo-shell/) or [Robomongo](https://robomongo.org/) to access your database.

2. Refresh the page while logged in and you'll see "admin" menu:
![image](https://user-images.githubusercontent.com/87168/28822072-8e49013e-76c0-11e7-9599-e469d2d9c1c0.png)

Or directly via routes:
- http://localhost:3000/admin/users
- http://localhost:3000/admin/articles

**Comment by divyashobana19** [comment]
In which file i want to modify roles?
Can you explain briefly.

**Comment by simison** [comment]
@divyashobana19 are you familiar with MongoDB? Your users and other content is stored in MongoDB. I recommend you familiarise yourself first with Mongo and you'll understand what I'm saying then.

https://docs.mongodb.com/manual/introduction/

**Comment by divyashobana19** [comment]
I know to edit in mongoDb,is there anything like roles in register page.so that we can edit in register page rather than using admin.

**Comment by simison** [comment]
Do you mean signup controller?  https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.authentication.server.controller.js#L21-L50

You can also play around with defaults for the model: https://github.com/meanjs/mean/blob/master/modules/users/server/models/user.server.model.js#L106-L113

**Comment by sabousha** [comment]
No.. you cannot register an admin.  You can only generate an "admin" user through Seed or by modifying the database as @simison said.
