### ISSUE TITLE
Forgot your password issue

### ISSUE THREAD

**Issue by plmvijay** [meanjs/mean#1833]
it throwing  Error: **No account with that username has been found** even when i gave correct email id.can u please tell me what is the issue and how can i solve that

**Comment by simison** [comment]
It seems to accept only username, not email.

https://github.com/meanjs/mean/blob/master/modules/users/server/controllers/users/users.password.server.controller.js#L33

**Comment by simison** [comment]
If you wanna do a quick fix in your app, you can just modify those lines to something like this:

```js
      var userHandle = req.body.username.toString().toLowerCase();

      User.findOne({
        $or: [
          { username: userHandle },
          { email: userHandle }
        ]
      }
```

https://github.com/Trustroots/trustroots/blob/master/modules/users/server/controllers/users/users.password.server.controller.js#L42-L48

**Comment by plmvijay** [comment]
hi thanks for your reply, but even after modification still the same issue (No account with that username has been found) exits

**Comment by simison** [comment]
Does it work with the username?

Could you confirm that username and email are really those in the database as well?

Make sure you're looking at the right database (`mean-development` if you're running in dev)

**Comment by plmvijay** [comment]
Hi if i gave username means it throws  **Error: Failure sending email,**
if i gave email id means **Error: No account with that username has been found**,
i checked both given username and email available in database

**Comment by simison** [comment]
Email error is just due `smtpTransport.sendMail()` not being able to send emails, so you'll have to fix that separately. 

You can do so by copying this block to your local env config: https://github.com/meanjs/mean/blob/master/config/env/development.js#L59-L68

You can use [Sparkpost](https://www.sparkpost.com/) to send your emails or personally I prefer running [Maildev](http://danfarrelly.nyc/MailDev/) for development.

**Comment by simison** [comment]
Someone else had the same issue before: https://github.com/meanjs/mean/issues/1679

**Comment by plmvijay** [comment]
Error: Failure sending email, i will check your given solution, but i need to give directly email because i no more gonna use username

**Comment by simison** [comment]
This might be helpful: https://nodemailer.com/smtp/ (Nodemailer currently in Mean.js might be older version though, I would double check that).

If you don't need username support, you can just change `username` to `email` everywhere, but remember that if users sign up using FB or similar, you might need to have something to handle those situations.

**Comment by plmvijay** [comment]
i not gonna use social login so only am asking email instead of username

**Comment by simison** [comment]
@plmvijay I made a PR for this: https://github.com/meanjs/mean/pull/1834 — feel free to test it out and lemme know if it works for you.

**Comment by sabousha** [comment]
Nice! @simison
