### ISSUE TITLE
server issue

### ISSUE THREAD

**Issue by plmvijay** [meanjs/mean#1835]
i changed js files in server and run the website but the changes not impacted .can anyone please tell which command i need to run to impact the changes in website?

**Comment by simison** [comment]
You need to tell more than that about your setup.

- Is this in dev or prod mode?
- If it's in production, how do you serve your app? Using some app server like forever, pm2 or similar?
- What did you exactly do, what did you expect to happen and what happened?

**Comment by plmvijay** [comment]
first of all how can i identify mode?
am running my application in linux ,am directly installed from gitup only.
i removed username field in signup.client.view.html and user.server.model.js file but still i get please fill username field error

**Comment by simison** [comment]
![image](https://user-images.githubusercontent.com/87168/28875313-d5b67c80-779d-11e7-8b4c-ed3c17c5b9b0.png)

Environment: development/production

**Comment by plmvijay** [comment]
in which file i can see this

**Comment by simison** [comment]
@plmvijay Did you get this solved?

**Comment by plmvijay** [comment]
yes

**Comment by simison** [comment]
What was the issue then? :-)
