### ISSUE TITLE
How to use socket.io in meanjs?

### ISSUE THREAD

**Issue by zhouzhou-96** [meanjs/mean#1836]
I want to use meanjs chat with Angular2 client via socket.io.I add the code in /controllers/socket.test.js:
```
var http = require('http');

var fs = require('fs');

// Loading the index file . html displayed to the client
var server = http.createServer(function(req, res) {
    fs.readFile('./index.html', 'utf-8', function(error, content) {
        res.writeHead(200, {"Content-Type": "text/html"});
        res.end(content);
    });
});

// Loading socket.io
var io = require('socket.io').listen(server);

// When a client connects, we note it in the console
io.sockets.on('connection', function (socket) {
    console.log('A client is connected!');
});

server.listen(4200);
```

But it seems that the port has been used by Angular2 client:
![2017-08-04 14 18 44](https://user-images.githubusercontent.com/26320443/28956569-404ad194-7920-11e7-9c55-830f3ee2a4dc.png)

How can I solve it?Thank you.

**Comment by simison** [comment]
`EADDRINUSE :::4200` error means that you already have something in port 4200 and your `server.listen(4200)` won't work. Maybe you have the app running already in another terminal?

Are you sure this question is relevant to this repository, as we don't have Angular2 yet?

**Comment by zhouzhou-96** [comment]
@simison Thank you!I think I got it,I let server.listen(4000) and it works.The port 4200 is the Angular client port.
