### ISSUE TITLE
A issues of socket.io in mean.js

### ISSUE THREAD

**Issue by Huang9495** [meanjs/mean#1838]
When I open the mean.js through 'npm start' or 'node server.js',the initiate of server is OK but the socket.io seems occur issue because the something that I set up doesn't take place when I socket.io have connected. 
I edit the code of client is OK, because I send the data from my client to server from another computer. the code of my server is same to my workmate's code of server.So I what the reason is to the issue and how to resolve it ?

### **My operation environment :**
Ubuntu 14.04;node:6.11.1;npm:3.10.10;mongodb:3.0.15;bower:1.8.0;chrome: google;

## **the error prompt of google:**
zone.js:2622 GET http://localhost:4000/socket.io/?EIO=3&transport=polling&t=LtFLi8h net::ERR_CONNECTION_REFUSED

## **#**## My code of server:****
```js
var express = require('express');
var app = express();
var server = require('http').createServer(app);
var io = require('socket.io').listen(server);
var port = process.env.PORT || 4000;
server.listen(4000, function() {console.log('Server listening at port %d');});
io.on('connection', function(socket) {
  console.log('hahah');
  socket.on('message', function(data) {
    console.log('gogo');
    console.log(data);
  });
});
```
## **#**## My part code of client:****
const config: SocketIoConfig = {url:'http://localhost:4000',options:{}};

**Comment by simison** [comment]
Are you using meanjs and if so, which version? Your code doesn't look like our socket.io implementation:

https://github.com/meanjs/mean/blob/dc880eb5a77168099b214f1733ed0d6d23ff7093/config/lib/socket.io.js

If this isn't meanjs specific, I'd encourage you to open this at Stackoverflow or similar.

**Comment by Huang9495** [comment]
Hi @simison  I clone the mean.js through "git clone https://github.com/meanjs/mean.git meanjs", now I can initiate the socket.io but I need to initiate the socket.io through node example.js(name of file) rather than node server.js and I need to do it in the subpath of the example.js. I don't know why I need to do it so?

**Comment by simison** [comment]
@Huang9495 I don't follow — could you give exact commands you're doing?

**Comment by Huang9495** [comment]
@simison  I do a test that initiate mean.js through commands is node server.js this afternoon successful. And I can transfer data between client and server through socket.io ,because I put my code of socket.io in the file named server.js in the mean.js .So when I initiate the mean.js ,the socke.io is initiated at the same time. I think I have resolve this issue ,can you approve of me ? An  my terminal of mean.js is this when I start it through node server.js

**Comment by Huang9495** [comment]
![screenshot from 2017-08-12 20 53 39](https://user-images.githubusercontent.com/26674689/29240881-74a820aa-7fa0-11e7-95b7-bab2cb3b4d94.png)

**Comment by simison** [comment]
Glad you got it sorted out. :-)

**Comment by Huang9495** [comment]
HaHa! @simison  I very happy to get your help ! Thank you very much!
