### ISSUE TITLE
Has anybody implemented signin redirection to "previous page"?

### ISSUE THREAD

**Issue by igorauad** [meanjs/mean#185]
In case anyone implemented a scheme for redirecting the user to his previous state after sign-in , would it be possible to share?

I was thinking I could some how add the previous state information to $state (as below) and inform this to the backend, which, in turn, would have to inform back after successful authentication. Perhaps this is more work than necessary. Thoughts? 

```javascript
app.run(function ($rootScope, $state) {
  $rootScope.$on('$stateChangeSuccess', function (event, toState, toParams, fromState) {
    $state.previous = fromState;
  });
});
```

**Comment by Uter1007** [comment]
Are there any updates to this feature ? Is it possible to have it already in the current master branch ? Is it possible to use: https://github.com/jaredhanson/connect-ensure-login ? Sorry for my n00b questions but I am a total Javascript rookie ;)

**Comment by lirantal** [comment]
closed, implemented in https://github.com/meanjs/mean/pull/487
