### ISSUE TITLE
client.service.js files URL issue

### ISSUE THREAD

**Issue by a3aakash** [meanjs/mean#1861]
In the previous versions it was not creating issue. after update in *.client.service.js files url is not hiitng correctly to the server by which error comes "Cannot post to <url>". When I place '/' manually before the url start it started working fine. Please check and update me for the same ASAP.

**Comment by mleanos** [comment]
Can you share your client.service file? How did you "update" your project?

**Comment by a3aakash** [comment]
```
(function () {
  'use strict';

  angular
    .module('blogs')
    .factory('BlogsService', BlogsService);

  BlogsService.$inject = ['$resource'];

  function BlogsService($resource) {
    return $resource('/api/blogs/:blogId', {
      blogId: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }
}());
```

**Comment by a3aakash** [comment]
this is my code where is place '/' at the beginning in $resource url

**Comment by mleanos** [comment]
So you added the "/" and it fixed the issue? If so, then you just need to add that to your other client-side services.

Did you use the MEAN.js Generator to create this new Blogs module?

**Comment by a3aakash** [comment]
Yes I know to add '/' to the URL in these type of files.. but why should I add this manually. Then whats the use of yeoman generator in mean.js. Yes I am using the generator for building the modules...

**Comment by mleanos** [comment]
The MEAN.js Generator project just happens to be out-of-sync from the upstream MEAN.js code-base. It's unfortunate, and we hope to get that project updated again in the near future.

I'm going to close this now, but if you have any further problems or comments feel free to add them here.
