### ISSUE TITLE
warnings and errors when run npm install on Windows 10 (64-bit)

### ISSUE THREAD

**Issue by Rocking80** [meanjs/mean#1862]
Hi,

I got these warnings and errors when run `npm install` on Windows 10 (64-bit).  Is this normal or are we going to fix this? Thanks.

<pre>
C:\src\meanjs> npm install

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint@^2.2.0 but none was installed.
npm WARN eslint-config-airbnb@6.0.2 requires a peer of eslint-plugin-react@^4.0.0 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! node-sass@4.5.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.5.3 postinstall script 'node scripts/build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-sass
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\meanjs\npm-debug.log
</pre>

**Comment by Rocking80** [comment]
node-sass error is removed. The warnings are still there.

**Comment by sabousha** [comment]
I am also running Win10 64Bit and I did a clean install including NPM a week ago with no issues

**Comment by AmruthPillai** [comment]
I was getting similar errors.
Fixed it by first running:
`npm install node-sass --msvs_version=2015`

and then:
`npm install`
