### ISSUE TITLE
Dependency inject in Controller doesn't work

### ISSUE THREAD

**Issue by lriquelme** [meanjs/mean#1889]
Hi, i have this problem...

In my module config 'financiadoras', have inject angularMask (for example) and still working, no errors..
`(function (app) {
  'use strict';

  app.registerModule('financiadoras', ['core']);// The core module is required for special route handling; 
  app.registerModule('financiadoras.admin', ['core.admin', 'angularMask']);
...
}(ApplicationConfiguration));
`

The file is readable in browser http://.../lib/angular-input-mask/src/angular-simple-mask.js 
But, when inject in the controller 

`
(function () {
  'use strict';

  angular
    .module('financiadoras.admin')
    .controller('TasasAdminController', TasasAdminController);

  TasasAdminController.$inject = [... , 'angularMask']
`

I got an error **[$injector:unpr] Unknown provider: angularMaskProvider**
The same problem with cleave.js.

What is wrong? In old version (2016) this work fine, not now

Sorry for my english,

Thanks!

**Comment by mleanos** [comment]
Have you tried adding `angularMask` to the Core angular [app config](https://github.com/meanjs/mean/blob/master/modules/core/client/app/config.js#L9)'s list of dependencies? You shouldn't need to register Angular Mask as a module with your Angular app.

If that doesn't help, maybe the Angular Mask module that's exported from the library has a different name? e.g. `angular-mask`, or something similar.

**Comment by mleanos** [comment]
@lriquelme Any update on this?

I'm going to close this issues, since it's not really MEAN.js specific. If you still need help with this, feel free to come back and ask.
