### ISSUE TITLE
Running with issue while running "npm start"

### ISSUE THREAD

**Issue by deepakparamesh** [meanjs/mean#1924]
hi, 
    I am trying to get the basic boiler plate of the meanjs. but finding an issue after doing all the below steps .
1. Installed all the prerequisite 
      npm install -g bower
      npm install -g grunt-cli
      npm install -g yo
      npm install -g generator-meanjs@0.1.12 
   - all were installed properly

 2. Ran the command  "yo meanjs --skip-install"
    - the project folders got scaffold properly in my directory. 

3. Ran the command  "npm install" 
    - I hope, all my node modules got installed. 

4. Then at last to get the boilerplate screen, I ran "npm start" on my CLI 
    - but all I got is this ..
    
![meanjs_issue](https://user-images.githubusercontent.com/12880320/33205805-4055f73e-d12e-11e7-87c0-63b4861ecadb.PNG)

Please help me to fix this issue. I do not know the reason of why this issue is arriving. 
Thank you in advance.

**Comment by PierreBrisorgueil** [comment]
hello, you are on an old version of meanjs, please don"t use yo generator, juste clone this repo
