### ISSUE TITLE
Message about 'no articles yet' not showing up.

### ISSUE THREAD

**Issue by AKA-AK** [meanjs/mean#1930]
In the Admin - 'manage articles' view, if there are no articles yet there's supposed to be an alert

> No articles yet, why don't you create one?

However it's not showing up.

I believe in line 23 instead of: 

> articles.$resolved

It should be: 

> vm.articles.$resolved

**Comment by sabousha** [comment]
yes :) if you wish, you can make the change, test it, and if successful, submit a pull request :)
