### ISSUE TITLE
Heroku deploy minified public/dist

### ISSUE THREAD

**Issue by ykyp** [meanjs/mean#1937]
Hi,

I have successfully deployed the meanjs app to heroku but even when setting NODE_ENV = production I can still see all the unminified sources been deployed. How can I deploy only what is inside public/dist?

I figured is still running development environment as I can see requests to livereload. Any advice on how to switch to production environment would be much appreciated,

Thanks

**Comment by PierreBrisorgueil** [comment]
Hi, I never work with Heroku, but to deploy in production mode, just make a 'gulp prod' and start the server with NODE_ENV=production node server.js, and it will be ok :)

For the files deployed, the totally unminified will be always deployed, it is not a problem, in production only the dist and the templating system will be used for the client side :)

**Comment by ykyp** [comment]
Thanks a lot, it's working now
