### ISSUE TITLE
Change Client/Admin to Client Settings with "admin" role.

### ISSUE THREAD

**Issue by acidicchip** [meanjs/mean#1938]
Your system is confusing. If I want to add another role to administer or moderate settings, it's confusing to call it "admin". You either need a moderator role in your schema or you need to change it to "settings" all around instead of mixing "admin" and "settings" together.

**Comment by PierreBrisorgueil** [comment]
Hy, 

This is a starter pack, feel free to edit like you want, and add a moderator if it's needed. I did it on my side. Articles & Users admins parts are just example, not a definitive solution. 

I'm not sure that adding additional roles in a technical stack is the goal.
