### ISSUE TITLE
MeanJS App is not starting using node v8

### ISSUE THREAD

**Issue by hazemhagrass** [meanjs/mean#1939]
Hi,
My meanjs app stopped working directly after I upgraded my node version. I removed all node_modules/ folder then run `npm install` without any luck! Any Help!
<img width="541" alt="screen shot 2017-12-19 at 3 35 12 pm" src="https://user-images.githubusercontent.com/3625423/34159536-4df2f650-e4d2-11e7-8c0c-1bfa67ba5346.png">
<img width="1266" alt="screen shot 2017-12-19 at 3 35 18 pm" src="https://user-images.githubusercontent.com/3625423/34159537-4e137f06-e4d2-11e7-807f-906e5dde8c90.png">
<img width="1274" alt="screen shot 2017-12-19 at 3 35 35 pm" src="https://user-images.githubusercontent.com/3625423/34159538-4e33ca90-e4d2-11e7-9811-9f2632c55625.png">

**Comment by PierreBrisorgueil** [comment]
hello, https://travis-ci.org/meanjs/mean

everything is ok on node v8+

Please try baby switch from grunt to gulp 
it will be ok :)

**Comment by hazemhagrass** [comment]
It's working now, thanks
