### ISSUE TITLE
User data's are not getting after refreshed the setting page?

### ISSUE THREAD

**Issue by Maniselvam006** [meanjs/mean#1951]
Hi guys I am using MEAN stack in my application with AngularJS as my front-end. 
after signup into the portal, in setting profile page `user data's are fetching fine and displaying perfectly`, while `refreshed the page user information and data's are not showing` , the input fields are displaying empty . please look the following screen shots.
![stting page](https://user-images.githubusercontent.com/24452208/37092293-52c120fc-2231-11e8-8d4a-6c4b0bdbe4ec.PNG)

* After refreshed the edit-profile page:-

![after refresh](https://user-images.githubusercontent.com/24452208/37092298-55815faa-2231-11e8-9006-301134081407.PNG)

* only three fields data's s displaying like ` first name ,last name and email` we expecting for all fileds data's.

* **for example:-**
 *  the same issues are arrived in admin edit page like `edit-user.client.view.html`, so i have added some fields like :-
 `user.religion = req.body.religion;
  user.location = req.body.location;` in `admin.server.ontroller.js` the problem solved and after refreshed the page all data's are displayed perfectly.
* But we exactly don't know which server page need to add these fields `user.religion = req.body.religion;
  user.location = req.body.location;` and why the user data's are not showing after refreshed the edit-profile page please check and help us. thanks!!!!

**Comment by umairch** [comment]
Boy can you please share your code? So i can help you more appropriately.

**Comment by umairch** [comment]
I think you are not passing ID in URL mean in req.query that's  why when you refresh your browser it couldn't find id to fetch query, try to pass id in URL.

**Comment by umairch** [comment]
you're getting no data after refreshing? or getting incomplete content.?

**Comment by umairch** [comment]
Share you server controller, Client controller of particular module.

**Comment by Maniselvam006** [comment]
Thanks for your comment, please look at my second screen shots, only `first name, last name and email` only showing other field data's are not displaying... 
**In users module:-**
*  `user.server.model.js`  i have added like
` location: {
    type: String,
    required: 'Location is Required',
    trim: true
  }, `
`religion: {
    type: String,
    required: 'Religion is Required',
    trim: true
  },`

then in my `edit-profile.client.view.html`:-
* I have added like:-
` <div class="col-md-6 form-group" show-errors>
          <label for="religion">Religion</label>
          <input type="text" id="religion" name="religion" class="form-control" ng-model="vm.user.religion" placeholder="Religion" required>
          <div ng-messages="vm.userForm.religion.$error" role="alert">
            <p class="help-block error-text" ng-message="required">Religion is required.</p>
          </div>
        </div>

        <div class="col-md-6 form-group" show-errors>
          <label for="location">Location</label>
          <input type="text" id="location" name="location" class="form-control" ng-model="vm.user.location" placeholder="Location" required>
          <div ng-messages="vm.userForm.location.$error" role="alert">
            <p class="help-block error-text" ng-message="required">Location is required.</p>
          </div>
        </div>`

* Please let us know what i have missed it? and how to solve this issue.

**Comment by umairch** [comment]
can you please share your whole module in rar file ?so i can check or if you have online git repo please share, I have to see your client route, server controller , client controller and serve route of particular module.

**Comment by umairch** [comment]
can you please call me at umairsch 
at skype and share you r screen

**Comment by Maniselvam006** [comment]
thanks for sharing your skype ID will do call but not right now... have you found the solution?

**Comment by umairch** [comment]
what is exact page name where you're showing this data.

**Comment by Maniselvam006** [comment]
the exact page path is :- users-client-views-settings- `edit-profile.client.view.html` 
in this page only we are trying to display user information

**Comment by Maniselvam006** [comment]
@umairch any solutions?

**Comment by Maniselvam006** [comment]
@umairch any solutions?

**Comment by umairch** [comment]
@Maniselvam006 you are still stuck on this ?

**Comment by umairch** [comment]
I told you to share your screen or PR So I can help you accordingly.

**Comment by Maniselvam006** [comment]
@umairch thanks for your helping thoughts ... i solved the issue ... i just add needed model values in `core.server.controller.js` it's solved my issues thanks...keep in touch..

**Comment by Maniselvam006** [comment]
@umairch thanks for your helping thoughts ... i solved the issue ... i just add needed model values in `core.server.controller.js` it's solved my issues thanks...keep in touch..
