### ISSUE TITLE
"Unexpected request: GET .../.html" on Karma tests

### ISSUE THREAD

**Issue by igorauad** [meanjs/mean#198]
When trying to integrate tests into my project, an error in which the views (.html files) are requested happens when I call `$httpBackend.flush()` in each test. Something likes this:

```
Error: Unexpected request: GET public/modules/landing/views/landing-consumers.client.view.html
    No more request expected
```

This issue has been discussed within the UI-router group (see [https://github.com/angular-ui/ui-router/issues/212](https://github.com/angular-ui/ui-router/issues/212)). Did any of you had this and managed to solve?

**Comment by SrinivasNarayansetty** [comment]
Dear Potstickers ,
 I Have tried same  ode whatever u have mentioned in Karma Configuration file but i am not using any routing in my project .It is Showing an error Like this.Can You Help me in this


![screenshot from 2016-05-19 11-25-51](https://cloud.githubusercontent.com/assets/17430025/15383939/781011de-1db4-11e6-89e7-6a888059dbd4.png)

**Comment by Atul-sac** [comment]
Hi,
I am using $routeProvider and i have started facing same issue from 10 days back. same test cases were working before approx 10 days, but when i did fresh installation of all dependencies mentioned in package.json. my all test cases started failing which are dependent on $http service call and also which are based on $watch (basically where $apply() is called manually). 
I am getting basically these two types of error - 

1. Error: Unexpected request: GET templates/home.html No more request expected
2. Error: Unexpected request: GET API_URL No more request expected

It seems that few wrong commits has been made recently on KARMA/JASMINE, which are causing these issues, as mine old code base is working fine, only after installing fresh dependencies these test cases are failing now.

I am using below dependencies - 

"devDependencies": {
    "angular": "^1.6.5",
    "angular-mocks": "^1.6.5",
    "angular-route": "^1.6.5",
    "browserify-istanbul": "^2.0.0",
    "grunt": "^1.0.1",
    "grunt-browserify": "^5.0.0",
    "grunt-contrib-connect": "^1.0.2",
    "grunt-contrib-copy": "^1.0.0",
    "grunt-contrib-jshint": "^1.1.0",
    "grunt-karma": "^2.0.0",
    "istanbul": "^0.4.5",
    "jasmine-core": "^2.6.4",
    "karma": "^1.7.0",
    "karma-bro": "^0.11.1",
    "karma-browserify": "^5.1.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.0",
    "karma-phantomjs-launcher": "^1.0.4"
  }

Please help me out. 
Thanks!
