### ISSUE TITLE
Some modules aren't working in production mode

### ISSUE THREAD

**Issue by ledouxm** [meanjs/mean#1986]
Hi, I created a web application using MeanJS and everything worked fine but then I developped some additional modules that are working well in development mode but seem not to be loaded in production mode. I have no idea why...

I'm using node v7.2.0 and meanjs v0.4.2.

**Comment by umairsch** [comment]
@ledouxm Please elaborate what problem you're facing specifically, any error at client side or server side ?

**Comment by ledouxm** [comment]
There is no error neither client nor server side. Those modules appear correctly in the "topbar" menu and are working in development mode.
Every other module is working in production mode but only those don't appear...

**Comment by umairch** [comment]
@ledouxm  have you build your project before running on Production mode, Using Command: grunt build

**Comment by sabousha** [comment]
grunt? you mean "gulp build"?

**Comment by umairch** [comment]
in 0.4.2 you can use both grunt and gulp, Use grunt build and then grunt prod to run on production mode.

**Comment by ledouxm** [comment]
thanks for your answers, after a few days of trying, I found out that ng-annotate were not working because of one function which had a parameter with a default value, and ng-annotate doesn't work when ES6 is used.

Problem solved.
