### ISSUE TITLE
Error-first callbacks: Line 169 on 'users.authentication.server.controller.js'

### ISSUE THREAD

**Issue by igorauad** [meanjs/mean#201]
Regarding line 169 in 'users.authentication.server.controller.js':

```
return done(new Error('User is already connected using this provider'), user);
```

does it make a difference to pass the `user` as a second argument? As I am seeing here, when an error is passed, the other arguments are ignored. 

I'm asking this because I wanted to pass `user` and `redirectUrl` even when errors occur, so that I can redirect the user to the right page. I also wanted to send the error back to the user, so the error should be preserved.

**Comment by szchenghuang** [comment]
It seems the optional 3rd argument `redirectURL` takes effect only if `done` is invoked with the 1rd argument of `null`, 2nd of `false`.

Based on that, I am also wondering if that argument in Line95 same file would always be `undefined`.
```
return res.redirect(redirectURL || '/');
```
