### ISSUE TITLE
Cannot use new Angular service properly

### ISSUE THREAD

**Issue by skyserpent** [meanjs/mean#203]
When I get a fresh installation of MEAN, I use 'npm install & bower install'. Everything works great up to that point, I even see the homepage when I connect through the browser. However, when I generate an Angular service with yo, I try to inject that service name into the controller like (where 'Friends' is the factory service for my core module):

angular.module('core').controller('HomeController', ['$scope', 'Authentication', 'Friends',
    function($scope, Authentication, Friends) {   ........

Upon doing this, I get this error:
Error: [$injector:unpr] Unknown provider: FriendsProvider <- Friends

Would like any help please.

**Comment by kikoseijo** [comment]
Im facing same problem, using:
yo meanjs:angular-service

After i try to use in the controller throws an error:
Error: [$injector:unpr] Unknown provider:
