### ISSUE TITLE
Suggestion: Removing unused CSS

### ISSUE THREAD

**Issue by shubhamVerma** [meanjs/mean#221]
Hey guys, I was checking out the sample app on Heroku. I ran an audit with the Chrome dev tools. 

![image](https://cloud.githubusercontent.com/assets/2177282/4693951/7cac5030-57b4-11e4-9fd2-e09028d80f89.png)

I was wondering if we can add the [grunt-uncss](https://github.com/addyosmani/grunt-uncss) plugin for removing unused css.

Here's the link to the article - http://addyosmani.com/blog/removing-unused-css/

Cheers,
Shubham

**Comment by ilanbiala** [comment]
@shubhamVerma the 0.4.0 branch has Gulp. The only issue with using {{build tool here}}-uncss is that some classes may be applied through directive JS, so how can the tool really know. And some might not even be in code, like Angular-bootstrap requires their JS and bootstrap's CSS. How will it not remove bootstrap's CSS?

**Comment by codydaig** [comment]
@shubhamVerma Any update on this?

**Comment by lirantal** [comment]
well there's still unused CSS, but that's obvious, because we are including for example bootstrap.css and the MEAN.JS project isn't about implementing every piece of that.

So that's not necessarily a defect, but rather we should look into using grunt-uncss, possibly.

**Comment by lirantal** [comment]
So @codydaig are we going for grunt-uncss or puritycss?

**Comment by codydaig** [comment]
I'm unfamiliar with grunt-uncss. Personally, I'd pick purifycss. I submitted a new PR against master #819. It's open for discussion.

**Comment by lirantal** [comment]
Quite old of a thread, closing it and anyone is welcome to try and introduce postcss + uncss for this feature.
