### ISSUE TITLE
Best practice to publish content to a CDN (CloudFronts)

### ISSUE THREAD

**Issue by gonzalodiaz** [meanjs/mean#262]
Hello All. I been working with this excellent boilerplate for a while. Currently I have an application on production (beta) and I'm trying to sync the public content with a CDN. 

I'm having really hard time to accomplish this due to the structure of mean.js.

Have you ever tried to do so? What would be the best (or at least the working...) way to sync the static files on the CDN?.

Thanks

**Comment by igorauad** [comment]
Hi @gonzalodiaz . Please, let me know if that problem you had is the same as mine and whether you can help me.

I'm willing to have a way of dynamically changing the image URLs to the CDN-hosted ones in the `production` environment, such that I can keep the local paths in `development` and don't have to rely on fetching them from the CDN. I also don't want to maintain two different versions of the code, one for `production` and one for `development`. Was that your issue?

How to handle this? @lirantal , @ilanbiala

**Comment by ilanbiala** [comment]
Would changing the file paths in the arrays in the config to HTTP URLs not work?

**Comment by igorauad** [comment]
@ilanbiala just to make sure you understand, I'm talking about the images that are included in the front-end angular views.

**Comment by ilanbiala** [comment]
Can you give me a sample piece of code? I think I understand but I'm not positive.

**Comment by igorauad** [comment]
Suppose, for example, for one of the images in `authentication.client.view.html`:

Let's say:
```{html}
<img src="/modules/users/img/buttons/facebook.png">
```

If I, then, wanted to have the following without having to commit it:
```{html}
<img src="https://xxx.cloudfront.net/buttons/facebook.png">
```

**Comment by ilanbiala** [comment]
@igorauad are you familiar with Angular providers and constants? If so, depending on the size of the app, the solution I have in mind might work for you.

Create 2 constants: 
```js
.constant('devURLs', {image1URL: '/abc.png', image2URL: '/abc2.png'})
.constant('prodURLs', {image1URL: '//google.com/abc.png', image2URL: '//google.com/abc2.png'})
```

Create a provider:
```js
.provider('url', ['devURLs', 'prodURLs', function urlProvider(devURLs, prodURLs) {
  var isDevelopment = true; // change this for on-demand, or use an HTTP request to determine

  return {
    useDevelopment: function() {
      isDevelopment = true;
    },
    useProduction: function() {
      isDevelopment = false;
    },
    setEnvironment: function() {
      // $http to check the environment based on the server or maybe use the window.location.host
    },
    $get: [function() {
      return {
         getURL: function(urlTag) {
           return (isDevelopment ? devURLs : prodURLs)[urlTag];
         }
      };
    }];
}])
```

In the config:
```js
.config(function(urlProvider) {
  // either set the environment automatically or manually, we'll do manually for now
  urlProvider.useProduction();
});
```

In the run:
```js
.run(['$rootScope', 'urlProvider', function($rootScope, urlProvider) {
  $rootScope.urlProvider = urlProvider;
}]);
```

In the template:
```js
<img ng-src="urlProvider.getURL('home')">
```

Does that work for you? Some code might need small tweaks, but the backbone is there.

**Comment by igorauad** [comment]
Fantastic, @ilanbiala . I will check that soon. 

I'm partially familiar with this, but some details like how the `$get` function was defined I have to take a better look. 

I was thinking perhaps of keeping as constants just the prefix of the URL. For example, for production `xxx.cloudfront.net` while for development `/modules`. Do you think that would be better?

**Comment by ilanbiala** [comment]
That is basically what I'm doing, except with some sugar on top to decide whether to use the production or development URLs built-in. Either way should work, but it just depends on how big of an app you need. Mine could also easily incorporate responsive image URLs by doing `.getURL('home', '2x')` and having an object of URLs inside the URL constants object.

**Comment by igorauad** [comment]
Great, @ilanbiala . It works! Again, thank you very much.

**Comment by ilanbiala** [comment]
@igorauad great! Are you using that specific code directly or did you change something?

**Comment by igorauad** [comment]
I experimented it and got it to work with a small tweak. After a while, though, I changed it completely. The problem I had was with passing a provider into a config method.

I was attaching `urlProvider` to the `core` module. However, when calling a `angular.module('core').config` from a separate `core.client.config.js` file, `urlProvider` injection was failing. I'm not 100% sure, but I concluded the problem was with the order in which the declaration of the provider occurred with respect to the `config` method, as stated in [http://stackoverflow.com/questions/18350416/angular-error-unknown-provider-during-module-config](http://stackoverflow.com/questions/18350416/angular-error-unknown-provider-during-module-config).

I experiment a little more and realized I would need the environment for other stuff too (besides deciding image urls), like css styles containing image URLs. So I decided to simply return an `env` property within `ApplicationConfiguration` in the `config.js` file, the first thing that gets called. 

I basically did:
```{js}
var isDevelopment = (window.location.host === 'localhost:3000');
```

And changed the return to:
```{js}
return {
		applicationModuleName: applicationModuleName,
		applicationModuleVendorDependencies: applicationModuleVendorDependencies,
		registerModule: registerModule,
		html5Mode: html5Mode,
		env: isDevelopment ? 'development' : 'production'
	};
```
Now on `application.js` I have something like this:
```{js}
angular.module(ApplicationConfiguration.applicationModuleName).run(function($rootScope, $state) {
    $rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
        $state.previous = { state: fromState, params: fromParams };
        $rootScope.title = toState.title;
        $rootScope.style = toState.style;
        $rootScope.meta = toState.meta;
    });
    // Expose a prefix for the static image URLs
    $rootScope.imgURL =  ((ApplicationConfiguration.env === 'development') ? '/modules' : '//static.cabeado.com/img');
});
```

Then, my images are:
```{html}
<img ng-src="{{imgURL}}/users/img/buttons/facebook.png">
```

**Comment by ilanbiala** [comment]
If it works for you, it's good!
