### ISSUE TITLE
enhancement: i18n support

### ISSUE THREAD

**Issue by frederik** [meanjs/mean#27]
I currently have the need to localize a lot of core to display authentication information (in German).

To do that I added angular-translate and a local core.client.translation.js with some basics (these files should go into json files one day). I'll have to change all templates (especially the header to now use the translate directive a la {{ 'SIGNOUT' | translate }}).

Any ideas on how to incorporate i18n on the server side so we could re-use translations? I'd be willing to provide a fork with the changed the templates, German translations etc. I'd wait for 0.3 to ship though, and then fork the new development branch.

**Comment by afucher** [comment]
Hi, is there someone working on it?? So I could help??

**Comment by codydaig** [comment]
@afucher I'm assuming since this issue has been stale for over a year that it's all yours in you want to submit a PR.

**Comment by afucher** [comment]
@codydaig I'm starting to develop my first app, using MEAN stack. But, I need to use i18n.. so, if I do any implementation, I'll submit a PR..  :)

**Comment by lirantal** [comment]
@afucher great, I'm closing this issue and looking forward for your i18n PR :)

**Comment by pun4drunk** [comment]
Hi guys! Any progress with i18n?

**Comment by afucher** [comment]
@pun4drunk I'm not working with MEAN, so I don't have news....

**Comment by ilanbiala** [comment]
@pun4drunk we probably won't have i18n for 0.5.0, so we'll look into it for the next few versions.

**Comment by pun4drunk** [comment]
can I make a PR? :)
