### ISSUE TITLE
"Getting Started Before you begin make sure you have the yo scaffolding tool installed" bad link issue.

### ISSUE THREAD

**Issue by gavinheck** [meanjs/mean#270]
OBSERVED: 
via http://meanjs.org/generator.html

Selecting the 
yo scaffolding tool 
link (http://yeoman.io/generators.html) 
via the "Getting Started
Before you begin make sure you have the yo scaffolding tool installed"
 
section yields a "Sorry, but the page you were trying to view does not exist" message

EXPECTED: 
via http://meanjs.org/generator.html

Selecting the 
yo scaffolding tool 
link (http://yeoman.io/generators.html) 
via the "Getting Started
Before you begin make sure you have the yo scaffolding tool installed" 
section yields a 
Yeomans generator page

REPRO:
Go to 
via http://meanjs.org/generator.html

Selecting the 
yo scaffolding tool 
link (http://yeoman.io/generators.html) 

Fix
link should be
http://yeoman.io/generators/ 
instead of 
http://yeoman.io/generators.html

Best

J Gavin Heck, CSM, QA
gavinheckua@gmail.com

**Comment by ilanbiala** [comment]
@gavinheck it seems this was merged into the new generator on the master branch. Can you try it out and see if it is still incorrect?,

**Comment by gavinheck** [comment]
Still not working.

**Comment by ilanbiala** [comment]
@gavinheck can you submit a PR for [the line](https://github.com/meanjs/mean/blob/gh-pages/generator.html#L163) and I'll get it merged in.
