### ISSUE TITLE
Error when for 0.4.4. Refused to execute script from "*.js" because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by rojectsky** [meanjs/mean#283]
Hi Guys, was working good with 0.3.3. but got bellow error with 0.4.0.

Refused to execute script from 'http://localhost:3000/modules/core/controllers/header.client.controller.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
![meanjs0 4 error](https://cloud.githubusercontent.com/assets/9579989/5227098/d2c619aa-774a-11e4-8f3a-8f6aaab6fa58.png)

I am using window 8.1. node js v0.10.24.

**Comment by a-lucas** [comment]
Still got the same issue on linux

**Comment by codydaig** [comment]
@a-lucas This ticket is VERY old. Please open a new issue and describe in detail with error messages what is going on and how we can replicate it.

**Comment by limingyangit** [comment]
I have same issue,because I am not careful of losting the JS file.

**Comment by Bagma** [comment]
Still having the issue in 2018, please help

**Comment by travega** [comment]
I'm still having this issue in 2018 too! Please help me also :)
