### ISSUE TITLE
OAuth - not supported refresh case

### ISSUE THREAD

**Issue by sielay** [meanjs/mean#288]
Hi

From what I understand OAuth executed against some provider will not update user (will throw Exception that this provider is already used for this user). I think that is good, as far as you don't want to re-use same feature/redirections to refresh tokens.

If you agree with me I can prepare patch, that:
- checks, if provider `id` field is the same, in that case update provider data
- still throws error on mismatched `id` in the same provider
- works both with `user.providerData` and `user.additionalProvidersData`

Hope it makes sense

**Comment by NeverOddOrEven** [comment]
Closing this. Active issue can be found here: https://github.com/meanjs/mean/pull/343
