### ISSUE TITLE
Unable to start MEAN.js (0.4) on windows environment

### ISSUE THREAD

**Issue by chronotc** [meanjs/mean#291]
It appears that the getGlobbedPaths is not excluding the file path correctly on windows.

I have made a slight modification to 

```Javascript
var initGlobalConfigFolders = function(config, assets) {
    // Appending files
    config.folders = {
        server: {},
        client: {}
    };

    
    // Setting globbed client paths
    config.folders.client = getGlobbedPaths(path.join(process.cwd(), 'modules/*/client/'), process.cwd().replace(new RegExp(/\\/g),'/'));
};
```

which basically replaces \ with / so that getGlobbedPaths can process the arguments correctly.
Is this the correct approach?

original google group post: https://groups.google.com/forum/#!topic/meanjs/qOPHzMtWrPY

Cheers,
Silla

**Comment by ilanbiala** [comment]
@chronotc is this still an issue with the latest 0.4.0 commit?

**Comment by NeverOddOrEven** [comment]
I've been devving on Windows last two days @ilanbiala. The recent merge fixes it.

**Comment by ilanbiala** [comment]
@chronotc can you try it out? If you still have issues, we can reopen this issue.
