### ISSUE TITLE
Paths to templates should be absolute or config option required.

### ISSUE THREAD

**Issue by sielay** [meanjs/mean#293]
At the moment angular templates are defined without / prefix, what make them relative. In case you want to use both express and angular routing you will come to situation that path http://myhost/myroute/#!/ will add /myroute to all template paths. It blocks ability to create separate sub apps using the same main components. It could be resolved in state configuration per module, but won't be obvious enough to some contributors.

**Comment by ilanbiala** [comment]
@sielay I'm not sure I totally understand, can you show an example of something that wouldn't work right now?

**Comment by ilanbiala** [comment]
@sielay is this still an issue?

**Comment by lirantal** [comment]
@sielay @rhutchison @trainerbill can you look at this?

**Comment by sielay** [comment]
I had no problems with this in 0.4.0 or don't remember them.

**Comment by lirantal** [comment]
Cool.
