### ISSUE TITLE
Update docs to v0.4

### ISSUE THREAD

**Issue by JuanCaicedo** [meanjs/mean#294]
I get the impression that the docs still reflect v0.3, as this is still what is in the master branch. They will have to be updated for the new vertical structure, including the yeoman commands which have changed in the generator-meanjs project. 

I'm willing to start looking at this and make some PRs if that would be helpful!

**Comment by ilanbiala** [comment]
@JuanCaicedo any docs that you make for 0.4.0 would be extremely helpful, as we are planning to finalize 0.4.0 very soon and formally release it.

**Comment by JuanCaicedo** [comment]
@ilanbiala For sure, I can put something out for that. For clarification, should I send PRs here to generator-mean-js?

**Comment by ilanbiala** [comment]
Here would be better.

**Comment by codydaig** [comment]
@ilanbiala Can we close this Issue and move 0.4.0 documentation discussions to #443 ?
