### ISSUE TITLE
Asset cache busting

### ISSUE THREAD

**Issue by simison** [meanjs/mean#299]
Something pretty basic but not that straightforward to implement. 

Would love to see this in meanjs and probably going to give it ago after some while if nobody else takes this before. For now I just added string at config file which I change each time I deploy to production. Any ideas / examples how to implement this?

Some food for thought:
https://github.com/techpines/asset-rack/
https://www.npmjs.com/package/grunt-hashify
https://www.npmjs.com/package/angular-cache-buster

Thoughts?

**Comment by ilanbiala** [comment]
[Compression](https://github.com/expressjs/compression#resflush) does cache some of the compressed assets. How much cache busting are we walking about?

**Comment by ilanbiala** [comment]
@simison if you have a short script that you use, then we can integrate it under scripts/.
