### ISSUE TITLE
indent_style set to tab in .editorconfig

### ISSUE THREAD

**Issue by taji** [meanjs/mean#301]
Is this right?:

`# Standard at: https://github.com/felixge/node-style-guide`
`[**.js, **.json]`
`trim_trailing_whitespace = true`
`indent_style = tab`

The felix node style guide recommends a **two space indention** so I'm confused by the "indent_style=tab" setting. Not interested in a flame war, just want the comment to match the setting or vice-versa.

**Comment by ilanbiala** [comment]
@lirantal @NeverOddOrEven Usually people do something like this assuming the global rules apply:

```
# Tab indentation (no size specified)
[**.js, **.json]
indent_style = tab

# Matches the exact files either package.json or .travis.yml
[{package.json, .travis.yml}]
indent_style = space
indent_size = 2
```

Thoughts on adding a specific rule for package.json and .travis.yml? I think it is pretty conventional to use spaces in those files when talking to most people about it.

**Comment by lirantal** [comment]
I agree

**Comment by NeverOddOrEven** [comment]
I really like consistency, regardless of personal preference towards tabs or spaces. @ilanbiala, you seem to have been most active in gathering opinions on spaces vs tabs, and if spaces, how many.

I prefer for ilan to declare the majority opinion on this issue and get these choices in a PR for various editors (notepad++, vimrc, brackets, etc...). If someone knows how to get formatting checks in Travis, let's do that too.

**Comment by NeverOddOrEven** [comment]
There is another conversation going on in parallel on the generator side. Including a link here to that debate.

https://github.com/meanjs/generator-meanjs/issues/60#issuecomment-69343090

**Comment by codydaig** [comment]
I think that has been taken care of.
