### ISSUE TITLE
Image upload v0.4

### ISSUE THREAD

**Issue by gsyarov** [meanjs/mean#310]
I have problem with image upload. When i click button upload server side send POST http://localhost:3000/api/users/picture 400 (Bad Request) .
Anyone can help me ?
Thanks.

**Comment by taninme** [comment]
Hi Can you please share the code for image upload ? this will be a big help. Thanks in advance ..

**Comment by soulgrasp** [comment]
dude you have to change the path thats all

**Comment by taninme** [comment]
I'm trying to use 0.4 code in 0.3 for generic image upload. is that a package ? thanks
