### ISSUE TITLE
The issue of absolute file paths in the view template

### ISSUE THREAD

**Issue by brooklynb7** [meanjs/mean#313]
I use a proxy_pass server like nginx and config the location of http://hostname/meanjs to http://l127.0.0.1:3000. But I encountered issues caused by the absolute file paths in the view template. Then I have to check all the views and correct them to the relative paths, e.g.

`data-ng-include="'./modules/core/views/header.client.view.html'"` >> 
`data-ng-include="'./modules/core/views/header.client.view.html'"`

`href="/#!/signin"` >> `href="./#!/signin"`

`src="/modules/users/img/buttons/github.png"` >> 
`src="./modules/users/img/buttons/github.png"`  

......

So I think it's better to use the relative path for 'include, href, src' in the sample application. Thx.

**Comment by ilanbiala** [comment]
@brooklynb7 is the URL a typo with the I in front of the 1? Does using relative paths require any changes? If so, can you post the code that you changed other than the paths?

**Comment by brooklynb7** [comment]
I only changed the paths from the absolute to the relative.
It's no problem to use the absolute paths when your application's root path is something like
http://127.0.0.1/#!/signin .
But if your application's root path is something like http://127.0.0.1/mean/#!/signin ,  the absolute paths in the client template will lead the url to http://127.0.0.1/#!/sigin and then 404 occurs.

So I think it's more reasonable if the paths in the client template are relative rather than absolute.

**Comment by lirantal** [comment]
Closing old thread.
