### ISSUE TITLE
Move static files middleware before sessions

### ISSUE THREAD

**Issue by bmonty** [meanjs/mean#318]
I was having a performance problem with reloading a site built off of meanjs.  I solved the problem by moving the config for the static files middleware before the sessions middleware.  Static files load significantly faster because there isn't session tracking being done for each of them.

**Comment by pursual** [comment]
This is broken again.

**Comment by mleanos** [comment]
@pursual Can you provide more details on what you're experiencing, and how this is broken?

**Comment by pursual** [comment]
The session is now initiated before the static routes, and every request for a static file pings mongo. Bottom of config/lib/express.js

**Comment by mleanos** [comment]
@pursual Yes.The session is initiated before the static routes. https://github.com/meanjs/mean/blob/master/config/lib/express.js#L232-L242

I can confirm that there is a significant performance increase when moving the Helmet & Static routes middleware before the Session. 

Thanks @pursual for pointing this out. I think was re-introduced during the move from the older structure of 0.3 to 0.4. 

@lirantal Can you confirm that this indeed does have an impact given our current structure. My performance testing here was very rudimentary. 

@codydaig @ilanbiala Any special insight into this?

**Comment by pursual** [comment]
Pull request submitted, worked fine in my project.

**Comment by lirantal** [comment]
right, that PR is good, we should merge it.
