### ISSUE TITLE
How to deploy meanjs application to production on Windows?

### ISSUE THREAD

**Issue by ywang1724** [meanjs/mean#327]
Hello,

How to deploy meanjs application to production on windows? On linux, do it with "NODE_ENV=production node server", but it doesn't work on windows.

thanks.

**Comment by jajourda** [comment]
@ywang1724 what was the solution you found? I am using v0.4 of meanjs myself.

**Comment by ywang1724** [comment]
@jajourda My solution was grunt prod.
