### ISSUE TITLE
Critical issue with the client side not rendering signup/signin pages

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#334]
Hey,

I'm seeing an issue where if I start the project through the 'master' branch, the home page loads ok, but clicking the Signup or Signin buttons on the top navigation menu the page just refreshes without actually loading the correct HTML for it.

Can anyone else reproduce it?

**Comment by smirnovigor** [comment]
@lirantal I have the same behavior. When I refresh the page (`/articals` for example), I get infinite static resources loading. In server console there are few static js files that don't have load time. When I move static middleware in config file before session middleware, it work perfect but without browser cache.

**Comment by lirantal** [comment]
@smirnovigor interesting. can you further test and see if you can find the fix for this problem?

**Comment by lirantal** [comment]
Hey @smirnovigor I think I found the issue.
There seems to have been an angular update that we needed to install. Running 'npm install' installed it for me, and fixed the authentication issue.

Can you try it too and let me know if it's resolved?

**Comment by smirnovigor** [comment]
@lirantal after little playing around, I don't know why, application works fine, with browser cache. So I stay with config.js changes, that actually equivalent to your [last commit](https://github.com/meanjs/mean/commit/bde2412e2a164803c545f70ea4ba73c6045915b8)
