### ISSUE TITLE
2 different views with forms for creating and updating articles - bad practice

### ISSUE THREAD

**Issue by ramusus** [meanjs/mean#336]
I suppose it would be better to join them into one view with one article form. Otherwise there is violatation of DRY principe. And it's much more complicated handle of the same html form in 2 different places
I can make PR If you agree with my point of view.

**Comment by androidfred** [comment]
I agree, this violates DRY and is bad practice, would be great if you could fix it!

**Comment by ramusus** [comment]
just commited pull request

**Comment by JuanCaicedo** [comment]
My post was about using a directive and controlling the method through an attribute, but this seems much neater!

**Comment by lirantal** [comment]
Seems we've already done some refactoring there on the articles module.
Closing.

@ramusus @JuanCaicedo welcome to comment and add anything else if you'd like.
