### ISSUE TITLE
generator features

### ISSUE THREAD

**Issue by tejasmanohar** [meanjs/mean#340]
https://twitter.com/tejasmanohar/status/550699485421375488

http://blog.meanjs.org/post/102298011468/0-4-release-notes

where is the "gulp" generator feature? or sass? or less? or socket.io?

**Comment by MangeshMp** [comment]
In 0.4.0 branch

**Comment by tejasmanohar** [comment]
@MangeshMp Ah, when's expected release? Will I be able to upgrade or migrate my code over easily?

**Comment by ilanbiala** [comment]
@MangeshMp @tejasmanohar generator questions should probably be posted over in that repository. You can use 0.4.0 today - I've been using many chunks of that code for a few months - it's pretty stable.

**Comment by NeverOddOrEven** [comment]
The 0.4.0 repository branch is stable. The generator-meanjs repo should be stable soon.

**Comment by NeverOddOrEven** [comment]
However, the option to context switch between gulp and grunt, less/sass/css, etc... will likely require additional PRs. The most basic functionality is being done right now just to get things working.

**Comment by ilanbiala** [comment]
@tejasmanohar if you have any other questions, feel free to post to the forum or here.
