### ISSUE TITLE
Unable to connect to mongoDB in Docker

### ISSUE THREAD

**Issue by xch91** [meanjs/mean#342]
When I start with fig up, I always get the error of unable to connect db. The log is detailed as below:

$ fig up
Creating mean_db_1...
Creating mean_web_1...
Attaching to mean_db_1, mean_web_1
db_1  | 2015-01-02T04:15:18.317+0000 [initandlisten] preallocateIsFaster=true 3.12
db_1  | 2015-01-02T04:15:18.577+0000 [initandlisten] allocating new ns file /data/db/local.ns, filling with zeroes...
db_1  | 2015-01-02T04:15:18.844+0000 [FileAllocator] allocating new datafile /data/db/local.0, filling with zeroes...
db_1  | 2015-01-02T04:15:18.844+0000 [FileAllocator] creating directory /data/db/_tmp
db_1  | 2015-01-02T04:15:18.920+0000 [FileAllocator] done allocating datafile /data/db/local.0, size: 64MB,  took 0.072 secs
db_1  | 2015-01-02T04:15:18.921+0000 [initandlisten] build index on: local.startup_log properties: { v: 1, key: { _id: 1 }, name: "_id_", ns: "local.startup_log" }
db_1  | 2015-01-02T04:15:18.921+0000 [initandlisten] 	 added index to empty collection
db_1  | 2015-01-02T04:15:18.921+0000 [initandlisten] command local.$cmd command: create { create: "startup_log", size: 10485760, capped: true } ntoreturn:1 keyUpdates:0 numYields:0  reslen:37 344ms
db_1  | 2015-01-02T04:15:18.921+0000 [initandlisten] waiting for connections on port 27017
web_1 | Running "jshint:all" (jshint) task
web_1 | >> 55 files lint free.
web_1 | 
web_1 | Running "csslint:all" (csslint) task
web_1 | >> 2 files lint free.
web_1 | 
web_1 | Running "concurrent:default" (concurrent) task
web_1 | Running "watch" task
web_1 | Running "nodemon:dev" (nodemon) task
web_1 | Waiting...
web_1 | [nodemon] v1.2.1
web_1 | [nodemon] to restart at any time, enter `rs`
web_1 | [nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
web_1 | [nodemon] starting `node --debug server.js`
web_1 | debugger listening on port 5858
web_1 | Application loaded using the "development" environment configuration
web_1 | MEAN.JS application started on port 3000
web_1 | Could not connect to MongoDB!
web_1 | Error: failed to connect to [localhost:27017]

I looked up #142 which seems to be the most relavant and applied the same change in my config file, but the problem still persists. Below are my Dockerfile and fig.yml and some logs that might be of interest in diagnosing the problem. Any help is much appreciated. I'm using Virtualboxed Ubuntu 14.04 x64:

```
$ cat Dockerfile 
FROM dockerfile/nodejs

MAINTAINER Matthias Luebken, matthias@catalyst-zero.com

WORKDIR /home/mean

# Install Mean.JS Prerequisites
RUN npm install -g grunt-cli
RUN npm install -g bower

# Install Mean.JS packages
ADD package.json /home/mean/package.json
RUN npm install

# Manually trigger bower. Why doesnt this work via npm install?
ADD .bowerrc /home/mean/.bowerrc
ADD bower.json /home/mean/bower.json
RUN bower install --config.interactive=false --allow-root

# Make everything available for start
ADD . /home/mean

# currently only works for development
ENV NODE_ENV development

# Port 3000 for server
# Port 35729 for livereload
EXPOSE 3000 35729
CMD ["grunt"]


$ cat fig.yml 
web:
  build: .
  links:
   - db
  ports:
   - "3000:3000"
  environment: 
   NODE_ENV: development
db:
  image: mongo
  ports: 
   - "27017:27017"


$ sudo netstat -tnpla
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      1181/dnsmasq    
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      516/cupsd       
tcp6       0      0 :::27017                :::*                    LISTEN      1358/docker.io  
tcp6       0      0 :::3000                 :::*                    LISTEN      1358/docker.io


$ ifconfig
docker0   Link encap:Ethernet  HWaddr 56:84:7a:fe:97:99  
          inet addr:172.17.42.1  Bcast:0.0.0.0  Mask:255.255.0.0
          inet6 addr: fe80::5484:7aff:fefe:9799/64 Scope:Link
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:92 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:6200 (6.2 KB)  TX bytes:648 (648.0 B)

eth0      Link encap:Ethernet  HWaddr 08:00:27:7a:bc:be  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe7a:bcbe/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:13111 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8235 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:11341502 (11.3 MB)  TX bytes:947108 (947.1 KB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:2303 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2303 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:241444 (241.4 KB)  TX bytes:241444 (241.4 KB)


# In my /config/env/development.js:
module.exports = {
    // db: 'mongodb://localhost/mean-dev',
    db: 'mongodb://' + (process.env.DB_1_PORT_27017_TCP_ADDR || 'localhost') + '/mean-dev',
```

**Comment by ilanbiala** [comment]
@lirantal @NeverOddOrEven I don't use Docker. Are you guys familiar with it?

**Comment by lirantal** [comment]
not using docker either, sorry.

**Comment by SOSANA** [comment]
If your mongdb needs to be started prior to init this. This same error I get if I don't start mongo prior

**Comment by xch91** [comment]
@SOSANA actually I've tried to start Mongo server manually as well but it seems like web server was still rejected. My initial guess was the booting order too, but shifted to suspecting IPv6 stuff which I'm quite unfamiliar of. Sorry guys, I have given up and drifted away from this approach.
