### ISSUE TITLE
Gulp 4.0 development

### ISSUE THREAD

**Issue by ilanbiala** [meanjs/mean#344]
Gulp 4.0 brings some nice features, so I think we should just switch to Gulp 4.0 ASAP once it comes out (next couple weeks probably) and not have people working with a more complicated version that requires a plugin to do series tasks. Any thoughts @lirantal @roieki @amoshaviv?

**Comment by lirantal** [comment]
sounds interesting.
@ilanbiala  ping us back on this thread when it's out?

**Comment by ilanbiala** [comment]
Almost everything in the gulpfile can be switched now (I'm using Gulp 4.0), except for environment setting, which I'm currently figuring out. The other thing is does it really make sense to keep Grunt and Gulp? I get that we don't want to be opinionated, but it means we have to spend more time and both come out worse. Shouldn't we just pick one?

**Comment by simison** [comment]
@ilanbiala, well, otherwise other people need to spend that time. Isn't that the point of boilerplate that they don't need to? ;-)

**Comment by SOSANA** [comment]
@simison 1+

Don't ditch grunt, if these two build system's are popular as of right now then keep them both as of 4.0 release. If in future release's things change sure drop it but there should be option to use both. Can't speak for everyone but I use both depending on project.

**Comment by ilanbiala** [comment]
@simison @SOSANA I'm not saying ditch it, but Gulp is faster, easier to understand, and cleaner for most people. It would be up to the team, but ultimately it doesn't make sense for a project to have to support both, a community member can always maintain it and submit PRs.

**Comment by SOSANA** [comment]
@ilanbiala Curious what the team's thoughts are on this? Keep both for now?
@roieki @lirantal @amoshaviv

**Comment by sielay** [comment]
+1 always can learn something new

**Comment by roieki** [comment]
I think this touches a growing problem in our repo. As of now, the 0.3 and 0.4 branches are diverging more and more, but I can't say there's a clear cut consensus about which should be the main focus of attention, or in other words - the master branch. I think this would require more discussion, and I suggest scheduling a community hangout to discuss the issue.

**Comment by lirantal** [comment]
@roieki you're right.
Let's schedule it 1-2 weeks in advance so there's an empty slot in our calendars and I'd appreciate if we can do it around working hours of GMT+2 (9AM to 7PM works fine for me)

**Comment by lirantal** [comment]
Not sure what we meant by Gulp 4 when this thread started but seems like we're there now :)
Closing.

cc @ilanbiala
