### ISSUE TITLE
response code 500 on accessing non-existing document?

### ISSUE THREAD

**Issue by FREEZX** [meanjs/mean#348]
Hi,

I'm currently developing an application using mean, and something caught my attention:
https://github.com/meanjs/mean/blob/master/app/controllers/articles.server.controller.js#L93

This returns 500 internal server error if the document does not exist.
In my opinion this should send back 404 Not Found, without disclosing a stack trace.

**Comment by ilanbiala** [comment]
@lirantal isn't the specific route [this one](https://github.com/meanjs/mean/blob/master/app/routes/articles.server.routes.js#L15)? That just calls articleById internally and sends the result.

**Comment by lirantal** [comment]
@ilanbiala that's the route but it uses the :articleId parameter which is resolved using express's app.param() method.

**Comment by ilanbiala** [comment]
@lirantal yep, that's what I said. So what's the consensus, should we at least send a 400 if the id is not a valid ObjectId? I think we should start with that and work forward.

**Comment by lirantal** [comment]
merged the relevant PR so I'm closing this.
