### ISSUE TITLE
Swagger integration

### ISSUE THREAD

**Issue by quocvu** [meanjs/mean#352]
I would like to have Swagger to document the server API integrated to MEAN.JS

https://helloreverb.com/developers/swagger

Really missed it (I used to be on Loopback)

**Comment by jloveland** [comment]
+1

**Comment by frederik** [comment]
+1

Have you looked at raml? I've only used Swagger so far but RAML looks really nice (especially the notebooks that are showcased in the video). This could be really great to get started with the article api from meanjs.

http://raml.org/

**Comment by ilanbiala** [comment]
If anyone wants to create a PR for Swagger documentation, I can get it merged in.

**Comment by ilanbiala** [comment]
This seems like extra that most users won't need, I'm going to close for now because there are also better features we should spend more time on.
