### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by jloveland** [meanjs/mean#353]
It would be beneficial for meanjs to [tag](http://git-scm.com/book/en/v2/Git-Basics-Tagging) releases.

Also, we may want to consider the github [reference](https://help.github.com/articles/creating-releases/) for creating releases.

I should be able to checkout a version by tag:
```git checkout tags/<tag_name>```

for example
```git checkout tags/v0.4.0```

**Comment by ilanbiala** [comment]
@jloveland I like the idea, but I think `tags/0.4.0` would be better, no?

**Comment by jloveland** [comment]
Convention in the git wiki shows v

http://git-scm.com/book/en/v2/Git-Basics-Tagging

**Comment by britztopher** [comment]
@ilanbiala can we close this ticket because its more of an adoption of a methodology/practice for tagging releases?  I would like to also see tags on all major/minor/patches using the semver notation.  I am guessing we will start to do this starting with 0.4.0 branches

**Comment by ilanbiala** [comment]
Yep, that's the plan.
