### ISSUE TITLE
Cannot add client js|css files from modules

### ISSUE THREAD

**Issue by xxorax** [meanjs/mean#356]
To be able to extend meanjs with others libraries, we should be able to add new javascript and CSS files from module.
Because of this in config/config.js :
```
config.files.client.js = getGlobbedPaths(assets.client.lib.js, 'public/').concat(getGlobbedPaths(assets.client.js, ['client/', 'public/']));
```
We cannot simply add libray  before the server js files of module (module/*/client/*.js) because they are all merged in config.files.client.js.

I think we should globbed the paths of assets.client files after calling initModulesConfiguration in config/lib/express.js , then we allow to manipulate client files from module.
Thanks

**Comment by ilanbiala** [comment]
@xxorax this seems specific to your application design, so we'll leave this out of MEAN.js for now.
