### ISSUE TITLE
Cannot lazyload javascript file

### ISSUE THREAD

**Issue by xxorax** [meanjs/mean#357]
Because all client js files of module are loaded, we cannot defer the load of a js file from a module, to use like [ocLazyload](https://github.com/ocombe/ocLazyLoad) angular module.
This is set in config/assets/default.js :
```
modules/*/client/**/*.js
```
I think we should define all the folders of a module where we autoload the js file, or at least define one folder where we don't load the js files, and so do something like :
```
modules/*/client/!(lazyload)/**/*.js
```

Thanks

**Comment by ilanbiala** [comment]
@xxorax this may be more suited for the generator. It seems that not many people use it, so feel free to just add it in yourself.
