### ISSUE TITLE
How to change debugger port

### ISSUE THREAD

**Issue by joeyvmason** [meanjs/mean#358]
I'm running multiple MEAN apps at the same time (on different ports, of course). However, I'm not able to change the the port that the debugger listens on. I've tried changing the `debug-port` field on `node-inspector` from 5858 to 5859, but am still seeing this logged when I run the application with command `grunt`:

`debugger listening on port 5858` 

which results in this error message

`Failed to open socket on port 5858, waiting 1000 ms before retrying`

because that port is already being used by a different MEAN app.

**Comment by ilanbiala** [comment]
@joeyvmason you are using `grunt debug`? If that's the case, you'll need to add command line port arguments to that command and place them in the options object for [grunt-node-inspector](https://github.com/ChrisWren/grunt-node-inspector) when called.

**Comment by joeyvmason** [comment]
No, I am just using `grunt` to run both applications. One app is running on port 3000 and the other on 3001. Is there no way to set the port to listen on in the `grunfile.js`?

**Comment by ilanbiala** [comment]
Try [Grunt's CLI args page](http://gruntjs.com/api/grunt.option). I think you'll find what you need there. Intercept the `--port=` argument, and place that as `5859 || grunt.option('port')`.

**Comment by joeyvmason** [comment]
Resolved the issue by changing `nodemon` to look like this:

```
nodemon: {
			dev: {
				script: 'server.js',
				options: {
					nodeArgs: ['--debug=5859'],
					ext: 'js,html',
					watch: watchFiles.serverViews.concat(watchFiles.serverJS)
				}
			}
		},
```

**Comment by ilanbiala** [comment]
@joeyvmason does that not still set the same debug port for every app that you use nodemon to run?

**Comment by GiankOtarola** [comment]
@joeyvmason perfect solution, fixed for me!
