### ISSUE TITLE
Viewing Articles to Guest users

### ISSUE THREAD

**Issue by denzelwamburu** [meanjs/mean#359]
I have gone through the api docs and seem to figure out how to make the articles visible to everyone who clicks on the site. Any idea?

**Comment by thejones** [comment]
Do you mean the actual viewing of articles (list of all articles in database) or the menu item in the header?

**Comment by denzelwamburu** [comment]
Both of them,the guest should see the menu and the articles under each 'category' without necessarily having to login,but for them to publish they have to login.

**Comment by lirantal** [comment]
You can this behavior in:
```
app/routes/articles.server.routes.js
```

Where it requires a logged-in session for the user to be able to manage the articles content type.
Notice that it might further require you to make changes to how the model is handled as it is expecting a user object in various places and you'll need to account for it for anonymous users.

**Comment by thejones** [comment]
There are a few moving parts to this. As noted above the server route handles if auth is needed. The .get(articles.list) route for reading should be available to public by default. Double check that as it might be different than my project. 

From the client side look at the menu options. (This will vary depending on what menus you are using)
http://meanjs.org/docs.html#menus you will see that the signature here has ...(menuId, [isPublic], [roles]). The isPublic is very important here and I recommend being explicit on these. Also notice that it is on the Menu and sub-menu items so you can control listing verse creating. 

menus.client.service.js
```this.addMenu('topbar', true);```
articles.client.config.js
```Menus.addMenuItem('topbar', 'Articles', 'articles', 'dropdown', '/articles(/create)?',true);
	Menus.addSubMenuItem('topbar', 'articles', 'List Articles', 'articles', null, true);
	Menus.addSubMenuItem('topbar', 'articles', 'New Article', 'articles/create', null, false);```

**Comment by denzelwamburu** [comment]
Awesome thank for the tip its working so fine and its awesome(again).
Thanks, Cheers :+1: )
