### ISSUE TITLE
Suggestion: improving Yo with new questions on public/private app

### ISSUE THREAD

**Issue by ghost** [meanjs/mean#361]
Just two simple thoughts: as for now the generated app is like a blog (everyone can GET everyone else's resources) and discrimination between user being logged in or not is handled client-side.

For the first one: asking "Are user resources private?" with "Yes" as answer should modify GETs from
```javascript
Resource.find().sort('-created').populate('user', 'displayName').exec( ...
```
to
```javascript
Resource.find({'user':req.user.id}).sort('-created').populate('user', 'displayName').exec( ...
```

For the second: asking "Users must be logged in to access your application?"  with "Yes" as answer should modify core.server.controller from
```javascript
exports.index = function(req, res) {
	res.render('index', {
		user: req.user || null,
		request: req
	});
};
```
to something like
```javascript
exports.index = function(req, res) {
	if(!req.isAuthenticated()) {
		res.render('auth', {
			request: req
		});
	} else {
		res.render('index', {
			user: req.user,
			request: req
		});
	}
};
```
so that user login/signin is handled in a separate view, without ever showing your app

Is it reasonable?

PS: Sorry for posting on GitHub, maybe this should be discussed on the Google group first and when a solution comes out moved here for a more "dev" discussion, I'll also post there so close this issue if you want

**Comment by ilanbiala** [comment]
As of now, our flow is pretty well-defined and people haven't complained about it. That said, if you want to create a PR, we can gauge interest for it. In the mean time, I'm going to close this issue.
