### ISSUE TITLE
iOS browsers (over)caching XHR requests

### ISSUE THREAD

**Issue by albertboada** [meanjs/mean#370]
Happens both on Safari and Chrome, at least in iOS8. 

How to reproduce:
- visit http://meanjs.herokuapp.com on your iOS browser
- sign up or log in
- list articles
- create new article
- list articles again

Your new article is often not there, even tho if you fully refresh the page, but if you pay a visit with your desktop browser, the article is there.

Problem is the `/articles` xhr call is returning the exact same result than the one before creating the new article (with Cached: Yes), or at least that's what I'm seeing with Safari's remote web inspector. 

Anyone else has noticed this?

**Comment by codydaig** [comment]
@albertboada Is this still an issue on the latest master branch?

**Comment by lirantal** [comment]
Quite old, closing for now.
