### ISSUE TITLE
Signout not working in Safari with sample application

### ISSUE THREAD

**Issue by rweindl** [meanjs/mean#372]
Hey, when trying to 'Signout' using Safari the user is redirected to '/' but actually not being logged out. 

Edit: I found out that that in Safari `$scope.authentication.user` is not set to `null` when the `Signout` button is pressed the first time?!

Old (before Edit): Two observations before diving deeper in the code (see below in the comment).
I recognized that Safari (not working) is creating two sessions and Chrome (working) only one session in the MongoDB. At Safari I have to press 'Signout' again in order to finally sign out a user in Safari.

Another observation: When pressing 'Signout' in Safari the first time and then reloading the page I download an empty 'Unknown' file but when hitting enter in the address line I am signed out.

**Comment by mshirlaw** [comment]
I also see this behaviour on Safari. I need to make two GET requests to /auth/signout before I am logged out correctly.

**Comment by rmlopes** [comment]
Hey, is this on the 0.4.0 branch or master? What is the Safari build?  I cannot replicate using Safari Version 8.0.4 (10600.4.10.7)

**Comment by benmarten** [comment]
+1

**Comment by puntubabu** [comment]
rweindl I followed your steps, but I'm still redirecting to the same page, without logging out. It's only if I log out twice that I am taken back to the main page.

**Comment by lirantal** [comment]
Guys is this still an issue with the latest `master` branch? can you please confirm?

**Comment by codydaig** [comment]
I am unable to reproduce on the latest master branch on 8.0.7 on mac os 10.10.4.

**Comment by lirantal** [comment]
Thanks for looking into it @codydaig , can be closed then.
