### ISSUE TITLE
html5Mode page reloading and direct links not working (pretty urls)

### ISSUE THREAD

**Issue by promijn** [meanjs/mean#378]
I had some problems with the html5mode and pretty urls. 
The problem occurs when I refresh the localhost:3000/example page. I get the following output: 

    Cannot GET /example

After some searching I cam across this https://github.com/meanjs/mean/issues/161#issuecomment-54321788

I changed in my config/express.js

    app.get('/', core.index);

into

    app.get('/*', core.index);

This solved my problems with pretty urls and page reloading

**Comment by codydaig** [comment]
I believe this change has been implemented.
https://github.com/meanjs/mean/blob/0.4.0/modules/core/server/routes/core.server.routes.js#L14

Can this issue be closed?

**Comment by ilanbiala** [comment]
@promijn any issues
