### ISSUE TITLE
super slow startup time

### ISSUE THREAD

**Issue by thedug** [meanjs/mean#380]
When I run fig jshint runs within a few seconds but it takes minutes before the server is up and listening.

Any tips on finding the culprit?

**Comment by thedug** [comment]
When I updated fig to run node server.js things run much faster.

I assume this is because of the watch? 

Still digging....

**Comment by thedug** [comment]
I've been spinning why wheels and don't see any reason why simply adding watch to a folder with 3 files in it should increase start-up time to 3-6 minutes.

**Comment by PeterTucker** [comment]
I get the same problem. @thedug , have you had any progress on this?

**Comment by thedug** [comment]
@PeterTucker  Are you using Vagrant?

**Comment by PeterTucker** [comment]
No, I'm not using Vagrant.

**Comment by thedug** [comment]
What is your setup? OS? Virtual Machine?

**Comment by PeterTucker** [comment]
Oops, probably should have listed this before hand. I'm using the Ubuntu Bitnami MEAN stack on VirtualBox.

**Comment by thedug** [comment]
What is your host OS?

**Comment by PeterTucker** [comment]
OSX 10.9.5

**Comment by thedug** [comment]
Update the folder share to use nfs

**Comment by thedug** [comment]
For vagrant:

  config.vm.synced_folder ".", "/home/vagrant", :nfs=> true, nfs_udp: false

**Comment by PeterTucker** [comment]
Hi Douglas, I found the problem. Port 35729 was closed and livereload.js was hanging on that. As soon as I opened the port everything is running smoothly. Thanks again for your help.

-Peter
