### ISSUE TITLE
cannot run NPM INSTALL - npm ERR! Unexpected number

### ISSUE THREAD

**Issue by nhhockeyplayer** [meanjs/mean#383]
Hi,

I just created a meanjs project the other day built it ran it fine.

So I started a new one. Using the latest meanjs. This is what I get. Can you help ?

C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo\photoIo>npm install
npm ERR! install Couldn't read dependencies
npm ERR! Failed to parse json
npm ERR! Unexpected number
npm ERR! File: C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo\photoIo\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR!
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo\photoIo
npm ERR! node -v v0.10.31
npm ERR! npm -v 1.4.23
npm ERR! file C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo\photoIo\package.json
npm ERR! code EJSONPARSE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo\photoIo\npm-debug.log
npm ERR! not ok code 0

C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo\photoIo>

**Comment by nhhockeyplayer** [comment]
Here are the steps I took to establish this new project.
I just fiollowed what the git front page said to do.

C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean>cd photo

C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo>dir
 Volume in drive C has no label.
 Volume Serial Number is A40F-8430

 Directory of C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo

01/28/2015  09:19 PM    <DIR>          .
01/28/2015  09:19 PM    <DIR>          ..
12/03/2014  05:24 PM             8,251 .jshintrc
01/28/2015  09:19 PM               502 .project
01/28/2015  09:19 PM    <DIR>          .settings
01/29/2015  05:16 AM                72 .tern-project
01/28/2015  09:19 PM               346 README.md
               4 File(s)          9,171 bytes
               3 Dir(s)  18,863,939,584 bytes free

C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo>mean init photoIo
? What would you name your mean app? photoIo
? Do you prefer grunt or gulp as a taskrunner? grunt
? Which mean packages would you like to install? mean-admin
Cloning branch: master into destination folder: photoIo
Cloning into 'photoIo'...
Use `mean --help` from command line for all CLI options
Be sure to checkout all the docs on http://mean.io
Version: 0.4.3 cloned

                t  t
           t@@%SS%XS@@S@X88X
       8XtSS88.;::::8t.8t.:8S88X8:
   .8t@888 ;t8.8 8  :8%;.8:;8t.;8S88;
 tt@8;;;. ::. . . :;::..::8%  8::8;X88%;
 X8;t;8 :XSXXS@t8 :8;.8t88     8;: 8t8t
 ;;::. :8:XSXXS8 :. 8%; ;:     8.8%;:S@t
  X.8 :. XXXSXSS88  :..88      8::..8;%
  @8;:8 :XSXXSXS% .:8t:8.      S.8t.;..
  @S;. ::XXSX%XXS8:.;.;t. X%   8::.8@X
  88;::8 SXXS@@%XX88;88  .t;   88t.:@%8
  %;:8  :XSX@..8SSS :@   S.t   St.8;%@
   %: .::XXSXXt:@XSS S  X 8    8..;.8;
   8SS8 :XSXX%;8@@XXS  :;.;    8.8;8 ;
   :S: :8:XXX;. ;XSX   8:8t    S;:.Xt
   @88 . XSXX%:;:;XX  8..:.    88t.8%
   X: :;:XXSXS;8 88t ;:8t.8    8t.8S@:
    t.:8 SXSX%. . .S S%:8%     8 ::8%
    88; :8888@8 .::88.8%  :8888t8;;;@
    :@@@t88 t  :8 . :.:..8  8 .8S8Xt.
      ;t8S8@@8 . ::8;8;8% :tX88@%.8
         ;:.@8@%88   ; ;@88@t8;:
             ;;8S88S;8%888;8
                ;::tS88
                   t8


cp: dest file already exists: Gruntfile.js

   install dependencies:
     $ cd photoIo && npm install

   run the app:
     $ grunt

   Extra Docs at http://mean.io

   git remote upstream set


C:\apache-tomcat-8.0.12-x64\webapps\ROOT\angular\mean\photo>

**Comment by sylvainlap** [comment]
I think you're using Mean.IO, and you are on the Mean.JS GitHub.

**Comment by nhhockeyplayer** [comment]
well yeah...

it looks like mean.io is no longer legit ?

so I stayed with meanjs

?
  
    
    
  
  
 		 	   		  =

**Comment by sylvainlap** [comment]
Mean.JS is a "fork" of Mean.IO, leaded by the original creator of Mean.IO. You can find more info here : http://blog.meanjs.org/post/76726660228/forking-out-of-an-open-source-conflict

**Comment by nhhockeyplayer** [comment]
does this infer that mean.io is retired and we should just use meanjs ?

Best regards 
and thanks... KEN

Date: Mon, 2 Feb 2015 03:17:43 -0800

**Comment by sylvainlap** [comment]
No, both projects are still alive. You can use mean.js or mean.io, they both have their community.
However, you are currently using mean.io, and post your problem on the mean.js github. You should go there : http://mean.io/#!/support

**Comment by ilanbiala** [comment]
@nhhockeyplayer it seems that the package.json for another package is malformed, try to post their with the issue. This doesn't seem to be related to MEAN.js, so I'm going to close it unless you comment with more info that shows that it is.
