### ISSUE TITLE
Nested Controllers In Forms

### ISSUE THREAD

**Issue by vinayuttam** [meanjs/mean#385]
For example if I have two controllers called CoursesController and StudentsController.

In my application, a student can register for a courses. In the StudentRegistration create form I have Student ID, StudentName, StudentCourses

Here the StudentCourses is a Select form field which allows multiple selections, the options are populated using CoursesControllers. I am able to print the selected courses id's on the create page but when I submit the form angular returns undefined.

I'm using the ng-options to populate the select options by using CoursesController inside the StudentsController

**Comment by vinayuttam** [comment]
For example if I have two controllers called CoursesController and StudentsController.

In my application, a student can register for a courses. In the StudentRegistration create form I have Student ID, StudentName, StudentCourses

Here the StudentCourses is a Select form field which allows multiple selections, the options are populated using CoursesControllers. I am able to print the selected courses id's on the create page but when I submit the form angular returns undefined.

I'm using the ng-options to populate the select options by using CoursesController inside the StudentsController

**Comment by ilanbiala** [comment]
Custom modifications shouldn't be in MEAN.js.
