### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by Trevogre** [meanjs/mean#387]
Late in the day and my brain is feeling like mush.

(I apologize in advance for the long message. This is probably not an Issue as much as it is an issue with meanjs documentation not helping me understand what the hell this is supposed to do :) Thank you to anyone who can tell why this doesn't work)

I'm trying to add a route. The clone route below

```
	app.route('/estimates')
		.get(estimates.list)
		.post(users.requiresLogin, estimates.create);

	app.route('/estimates/:estimateId')
		.get(estimates.read)
		.put(users.requiresLogin, estimates.hasAuthorization, estimates.update)
		.delete(users.requiresLogin, estimates.hasAuthorization, estimates.delete);
    
    app.route('/clone/:estimateIdToClone')
        .get(estimates.clone);
    
	// Finish by binding the Estimate middleware
	app.param('estimateId', estimates.estimateByID);
       app.param('estimateIdToClone', estimates.estimateByID);
```

I get the following when accessing it directly for testing.

```
Page Not Found
	/clone/54cee4748c7ca0681942672e is not a valid path.
```

Where the id is from a working estimate in my model. 
Essentially I'm just trying to create a copy of the estimate.

Just for fun here is the server.controller code.

```
/**
 * Clone an Estimate
 */
exports.clone = function(req, res, next, id) {
    Product.findById(id).exec(function(err, estimatetoclone) {
        
        estimatetoclone._id = undefined;
        estimatetoclone.isNew = true;

        estimatetoclone.save(function(err) {
            if (err) {
                return res.status(400).send({
                    message: errorHandler.getErrorMessage(err)
                });
            }
        });
    });
};
```

But I don't think there is an issue there. Thought I wouldn't no it because the route just fails. I originally used the estimateByID param to try and get the id from the url, as it works in my findOne calls. Unfortunately the clone url just doesn't appear to run at all.

It has got to be a typo or something I just am not getting. Unfortunately that appears to be a lot be cause the structure of meanjs routing is kind of driving me nuts and the documentation out there doesn't seem to be getting through to me.

Can I not just define a route to a server controller function? I have one other route situation

```
app.route('/notes/:noteId')
		.get(notes.read)
		.put(users.requiresLogin, notes.hasAuthorization, notes.update)
		.delete(users.requiresLogin, notes.hasAuthorization, notes.delete);

	// Finish by binding the Note middleware
	app.param('noteId', notes.noteByID);

    
    // Notes Routes
    app.route('/estimatenotes/:noteEstimateId')
        .get(notes.listEstimateNotes);
    
	// Finish by binding the Note middleware
    app.param('noteEstimateId', notes.listEstimateNotes);
```

So when I run the query and get the notes just for one estimate it returns the proper list, but then the original note route for delete tries to go to '/estimatenotes/ to do the delete. I was assuming that since it returned the collection from that url that when I do the $delete on an object on the list from the client side that it tries to go the url that I pulled from instead of the 'notes/:noteId' route. I tried just adding the .delete line to the '/estimatenotes/' route so that could also participate by it throws.

```
Error: [$resource:badcfg] Error in resource configuration for action `remove`. Expected response to contain an object but got an array
```

Here is the code. Seems pretty standard.

```
// Find notes for estimate
		$scope.findEstimateNotes = function() {
			$scope.notes = EstimateNotes.query({ 
				noteEstimateId: $scope.estimate._id
			});
            console.log($scope.notes);
		};
```
That works.

This doesn't
```
// Remove existing Note
		$scope.removeNote = function(note) {
			//console.log(note);
            if ( note ) { 
				note.$remove(); 

				for (var i in $scope.notes) {
					if ($scope.notes [i] === note) {
						$scope.notes.splice(i, 1);
					}
				}
			} else {
				$scope.note.$remove(function() {
					//$location.path('notes');
                    $scope.findEstimateNotes();
				});
			}
		};
```
 
Thank you for your assistance.

**Comment by Trevogre** [comment]
I forgot, this might also be relevant. This setup also confuses me. I'm creating new factories to add the routes to the client side for the issue with my notes. This works but I really wish that there wasn't any of this default mapping that doesn't make sense. Where I run a .query() on the factory and that maps to a .get on the server routes. And $remove somehow ends up with the .delete. 

For Factories. How do I write these so there is a clear one to one mapping between the server functions and the client functions. I see that the update is marked as a put, so it appears as though you can write this code to explicitly map functions you are going to run like Notes.update. 

There is too much cleverness in this for me. I need to just be able to see a function and run it. Run a mongoose query on the server, set the url that it spits out at, and pass the parameters from a factory.

I'm assuming that my note problem is because I'm returning an array from the server and it is passing back an array vs. the meanjs generated code where you delete from a find once. So I have to write a different function that does a new mongoose query with the id of the item that I want deleted and delete it. Rather than running a straight $remove that just fails, even though I'm call the function just the same on the client as I would on a page where I returned only one record. 

To much magic!!!. :) why isn't this more straight forward.

```
'use strict';

//Notes service used to communicate Notes REST endpoints
angular.module('notes').factory('Notes', ['$resource',
	function($resource) {
		return $resource('notes/:noteId', { noteId: '@_id'
		}, {
			update: {
				method: 'PUT'
			}
		});
	}
]);

angular.module('estimates').factory('EstimateNotes', ['$resource',
	function($resource) {
		return $resource('estimatenotes/:noteEstimateId', { noteEstimateId: '@_id'
		}, {
			update: {
				method: 'PUT'
			}
		});
	}
]);
```

**Comment by aarosil** [comment]
Trevor,

This https://docs.angularjs.org/api/ngResource/service/$resource will help
clear up a lot of confusion (read again and again, it's very dry, "like
stereo instructions").  Especially read under the "returns" header since
that describes what it is you're getting back from your EstimateNotes
service and using in the controller

the $resource is a high level abstraction for $http so you may want to use
$http at first in a test controller to get a feel how everything works with
calling your routes directly, without the higher level abstraction mapping
things automatically for you.

Whenever you see this:

Expected response to contain an object but got an array

That means your Node.JS route returning array and Angular was expecting to
see an object.  Only `query` expects array, the others expect to deal with
single objects.  You can also get the opposite error.  The default
`$resource` mappings are here,

{ 'get':    {method:'GET'},
  'save':   {method:'POST'},
  'query':  {method:'GET', isArray:true},
  'remove': {method:'DELETE'},
  'delete': {method:'DELETE'} };

if you need differently you can override and create a customized action
with the `isArray` option set, using config options passed as 3rd arg to
`$resource` (see the "actions" entry under the "Arguments" table of the
linked doc). `update` from your 2nd post would be an example of a custom
resource action (here used to specify `PUT` instead of the default
`POST`).

I feel your pain about how clever everything is but I will say once you
wrap your head around how stuff works it will make your life a lot easier
in the long run.

Thanks,
Aaron

**Comment by Trevogre** [comment]
Thank you for your response. I'm going to have to parse through this a bit more. This didn't address the first part of my question. Which I believe is express centric. 

```
app.route('/clone/:estimateIdToClone')
        .get(estimates.clone);
```
returns

```
Page Not Found

	/clone/54cee46a8c7ca0681942672d is not a valid path.
```

from 

```
http://localhost:3000/clone/54cee46a8c7ca0681942672d
```

I'm trying to access it directly just to see if it is doing anything but it just errors out. All of the other routes in the file work. 

Below is the code it is trying to run but that shouldn't matter as it is failing at the route level. 

There is something fundamental that I don't understand about the rules for adding server side routes, or potentially the code is failing and just resulting in the route not appearing valid? I don't know. One of those very frustrating things. I would think defining a route would just be as simple as that function. Maybe a default browser visit is not a GET? Feeling a bit stupid again :).

```
/**
 * Clone an Estimate
 */
exports.clone = function(req, res, next, id) {
    Product.findById(id).exec(function(err, estimatetoclone) {
        
        estimatetoclone._id = undefined;
        estimatetoclone.isNew = true;
        
        console.log(estimatetoclone);
        
        estimatetoclone.save(function(err) {
            if (err) {
                return res.status(400).send({
                    message: errorHandler.getErrorMessage(err)
                });
            }
        });
    });
};
```

**Comment by Trevogre** [comment]
Huh... it tries to get every url at that route. The ones at the bottom prepend the /clone/ onto everything. I didn't inlcude all of theme, just the error and the first few. 

I guess I have something else going on, but the app doesn't fail otherwise, so I'll to track down why adding that route would trigger this issue. Seems strange that it would somehow be grabbing the css file. 

```
Completed in 4.469s at Tue Feb 03 2015 14:17:44 GMT-0800 (Pacific Standard Time)
 - Waiting...
GET /clone/54cee46a8c7ca0681942672d 404 192.240 ms - -
CastError: Cast to ObjectId failed for value "default.css" at path "_id"
    at ObjectId.cast (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_mo
dules\mongoose\lib\schema\objectid.js:116:13)
    at ObjectId.castForQuery (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest
\node_modules\mongoose\lib\schema\objectid.js:165:17)
    at Query.cast (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_modul
es\mongoose\lib\query.js:2340:32)
    at Query.findOne (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_mo
dules\mongoose\lib\query.js:1118:10)
    at Query.exec (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_modul
es\mongoose\node_modules\mquery\lib\mquery.js:2213:16)
    at Query.exec (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_modul
es\mongoose\lib\query.js:1797:19)
    at exports.estimateByID (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\
app\controllers\estimates.server.controller.js:151:56)
    at paramCallback (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_mo
dules\express\lib\router\index.js:386:7)
    at param (G:\Dropbox\agreenweb\Clients\Paynorthwest\meantest\node_modules\ex
press\lib\router\index.js:366:5)
    at Function.proto.process_params (G:\Dropbox\agreenweb\Clients\Paynorthwest\
meantest\node_modules\express\lib\router\index.js:392:3)
GET /clone/lib/bootstrap/dist/css/bootstrap.css 404 46.668 ms - -
GET /clone/lib/bootstrap/dist/css/bootstrap-theme.css 404 46.189 ms - -
GET /clone/lib/angular-toggle-switch/angular-toggle-switch.css 404 49.276 ms - -
```

**Comment by Trevogre** [comment]
I think I fixed one part.

I had the estimate._id = undefined which I thought would just give me a new ObjectId automatically, maybe it will and that wasn't causing an issue, but this works.

So the is an answer for the question "How do you clone/copy a mongoose document on the server".

I was trying to do this on the client side but just changing the _id and doing a $save but that didn't seem to want to work.

My debugging setup isn't terrible robust at the moment, so I probably could have interpreted the messages better, I suppose that my code was throwing the page not found and I just didn't realize it and thought the error was in the router. :)
```
exports.cloneByID = function(req, res, next, id) { 
	Estimate.findById(id).exec(function(err, estimate) {
		
        if (err) return next(err);
		if (! estimate) return next(new Error('Failed to load Estimate ' + id));
		        
        estimate._id = mongoose.Types.ObjectId();
        estimate.isNew = true;
        
        estimate.save(function(err) {
            if (err) {
                return res.status(400).send({
                    message: errorHandler.getErrorMessage(err)
                });
            } else {
                req.estimate = estimate;
                res.jsonp(req.estimate);
            }
        });
	});
};
```
I had the middlewear function pointed to the wrong function.
```
app.route('/clone/:estimateIdToClone')
        .get(estimates.cloneByID);
    
    app.param('estimateIdToClone', estimates.cloneByID);
```

**Comment by aarosil** [comment]
You're on track, just break everything into small pieces so you can see how
they individually work.  Even setting up a throwaway project try out how
different things like Express routing,AngularJS $resource, etc.  Just setup
something simple and modify only one piece at a time so you know all the
others work as expected

As far as cloning the Mongoose document, probably easiest would be `new
Model(existingModelYouWantToClone)` (on Node.JS side, after deleting the
_id) or use _.assign/merge from lodash library, there's probably better
ways to do it too

**Comment by ilanbiala** [comment]
Please post questions like this on Stackoverflow or on the forums before coming here. If you still have this issue, then comment again with your progress and we'll try to help.
