### ISSUE TITLE
Keeping MEAN app user/session data segregated

### ISSUE THREAD

**Issue by tylerdmace** [meanjs/mean#388]
I would like to use one MongoDB datastore for the UI-specific functionality (users, sessions, etc) and would like to be able to use another for everything else. What's a good and clean way to implement this? Anyone got some examples or a write up by chance?

**Comment by ilanbiala** [comment]
http://stackoverflow.com/questions/19474712/mongoose-and-multiple-database-in-single-node-js-project
http://mongoosejs.com/docs/connections.html
Feel free to come back with further questions.

**Comment by tylerdmace** [comment]
Thank you :) I was looking for some insights on implementing it within a mean.js build, specifically. Any input there?

**Comment by ilanbiala** [comment]
What's the issue with using collections in the database? You would avoid lots of headache.
