### ISSUE TITLE
Add more control fields for articles

### ISSUE THREAD

**Issue by miguelcoba** [meanjs/mean#390]
Change the user and created fields in the article model for new fields that track who and when the article was created or updated.

Should add the following fields:

updatedAt, default value: Date.now
updatedBy, default value: req.user
createdAt, default value: Date.now
createdBy, default value: req.user

**Comment by ilanbiala** [comment]
The PR for this issue was merged in, should be resolved.

**Comment by britztopher** [comment]
@ilanbiala @miguelcoba Any idea why this ticket has open closed so many times?  Anything I can help with?

**Comment by ilanbiala** [comment]
This issue has only been closed then reopened once, it references lots of other things though. I'd like to merge this in, but I think @miguelcoba had some issues with redoing this PR on 0.4.0 instead of master based on the latest comment in #392.

**Comment by britztopher** [comment]
@ilanbiala i see now, I saw 'closed' above on #391, thinking it was this ticket.  My B on not looking more closely.  Thanks, I wont make this mistake twice

**Comment by ilanbiala** [comment]
@miguelcoba since we haven't done much about it, I'm going to close this PR unless people express strong interest in bringing it back or you can get it into 0.4.x once we have released 0.4.0
