### ISSUE TITLE
angular is not defined

### ISSUE THREAD

**Issue by emadd** [meanjs/mean#393]
Fresh install.  Bower installed, Node packages installed.  The HTML template doesn't even try to include angular, but I suspect that is because there is no lib folder in public.

**Comment by emadd** [comment]
Copying contents of bower_components to public/lib fixes issue, but why do I have to do this?

**Comment by sylvainlap** [comment]
You normally don't have to copy bower_components to public/lib. The .bowerrc file tells Bower to do that for you : https://github.com/meanjs/mean/blob/master/.bowerrc

**Comment by MangeshMp** [comment]
It is possible in your case the 'bower install' step failed while running 'npm install'

try running 'bower update' again and then
check if the lib file is created.

**Comment by sylvainlap** [comment]
The package.json file says :
"postinstall": "bower install --config.interactive=false"

What happens if bower is not globally installed ? Is NPM able to find itself bower in node_modules/ ?

**Comment by gcoupelant** [comment]
Stupid question, but did you have the .bowerrc file in your root directory ? If you copy/paste the files using a file manager, it may have skipped hidden files.

**Comment by ilanbiala** [comment]
Please post questions like this on Stackoverflow and the forums before coming here. If this is still an issue after exploring those solutions, then feel free to comment with your progress.
