### ISSUE TITLE
Update of the public/dist/application.js file

### ISSUE THREAD

**Issue by sylvainlap** [meanjs/mean#394]
Hi,

How the public/dist/application.js file is updated ?

For example, there were modifications in the public/modules/users/service files, but the changes are not taken into account in the public/dist/application.js file. What is the process to update the application.js file ?

**Comment by ilanbiala** [comment]
`public/dist/application.js` really shouldn't be in Git, because it is a compiled file. You should run `grunt` or `gulp` to compile that file and update it.

**Comment by sylvainlap** [comment]
I totally agree. Why don't you remove "dist" files from the repo ?

**Comment by ilanbiala** [comment]
@sylvainlap do you want to put together a PR that removes these files and adds them to the .gitignore? @lirantal is there any reason we kept dist files in the repo?

**Comment by sylvainlap** [comment]
I'll do that !

**Comment by ilanbiala** [comment]
@sylvainlap that's great, but just to make sure before you go ahead I want to check with another contributor to see if there's a specific reason dist files are in the repo.

@lirantal @roieki @amoshaviv @NeverOddOrEven any thoughts why dist files are in the repo?

**Comment by sylvainlap** [comment]
I'll just do the PR on both branches.
Merge them when you have the green light !

**Comment by sylvainlap** [comment]
PR created on both branches.

**Comment by Shrizzy** [comment]
Hmm...not entirely sure about this one. 
My current process is to build prior to deployment. For example, prior to deployment I run 'Grunt Build'. This creates/updates the distribution files, then I add them to Git and then push to the relevant server. This generally means that I can avoid running dev dependencies (like Grunt) on the server.

Do most people run Grunt or Gulp on the server? Or would this change be used to support automated deployment?

On a separate note, I've started using Gulp a lot recently, and noticed that a lot of example projects with Gulp seem to package up their distribution files in a central distribution folder i.e. the output of almost every Gulp process seems to create or update a file in a central location. Whereas we seem to have a mixture of module centric, and app centric distribution files. Here's an example from Foundation Apps: 
https://github.com/zurb/foundation-apps/blob/master/gulpfile.js

**Comment by lirantal** [comment]
@ilanbiala I think we just missed that probably.

**Comment by ilanbiala** [comment]
Ok, so I'm going to get the PR merged in, because anyway people will be overwriting these files before any sort of deploy.

**Comment by ilanbiala** [comment]
Merged.

**Comment by sylvainlap** [comment]
The workflow that @Shrizzy describes is, I think, what most people do.
Maybe we went too fast, and adding public/dist in the .gitignore is not a good idea, because people won't be able to push dist files in their private reps.
Maybe we should remove public/dist from the .gitignore ?

**Comment by ilanbiala** [comment]
I think most people don't check in dist files because they have to npm install anyway and it forces you to create new versions.

**Comment by sylvainlap** [comment]
But on a "prod" server, when doing "npm install --production", Grunt won't be installed, and you won't be able to "grunt build".
I think a developper will dev on a dev machine, then use "grunt build", "git push" the dist files on his rep, and pull them on the prod machine (like @Shrizzy said). That's why I think we should remove public/dist from the .gitignore.

**Comment by ilanbiala** [comment]
@sylvainlap the user can easily make that change if it benefits them, but honestly biggest cause of deployment issues is not rebuilding assets. Besides that some parts of Grunt should be dev  dependencies, and some could easily be considered regular dependencies.

**Comment by sylvainlap** [comment]
OK, I agree ! :)
