### ISSUE TITLE
MissingSchemaError: Schema hasn't been registered for model "User".

### ISSUE THREAD

**Issue by superandrew** [meanjs/mean#398]
Hi, I have this problem only when i run the basic superheroes example in a dreamhost VPS using pm2 or forever as a service. That means that If I run `node server.js` it works, if I run 
`pm2 (forever) start server.js`

I have this error repeating itself many times, until the service stops. I've tried to recreate it on a local machine, but here it works. I really don't know where to look.

Here's the full error stack:

    MissingSchemaError: Schema hasn't been registered for model "User".
    Use mongoose.model(name, schema)
    at Mongoose.model (/home/fucinadev/*********.com/node_modules/mongoose/lib/index.js:323:13)
    at Object.<anonymous> (/home/fucinadev/*********.com/config/passport.js:7:29)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/fucinadev/*********.com/server.js:27:1)
    at Module._compile (module.js:456:26)

Any help would be appreciated.

**Comment by ilanbiala** [comment]
check `config/passport.js:7`

**Comment by superandrew** [comment]
I have in config/passport.js:
    `var passport = require('passport'),
	User = require('mongoose').model('User'), -->line 7
	path = require('path'),
	config = require('./config');`

in server.js line 27 is simply
`require('./config/passport')();`
I am really new at mongo, so this doesn't mean anything to me.

Thanks

**Comment by ilanbiala** [comment]
So your models aren't being instantiated. Did you change anything since downloading MEANJS?

**Comment by superandrew** [comment]
no but, as I said, locally the application works both using
`node server.js`
and
`pm2 start server.js`

in this server the application works using
`node server.js` or `forever server,js`
but doesn't work launching it as a service, e.g. 

`pm2 start server.js`

**Comment by ilanbiala** [comment]
That's not MEANJS specific, so we ask that you post on stackoverflow or another site before coming here. We'll gladly take a look if all the other possible avenues have been exhausted.

**Comment by MangeshMp** [comment]
Hi ,

Please try adding these lines in the file where it is giving error.

in master
var path = require('path');
var User = require(path.resolve('./app/models/user.server.model'));

Thanks

Mangesh




On Sun, Feb 8, 2015 at 4:47 AM, Andrea Maschio <notifications@github.com>
wrote:

> Hi, I have this problem only when i run the basic superheroes example in a
> dreamhost VPS using pm2 or forever as a service. That means that If I run node
> server.js it works, if I run
> pm2 (forever) start server.js
>
> I have this error repeating itself many times, until the service stops.
> I've tried to recreate it on a local machine, but here it works. I really
> don't know where to look.
>
> Here's the full error stack:
>
> MissingSchemaError: Schema hasn't been registered for model "User".
> Use mongoose.model(name, schema)
> at Mongoose.model (/home/fucinadev/*********.com/node_modules/mongoose/lib/index.js:323:13)
> at Object.<anonymous> (/home/fucinadev/*********.com/config/passport.js:7:29)
> at Module._compile (module.js:456:26)
> at Object.Module._extensions..js (module.js:474:10)
> at Module.load (module.js:356:32)
> at Function.Module._load (module.js:312:12)
> at Module.require (module.js:364:17)
> at require (module.js:380:17)
> at Object.<anonymous> (/home/fucinadev/*********.com/server.js:27:1)
> at Module._compile (module.js:456:26)
>
> Any help would be appreciated.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/398>.
>



-- 
Thanks and Regards,
Mangesh Pimpalkar

**Comment by ym-cron-eu** [comment]
@superandrew I just had that problem - it's because of how paths in mean.js are defined, so that it depends on the process.pwd(). since I'm running stagecoach, I had to add a --workingDir to the forever start params. hope that helps!

**Comment by shawn3a** [comment]
@superandrew I also encounter this issue and found mean js can only run in mean directory just like @ym-cron-eu said it's how paths in mean.js are defined. I use upstart to run node so the fix is just add "cd $yourMeanjsPath", then "exec $yourNodePath $yourMeanjsPath/server.js". All fine for me.

**Comment by ym-cron-eu** [comment]
just realized I haven't put in the exact line I used for forever, maybe it helps too :)
`PORT=8080 NODE_ENV=production forever -d -v --minUptime 1000 --spinSleepTime 5000 --workingDir `pwd` -o data/console.log -e data/error.log start `pwd`/server.js && echo "Site started"`

**Comment by scottbcovert** [comment]
FWIW if anyone runs across this while using Docker for development/deployment w/ live reload a good place to start looking is the paths you're using for volume mounting. As per docker/docker#13121 if your local path is invalid Docker will create the path on your host machine rather than throw an error. This means the app and public folders mounted to your container will be empty so your Mongoose models won't be instantiated and this is the error message your container will throw.

**Comment by lirantal** [comment]
thanks @scottbcovert

**Comment by BeShclo** [comment]
Who can help me to translate into Chinese?    T_T

**Comment by rahulgupta1210** [comment]
MissingSchemaError: Schema hasn't been registered for model "contact".
Use mongoose.model(name, schema)
    at new MissingSchemaError (D:\meanstackProject\contactList\node_modules\mongoose\lib\error\missingSchema.js:20:11)
    at Mongoose.model (D:\meanstackProject\contactList\node_modules\mongoose\lib\index.js:337:13)
    at Object.<anonymous> (D:\meanstackProject\contactList\models\contact.js:22:43)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (D:\meanstackProject\contactList\routes\route.js:4:17)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

Any help would be appreciated.
