### ISSUE TITLE
Grunt / Gulp build

### ISSUE THREAD

**Issue by sylvainlap** [meanjs/mean#399]
Hi,

In the Grunt file, there is:
grunt.registerTask('build', ['env:dev', 'lint', 'ngAnnotate', 'uglify', 'cssmin']);

And in the Gulp one:
gulp.task('build', function(done) {
	runSequence('env:dev' ,'lint', ['uglify', 'cssmin'], done);
});

Is there any reason to set NODE_ENV to development before the build ? I don't think that NODE_ENV is used during the build process.

**Comment by gcoupelant** [comment]
You could set NODE_ENV before using the "gulp build" command.
I think it's rather a safety net.

**Comment by codydaig** [comment]
@sylvainlap We're you able to figure this out?

**Comment by codydaig** [comment]
@sylvainlap I'm closing this issue. Feel free to reopen if it's sill an issue.
