### ISSUE TITLE
Cloud 9 -  c9

### ISSUE THREAD

**Issue by cliffeby** [meanjs/mean#4]
Deploying in the Cloud 9 IDE took some time, but I now have an the framework running.  Here are some suggestions to others that want to use Cloud 9 for this MEANjs stack.
1.  I was unable to use the Cloud 9 download option for MEANjs on Github.  Instead I copied the url and did a $ git clone url.  The MEANjs always seemed to load fine, but the bower, grunt, and npm installs were often slow and created an incomplete install.  Repeating the install never worked.
2.  When network speed (mine or c9?) was fast, I'd get a good install, but generally needed to do a npm bower update as recommended in the documentation.
3.  You create the Mongodb instance on c9 as follows:
  $ mkdir data
  $ echo 'mongod --bind_ip=$IP --dbpath=data --nojournal --rest "$@"' > mongod
  $ chmod a+x mongod  
and start it with a ./mongod (Note it's a dot/)  I use a new terminal window (alt T) for the mongod instance.
4.  You have to change server.js from app.listen(config.port) to 
app.listen(process.env.PORT || 3000, process.env.IP || '0.0.0.0', function(){}
5.  grunt in the lower terminal panel should get you going.

**Comment by mhenke** [comment]
Key for me was running comment 4 steps, then the ticket description steps

**Comment by mhenke** [comment]
Key for me was comment 4 steps, then step 3 & 4 in the ticket. Also not using grunt to start the server but a run task using server.js
