### ISSUE TITLE
Adding Custom User Fields

### ISSUE THREAD

**Issue by denzelwamburu** [meanjs/mean#400]
Creating custom fields when making CRUD modules for example article is fine,like the codes below
// Create new Article
		$scope.create = function() {
			// Create new Article object
			var article = new Article ({
				name: this.name,
                                category: this.category,
	                        rate: this.rate
			});
I also want to add custom fields to user.For example adding a gender field. The controllers for this seam different.Where are the controllers for User?

**Comment by sylvainlap** [comment]
Here : https://github.com/meanjs/mean/tree/master/app/controllers/users

**Comment by denzelwamburu** [comment]
@sylvainlap Thanks.I have a round way it but the main issue is in the controllers of angularjs.
When for example lets say binding the users DisplayName it goes something like this article.user.displayName and the output is the users display name.So after creating the new field how do i call something like article.user.gender to output the user's gender that is contained in the user's model?

**Comment by sylvainlap** [comment]
I don't really understand the issue here :/
Can you post some code so I can see your point ?

**Comment by denzelwamburu** [comment]
@sylvainlap 
	<small>
		<em class="text-muted">
			Posted on
			<span data-ng-bind="electronic.created | date:'mediumDate'"></span>
			by
			<a  span data-ng-bind="electronic.user.displayName"></a span>
                        in 
                       <a  span data-ng-bind="electronic.location"></a span>
                      and user is a 
                       <a  span data-ng-bind="electronic.user.gender"></a span>
		</em>
	</small>

electronic.created shows the date the item was created :+1: That is very fine.
electronic.location shows the loaction that the item was created in.Thats ok.No issue here.
electronic.user.displayName shows the User's display name that works very fine.
electronic.user.gender This is where the issue is.It is not displaying the users gender though i know there are some code's missing somewhere(where am trying to find out)that suppose to bind the user's gender.I have defined the gender model in the user.server.model.js

  gender: {
		type: String,
		default:'',
		validate: [validateLocalStrategyPassword, 'Password should be longer']
	},

Now the issue is how to i bind this data considering the are not from the same 'module'. I guess it should be something like article.user.gender or something near like that.
Hope it's clear right now.

**Comment by sylvainlap** [comment]
Why did you add the validateLocalStrategyPassword in the gender object ?

**Comment by denzelwamburu** [comment]
Ignore that i just copy pasted and still removing the validate it doesnt work.
The issue here is passing the objects that are in the server and model to the angular in the frontend.

**Comment by andreafdaf** [comment]
Have you checked the populate function? The default one look's like that:
```javascript
Article.find().sort('-created').populate('user', 'displayName').exec ...
```
to achieve what you're saying it should be replaced with:
```javascript
Article.find().sort('-created').populate('user', 'displayName gender').exec ...
```
If that's the issue I strongly suggest you to check mongoose's docs before proceeding with your coding (Y)

**Comment by wesleyfsmith** [comment]
@denzelwamburu I believe you want to do a GET request on /users/me . That will return the current logged in user, or a NULL if you aren't logged it.

**Comment by ilanbiala** [comment]
@denzelwamburu take a look at #343. We'll do all the refactoring in 1 PR.
