### ISSUE TITLE
Deleting User Cookie on Signout

### ISSUE THREAD

**Issue by jrogozen** [meanjs/mean#401]
Hi, I'm new to the MEAN stack and am trying to wrap my head around user authentication / authorization.

I edited the authentication.client.service.js file to include a function to check whether a user is an admin (client side)

```javascript
angular.module('users').factory('Authentication', [
  function() {
    var _this = this;

    _this._data = {
      user: window.user
    };

    function isAdmin() {
      var user = _this._data.user;
      
      if(_.contains(user.roles, 'admin')) {
        return true;
      }

      return false;
    }

    return {
      isAdmin: isAdmin,
      auth: _this._data
    };
  }
]);
```
Everything seems to work, except if a user signs out serverside (/api/signout), the window still holds the old user object. 

Is the best fix for this to attach a scope function to a logout button that would reset the window.user on the client side? Am I missing something otherwise?

Thanks!

**Comment by ilanbiala** [comment]
@jrogozen depending on the size of your application, you will want to do different things. If you are using a small email, then I would do what you are suggesting. If it's a larger app, I would make a general database service and when you call `auth.signout` or whatever, then call `db.fetchMe()` and that will set `window.user`. The database service could also manage articles, users, other interactions and act as a general client-side wrapper.

**Comment by jrogozen** [comment]
Thanks! Makes sense.
