### ISSUE TITLE
Angular dependency not defined  in Mean 0.3~ master

### ISSUE THREAD

**Issue by karan-kapoor90** [meanjs/mean#403]
I needed the socket functionality from the 0.4 branch and its working perfectly fine. Managed to get 1 to 1 messaging working between users by saving socket id's in the user model.

Anyways, in order to get it running, I added the 'Socket' dependency into my angular controller to the module 'socket' as follows : 
<code> angular.module('networks').controller('NetworksController', ['$scope','Socket',     '$stateParams','$http','$location', 'Authentication', 'Networks',
	function($scope, Socket, $stateParams,$http,$location, Authentication, Networks) {</code>

after doing so, I took out some code from this and decided to create a service in the same angular module as follows :
    <code>angular.module('socket').service('NotifFactory', [Socket, function(Socket) {</code>

However this gives me an error - Socket is not defined

Why does this happen and how can we fix this ?

**Comment by denzelwamburu** [comment]
@karan-kapoor90 have you tried using angular socket provider like https://github.com/btford/angular-socket-io then declare the module ['btford.socket-io'] ?
Should work perfectly

**Comment by karan-kapoor90** [comment]
That wasn't the issue. Never mind. Fixed it. Thanks.
