### ISSUE TITLE
Purpose of Controller "Read"

### ISSUE THREAD

**Issue by jrogozen** [meanjs/mean#405]
Hi,

I'm trying to wrap my head around 

```javascript
exports.read = function(req, res) {
	res.json(req.article);
};
```

I don't understand how this works in conjunction with 

```javascript
exports.articleByID = function(req, res, next, id) {
	Article.findById(id).populate('user', 'displayName').exec(function(err, article) {
		if (err) return next(err);
		if (!article) return next(new Error('Failed to load article ' + id));
		req.article = article;
		next();
	});
};
```
and 

```javascript
app.param('articleId', articles.articleByID);
```

Why not just put the articleByID code into the read function? Why have the read function at all?

Thanks!

**Comment by ilanbiala** [comment]
Because that article Middleware is used for multiple functions and it loads the article before any other handler runs. Use console.log to see what is happening.
