### ISSUE TITLE
how to get started with meanjs 0.4

### ISSUE THREAD

**Issue by danywheeler** [meanjs/mean#406]
since the doc is still 0.3 so , I'd like to know if I want get started with 0.4 what is the best way to do it . maybe use generator-meanjs ? if so , then I need the version 0.4 of generator ? any help would  appreciate. and I'd like to say , I've looked meanio but , I like meanjs , because it's code style , and fold structure.

**Comment by dlbrown06** [comment]
+1

**Comment by v4l3r10** [comment]
+1, the true problem is how migrate from  0,3 to 0.4 on a existing project :) but i'm waiting the release  of 0.4 ... i think  that the coder will add some info in the README.
About generating new project i think that  the YO generator has the same structure of 0.3... try it bro ;)

**Comment by berendt** [comment]
I documented how to install version `0.4-dev` at https://blog.berendt.io/your-first-mean-application-with-meanjs/. Maybe this is useful for the moment.

**Comment by lirantal** [comment]
Thanks Christian.
I'll make sure to tweet, and blog about it for the rest of the community.

On Mon, Feb 16, 2015 at 2:54 PM, Christian Berendt <notifications@github.com
> wrote:

> I documented how to install version 0.4-dev at
> https://blog.berendt.io/your-first-mean-application-with-meanjs/. Maybe
> this is useful for the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/406#issuecomment-74504113>.
>



-- 
-- 
Sincerely, Liran Tal
http://www.enginx.com

**Comment by metasean** [comment]
@v4l3r10 - I haven't been through it, but Shristi, over at Bossable, has a series of videos and blog entries where she converts an 0.3 app (built during her 30 day Honolulu Challenge series) to 0.4  - http://www.bossable.com/1211/meanjs-transition-to-0-4-part-1/   

@danywheeler & @dlbrown06 - You may also want to check out Shristi's "Install MEAN.js 0.4.0 and run using Gulp" video - http://www.bossable.com/1180/install-mean-js-040/ - She provides just a bit more information than @berendt's blog entry

**Comment by ilanbiala** [comment]
Moving to #443
