### ISSUE TITLE
Enhancement: Admin pages for users and roles

### ISSUE THREAD

**Issue by amobrem** [meanjs/mean#41]
Can something like the be added to the core product:

http://jedireza.github.io/drywall/

**Comment by cdupoiron** [comment]
+1 
@JonVisc Did you make any project with admin pages included since you posted?

**Comment by JonVisc** [comment]
I started to but  have only like 1 true day of solid dev on the implementation before I was pulled off onto different things.  :-/  Sorry for the let down.

**Comment by Trevogre** [comment]
Is there a design for the admin pages, or a feature list. I'm going to have to work on something for my current project. I'd like to not get too far off the path. I suppose I could attempt to contribute something.

I think I need add user / and edit user for the admin. Roles other than admin would be nice but I don't think necessary for the version of mean that I'm using since the permissions are mostly manually added in a final project.

**Comment by ckapop** [comment]
I noticed user roles were added to the User model: http://meanjs.org/changelog.html
Is there any documentation on the best way to use this feature? I do not think the generator supports it yet.

**Comment by v4l3r10** [comment]
in 0.3 i have found  a user.hasAuthorization module that helped me  to make an ACL system for REST:

```
app.route('/sales/:saleId')
        .get(sales.read)
        .put(users.requiresLogin, users.hasAuthorization(['admin']), sales.update)
        .delete(users.requiresLogin, users.hasAuthorization(['admin']), sales.delete);
```
and in user.roles model i have added different roles

 
and in  angularjs app added a new module called "admin" and filter it on menu with:
```
// Admin module config
angular.module('admin').run(['Menus',
    function(Menus) {
        Menus.addMenuItem('topbar', 'Admin', 'admin','dropdown',undefined,false,['admin']);
        Menus.addSubMenuItem('topbar', 'admin', 'Sale', 'admin/sales'); 
        Menus.addSubMenuItem('topbar', 'admin', 'Provider', 'admin/providers'); 
        Menus.addSubMenuItem('topbar', 'admin', 'User', 'admin/users'); 

    }
]);
```
addMenuItem accept a param that as an array of ROLES

**Comment by ckapop** [comment]
Thank you v4l3r10!

**Comment by trainerbill** [comment]
@roieki I made a small admin module to handle some user CRUD functions:

https://github.com/trainerbill/mean/tree/AdminConsole

Was wondering if you or someone on the project wanted to take a look and provide feedback.

**Comment by bastianwegge** [comment]
+1

**Comment by dillonlara115** [comment]
+1

**Comment by codydaig** [comment]
#676

**Comment by lirantal** [comment]
definitely @codydaig , thanks for looking into it, closing.
