### ISSUE TITLE
Social authentication with 0.4-dev not working

### ISSUE THREAD

**Issue by berendt** [meanjs/mean#410]
I tried to configure the social authentication (Google and Github) with `0.4-dev`. While it worked with version `0.3` it does not work with version `0.4-dev`. Clicking on `/api/auth/google` or `/api/auth/github` on `/authentication/signup` always routes me to `/`. Same for `/authentication/signin`. In `config/env/development.js` I added the correct `clientId` and `clientSecret` parameters. Do I have to configure anything else to make social authentication working with version `0.4-dev`?

**Comment by DanyWheeler** [comment]
are you using generator-meanjs ? if so , then check the config/env/*.js the callbackURL should started with /api/......   , check the github version , it's correct.

**Comment by berendt** [comment]
@DanyWheeler Yes I used `generator-meanjs` to generate the app. But the `callbackURL` for `github` is `/auth/github/callback` (I have not modified this entry). This is also the callback URL I added at https://github.com/settings/applications/ when registering a new application.

I think the issue is that I copied my modified signup/signin formulars from my first try with version `0.3` and the the callback URL changed from version `0.3` to `0.4`. I will check this now.

**Comment by berendt** [comment]
No local modifications in the views. The social auth URLs moved to https://github.com/meanjs/mean/blob/0.4.0/modules/users/client/views/authentication/authentication.client.view.html in version `0.4`. I do not know why, I had wrong entries in https://github.com/meanjs/mean/blob/0.4.0/config/env/development.js (missing `/api`). Probably I copied this file from my old `0.3` environment and have not checked it. I adjusted the file itself and updated the callback URL on Github but it is still not working.

**Comment by berendt** [comment]
It looks like the published `0.4-dev` version is broken. I installed a fresh environment with `npm install -g meanjs/generator-meanjs#0.4-dev` and bootstrapped the application. After the bootstrap the callback URL for Github is `callbackURL: '/auth/github/callback'` in `config/env/development.js` and not `/api/auth/github/callback` like in https://github.com/meanjs/mean/blob/0.4.0/config/env/development.js#L31.

**Comment by berendt** [comment]
It is a problem in `generate-meanjs` and not in `mean`. It looks like `generate-meanjs` does not deploy the latest version of `mean` at the moment. I think I misunderstood the usage of `generator-meanjs`. I thought that I have to use `generate-meanjs` in version `0.4-dev` to deploy the latest content of the `mean` repository. But this is wrong. After using `mean` as the base for my application (skipping `generate-meanjs`) everything is working like expected and I can use Github for social authentication. I think I have now understood how to not use `generator-meanjs` and how to directly use `mean` to bootstrap new applications. I will update my blog post at https://blog.berendt.io/your-first-mean-application-with-meanjs/ tomorrow to describe how to directly use `mean`.
