### ISSUE TITLE
I am having issues with getting angular-stripe working. 

### ISSUE THREAD

**Issue by countrdd** [meanjs/mean#420]
Unsure where to put this, in the layout system.

**Comment by ilanbiala** [comment]
Any code?

**Comment by countrdd** [comment]
Sorry. I actually figured it out.....but quick question. with stripe, they have a restfull were the meanstack rest will communication with stripe.js rest, this is done so the API key is not exposed on the SPA(client) side. Anyone done something like this with the CRUD?

**Comment by ilanbiala** [comment]
I don't understand.

**Comment by countrdd** [comment]
I will figure it out..

I just need to do CRUDS from the Client side to the server side, but on the server side it would not be accessing Mongo, would be getting data from another Rest API server.

**Comment by ilanbiala** [comment]
Checkout supertest.
