### ISSUE TITLE
document returned on article update have user password and roles field.

### ISSUE THREAD

**Issue by ravisuhag** [meanjs/mean#423]
/* Update article */

		exports.update = function(req, res) {
		    var article = req.article;
		    article = _.extend(article, req.body);

		    article.save(function(err) {
		        if (err) {
		            return res.status(400).send({
		                message: errorHandler.getErrorMessage(err)
		            });
		        } else {
		            res.json(article);
                            console.log(article.user);
		        }
		    });
		};

result
   
           {
				     "_id": "54b2489067fde3919071f08a",
				     "displayName": "Ravi Suhag",
				     "created": "2015-02-19T12:31:55.349Z",
				     "roles": [
				         "user"
				     ],
				     "password": "",
				     "email": "",
				     "lastName": "",
				     "firstName": ""
     }	

Is mongoose messing up here ?

**Comment by ilanbiala** [comment]
@ravisuhag is this still an issue?

**Comment by mleanos** [comment]
@ilanbiala I just tried to reproduce this behavior, and could not. Just these two fields are being returned.

```
{ displayName: 
  'Michael Leanos',
  _id: 5617bdec39b4417808bdf661 
}
```
We can probably close this.

**Comment by codydaig** [comment]
@ravisuhag Is this is still an issue, feel free to reopen.

**Comment by ravisuhag** [comment]
@codydaig  looks fine now. Thanks
