### ISSUE TITLE
module accessibility

### ISSUE THREAD

**Issue by szchenghuang** [meanjs/mean#427]
The menu items of the `articles` module are configured to be hidden from unauthenticated users. However, I can access them by entering URLs:

http://localhost:3000/#!/articles
http://localhost:3000/#!/articles/create

Is this intended?

I noticed that there is an `isPublic` property in the menu item and sub-menu item structures. By configuring that property as below
```
// In menu.clients.service.js
this.addMenu('topbar', true')

// In articles.client.config.js
Menus.addSubMenuItem('topbar', 'articles', 'New Article', 'article/create', undefined, false);
```
the `New Article` menu item becomes hidden while `List Articles` is inherently public. But access through URL http://localhost:3000/#!/articles/create is still possible. I am wondering if there should be a listener as below or something added to the sample `article` module to complete the design of the `isPublic` property? (Notice that the following code is not considered thoroughly.)
```
// In articles.client.config.js
$rootScope.$on('$stateChangeSuccess', function(event, toState, toParams, fromState, fromParams) {
    if (!Authentication.user) {
        var currentUrl = toState.url;
        var menu = Menus.getMenu('topbar');
        for (var itemIndex in menu.items) {
            for (var subitemIndex in menu.items[itemIndex].items) {
                if (menu.items[itemIndex].items[subitemIndex].uiRoute === currentUrl) {
                    if (!menu.items[itemIndex].items[subitemIndex].isPublic) {
                        event.preventDefault();
                        $location.path('/');
                    } 
                }
            }
        }
    }
});
```

**Comment by AndrewKerton** [comment]
I've been working on something similar but for the whole application. I want to validate the user is signed in before they can access anything on the site. 
I'm having trouble due to the "vertical module" design of the application because I don't want add a $stateChangeStart to all modules, I'd rather have a global state change listener.

Have you made any progress on your app?

**Comment by szchenghuang** [comment]
How about adding a listener to the unique`$rootScope` and placing your logic in that listener? Since `$rootScope` is unique per application, the listener can be triggered globally and therefore it doesn't need to be replicated in each module. I might consider `core` module's controller to be a place to inject the dependency of `$rootScope` since its name sounds more global than other modules. :)

Obviously the snippet I gave originally is placed to an improper location. The effect it takes is not meant for `Articles` only. On the other hand, I was not able to redirect the user to home at times if the listener I register is `stateChangeStart` but `stateChangeSuccess`.

In my app however, I later moved my actual functionality away from the navigation menu considering the action it takes subsequently.

**Comment by ilanbiala** [comment]
@szchenghuang is this still an issue for you?

**Comment by szchenghuang** [comment]
@ilanbiala, Hmmm..., not for now.
