### ISSUE TITLE
Uploading images

### ISSUE THREAD

**Issue by denzelwamburu** [meanjs/mean#429]
I know this question has been asked and has been around for quite sometime.
Am making an app where users should post images to server and the image retrieved in the view.
I need a way to store maybe the images url in the db,and a mongoose shema.The backend code i have is 
in the image.server.controller.js

//image upload handler

exports.imageUpload = function(req, res) {
    var file = req.files.file,
        path = './public/modules/images/img';

    // Logic for handling missing file, wrong mimetype, no buffer, etc.

    var buffer = file.buffer, //Note: buffer only populates if you set inMemory: true.
        fileName = file.name;
    var stream = fs.createWriteStream(path + fileName);
    stream.write(buffer);
    stream.on('error', function(err) {
        console.log('Could not write file to memory.');
        res.status(400).send({
            message: 'Problem saving the file. Please try again.'
        });
    });
    stream.on('finish', function() {
        console.log('File saved successfully.');
        var data = {
            message: 'File saved successfully.'
        };
        res.jsonp(data);
    });
    stream.end();
    console.log('Stream ended.');
};

I used multer to handle the upload https://github.com/expressjs/multer and i have already required it.

exports.imageUpload = function(req, res) {
    var file = req.files.file,
        path = './public/modules/images/img';

   // Logic for handling missing file, wrong mimetype, no buffer, etc.

    var buffer = file.buffer, //Note: buffer only populates if you set inMemory: true.
        fileName = file.name;
    var stream = fs.createWriteStream(path + fileName);
    stream.write(buffer);
    stream.on('error', function(err) {
        console.log('Could not write file to memory.');
        res.status(400).send({
            message: 'Problem saving the file. Please try again.'
        });
    });
    stream.on('finish', function() {
        console.log('File saved successfully.');
        var data = {
            message: 'File saved successfully.'
        };
        res.jsonp(data);
    });
    stream.end();
    console.log('Stream ended.');
};

I need to add angular controller and view in the client side.
i had a simple form with 
          enctype="multipart/form-data"
          action="/images"
          method="post">
    
Am stuck around here ,any help will be appreciated.

**Comment by ilanbiala** [comment]
This really isn't a MEAN.js question. Please post on SO or on the Google forum before coming here.

**Comment by karan-kapoor90** [comment]
... Or carefully look through the mean 0.4 code where you'll find all the
answers since the code is already there! 😊

**Comment by denzelwamburu** [comment]
@karan-kapoor90 Hey,am using mean 0.4, :( i can't see the code apart for the one of uploading user image.
