### ISSUE TITLE
Error with yo meanjs error access morgan 

### ISSUE THREAD

**Issue by radjivC** [meanjs/mean#430]
Hi, when I use the yo generator with sudo or without sudo, the generator can't read the .npm/ folder 

![capture d ecran 2015-02-26 a 11 48 36](https://cloud.githubusercontent.com/assets/5714138/6390548/74f9a9d2-bdad-11e4-9d4c-9583c620a922.png)

I made a github gist with my npm log at this adress, if you need more information.
 
https://gist.github.com/radjivC/44661c70ee8e3edac98c

Thank you

**Comment by ilanbiala** [comment]
Why `sudo`?

**Comment by radjivC** [comment]
Because I try without sudo and I saw an error access, so i tried sudo :(

**Comment by ilanbiala** [comment]
Do you get this error when working with other node projects that touch .npm?

**Comment by radjivC** [comment]
not other node project were working when I use yo generator

**Comment by ilanbiala** [comment]
@radjivC has this been resolved?

**Comment by ilanbiala** [comment]
I'm going to close this issue. If this still comes up, please repost on the generator repo.

**Comment by radjivC** [comment]
@ilanbiala it's still here, I will post the post on the generator repo, thanks for you help
