### ISSUE TITLE
npm install  error    bower install --config.interactive=false

### ISSUE THREAD

**Issue by chelsh** [meanjs/mean#431]
D:\rehu\ReHuManager>npm install          
npm WARN package.json rehumanager@0.0.1 No repository field.
\
> rehumanager@0.0.1 postinstall D:\rehu\ReHuManager
> bower install --config.interactive=false

bower angular#~1.2          not-cached git://github.com/angular/bower-angular.git#~1.2
bower angular#~1.2             resolve git://github.com/angular/bower-angular.git#~1.2
bower angular-mocks#~1.2    not-cached git://github.com/angular/bower-angular-mocks.git#~1.2
bower angular-mocks#~1.2       resolve git://github.com/angular/bower-angular-mocks.git#~1.2
bower angular-animate#~1.2  not-cached git://github.com/angular/bower-angular-animate.git#~1.2
bower angular-animate#~1.2     resolve git://github.com/angular/bower-angular-animate.git#~1.2
bower angular-sanitize#~1.2 not-cached git://github.com/angular/bower-angular-sanitize.git#~1.2
bower angular-sanitize#~1.2    resolve git://github.com/angular/bower-angular-sanitize.git#~1.2
bower angular-touch#~1.2    not-cached git://github.com/angular/bower-angular-touch.git#~1.2
bower angular-touch#~1.2       resolve git://github.com/angular/bower-angular-touch.git#~1.2
bower angular-ui-utils#~0.1.1       not-cached git://github.com/angular-ui/ui-utils.git#~0.1.1
bower angular-ui-utils#~0.1.1          resolve git://github.com/angular-ui/ui-utils.git#~0.1.1
bower angular-bootstrap#~0.11.2     not-cached git://github.com/angular-ui/bootstrap-bower.git#~0.11.2
bower angular-bootstrap#~0.11.2        resolve git://github.com/angular-ui/bootstrap-bower.git#~0.11.2
bower bootstrap#~3                  not-cached git://github.com/twbs/bootstrap.git#~3
bower bootstrap#~3                     resolve git://github.com/twbs/bootstrap.git#~3
bower angular-ui-router#~0.2.11     not-cached git://github.com/angular-ui/ui-router.git#~0.2.11
bower angular-ui-router#~0.2.11        resolve git://github.com/angular-ui/ui-router.git#~0.2.11
bower angular-resource#~1.2         not-cached git://github.com/angular/bower-angular-resource.git#~1.2
bower angular-resource#~1.2            resolve git://github.com/angular/bower-angular-resource.git#~1.2
bower angular-sanitize#~1.2           download https://github.com/angular/bower-angular-sanitize/archive/v1.2.28.tar.gz
bower angular-mocks#~1.2              download https://github.com/angular/bower-angular-mocks/archive/v1.2.28.tar.gz
bower angular-bootstrap#~0.11.2       download https://github.com/angular-ui/bootstrap-bower/archive/0.11.2.tar.gz
bower angular-ui-utils#~0.1.1         download https://github.com/angular-ui/ui-utils/archive/v0.1.1.tar.gz
bower angular-animate#~1.2            download https://github.com/angular/bower-angular-animate/archive/v1.2.28.tar.gz
bower angular#~1.2                    download https://github.com/angular/bower-angular/archive/v1.2.28.tar.gz
bower angular-touch#~1.2              download https://github.com/angular/bower-angular-touch/archive/v1.2.28.tar.gz
bower angular-ui-router#~0.2.11       download https://github.com/angular-ui/ui-router/archive/0.2.13.tar.gz
bower angular-resource#~1.2           download https://github.com/angular/bower-angular-resource/archive/v1.2.28.tar.gz
bower angular-mocks#~1.2               extract archive.tar.gz
bower angular-mocks#~1.2              resolved git://github.com/angular/bower-angular-mocks.git#1.2.28
bower angular-animate#~1.2             extract archive.tar.gz
bower angular-animate#~1.2            resolved git://github.com/angular/bower-angular-animate.git#1.2.28
bower angular-bootstrap#~0.11.2        extract archive.tar.gz
bower angular-touch#~1.2               extract archive.tar.gz
bower angular-bootstrap#~0.11.2   invalid-meta angular-bootstrap is missing "ignore" entry in bower.json
bower angular-bootstrap#~0.11.2       resolved git://github.com/angular-ui/bootstrap-bower.git#0.11.2
bower angular-touch#~1.2              resolved git://github.com/angular/bower-angular-touch.git#1.2.28
bower angular-ui-utils#~0.1.1          extract archive.tar.gz
bower angular-sanitize#~1.2            extract archive.tar.gz
bower angular-ui-utils#~0.1.1     invalid-meta angular-ui-utils is missing "ignore" entry in bower.json
bower angular-ui-utils#~0.1.1         resolved git://github.com/angular-ui/ui-utils.git#0.1.1
bower angular-sanitize#~1.2           resolved git://github.com/angular/bower-angular-sanitize.git#1.2.28
bower angular-resource#~1.2            extract archive.tar.gz
bower angular-resource#~1.2           resolved git://github.com/angular/bower-angular-resource.git#1.2.28
bower angular-cookies#~1.2              EAGAIN Request to https://bower.herokuapp.com/packages/angular-cookies failed: getaddrinfo EAGAIN

npm ERR! rehumanager@0.0.1 postinstall: `bower install --config.interactive=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rehumanager@0.0.1 postinstall script.
npm ERR! This is most likely a problem with the rehumanager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false
npm ERR! You can get their info via:
npm ERR!     npm owner ls rehumanager
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\rehu\ReHuManager
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     D:\rehu\ReHuManager\npm-debug.log
npm ERR! not ok code 0

**Comment by ilanbiala** [comment]
Retry it, it seems you had some connectivity problems.

**Comment by denzelwamburu** [comment]
hey @chelsh as of yesterday ,bower had issues but as of no they resolved the issue

**Comment by ilanbiala** [comment]
@chelsh seems like it should work now. Feel free to comment if you still have any issues.
