### ISSUE TITLE
yo meanjs  error

### ISSUE THREAD

**Issue by chelsh** [meanjs/mean#432]
npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.15 install script.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7600
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd D:\rehu\ReHuManager2
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

D:\rehu\ReHuManager2>node --version
v0.10.33

D:\rehu\ReHuManager2>npm --version
1.4.28

**Comment by denzelwamburu** [comment]
what version of yeoman are you using?

**Comment by ilanbiala** [comment]
Please repost this on the generator repo. Just a start, it looks like running `npm install` again may fix it. Try cleaning the cache as well with `npm cache clean`.
