### ISSUE TITLE
show utf charater in page

### ISSUE THREAD

**Issue by webnovin** [meanjs/mean#438]
I need to display characters on the page(home.client.view.html) and other page
but instead displays a question mark character,
How can I solve this problem?

**Comment by lirantal** [comment]
@webnovin I assume you need to show UTF-8 characters?
If so, it seems like the content type for the page is indeed set as UTF-8. Can you please confirm if that's not the case for you? (and also check whats the current content-type meta tag is set on your HTML page?

**Comment by codydaig** [comment]
Is this still an issue or can this be closed?

**Comment by lirantal** [comment]
quite old and no update so let's close for now.
