### ISSUE TITLE
is it able to separate front module and admin module in meanjs ?

### ISSUE THREAD

**Issue by danywheeler** [meanjs/mean#440]
I'd like to implement a website contain front page and admin page , the path looks like dev.joymv.net for front , dev.joymv.net/admin for admin , I know that meanjs loads all modules in one , so what I need to do to support this.  what is the best way to do this ?

**Comment by ilanbiala** [comment]
What's wrong with having two modules being loaded into the whole app module? This question is really more suited for StackOverflow by the way.

**Comment by danywheeler** [comment]
for instance if the front and admin page's layout is different or the admin page is only for desktop , or the front is only view in mobile . so we don't need to load them all.

**Comment by ilanbiala** [comment]
@danywheeler it's up to you and how you want your app to work. As long as it works, it doesn't matter too much and the structure will get better as you improve it.
