### ISSUE TITLE
Documentation for 0.4 branch

### ISSUE THREAD

**Issue by darko-mijic** [meanjs/mean#443]
Hello,

Does documentation for 0.4 branch exist? 
I would like to see the draft version and I would like to contribute.

Regards,
Darko

**Comment by Shrizzy** [comment]
There's no specific documentation for 0.4 yet, but you can find the current documentation on the gh-pages branch. If you're keen, perhaps start with moving across the reusable parts of the current doco into the docs/0.4 folder.

I've noticed a lot of repos using Jekyll, and Kramdown for documentation lately. An example is express.js: https://github.com/strongloop/expressjs.com

**Comment by codydaig** [comment]
Has there been any work on the docs for 0.4.0 or shall I get started setting up a Jekyll solution and populating it with content that applies from the previous version?

**Comment by codydaig** [comment]
Has anybody started on the 0.4.0 docs yet? Can I set-up a Jekyll solution and get rolling on moving the old documentation that still applies over?

**Comment by Shrizzy** [comment]
I haven't seen much happening with the docs. If you're able to kick things off, submit a PR and we'll go from there. 
Similar to Issue #294

**Comment by codydaig** [comment]
See Pull Request #649

**Comment by lirantal** [comment]
@codydaig yes, looks good.
please keep up the 0.4.0 documentation there and we also need to get more reviewers on that PR.

**Comment by codydaig** [comment]
Should the 0.4.0 documentation follow the same format and structure as the current documentation? Does anybody have any changes they would like to see happen?

**Comment by lirantal** [comment]
specifically I don't have any objections

**Comment by ilanbiala** [comment]
Condensed a few issues about 0.4 into this issue. For anyone who would like to contribute documentation to 0.4.0 @codydaig has helped us set up a Jekyll gh-pages site, so help us tie up loose ends and contribute any documentation you can!

**Comment by codydaig** [comment]
I submitted a pull request #652 which demonstrates how documentation can be added. I also restructured the permalinks which I outlined and explained in the pull request.

My current question for discussion: I have not used the Yo Generator very much, so I would like some guidance. I'm assuming that the current version of the generator will still be accessible once 0.4.0 is released. With this assumption, I would structure the Yo Generator section the same as the documentation.
I'd appreciate some feedback and guidance on the structure and on the yo generator section. 
Thanks!

**Comment by ilanbiala** [comment]
@codydaig the generator will be put on hold until we can properly establish a simple way of using the mean repo instead of copying over and updating the files manually. Also, there is too much flux right now so we can't really keep updating so quickly.

**Comment by ilanbiala** [comment]
I'm going to close this issue and we'll move future documentation discussion into more specific, separate issues if necessary.

**Comment by codydaig** [comment]
@ilanbiala Just to clarify: we're going to keep the generator out of the 0.4.0 documentation and just say clone the repo or download the source code as the installation options for now?

**Comment by ilanbiala** [comment]
Yes

**Comment by codydaig** [comment]
@ilanbiala Thanks! I will get started on that tomorrow.

**Comment by lirantal** [comment]
@codydaig I would leave the generator section there for people whom are targeting for that can find it and simply say there that the generator today works with the 0.3.0 stable version of MEAN.JS release, and not with the current master/0.4.0 branch.

**Comment by codydaig** [comment]
@lirantal i should have clarified. I'm going to take the generator out of the 0.4.0 section as an installation option. But I will put a note on top of the generator section on the website saying it only works for 0.3.0.

**Comment by lirantal** [comment]
cool
