### ISSUE TITLE
Config files merging issue

### ISSUE THREAD

**Issue by HappyTreesDev** [meanjs/mean#444]
While reading this article, http://www.ibm.com/developerworks/library/wa-mean2/index.html, the author pointed out that by default, the config files are not merged as one would expect. I believe that it should be changed.

The simple solution, explained in the article, is to go to config/config.js and change _.extend to _.merge

**Comment by ilanbiala** [comment]
@lirantal sounds good to me, but @HappyTreesDev is the order for which one takes precedence still correct?

**Comment by HappyTreesDev** [comment]
From what I saw, the order is correct how it is. Just change extend to merge and it should be good. All is imported first and then the other configuration is imported and overwrites what is needed.

**Comment by HappyTreesDev** [comment]
Actually, upon further reading, extend will combine the files and overwrite one level deep. Merge recursively overwrites. I still feel Merge makes more sense to me, but I am not sure what others might expect.

An example would be,
array1 = {a: something, b: { a:something}}
array2 = {a:new, b:{c:new}}

_.extend(array1,array2) = {a:new, b:{c:new}}
_.merge(array1,array2) = {a:new, b:{a:something, c:new}}

I am not quite sure which is preferred, but I feel now that I think of it that extend might be the more natural solution.

**Comment by lirantal** [comment]
I'm pretty sure the meaning here is to extend, not to merge.
Configuration options in more specific files, such as each environment, should be overriding any general configuration items.

**Comment by HappyTreesDev** [comment]
Sounds good to me. I was mistaken with my initial understanding of how the
function should work and it should stay how it is in my opinion.

**Comment by ilanbiala** [comment]
@HappyTreesDev I'm going to close this. Feel free to comment if you have any further questions.
