### ISSUE TITLE
$http duplicate calls 

### ISSUE THREAD

**Issue by karan-kapoor90** [meanjs/mean#447]
I've been using MEAN.js for a while and I noticed that after clicking on a button that say, for instance does an http.post, if I stay on the page for a while, the same post request is sent out again.
While I do know this is an angular.js issue, has anyone here been able to get past it so far? Its leading to multiple posts of the same data.

**Comment by ilanbiala** [comment]
@karan-kapoor90 can you give a specific case?

**Comment by jloveland** [comment]
@karan-kapoor90 are you seeing this with a form submission? 

If you are, I have seen this behavior when I submit a form on my app. The issue was related to having multiple buttons in the form: a couple buttons to add items to a list and a submit button. The problem was that I didn't add `type="button"` in the buttons that add items to the list.

see here:
http://stackoverflow.com/questions/26002377/angularjs-how-to-use-ng-click-without-submitting-the-form

**Comment by karan-kapoor90** [comment]
Oh! I'll have to check. What if I don't use forms at all?just pure simple
buttons. That should work too then, right?

**Comment by jloveland** [comment]
Correct, my note was assuming you were submitting a form. Sounds like you aren't, so my comment is not relevant to you.

If you give us more info on what you are doing, maybe the community could validate your issue.

**Comment by karan-kapoor90** [comment]
Ok so I looked into the code. I'm not using forms and all my buttons have <code>type="button"</code> set. But I still have the issue.

    <button type="button" class="btn btn-success btn-s" ng-click="uploader.uploadAll()" ng-disabled="!uploader.getNotUploadedItems().length">
					<span class="glyphicon glyphicon-upload"></span> Upload all
				</button>

If i leave the page open for a while, this button for instance, gets called again.

**Comment by ilanbiala** [comment]
It looks like you may be using a library. If you are, see if any options there have any effect. Buttons can't really get called by themselves in Angular so it must be some extra code that is doing it.

**Comment by karan-kapoor90** [comment]
I'm using the same uploader thats used in the mean 0.4 branch to upload user profile images. This is the same scenario depicted in #461 where the pages are not loading. 

for all GET / POST requests to server, the console gets stuck in as 


    GET /api/doSomething -- -- ms -- -- 

is it normal to not get a status code when initial loading?

Also the duplicate calls happen when the page has loaded and i click on a button that calls an http.post on a server route but nothing happens. On the console, I get the following, which then keeps repeating for  a while

    POST /api/doSomething -- -- ms -- --
    POST /api/doSomething -- -- ms -- --
    POST /api/doSomething -- -- ms -- --
    POST /api/doSomething -- -- ms -- --

I'm thinking maybe, what if the client side is all good and for some reason, the server is really not replying? Could be a network oriented issue as well ? Any idea on how I can debug and find out ?

**Comment by ilanbiala** [comment]
Check with console.log to see where the route handlers stop.

**Comment by karan-kapoor90** [comment]
that helped. Thanks
