### ISSUE TITLE
Session store should use mongoose for persisting sessions

### ISSUE THREAD

**Issue by edin-m** [meanjs/mean#451]
Currently we are using connect-mongo to store sessions. However this can complicate things if one were to use testing environment without database. When mocking with mockgoose there is issue because having connect-mongo mongo db is used directly. 

If we use session storage through mongoose then we would be able to mock entire underlying mongoose layer; and maybe sometime later use mongoose api to connect to other backends.

Is something like this possible, does it make sense?

**Comment by ilanbiala** [comment]
The session store requires no other implementation other than passing keys and such so why do we need to test it when connect-mongo already has tests.

**Comment by edin-m** [comment]
I'm referring to testing entire meanjs application without running mongodb server.
If we use mockgoose to mock mongoose usage of mongo db, the issue remains because connect-mongo uses native mongo driver to connect to mongo and if there is no mongodb then it fails.

**Comment by ilanbiala** [comment]
Why would you not test interaction with a database..?

**Comment by jloveland** [comment]
Here's some thoughts on why you would not want to mock the database when testing the database interaction:
http://stackoverflow.com/questions/12526160/mocking-database-in-node-js

It makes more sense to mock a service layer, but not the database interaction.

**Comment by ilanbiala** [comment]
@edin-m at this time we will not be mocking the database connection when testing. That's something that most users don't want, so if you would like to feel free to do so on your own.
