### ISSUE TITLE
Multiple Controllers

### ISSUE THREAD

**Issue by cliffeby** [meanjs/mean#452]
The following fails to load in the proper order on an intermittent basis.
```
angular.module('articles',[]);
angular.module('articles').controller('ArticlesController', ['$scope',...
angular.module('articles').controller('ModalCtrl', function ($scope,...
```
When failing, several grunt-test mocks report that ArticlesController is not a function.

I'm not familiar enough with the client plumbing, but I've read that for loading app.js should be after AngularJS but before any controllers / services / etc...otherwise angular won't be able to initialize your controllers.

For now, I'm using this in the ArticlesController:
```
var modalInstance = $modal.open({
                templateUrl: 'modules/articles/views/edit-xxx.client.view.html',
                controller:function ($scope, $modalInstance, xxx){...},...
```

**Comment by ilanbiala** [comment]
Please use code blocks when inserting code.

**Comment by cliffeby** [comment]
Should I resubmit?

**Comment by ilanbiala** [comment]
Just edit your posts above with code blocks.

**Comment by britztopher** [comment]
@cliffeby Do you have your function defined in your array like so:

```angular.module('articles').controller('ArticlesController', ['$scope', function($scope){...}]);```

**Comment by codydaig** [comment]
@cliffeby Is this still an issue?

**Comment by codydaig** [comment]
@cliffeby I'm closing this issue, however, feel free to reopen if it's still an issue.
