### ISSUE TITLE
0.4.0 and master roadmap

### ISSUE THREAD

**Issue by dotch** [meanjs/mean#455]
I was trying to find some info on what's keeping 0.4.0 from being merged into master since I was a little bit worried about those 2 branches diverging.
all I could find was a suggestion to do a hangout in  #344
are there any updates on this?

**Comment by ilanbiala** [comment]
Dupe of https://github.com/meanjs/mean/issues/402. Please search for other issues before posting a new one next time.

**Comment by dotch** [comment]
sorry! missed that one!
