### ISSUE TITLE
Server not loading pages 

### ISSUE THREAD

**Issue by garimaaswal** [meanjs/mean#461]
Our application has about 7-8 modules now, running on master 0.3 version of MEAN.js. Offlate, since the number of client js assets has increased alot, and all the assets are loaded the first time the user hits the page, the application has become very very slow. The GET requests in the log mostly show neither the 200 nor the 304 status code. 

Is anyone else having issue with slow load times in the project so far ? Any solutions ?
![image](https://cloud.githubusercontent.com/assets/10129931/6556260/68395060-c692-11e4-8f7b-31ccd41a210b.png)

**Comment by ilanbiala** [comment]
@garimaaswal you can concatenate the scripts into each module file to save on requests or even concatenate into 1 file if you have no naming conflicts.

**Comment by karan-kapoor90** [comment]
Hi ilan, is that good practise? Should that be done at runtime or should we
just do that at development time? Because then it makes so sense to have
this granular a folder structure of that's what we have to do in the end.

**Comment by ilanbiala** [comment]
Depends on your app's performance, in many cases it may be necessary to speed up initial page load time.

**Comment by karan-kapoor90** [comment]
Alright, I did as you suggested. Seems to have helped ALOT!! Thanks.
