### ISSUE TITLE
Getting a "Uncaught Reference" error to Angular Js when launched in production mode

### ISSUE THREAD

**Issue by neilhanekom** [meanjs/mean#466]
I needed to test whether I can run meanjs app in Production mode on a ubuntu machine before I attempt to continue to create anything further in the scaffolded project. 

So Constructed the Meanjs app through Yo and literally done nothing further and went on to grunt build.

So I performed a Grunt Build on  and set NODE_ENV=Production node server.(BTW whenever I set NODE_ENV=Production grunt I get a Fatal error: Unable to find local grunt.) 

When the app is running in "production" mode nothing happens but console displays the following error.
Uncaught ReferenceError: angular is not defined

Why is it doing this..??

**Comment by mbukosky** [comment]
I think I got this same issue before and I solved it by making sure that my config/env/production.js had the same references as the config/env/all.js . For some reason I needed to mirror my assest:lib:js changes from all.js to production.js

**Comment by adamwalz** [comment]
@mbukosky This is due to extending default and environment assets using `_.extend(object, sources)`. If a change is made to production client js assets then extend wipes out everything else in the default client assets object. I think a better alternative to this structure would be to flatten the assets structure instead of having nested objects so that extending can work as expected without having to copy so much.

For example. 
```
module.exports = {
  clientLibCSS:  [
    'public/lib/bootstrap/dist/css/bootstrap.min.css',
    'public/lib/bootstrap/dist/css/bootstrap-theme.min.css',
  ],
  clientLibJS: [
    'public/lib/angular/angular.min.js',
    'public/lib/angular-resource/angular-resource.min.js',
    'public/lib/angular-animate/angular-animate.min.js',
    'public/lib/angular-ui-router/release/angular-ui-router.min.js',
    'public/lib/angular-ui-utils/ui-utils.min.js',
    'public/lib/angular-bootstrap/ui-bootstrap-tpls.min.js',
    'public/lib/angular-file-upload/angular-file-upload.min.js'
  ],
  clientCSS:  'public/dist/application.min.css',
  clientJS: 'public/dist/application.min.js'
};
```

**Comment by mbukosky** [comment]
That makes sense, thanks for explaining

**Comment by ilanbiala** [comment]
@neilhanekom problem solved?

**Comment by simison** [comment]
@neilhanekom @ilanbiala close perhaps?
