### ISSUE TITLE
Error: error:unpr Unknown Provider after minification happens in grunt build

### ISSUE THREAD

**Issue by neilhanekom** [meanjs/mean#467]
When I run Meanjs in Production mode, after I did a grunt build the authentication service when used/ Injected in any controller throughs up a "Unknown Provider Error" in the Console:

Error: [$injector:unpr] http://errors.angularjs.org/1.3.14/$injector/unpr?p0=AuthenticationProvider%20%3C-%20Authentication%20%3C-%20HomeController

This is most definetly an issue with the grunt build and minification. However I dont know how to solve this....

**Comment by mbukosky** [comment]
Did you try looking at #360 ?

**Comment by neilhanekom** [comment]
been looking at it all day. Am I to use NODE_ENV=production grunt build..?
I see there is a fix but where to Get this.......?


On Tue, Mar 10, 2015 at 4:04 PM, Mike Bukosky <notifications@github.com>
wrote:

> Did you try looking at #360 <https://github.com/meanjs/mean/issues/360> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/467#issuecomment-78058936>.
>



-- 

Neil Hanekom
082 098 1180 (C)
neilhanekom1@gmail.com

**Comment by mbukosky** [comment]
I believe the fix is pending a [PR](https://github.com/FREEZX/mean/commit/a10805bfae19548e40e675517d62c7b0a558b2fe)

If you make these changes locally does it work for you?

**Comment by neilhanekom** [comment]
Oaky so I changed the gruntfile according to fix in #464. Now there is no
minification happening at all. Console throws : Warning: Task "loadConfig"
not found. Used --force, continuing...


On Tue, Mar 10, 2015 at 4:35 PM, Mike Bukosky <notifications@github.com>
wrote:

> I believe the fix is pending a PR
> <https://github.com/FREEZX/mean/commit/a10805bfae19548e40e675517d62c7b0a558b2fe>
>
> If you make these changes locally does it work for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/467#issuecomment-78065673>.
>



-- 

Neil Hanekom
082 098 1180 (C)
neilhanekom1@gmail.com

**Comment by mbukosky** [comment]
Odd, do you have a repo I can clone? I can try looking at it later tonight.

**Comment by neilhanekom** [comment]
Sure Thanks very much. I am going to send you a repo shortly.


On Tue, Mar 10, 2015 at 5:45 PM, Mike Bukosky <notifications@github.com>
wrote:

> Odd, do you have a repo I can clone? I can try looking at it later tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/467#issuecomment-78081520>.
>



-- 

Neil Hanekom
082 098 1180 (C)
neilhanekom1@gmail.com

**Comment by neilhanekom** [comment]
https://github.com/neilhanekom/avuxeni.git

On Tue, Mar 10, 2015 at 5:45 PM, Mike Bukosky <notifications@github.com>
wrote:

> Odd, do you have a repo I can clone? I can try looking at it later tonight.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meanjs/mean/issues/467#issuecomment-78081520>.
>



-- 

Neil Hanekom
082 098 1180 (C)
neilhanekom1@gmail.com

**Comment by mbukosky** [comment]
Thanks, will clone later tonight.

**Comment by mbukosky** [comment]
I think I figured out the issue of why you are getting the 'loadConfig' issue. It is because you are missing the custom task in your gruntfile.js

```
	// A Task for loading the configuration object
	grunt.task.registerTask('loadConfig', 'Task that loads the config into a grunt option.', function() {
		var init = require('./config/init')();
		var config = require('./config/config');

		grunt.config.set('applicationJavaScriptFiles', config.assets.js);
		grunt.config.set('applicationCSSFiles', config.assets.css);
	});
```

After adding this, I was able to get rid of the warning. But please note I was still not able to get the landing page to load. You will need to point the correct assets for your js and css. Your project has a different layout then MEAN so I couldn't figure out the ideal solution for you tonight.

Hope this helps

You can see my [gruntfile](https://github.com/mbukosky/SpotifyUnchained/blob/master/gruntfile.js) as a working example.

**Comment by lirantal** [comment]
looks like its resolved?
