### ISSUE TITLE
Mean 0.4 io.use called on clicking 'Chat'

### ISSUE THREAD

**Issue by karan-kapoor90** [meanjs/mean#473]
I was going through the mean 0.4 code and I noticed that the io.use middleware loading is called when the user clicks on the Chat item on the top menu, and not on first time page loading/ user login. Can't find the code that actually does that. Can anybody help?

**Comment by mleanos** [comment]
@karan-kapoor90 Do you still need help with this?

I believe this was fixed with #701

**Comment by ilanbiala** [comment]
@karan-kapoor90 closing, if you still need help please provide more info and we will revisit it.
