### ISSUE TITLE
the CURD of the generator for 0.4.0version does not work right

### ISSUE THREAD

**Issue by spyhole** [meanjs/mean#476]
whan i call "yo meanjs:curd-module customer", it call works as "yo meanjs".

**Comment by Shrizzy** [comment]
To create a vertical (crud) module in 0.4.0, please use this syntax: 
yo meanjs:vertical-module <entity>
so for your example, it would be: yo meanjs:vertical-module customer

Closing this issue - please have a look at this issue in the generator-meanjs repo: https://github.com/meanjs/generator-meanjs/issues/79

**Comment by spyhole** [comment]
thx @Shrizzy !

**Comment by bhavik3184** [comment]
yo meanjs:vertical-module companies doesn't work on my machine. I have windows 8.1

**Comment by sjamesbennettjr** [comment]
@bhavik3184 Are you getting an error message?

**Comment by bhavik3184** [comment]
@sjamesbennettjr noep it simply restarts with the question that it would, when we execute "yo meanjs"

**Comment by front-thinking** [comment]
@Shrizzy  tkx for your videos.

**Comment by ejeremias** [comment]
Hi Shrizzy
Thanks for you videos. I´m at Day 9, until here every things it's ok, but now I'm beached to generate the crud-module. Can you help? I used the two forms but a get the same error below:

You don't seem to have a generator with the name meanjs:vertical-module installed.
You can see available generators with npm search yeoman-generator and then install them with npm install [name].
To see the 1 registered generators run yo with the `--help` option.
PS C:\nodejs\projectos\myMEANProjecto>

**Comment by mdata2** [comment]
@ejeremias having the same issues you have.. Have you found a fix for it?

**Comment by ejeremias** [comment]
Unfortunately not yet. This same complicated! Can anyone help us?

**Comment by ilanbiala** [comment]
Hey everyone, please make an issue on the generator repo for any lingering issues, as this repo is for the framework and we're trying to keep it more organized so everything is in one place.
