### ISSUE TITLE
First login socket messages not going through

### ISSUE THREAD

**Issue by karan-kapoor90** [meanjs/mean#482]
I copied the socket implementation from the 0.4 branch to 0.3 and it works fine. However instead of calling the `this.Socket=io()` in the chatController like it is, in the 0.4 app, I call it in the AuthenticationController, as follows 

    app.controller('AuthenticationController', ['$scope', '$http', '$location', '$state', 'Authentication','Socket','socketFactory',
    function($scope, $http, $location, $state, Authentication,Socket,socketFactory) {

        $scope.authentication = Authentication;
        if (Authentication.user) 
            this.Socket = io();
            //this.Socket = io('http://vesmed-karan-kapoor-2.c9.io/');
            //this.Socket = socketFactory({ioSocket: io.connect('http://vesmed-karan-kapoor-2.c9.io/')});
        $scope.userType = ['doctor', 'patient','sponsor'];
        Socket.on('refreshSocket',function(data){
            $scope.authentication.user.socketid = data.myId;
            Authentication.user.socketid = data.myId;
            console.log('####### Refresh from auth cont');
        });

so it's called right as soon as the user logs in. On the server side, in the socket.io.js

    io.on('connection', function(socket) {
        //to resolve the location of chat.server.socket.config.js along with other possible files
        console.log('Connection event triggered on server');
        io.to(socket.id).emit('refreshSocket',{myId : socket.id});
        socket.broadcast.emit('isAlive',{user : socket.request.user._id, socketid : socket.id});
        config.files.server.sockets.forEach(function(socketConfiguration) {
            require (path.resolve(socketConfiguration))(io, socket);
        });
    });

always prints 

    Connection event triggered on server

The server is set to listens to 'chatMessage' events as 

    socket.on('chatMessage', function(message) {
        console.log('%%%%%%%%%%\n chat event emitted \n %%%%%%%%%%%%%%%%');
        message.source = socket.request.user._id;
        User.findOne({_id:message.target._id},'socketid', function(err,user){
            if (err){
                message.type = 'status';
                message.text = 'Oops! Something went wrong. Please try again after a while.';
                message.username = '';
                io.to(socket.id).emit('chatMessage', message);
                //do nothing, pass message to be inserted into users list of messages
                return err;
            } else if (user.socketid){
                //checking if the target user has an active connection
                var socketList = io.sockets.server.eio.clients;
                if (socketList[user.socketid] === undefined){
                    //socketid did not get removed correctly, the user is not online
                    saveMessages(socket.request.user._id,message.target._id,message.text);
                    message.type = 'status';
                    message.text = 'Message will be delivered when '+message.target.firstName+' is online!';
                    message.username = '';
                    io.to(socket.id).emit('chatMessage', message);
                    removeSocketId(message.target._id);
                }else {
                    //socketid is legit and is online!
                    message.type = 'message';
                    message.created = Date.now();
                    message.profileImageURL = socket.request.user.profileImageURL;
                    message.username = socket.request.user.firstName;
                    io.to(user.socketid).emit('chatMessage', message);
                    user.socketid='';
                    saveMessages(socket.request.user._id,message.target._id,message.text);
                }
            } else {
                //since target does not have a socketid, save message in chat history and send status message to sending user.
                saveMessages(socket.request.user._id,message.target._id,message.text);
                message.type = 'status';
                message.text = 'Message will be delivered when '+message.target.firstName+' is online!';
                //message.created = Date.now();
                //message.profileImageURL = socket.request.user.profileImageURL;
                message.username = '';
                io.to(socket.id).emit('chatMessage', message);
            }
        });

    });

**The problem**

As soon as my server starts, I login with a  user and click a button to emit a chatMessage event as follows

    $scope.sendIm = function(){
            if (this.chatText) {
                var message = {
                    target: $scope.targetUser,
                    text: this.chatText,
                    username: 'Me',
                    profileImageURL: $scope.authentication.user.profileImageURL,
                    created: Date.now()
                };
                //push to end of array, not top
                messages.push(message);
                console.log('******* Sending IM **********');
                Socket.emit('chatMessage',message);
                this.chatText='';   
            }
        };

I get the `******* Sending IM **********` console.log on the client when I send the message but not the 
`%%%%%%%%%%\n chat event emitted \n %%%%%%%%%%%%%%%%` on the server console.

This means that the server is not getting intimated about the 'chatMessage' event. If I refresh the client page and then click the button to send a message, the chatMessage event is successfully fired and I see the `%%%%%%%%%%\n chat event emitted \n %%%%%%%%%%%%%%%%` on the server console.

Anybody knows what I could be doing wrong?

**Comment by codydaig** [comment]
@karan-kapoor90 Are you still having issues?

**Comment by lirantal** [comment]
I believe @mleanos #701 fixes this. @karan-kapoor90 can you confirm?

**Comment by rhutchison** [comment]
@karan-kapoor90 Can you share your full chat implementation?  I like what I see

**Comment by lirantal** [comment]
@karan-kapoor90 I'm closing this one as we already provided a fix in PR #701 on the 0.4.0 branch.
