### ISSUE TITLE
server side route tests not working in 0.4.0 branch

### ISSUE THREAD

**Issue by deepakbhattarai** [meanjs/mean#486]
the `app`  is not exported in the server.js file. Message
``
timeout of 2000ms exceeded
``
I think the problem is because the variable `server` is not exported in the `server.js` file. So there is no server running in the test.

**Comment by ilanbiala** [comment]
@deepakbhattarai more details please.

**Comment by deepakbhattarai** [comment]
The error is in this code. This hook gives a timeout
``
	before(function(done) {
        var app = express.init(mongoose);
        agent = request.agent(app);
        done();
	});
``

The error
``

  1) Article CRUD tests "before all" hook:
     Error: timeout of 2000ms exceeded
      at done (D:\webdocuments\china-volunteers\node_modules\mocha\lib\runnable.
js:205:67)
      at D:\webdocuments\china-volunteers\node_modules\mocha\lib\runnable.js:226
:9
      at Server.<anonymous> (D:\webdocuments\china-volunteers\modules\articles\test
s\server\article.server.routes.tests.js:29:13)
      at Server.g (events.js:180:16)
      at Server.EventEmitter.emit (events.js:92:17)
      at net.js:1055:10
      at process._tickDomainCallback (node.js:463:13)
``

**Comment by ilanbiala** [comment]
Put in console.log throughout the functions to see where it stops. Then see what's wrong with the isolated statements.

**Comment by deepakbhattarai** [comment]
`before` is never completed. It gives a timeout. It stops in 'done()' line.

**Comment by ilanbiala** [comment]
Where is the last console.log that you see? You have something hanging when you call express.init most likely.

**Comment by TsarS** [comment]
Same issue 
  timeout of 2000ms exceeded   in test

**Comment by TsarS** [comment]
Same issue on fresh install 
 timeout of 2000ms exceeded

**Comment by netusco** [comment]
Same issue on fresh install 
timeout of 2000ms exceeded

**Comment by lirantal** [comment]
can you make sure you've got the latest master branch checked out please?
there is some issue there though, I'll submit a PR to fix it later tonight

**Comment by netusco** [comment]
ok I was a few commits behind and with the latest master branch checked out all tests pass smothly ;)

**Comment by lirantal** [comment]
great.
there is anyway an issue there with that test that I'll commit a fix in a couple of hours

**Comment by deepakbhattarai** [comment]
Great. It is working in the master branch.
