### ISSUE TITLE
Path problems in gulp tasks on Windows

### ISSUE THREAD

**Issue by gsavoie** [meanjs/mean#488]
So I've been trying to use Sass with .scss files and I noticed that when the gulp task runs it should be replacing '/scss' by '/css' but on Windows at this point we have something that looks like 'module\\client\\scss'.
Note: The less task also has the same problem. Perhaps the grunt config is also problematic.

For now I changed path.dirname.replace('/scss', '/css') to path.dirname.replace('scss', 'css') since it does the same thing but I'm not sure this is a good solution. If someone were to call their module "fooless" that could be problematic I guess...

What you guys think? Should we incorporate something like https://www.npmjs.com/package/slash to support both and keep the slashes? Add a string replace for the \\ to /?

Let me know and I can make the PR.

**Comment by ilanbiala** [comment]
Why not just do `path.dirname.replace(/(\/|\\)scss/, '$1css')`? This will handle both Windows and *nix.

**Comment by gsavoie** [comment]
For some reason I kept thinking with two steps! That does indeed work perfectly.
I also checked for grunt and the way it's done is different, we do not encounter this issue.

Should I make a PR ?

**Comment by ilanbiala** [comment]
A PR for 0.4.0 would be great!

**Comment by gsavoie** [comment]
Good, I'll work on that for 0.4.0, I don't think we have gulp on master anyway!

**Comment by gsavoie** [comment]
Alright @ilanbiala, I just created the PR #489 with those changes, simple changes but let me know if there's any issue :)

**Comment by rhutchison** [comment]
This was resolved by #666 (https://github.com/Gym/mean/commit/3e378b4a54f7393b0fbe9f522fdd4a329c41b5f4)

Close

**Comment by lirantal** [comment]
Thanks Ryan, closing.
