### ISSUE TITLE
Mean JS Angular App to Use Style Guide

### ISSUE THREAD

**Issue by britztopher** [meanjs/mean#490]
I am wondering if we could start following the john papa style guide for the angular application.  It proves to serve a lot of great ideas and fundamentals.  

https://github.com/johnpapa/angular-styleguide

**Comment by ilanbiala** [comment]
@britztopher Any initial changes that you think should be made?

**Comment by SOSANA** [comment]
Maybe I am miss understanding but we are doing this already for v4.0 we changed the file structure similar to what he recommends...

around 4:49
![image](https://cloud.githubusercontent.com/assets/2634185/6794567/f807e876-d198-11e4-8121-4fa49bb1bfac.png)

John Papa - 10 AngularJS Patterns - Code on the Beach 2014
https://www.youtube.com/watch?v=UlvCbnKAH3g

**Comment by ilanbiala** [comment]
I'm sure there are other things that could be changed, but I don't think everyone will necessarily agree with everything he recommends.

**Comment by britztopher** [comment]
@ilanbiala I would say these would be a good start:
1. Use IIFE's - https://github.com/johnpapa/angular-styleguide#iife  
2. Controllers - https://github.com/johnpapa/angular-styleguide#controllers
  a.  the whole section is really good and would be that hard to change some files
3. services - https://github.com/johnpapa/angular-styleguide#services

I mean I seem to follow the whole guide with a little deviation from folder/file structure, which makes code a lot easier to read and maintainable.  Also, the style guide does point out some good reasons why to do certain things.  Like why to use IIFEs.

@SOSANA the structure is on the ball, however, internals are not.

**Comment by Shrizzy** [comment]
Great idea @britztopher
One of the first things I do with a new meanjs app is split up the controllers into smaller components, remove the ng-init's and change the controllers to 'Controller as'. 
I'd really like to see the Controller As syntax, and removed references to $scope as we edge closer to Angular 2.0.

**Comment by aarosil** [comment]
This not entirely related but I think an awesome feature would be to be
able to provide your own templates to the generator.  Then one can follow
whatever style one likes or needs.

I often scaffold an app, then customize one module for specific needs of
that app, and after that I use `yo` to generate a new vertical module, and
replace the autogenerated files with what I customized and do a global
search and replace for the object name.

**Comment by wormyy** [comment]
+1 for using John Papa's style guide.

**Comment by simison** [comment]
Sounds like we could finally get rid of pre written annotations as well:

write:
```
angular.module('articles').controller("ArticlesController", function($scope, $stateParams, $location, Authentication, Articles) {
});
```
instead of:
```
angular.module('articles').controller('ArticlesController', ['$scope', '$stateParams', '$location', 'Authentication', 'Articles',
	function($scope, $stateParams, $location, Authentication, Articles) {
}]);
```

...and let [ng-annotate](https://www.npmjs.com/package/ng-annotate) do the job.

**Comment by jloveland** [comment]
+1

**Comment by mleanos** [comment]
+1

**Comment by ilanbiala** [comment]
Closing in favor of #636.
