### ISSUE TITLE
Email Integration

### ISSUE THREAD

**Issue by denzelwamburu** [meanjs/mean#491]
I just thought is it possible to add email feature in the boilerplate? 
Maybe add custom codes or apis from email clients.

**Comment by SOSANA** [comment]
@denzelwamburu Refer to the docs to implement email , SendGrid has cool tutorial.

**Comment by ilanbiala** [comment]
Specifically what? We already set up Nodemailer, what else are you looking for?

**Comment by denzelwamburu** [comment]
Is this feature on both of the versions

**Comment by ilanbiala** [comment]
It is already in master and will be in 0.4.0 in a better way.

**Comment by denzelwamburu** [comment]
Great i can't wait to try it further, in the mean time i will keep this issue closed.
