### ISSUE TITLE
Authentication service is reset to an empty string when redirected

### ISSUE THREAD

**Issue by c1moore** [meanjs/mean#493]
I noticed in my application, which has different levels of access for users (admin, user, ect.), that when a user is redirected from a page to which they should not have access (e.g.: an admin page when they are a normal user) that Authentication.user is reset to an empty string.

In my application, only registered users should see a page other than the sign in/sign up page.  So when a logged in user is redirected from the restricted page to the homepage, the homepage immediately redirects them to the sign in page and they are required to sign back in, which appears to be the expected behavior.  However, if the user refreshes the page, Authentication is reset to the value in window.user and is redirected to the homepage.  As log as the user does not attempt to access any data restricted to the user that was stored in window.user, the current user can access all information.  I believe window.user should also be set to null when setting Authentication.user to null to ensure that this cannot happen.

**Comment by ilanbiala** [comment]
@c1moore is this still an issue for you?

**Comment by c1moore** [comment]
I have fixed this in my own project, but, as I stated in the [pull request](https://github.com/meanjs/mean/pull/494), the code where the bug exists in the most recent version of mean is still the same.  I have not been able to run tests with the most recent version yet.  If you wish to close this issue before testing, go ahead, but it may be an overlooked security hole for other users.

**Comment by ilanbiala** [comment]
@c1moore there was no movement on that PR. @lirantal @codydaig do you still see this as an issue?

**Comment by jloveland** [comment]
@c1moore I would like to help reproduce what you are seeing. I can't seem to do this. If I try to access the following url without admin role http://localhost:3000/admin/users, I get a forbidden message in the ui
![screen shot 2015-11-03 at 10 18 37 pm](https://cloud.githubusercontent.com/assets/3456708/10928689/f428c982-8278-11e5-8387-659411d9be86.png)

I get redirectd to http://localhost:3000/forbidden. I do not get logged out.

Can you help me try to reproduce by pulling from master, reproducing, and posting very detailed instructions on the steps you took?

**Comment by mleanos** [comment]
I'm experiencing the same behavior that @jloveland reported. 

Doesn't look like this is an issue anymore.

**Comment by ilanbiala** [comment]
@c1moore can you just double check against current master?

**Comment by lirantal** [comment]
Closing old issue.
