### ISSUE TITLE
minifying meanjs(0.4) project with grunt/uglify breaks my app when in Production with $injector err

### ISSUE THREAD

**Issue by neilhanekom** [meanjs/mean#496]
Hi Guys, 

I am sitting with this issue with app when ran in production mode. I think the best approach now is to describe what is in my project so whoever sees this might have an Idea of what I am trying to accomplish an if someone has dealt with before.

What is in my Project/app:
- Meanjs 0.4 branch
- Angular ~1.3
- Angular-material

Check out my repository to see what is in there: https://github.com/neilhanekom/tzn.git

When I do a grunt build to test if my app could run in production I do grunt build for production. This create the application.min.js an application.min.css file in my public/dist folder.

However when I perform a "NODE_EN=production node server" the console spits out an [$injector:unpr] http://errors.angularjs.org/1.3.15/$injector/unpr?p0=AuthenticationProvider%20%3C-%20Authentication%20%3C-%20HeaderController

What I am assuming is that somewhere in the minification process with uglify something is going wrong. 

I dont know what particular to angular-material and minifying this is breaking my app.

Can anyone help here.. I quite desperate for a solution.

**Comment by ilanbiala** [comment]
This is using angular-material, which is not what MEAN.JS uses and therefore can't really be fixed here. You should post on Stackoverflow or on Angular-material's repository.
