### ISSUE TITLE
Page not found handler not working in 0.4.0

### ISSUE THREAD

**Issue by debrouxl** [meanjs/mean#501]
Steps to reproduce:
* clone the repository;
* run `npm install`;
* run `grunt`;
* load an URL for which there's no route, e.g. http://localhost:3000/abcdefghijklmnopqrstuvwxyz (why not ;) )

Expected result:
* a 404 status code and a redirection to http://localhost:3000/not-found , displaying an error message.

Actual result:
* a 200 status code and a redirection to http://localhost:3000 , effectively displaying the root page.

If I remove the "*" from the last route of modules/core/server/routes/core.server.routes.js, the 404 functionality is restored; however, sign up, sign in and pretty much everything else is broken, because of the fallback to the error routes defined in config/lib/express.js. I haven't yet found what the correct fix is.

I noticed the issue on my own testing application, when the server not only produced a 200 status code, but also the HTML content of the root page, when requested an image which wasn't there.

**Comment by dotch** [comment]
in case we want to keep the redirect to `/` where it might make sense we could just add this to `core.server.routes.js`:

``` javascript
// Return a 404 for all undefined api, module or lib routes
app.route('/:url(api|modules|lib)/*').get(core.renderNotFound);
```

in case we want a 404 for every undefined route we should define the root rout explicitly, by removing the `*` and our error routes kick in and do the rest for us:
``` javascript
// Define application route
app.route('/').get(core.renderIndex);
```

**Comment by dotch** [comment]
Since we are using html5-mode routes, anguler is responsible for showing 404 pages for most routes, right?
so guess we should handle the server side 404s like this:
``` javascript
// Return a 404 for all undefined api, module or lib routes
app.route('/:url(api|modules|lib)/*').get(core.renderNotFound); 
```
and either keep the redirect for everything else or implement angular based 404 logic as well.

**Comment by lirantal** [comment]
I assume we can close this now that we merged #566 ?

**Comment by mleanos** [comment]
I've verified this is working after merging #566. The app is responding with the not-found route on the front-end, when a non existing route is requested.

**Comment by codydaig** [comment]
Verified. Let's close.
