### ISSUE TITLE
Socket with meanjs

### ISSUE THREAD

**Issue by nidhin001** [meanjs/mean#504]
Hi, I'm new to meanjs. Can some one help me how to use socket with meanjs to get real time updation.

**Comment by YoannB** [comment]
Nice totu here : https://vexxhost.com/blog/mean-socket-io-integration-tutorial/

**Comment by codydaig** [comment]
The 0.4.0 branch also integrates socket.io for the chat module.

@nidhin001 Did your question get solved / can this issue be closed?

**Comment by nidhin001** [comment]
@codydaig  yeah. it is solved. thank you
