### ISSUE TITLE
0.4.0 not work on node 0.12.2

### ISSUE THREAD

**Issue by blueflagbj** [meanjs/mean#505]
0.4.0 not work on node 0.12.2！

When I installed it by generator-meanjs 0.4 ，I got this：
-----
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-contrib-cssmin will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-ng-annotate will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-csslint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-nodemon will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.2 included from grunt-node-inspector will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-less will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-jshint will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency mocha@>=1.20.0 included from grunt-mocha-test will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-uglify will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@0.4.x included from grunt-karma will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@>=0.4.0 included from grunt-contrib-sass will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-contrib-watch will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-protractor-runner will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN excluding symbolic link build\defs-config.json -> ../defs-config.json
npm WARN optional dep failed, continuing fsevents@0.3.5
-

> ws@0.4.31 install E:\webstorm\JiaYi\node_modules\socket.io\node_modules\engine.io\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

-
E:\webstorm\JiaYi\node_modules\socket.io\node_modules\engine.io\node_modules\ws>if not defined npm_config_node_gyp (no
(rebuild) am Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild \
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})

> phantomjs@1.9.16 install E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs
> node install.js

Download already available at C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip
Extracting zip contents
Removing E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Copying extracted folder C:\Users\ADMINI~1\AppData\Local\Temp\phantomjs\phantomjs-1.9.8-windows.zip-extract-1427986259
6\phantomjs-1.9.8-windows -> E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phanto
Writing location.js file
Phantom installation failed { [Error: EPERM, operation not permitted 'E:\webstorm\JiaYi\node_modules\karma-phantomjs-l
ncher\node_modules\phantomjs\lib\phantom\phantomjs.exe']
  errno: -4048,
  code: 'EPERM',
  path: 'E:\\webstorm\\JiaYi\\node_modules\\karma-phantomjs-launcher\\node_modules\\phantomjs\\lib\\phantom\\phantomjs
xe',
  syscall: 'chmod' } Error: EPERM, operation not permitted 'E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\no
_modules\phantomjs\lib\phantom\phantomjs.exe'
    at Error (native)
    at Object.fs.chmodSync (evalmachine.<anonymous>:948:18)
    at Object.chmodSync (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\f
extra\node_modules\graceful-fs\polyfills.js:141:17)
    at Promise._successFn (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\install.js:1
:8)
    at Promise._call (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\
w.js:373:13)
    at Promise._withInput (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules
ew\kew.js:333:25)
    at Promise.resolve (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\ke
kew.js:105:27)
    at resolver (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\kew\kew.j
409:17)
    at next (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\node_modules\fs-extra\node
odules\rimraf\rimraf.js:70:7)
    at FSReqWrap.CB [as oncomplete] (E:\webstorm\JiaYi\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\no
_modules\fs-extra\node_modules\rimraf\rimraf.js:106:9)
\

> ws@0.4.31 install E:\webstorm\JiaYi\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-clie
\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
E:\webstorm\JiaYi\node_modules\socket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws>i
not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
e-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
\

> kerberos@0.0.9 install E:\webstorm\JiaYi\node_modules\connect-mongo\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
E:\webstorm\JiaYi\node_modules\connect-mongo\node_modules\mongodb\node_modules\kerberos>if not defined npm_config_node
yp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebu
d )  else (rebuild)
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
\

> kerberos@0.0.9 install E:\webstorm\JiaYi\node_modules\acl\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
E:\webstorm\JiaYi\node_modules\acl\node_modules\mongodb\node_modules\kerberos>if not defined npm_config_node_gyp (node
C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  els
(rebuild)
\

> kerberos@0.0.9 install E:\webstorm\JiaYi\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
E:\webstorm\JiaYi\node_modules\mongoose\node_modules\mongodb\node_modules\kerberos>if not defined npm_config_node_gyp
 else (rebuild) es\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild -)
\

> bson@0.2.21 install E:\webstorm\JiaYi\node_modules\connect-mongo\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

|
E:\webstorm\JiaYi\node_modules\connect-mongo\node_modules\mongodb\node_modules\bson>if not defined npm_config_node_gyp
(rebuild) rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
|
> bson@0.2.21 install E:\webstorm\JiaYi\node_modules\acl\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

E:\webstorm\JiaYi\node_modules\acl\node_modules\mongodb\node_modules\bson>if not defined npm_config_node_gyp (node "C:
rogram Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (r
uild)
/
> bson@0.2.21 install E:\webstorm\JiaYi\node_modules\mongoose\node_modules\mongodb\node_modules\bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

E:\webstorm\JiaYi\node_modules\mongoose\node_modules\mongodb\node_modules\bson>if not defined npm_config_node_gyp (nod
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  el
 (rebuild)
-

> ws@0.4.32 install E:\webstorm\JiaYi\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_mod
es\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

\
E:\webstorm\JiaYi\node_modules\karma\node_modules\socket.io\node_modules\socket.io-client\node_modules\ws>if not defin
 npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin
ode-gyp.js" rebuild )  else (rebuild)
|

> ws@0.4.32 install E:\webstorm\JiaYi\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

/
E:\webstorm\JiaYi\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\ws>if not defined npm_con
g_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
" rebuild )  else (rebuild)
npm WARN optional dep failed, continuing default-browser-id@1.0.2
npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.2","npm":"2.7.4"})
\
> v8-debug@0.4.2 install E:\webstorm\JiaYi\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\
-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "E:\webstorm\JiaYi\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v8-d
ug\build\debug\v0.4.2\node-v14-win32-x64\debug.node" is installed via remote

> v8-profiler@5.2.4 install E:\webstorm\JiaYi\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modul
\v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "E:\webstorm\JiaYi\node_modules\grunt-node-inspector\node_modules\node-inspector\node_modules\v
profiler\build\profiler\v5.2.4\node-v14-win32-x64\profiler.node" is installed via remote

> node-sass@1.2.3 install E:\webstorm\JiaYi\node_modules\gulp-sass\node_modules\node-sass
> node scripts/install.js

connect ETIMEDOUT
connect ETIMEDOUT
fs.js:77
      throw err;  // Forgot a callback but don't know where? Use NODE_DEBUG=fs
            ^
Error: EPERM, unlink 'E:\webstorm\JiaYi\node_modules\gulp-sass\node_modules\node-sass\vendor\win32-x64\binding.node'
    at Error (native)
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js"
nstall"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.16 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.16 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\webstorm\JiaYi\npm-debug.log

....

**Comment by gsavoie** [comment]
It can work if you use gulp-sass 1.3.3. This is actually fixed here from #445 but not yet in the generator.

**Comment by blueflagbj** [comment]
think you,I got it!
