### ISSUE TITLE
Angoose in mean.js

### ISSUE THREAD

**Issue by js26** [meanjs/mean#506]
I'm trying to get angoose running in the mean.js
I following the guide for it
https://www.npmjs.com/package/angoose#1-npm-install-angoose

But I miss an app.js file in my mean.js application to add the require statement into:
Assuming you already have an express server/app file, you just need to add following line to the app.js, after the app.configure() block:

/** Angoose bootstraping */
require("angoose").init(app, {
   'module-dirs':'/models',
   'mongo-opts': 'localhost:27017/test',
});

**Comment by gsavoie** [comment]
I don't know anything about Angoose, but if you're working with 0.4 you should be able to find the express configuration in config/lib/express.js.
I would personally add a new module.exports.configureAngoose to do this config and call it in the module.exports.init. A bit like module.exports.configureSocketIO.

**Comment by ilanbiala** [comment]
@js26 this isn't something specific to MEAN.JS. Please use Stackoverflow or other forums before coming here. I'm closing this but if you do not get any answer from any other forum, feel free to come back here with your progress and we'll see what we can do. Also, in the future, please block your code using GFM to make it easier to read.
