### ISSUE TITLE
Make executable version of Mean.js with Enclose.js or other 

### ISSUE THREAD

**Issue by estvmachine** [meanjs/mean#507]
Hello i try to make a executable version of my project Mean.JS with Enclose.js (http://enclosejs.com/), but i have a problem with the exports of MongoDB and Consolidate, i make a screenshot of this situation.

![image](https://cloud.githubusercontent.com/assets/2062668/7005150/75bf4552-dc43-11e4-9242-60944f0da40b.png)

So there are two issues i have to resolve.

1. I have refactorize the require in MongoDB, the Enclose need a explicit path and here its loaded dynamically, but there are many methods.

```javascript
 [ 'commands/base_command'
  , 'admin'
  , 'collection'
  , 'connection/read_preference'
  , 'connection/connection'
  , 'connection/server'
  , 'connection/mongos'
  , 'connection/repl_set/repl_set'
  , 'mongo_client'
  , 'cursor'
  , 'db'
  , 'mongo_client'
  , 'gridfs/grid'
  ,	'gridfs/chunk'
  , 'gridfs/gridstore'].forEach(function (path) {
  	var module = require('./' + path);
  	for (var i in module) {
  		exports[i] = module[i];
      console.log(exports[i]);
    }
});
```

2. And for other side in the exportation of modules in Consolidate give the error "Cannot find module -name module- from  path/consolidate/name_module", and when i check the "node-modules" of Consolidate, its empty. I dont know why...

**Comment by ilanbiala** [comment]
Please use GFM to highlight your code properly.

**Comment by estvmachine** [comment]
Sorry i fix it the comment, still unresolved the issue.

**Comment by ilanbiala** [comment]
Did you `npm install`? What is `require('./' + path)` coming out to be?
