### ISSUE TITLE
Form validations are not working with angular amd

### ISSUE THREAD

**Issue by munikumar604** [meanjs/mean#508]
Hi team,
My Form:
 <form class="reachUs" name="reachUs" role="form" novalidate ng-submit="testSubmit()">
                <div class="form-group">
                    <input name="rsfullname" class="form-control" type="text" placeholder="Your Name" required>
                    <p ng-show="(reachUs.rsfullname.$invalid )&& !reachUs.rsfullname.$pristine " class="help-block danger">Your first name is required.</p>

                </div>
                <div class="form-group">
                    <input name="rsemail" class="form-control" type="email" placeholder="Your Email">
                </div>
                <div class="form-group">
                    <input name="rsphone" class="form-control" type="text" placeholder="Your Phone">
                </div>
                <div class="form-group">
                    <textarea name="rsmessage" class="form-control" placeholder="Message" gramm=""></textarea>
                </div>
                <div class="form-group center">
                    <button type="submit" class="btn btn-default btn-primary">Send Message</button>
                </div>
            </form>
My app.js:
  define(['angularAMD', 'angular-route', 'angular-animate', 'ui.bootstrap'], function (angularAMD) {

        var app = angular.module("webapp", ['ngRoute', 'ngAnimate', 'ui.bootstrap']);
       return angularAMD.bootstrap(app);
My reachus contriller js:
define(['main','angular'], function (app,angular) {
    app.controller('reachus', ['$scope', '$rootScope', function ($scope, $rootScope) {
        $scope.message = "Message from reachus";
Please help me on this
Thanks & regards

**Comment by ilanbiala** [comment]
More info please.

**Comment by codydaig** [comment]
@lirantal Can this issue be closed?

@munikumar604 If you are still having issues, feel free to reopen the issue and provide us with more information. Thanks!

**Comment by lirantal** [comment]
Closing
