### ISSUE TITLE
Twitter callback URL

### ISSUE THREAD

**Issue by junit38** [meanjs/mean#510]
```
twitter: {
	clientID: process.env.TWITTER_KEY || 'TWITTER_KEY',
	clientSecret: process.env.TWITTER_SECRET || 'TWITTER_SECRET',
	callbackURL: '/auth/twitter/callback'
},
```

Twitter launch an error when using callbackURL to pass the callback URL.
Work with:

```
twitter: {
	clientID: process.env.TWITTER_KEY || 'TWITTER_KEY',
	clientSecret: process.env.TWITTER_SECRET || 'TWITTER_SECRET',
	oob: '/auth/twitter/callback'
},
```

**Comment by ilanbiala** [comment]
Please highlight your code using GFM.

**Comment by codydaig** [comment]
@junit38 Are you still having issues?

**Comment by junit38** [comment]
Yes even with the new release (of MeanJs)

**Comment by codydaig** [comment]
@junit38 So, are you suggesting that https://github.com/meanjs/mean/blob/master/modules/users/server/config/strategies/twitter.js#L15 needs to be changed to:
```
oob: config.twitter.callbackURL,
```

**Comment by junit38** [comment]
Yes it seems to be the right solution.

**Comment by codydaig** [comment]
@junit38 Can you find something that backs that solution? I can't find anything in the passport-twitter codebase to justify that. Everything says you need to pass in the callback url with the key 'callbackURL'

**Comment by junit38** [comment]
If you try to connect to twitter with the current passport strategy an error message will be sent:
```
Error: Desktop applications only support the oauth_callback value 'oob'
        at Strategy.parseErrorResponse (/Users/mery/Rendu/Projet/meanMd/node_modules/passport-twitter/lib/strategy.js:182:10)
        at Strategy.OAuthStrategy._createOAuthError (/Users/mery/Rendu/Projet/meanMd/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16)
        at /Users/mery/Rendu/Projet/meanMd/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41
        at /Users/mery/Rendu/Projet/meanMd/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17
        at passBackControl (/Users/mery/Rendu/Projet/meanMd/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13)
        at IncomingMessage.<anonymous> (/Users/mery/Rendu/Projet/meanMd/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9)
```

**Comment by junit38** [comment]
Maybe if an error due to twitter's app parameters

**Comment by codydaig** [comment]
From researching it, I think it's something with your app settings on Twitter and that you have to provide the callback url on twitter as well

**Comment by junit38** [comment]
Ok so it's maybe a StackOverflow issue.

**Comment by codydaig** [comment]
@junit38 Did you check your application settings on Twitter? 

I'm going to set-up a test app tomorrow to mess with social authentication (like twitter, facebook, etc...). I'll check back in tomorrow and see if you've found anything or if I was able to make it work.

**Comment by junit38** [comment]
Yes I checked them. The problem is I can't set localhost as the application Callback Url.

**Comment by lirantal** [comment]
@junit38 makes sense...
so I think we can close this issue
