### ISSUE TITLE
Create a versioning Api in top of Mean js 0.4.0

### ISSUE THREAD

**Issue by b-barry** [meanjs/mean#512]
Hello,

Great work for the new version of mean js.
I want to use it to create a app that will provide a api such as Twitter or Twitch. The Api will be versioned, with a oauth 2 authentification.

Is it possible to build this with mean js 0.4.0 ?
Or I have to use only Express js ? Do you have some recommendations ?

Thanks you for your help.

Kinds regards

**Comment by ilanbiala** [comment]
Yes, it is possible, this question is better for Stackoverflow or another forum however. If you still do not get any information from there, then we can reopen this issue with whatever progress you have made.
