### ISSUE TITLE
Without logging in you can still access pages

### ISSUE THREAD

**Issue by couchguy** [meanjs/mean#513]
I'm not sure if I am missing a tag or something, but if a user is not logged in and they go the the articles page by typing it into the URL bar it does not boot them back to the home page. I have the understanding that the articles pages were secure and for logged in users only.

Thank you, This boilerplate has been great for learning more about the MEAN stack!

**Comment by jloveland** [comment]
hey dan, you can see on this line that the `.get` is not protected by authentication:
https://github.com/meanjs/mean/blob/master/app/routes/articles.server.routes.js#L12
on the next line, you can also see that the `.post` is protected like so 
`.post(users.requiresLogin, articles.create);`

so, if you wanted to protect the articles `.get` route, you can just add `users.requiresLogin` like so:
`.get(users.requiresLogin, articles.list);`

**Comment by couchguy** [comment]
Hey Jason,

Thank you for that! Is the flicker where it loads the articles page for a split second normal? is there something that I can change to remove that?

**Comment by pgrodrigues** [comment]
@couchguy see if [ngCloak](https://docs.angularjs.org/api/ng/directive/ngCloak) helps.

**Comment by couchguy** [comment]
Not having the issue of seeing the the angular code on the html page, but I tried that anyway I still see the flicker of the articles page.

**Comment by ilanbiala** [comment]
@couchguy that's pretty hard to cover up because you are making an HTTP request for the data. Either wait for the requests to finish before you render the page (with a z-index loading element on top or something similar) or embed some data in the page.

**Comment by couchguy** [comment]
Thats a pretty decent work around need to add in page loading spinners anyway, Thanks for all of the help!

**Comment by Dollab** [comment]
To avoid the flicker, I think you should move the query for the articles from the data-init in the view to the ui-router routes via the resolve property. This way the state only loads once the articles list has been resolved. 

The way ng-init is used in the boilerplate is improper (cf. angularJs doc : https://docs.angularjs.org/api/ng/directive/ngInit )

For example something like : 

```js
state('listArticles', {
  url: '/articles',
  templateUrl: 'modules/articles/views/list-articles.client.view.html',
  resolve: {
    ArticlesList : ['Articles', function (Articles) {
    // inject ArticlesList in the articles controller to access the data
      return Articles.query().$promise.then (function (data) {
        return data;
      }, function(error) {
        // Do something if error
      });
    }]
  }  
}).

**Comment by ilanbiala** [comment]
@couchguy what @Dollab is also a really good idea. The resolve property is a bunch of HTTP requests that have to finish before the page loads, but nothing will be shown until then if I remember correctly.

**Comment by simison** [comment]
[My solution](https://github.com/Trustroots/trustroots/blob/master/public/modules/core/controllers/main.client.controller.js#L23-L54) is to not allow state change happen to login-required pages using `$stateChangeStart` (shoots before state change).

I'm listing login-required pages for it, although I'll probably switch it to work other way around (white list safe pages).

At the same time I collect state info and [redirect to it](https://github.com/Trustroots/trustroots/blob/master/public/modules/users/controllers/authentication.client.controller.js#L51-L58) after successful login.

Indeed using ng-init is not a good idea. I'm not a big fan of having controller logic under route configs either. Instead, at the controller you can simply have `$scope.articles = Articles.query()` which allows you to have something like this at the template:
```html
<div ng-hide="$articles.$resolved">Loading...</div>
<div ng-show="$articles.$resolved">Articles...</div>
```
