### ISSUE TITLE
grunt karma - "Invalid config file"

### ISSUE THREAD

**Issue by danpantry** [meanjs/mean#514]
Hi, 

I just created a new meanjs project using `yo`. Tried to run `karma:test` and I receive the following error:

````
$ grunt karma:unit
Running "karma:unit" (karma) task
ERROR [config]: Invalid config file!
  Error: Cannot find module './env/undefined'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (e:\jaeger!\config\config.js:14:2)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)

````

Only modification I have made is altering both `env/config/test` and `env/config/development` to have my private network IP for MongoDB, rather than localhost. Neither are malformed or have syntax errors.

I'm on Windows 7 using Git Bash as my shell.

**Comment by DanPantry** [comment]
This appears to be due to my `NODE_ENV` not being set, although I'm not entirely sure why that is.

**Comment by simison** [comment]
If you run `karma:unit` task directly, `NODE_ENV` doesn't get set (it's normally set by task `env:test`, see `test` task from gruntfile.js).

You gotta run: `NODE_ENV=development grunt karma:test` and it should work.

**Comment by DanPantry** [comment]
Yeah, I worked around it by doing `NODE_ENV=test grunt karma:unit`, however this seems fairly counter-intuitive :\ I was expecting to just be able to `yo meanjs` and then `grunt karma`.

**Comment by simison** [comment]
Well, intuitively you'd just run `grunt test`. :-)

**Comment by DanPantry** [comment]
True, I suppose. I however just wanted to run Angular tests, so..

**Comment by lirantal** [comment]
FYI angular-fullstack generator isn't mean.js generator

**Comment by DanPantry** [comment]
I'm not entirely sure what point you are trying to make?

**Comment by DanPantry** [comment]
My mistake. I definitely used MeanJS generator (can be evidenced by checking the Dockerfile), I don't know why I put angular-fullstack there.

**Comment by lirantal** [comment]
ahh ok, just thought you may have mis-posted the question here.

**Comment by lirantal** [comment]
Issue seem to have been resolved, closing.
