### ISSUE TITLE
How to implement user with "admin" role, which is able to edit another users?

### ISSUE THREAD

**Issue by ketysek** [meanjs/mean#515]
Hi, I've got this in my `user.server.routes.js`
```
app.route('/users/:userId')
	.get(users.read)
	.put(users.hasAuthorization(['admin']), users.update)
	.delete(users.hasAuthorization(['admin']), users.delete);
app.param('userId', users.userByID);
```
Problem is with `app.param`, because method `userByID` is returning logged in user, so when I click on delete, it will delete my account...If I change `app.param` to find user from DB by userId, I'm getting authorization problems (403 forbidden) :( Could someone help me to solve this problem?
Thank you very much!

If I neglect safety ...
```
app.param('userId', users.userByID);
app.route('/users/:idUser')
	.get(users.read)
	.put(users.updateById)
	.delete(users.delete);
app.param('idUser', users.userById);
```
Now I am able to delete users, but If I edit some user, it will change logged in user to the edited one :(

**Comment by ketysek** [comment]
If I neglect safety ...
```
app.param('userId', users.userByID);
app.route('/users/:idUser')
	.get(users.read)
	.put(users.updateById)
	.delete(users.delete);
app.param('idUser', users.userById);
```
Now I can delete users, but if I edit some user, I am logged in as the edited user :(

**Comment by ilanbiala** [comment]
You need a middleware that uses `req.profile` and not `req.user`. [This is the line](https://github.com/meanjs/mean/blob/master/app/controllers/users/users.profile.server.controller.js#L17) that causes issues for you in this case.

**Comment by ketysek** [comment]
Yeah, I got it few minutes ago too :D Thanks! :)

**Comment by marianoqueirel** [comment]
Hi, one query
How you add more than one user role ?

Thanks!

**Comment by debrouxl** [comment]
Having > 1 role for an user can be achieved through direct MongoDB database manipulation, e.g. in the mongo shell.

**Comment by marianoqueirel** [comment]
The solution is this: In users.server.controller.js 
You should comment the line " delete req.body.roles; " , and in Angular create an array with roles you need. when you pass to server.  
```
exports.signup = function(req, res) {
	// For security measurement we remove the roles from the req.body object
	/*delete req.body.roles;*/

	// Init Variables
	var user = new User(req.body);
	var message = null;

	// Add missing user fields
	user.provider = 'local';
	user.displayName = user.firstName + ' ' + user.lastName;

	// Then save the user 
	user.save(function(err) {
		if (err) {
			return res.status(400).send({
				message: errorHandler.getErrorMessage(err)
			});
		} else {
			// Remove sensitive data before login
			user.password = undefined;
			user.salt = undefined;

			req.login(user, function(err) {
				if (err) {
					res.status(400).send(err);
				} else {
					res.json(user);
				}
			});
		}
	});
};
```

**Comment by simison** [comment]
@marianoqueirel remember that then you'll also need a middleware to validate roles. Otherwise you might as well just leave all admin pages open...

**Comment by marianoqueirel** [comment]
Ofcourse, in the route you can do this: 
```
app.route('/home/onlyAdmin')
  .get(users.requiresLogin, customers.read)
  .put(users.requiresLogin, customers.update)
  .delete(users.requiresLogin, users.hasAuthorization(['admin']), customers.delete);
```
Or if you want, you could do this from the Angular.

**Comment by trainerbill** [comment]
We are adding an admin module in the very near future for the specific purpose of adding additional roles to users:

https://github.com/meanjs/mean/pull/676

Can prolly close this issue

**Comment by lirantal** [comment]
yep, thanks @trainerbill

**Comment by bruna94** [comment]
Hello! Can someone please help me with a  step by step tutorial about setting up an admin user on my meanjs app? Thank you!

**Comment by trainerbill** [comment]
@bruna94 You can use the seed feature

MONGO_SEED=true grunt

The users and passwords will appear in the console

**Comment by bruna94** [comment]
im sorry i executed this in GitBash but the console of the page does not show anything... am i doing something wrong?

**Comment by trainerbill** [comment]
What version of MEAN are you running?  The seed feature was added within
the last 2 months.

**Comment by trainerbill** [comment]
@bruna94 Take this to the gitter chat so we don't revive this issue.

**Comment by steventj** [comment]
@marianoqueirel 
By commenting this line really help me sign up a user with some roles.
//delete req.body.roles;

**Comment by ckapop** [comment]
The issue I think I am running into is when editing other users profiles the password gets changed due to the 'pre' hook on user save whenever you try and save the changed profile:

UserSchema.pre('save', function(next) {
	if (this.password && this.password.length > 6) {
		this.salt = new Buffer(crypto.randomBytes(16).toString('base64'), 'base64');
		this.password = this.hashPassword(this.password);
	}

	next();
});

**Comment by mleanos** [comment]
@ckapop What version of MEANJS are you seeing this behavior?

The *password* field should never be present in either the request, or response. If the password is updated, in a request other than the create profile, then this would indeed be a bug. However, I think we took care of any issues with this already.

**Comment by ckapop** [comment]
@mleanos How can I check to be sure? It is probably not as current as it should be.

I have this method that was generated for me which looks like the new password is in the request, correct?

/**
 * Change Password
 */
exports.changePassword = function(req, res) {
	// Init Variables
	var passwordDetails = req.body;

	if (req.user) {
		if (passwordDetails.newPassword) {
			User.findById(req.user.id, function(err, user) {
...
