### ISSUE TITLE
Authorisation middleware

### ISSUE THREAD

**Issue by rmlopes** [meanjs/mean#518]
Hi,

I'm using the version on the master branch, and while playing around with the authorisation middleware I noticed that my functions had to be negated. I searched for a similar issue (open or closed) but could not find anything.

The example:
```javascript
/**
 * Group authorization middleware
 */
exports.hasAuthorization = function(req, res, next) {
	if (req.group.user.id !== req.user.id) {
		return res.status(403).send('User is not authorized');
	}
	next();
};

exports.hasMembership = function(req, res, next) {
	if (_.contains(req.group.members, req.user.id)) {
		return res.status(403).send('User is not a member');
	}
	next();
};
```

the hasAuthorization works fine, but in the hasMembership function I had to negate the condition. I have this issue with every functions that I use as authorization middleware (apart from the yo generated hasAuthorization). Am I missing something here?

**Comment by rmlopes** [comment]
I tried to replicate the issue in a vanilla installation by adding and testing against some user attributes but everything works as it should, so I must have other issue in the project.

**Comment by mleanos** [comment]
I believe your condition in the hasMembership function should be checking that group.members does NOT contain the req.user. 

!_.contains
