### ISSUE TITLE
Typescript version?

### ISSUE THREAD

**Issue by vko-online** [meanjs/mean#527]
This stack is very cool, but is there any typescript version?

**Comment by anderskristo** [comment]
@vko-online there is not a TypeScript version of this stack.

**Comment by vko-online** [comment]
But i guess it's not so hard to do, all stuff can be easily converted to mean.js, what if i make PR with typescript?

**Comment by ilanbiala** [comment]
@vko-online we're not going to merge that in simply because 99% of people don't need it and it won't be managed by core until many other things are taken care of first.

**Comment by vko-online** [comment]
But we just need some `.d.ts` and grunt compiler, it's really useful in webstorm

**Comment by ilanbiala** [comment]
Yes, but when it is actually released and tested.

**Comment by codydaig** [comment]
Can this issue be closed or is this still up for discussion?

**Comment by LiveLikeLastDay** [comment]
+1 for typescript.

**Comment by trendzetter** [comment]
-1 for microsoft fanboys

**Comment by lirantal** [comment]
while I was never a Microsoft fan, Angular2 is all about TypeScript so I wouldn't rule it out just yet.

**Comment by trendzetter** [comment]
it appears to me everything gets compiled to es6, debugging is going to be es6. it's unclear to me why angular needs typescript. it appears to me another case of where microsoft somehow forces someone hand to do stuff benefiting microsoft but harming themselves. Like nokia's windows phone strategy.

**Comment by trendzetter** [comment]
Their strategy might be to pollute as much open source projects as possible with their typescript sugar and thereby often making visual studio, running only on windows, their default development environment. Not that it will be impossible to develop on other platforms but possibly with all kind of catches. I am just thinking some things up, as it seems hard to get at clear decent technical justification.

**Comment by trendzetter** [comment]
of course I carefully watch how this develops. It could also become more of an xml like thing.

**Comment by jgcoded** [comment]
Any updates on a TypeScript version of this stack?
