### ISSUE TITLE
Use meanjs with remote public folder

### ISSUE THREAD

**Issue by Soufraz** [meanjs/mean#528]
Hi folks,
I have a project that is finished with meanjs.
However, I wonder how I can separate the client and the server of this project.
I must publish the project (/ public) in an app with cord. And let the server (/ app) running somewhere on the net.
I know the process of compiling the cordova app and configure the server.
But, What I need to know to separate the layer client x server in meanjs?

**Comment by Soufraz** [comment]
Well, I've managed to create a webApp based on meanjs. I'd now like to create an Mobile App using cordova/phonegap to also access this webApp database. My question is how could I use the front-end part already done as the basis for this Mobile App?

**Comment by dinu88** [comment]
You have controllers, only you have to do is to move and adopt this controllers to your new cordova app.
Anyway, I'll not suggest you to use Angular in phonegap app if you want to make it fast and responsive.
