### ISSUE TITLE
Upgrade ui-router to new ng-route router

### ISSUE THREAD

**Issue by britztopher** [meanjs/mean#530]
Just want to put this in a ticket so we can push it to a milestone release and get some conversation,  but we should be looking into getting the Angular 2.0 router into the meanjs repo and removing ui-router.

**Comment by anderskristo** [comment]
I don't think we should do this for 0.4.0, probably for 0.5.x or something..

**Comment by britztopher** [comment]
@anderskristo i definitely agree with you, but I just wanted to at least have a ticket we can get conversations flowing about upgrading the router.  By all means, if you have the power label this for 0.5 milestone feature

**Comment by ilanbiala** [comment]
@britztopher I don't think the new router is nearly as stable nor as flushed out in terms of features, but I haven't checked on it in a couple months. Are there still disparities?

**Comment by dotch** [comment]
I have been using it in a small project a few days ago. 
My only bigger issue was with injecting $scope into the controller constructor, which was fixed 5 days ago.
So all in all it mostly works, but it still lacks documentation and has a few bugs and is still subject to change. It was supposed to be released with angular 1.4, but I am not sure if that will happen.

**Comment by simison** [comment]
Upgrade — as of July:
- the API of the new router isn't yet stable and things are still changing.
- No docs yet.
- Estimated to be published with Angular 1.5, probably this autumn.

**Comment by ilanbiala** [comment]
Not happening as of now.
