### ISSUE TITLE
No built-in way to return an error back to UI from exports.oauthCallback

### ISSUE THREAD

**Issue by ppotoplyak** [meanjs/mean#539]
This issue is in reference to app/controllers/users/users.authentication.server.controller.js:exports.oauthCallback

I could not figure out how to return a custom error and have it be displayed to the client in the context of the current starter code.  My workaround was to redirect to a custom error page which is okay but not ideal.

Use case is checking if user's email is on an invite list and returning an error msg if not.  

It would be great if someone could confirm that this is indeed the case and that I am not overlooking some existing error return mechanism in exports.oauthCallback.

thanks

**Comment by trainerbill** [comment]
Can you be more specific?  Oauth requires redirecting off the application and when it redirects back the the return url it has to then authenticate and redirect somewhere.  If you look here:

https://github.com/meanjs/mean/blob/0.4.0/modules/users/server/controllers/users/users.authentication.server.controller.js

On line 87 if an error occurs it redirects to signin with the error on the URL.  Also if you put the err on the URL on the signin page you see the error:

http://localhost:3000/authentication/signin?err=this%20is%20a%20test

After I typed this whole thing i noticed that you probably aren't using 0.4.0.  You should switch to the 0.4.0 if you aren't committed to the master branch yet.

**Comment by ppotoplyak** [comment]
Great, this issue appears to be fixed in 0.4.0 with the introduction of the URL err arg.

Closing the issue.
