### ISSUE TITLE
Agile Board for Stories?

### ISSUE THREAD

**Issue by britztopher** [meanjs/mean#544]
Anyway we can get a Trello board or something to track status on issues, so we can track tickets and who's working on what?  Just an idea, as I am always trying to figure out whether I can pick up a issue ticket, or if someone else if working on it.  Like I said, just an idea.

**Comment by ilanbiala** [comment]
For people on the team we use the assigned person to keep track of who is handling a specific issue or going to be the one who merges a PR. Tickets are grouped by milestone and labeled for the most part. I don't really want to add another management platform, as it seemed to just move discussion away from the actual code and to just ideas/thoughts. If others thinks it's a great idea, we can try it though.

**Comment by cdriscol** [comment]
@britztopher - have you seen [waffle.io](https://waffle.io)?  it's a board for github issues..

**Comment by codydaig** [comment]
Is this still something that that the team wants to move too or should we just close it?

You can always view the issues, even through the team may not use it: https://waffle.io/meanjs/mean

**Comment by ilanbiala** [comment]
I don't really feel it's necessary. We're doing fine with GH milestones and labels. Closing unless anyone has something earthshattering.

**Comment by lirantal** [comment]
agree with @ilanbiala 
there's enough maintenance as is on the project.

We'll get 0.4.0 out the door and then consider.
