### ISSUE TITLE
How to develop social features (Follow/Stream/..) using MEANJS?

### ISSUE THREAD

**Issue by amrfaisal** [meanjs/mean#550]
What's the best approach to develop social features like (Follow/Activity stream) using MEANJS stack?
If we can take current article sample for example, how can we achieve this?

**Comment by randavidovitz** [comment]
[This](http://www.waistcode.net/blog/mongodb-newsfeed-schema-design-for-entexis) might give you more info

**Comment by amrfaisal** [comment]
I've checked that blog post couple of weeks ago, and here why I don't think it is relevant to MEAN stack:
1- As you may notice it's already 3 years old. 
2- The writer also was using Java as their back-end. So he don't think Nodejs.
3- The architecture isn't simple. I think he would have saved all user's news-feed items as an embedded array in one user's related document.

I think there's a better way uses all the features we currently have of using a MEAN stack.

Thanks

**Comment by codydaig** [comment]
@amrfaisal We're you able to figure anything out or are you still looking for some suggestions?

**Comment by amrfaisal** [comment]
I just followed some suggestion, but I badly looking for other suggestions if any.

**Comment by codydaig** [comment]
@amrfaisal What's your current method that your following?

**Comment by lirantal** [comment]
@amrfaisal but you're basically just asking about architecture and application development so this is quite off-topic from the actual mean.js framework core. I think a better place would be stackoverflow, reddit, or that kind of medium.
