### ISSUE TITLE
phantomjs installation failing

### ISSUE THREAD

**Issue by kwame2** [meanjs/mean#554]
Trying to install meanjs; all is almost ok but at the end installation fails due to failing installation of phantomjs.
Here is a piece of error log it outputs:
npm ERR phantomjs@1.9.16 install: 'node install.js'
npm ERR  Exit status code 1
npm ERR
npm ERR  Failed at the phantomjs@1.9.16 install script.
npm ERR This is most likely a problem with phantomjs package,
npm ERR not with npm itself.
npm ERR Tell the author that this fails on your system:
npm ERR node install.js
npm ERR There is likely addidional logging output above.
npm ERR System Windows_NT 6.1.7601
npm ERR command "D:\\servers\\node\\\\node.exe" "D:\\servers\\node\\node_modules\\npm\\bin\\npm-cli.js" "install"

I am on windows 7 with node v0.10.31 installed.. Please help urgently.

**Comment by randavidovitz** [comment]
[This](https://github.com/Medium/phantomjs/issues/279) might give you the answer, which implies that temp directory is located on different device

**Comment by ilanbiala** [comment]
Please use StackOverflow or another forum for answers that aren't specific to MEAN.JS.
