### ISSUE TITLE
Cannot install yo generator

### ISSUE THREAD

**Issue by polinac** [meanjs/mean#555]
I am installing yo generator in order to configure sample mean application (https://github.com/meanjs/mean).
I have Windows 8.1. I am following these instructions: http://meanjs.org/generator.html.
My cli is running with administrative permissions.
I executed "npm install -g yo" successfully.
"npm install -g generator-meanjs" fails for me:
![image](https://cloud.githubusercontent.com/assets/12117128/7578216/010e80ee-f807-11e4-871b-4a437679392d.png)

Could you please help me to resolve the issue?
I can send you my npm-debug.log.

**Comment by randavidovitz** [comment]
Looks to me like your node-cache folder is located in a place that causes you to have permission issues (using process monitor you can gain more info)

Suggest you move the folder to different location as an example : npm config set cache C:\dev\nodejs\npm-cache --global

**Comment by ilanbiala** [comment]
Please repost this in the generator repo.
