### ISSUE TITLE
New module not working caused by module name

### ISSUE THREAD

**Issue by goodseller** [meanjs/mean#558]
I have yo a new route 

    yo meanjs:express-model <module-name>

with a name like: "node", "node-info", "info" and found that is not loaded (tested with console.log).

Then I tried rename the default articles module as above and restart gulp, but still find err.

**Is there any restriction for the naming of the module?** Thanks.

Remarks:
- (name "express" works)
- OS: Windows 8 x64
- mean.js version 0.4.0

**Comment by ilanbiala** [comment]
This should be posted on the generator repo.
