### ISSUE TITLE
Use of some dependencies

### ISSUE THREAD

**Issue by estvmachine** [meanjs/mean#560]
Hi, i want to know why in the package.json appears these dependencies:

1.forever
2.async

 I cant find whats files use it.

**Comment by randavidovitz** [comment]
Async - used in app/controllers/users/users.password.server.controller.js to sequence async operastion one after the other (personally i think CO is better).

forever - used in the procfile which related to integration in heroku (declarion of the execution)

**Comment by estvmachine** [comment]
I got it, the Async looks very useful!.

In my implementation i delete the modules of users so i dont know its still useful these dependencies.

The 'forever' maybe its useful because i use 'scribe-js', but i dont find the file where its use it..

**Comment by ilanbiala** [comment]
@estvmachine it's a CLI tool. Please search through the code before posting questions.

**Comment by estvmachine** [comment]
Ok i read the github of Forever and see the file Procfile. Sorry i really want optimize my dependencies and dont really know for what exists this dependencies.  In the page of MEAN.js dont appears.

Now im gonna use both! thanks!

**Comment by ilanbiala** [comment]
Forever keeps MEAN running on Heroku even if it crashes.

**Comment by estvmachine** [comment]
Ok thanks

**Comment by sielay** [comment]
Async has nice waterfall implementation.
