### ISSUE TITLE
Bower packages and inclusion

### ISSUE THREAD

**Issue by superandrew** [meanjs/mean#562]
Hi, there is something I can't figure out in mean.js. When I install bower packages, how can I embed the dependencies as I would in a normal web project handled by grunt by using `grunt wiredep`?

I've tried to add them manually following the flow, they work locally but once they get pushed to heroku the application doesn't load the modules.

**Comment by ilanbiala** [comment]
@superandrew please use StackOverflow or another forum for questions regarding non MEAN.JS code before coming here.
