### ISSUE TITLE
Can't load third-party module

### ISSUE THREAD

**Issue by thanhthang20** [meanjs/mean#570]
I add [ngMaterial] (https://github.com/angular/material) module as below:

var applicationModuleVendorDependencies = ['ngResource', 'ngAnimate', 'ui.router', 'ui.bootstrap', 'ui.utils', 'ngMaterial'];

The error is shown in chrome inspector: 

Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:
Error: [$injector:modulerr] Failed to instantiate module ngMaterial due to:
Error: [$injector:nomod] Module 'ngMaterial' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

**Comment by ilanbiala** [comment]
Did you forget to add one of the scripts or something like that?

**Comment by thanhthang20** [comment]
I found that MEAN doesn't add script tag for angular-material.js in html header like another angular modules. I don't know how to fix it

**Comment by simison** [comment]
@thanhthang20 add it to
- `bower.json` and run `bower install`
- configs at `./config/assets/`

**Comment by codydaig** [comment]
@thanhthang20 Did you get your issue resolved or can this issue be closed?

**Comment by thanhthang20** [comment]
I use another framework instead of MEAN now, thanks!

**Comment by lirantal** [comment]
Huh?!
![image](https://cloud.githubusercontent.com/assets/316371/9377018/2ca96bf0-471d-11e5-825e-e4899c437b1f.png)

:)
