### ISSUE TITLE
Authentication from multiple devices

### ISSUE THREAD

**Issue by maelvis** [meanjs/mean#572]
Hi,

I'm building a web application using MEANJS. The application will be also accessible via smartphone and tablet. I use ionic framework to do it.
I don't know how to implement an authentication which will work for all those devices.
I read about Token and Session authentication but seriously I don't understand it at all and I don't know how it could help me.

Could some one help me, please ?

**Comment by ilanbiala** [comment]
@maelvis please post these questions in another forum before coming here, as this is mainly for issues and features. If you don't solve this after visiting another forum, then feel free to come back here with your progress.

**Comment by maelvis** [comment]
Ok. Thanks.
