### ISSUE TITLE
Feature Request: Multisite single sign on

### ISSUE THREAD

**Issue by sielay** [meanjs/mean#577]
Hi

I store it here as anyhow I will need to have it (or develop it) as continuation of [refactor user PR](https://github.com/meanjs/mean/pull/559). Anyhow, if anyone have time, ideas or opinion to shape it or do it before I'll be able to pick it up - feel free.

 * Assume main system is installed as `example.com`
 * System allow to spinoff other instances in subdomains like `subdomain.example.com`
 * Each subdomain system works as separate process with separate database
 * Subdomain system uses main system as `passport strategy` and consumes user session as it is from the main instance
 * Account management is always happening in main instance
 * Subdomain systems use ACL to decide who has access to them.
 * Subdomain systems doesn't use other passport strategies.

**Comment by lirantal** [comment]
@sielay I'm not sure I understand, can you further elaborate on the story here?

**Comment by codydaig** [comment]
@sielay So you want to have subdomains that are running their own instance of MEAN.js and databases, but you want them to share sessions, user accounts, and permissions?

**Comment by lirantal** [comment]
If that's the case then first thing is to make sure you that sessions are stored in a shared area like mongodb, redis, etc. Which will also make your app stateless (that is a good thing).

**Comment by codydaig** [comment]
@sielay Did that answer your question?

**Comment by sielay** [comment]
Yep. Let's close it.

**Comment by dbelieves** [comment]
i am going through the same problem.

what is meant by 'making the app stateless' ?

i have only one db of mongo which i want to be shared across all my subdomains.

can anyone help guide me do this ?
