### ISSUE TITLE
facebook, github, etc config is not a must

### ISSUE THREAD

**Issue by loulin** [meanjs/mean#585]
```
	app.locals.facebookAppId = config.facebook.clientID;
	                                          ^
TypeError: Cannot read property 'clientID' of undefined
```
If facebook is not configured, this error will throw. In fact, I don't think it's a must.

**Comment by loulin** [comment]
and mailer either
```
var smtpTransport = nodemailer.createTransport(config.mailer.options);
                                                            ^
TypeError: Cannot read property 'options' of undefined
```

**Comment by ilanbiala** [comment]
@loulin can you submit the fix via a PR and we'll merge it in?

**Comment by loulin** [comment]
It's only own opinion. I copied the config.example.js to config.js, then the error was thrown.
In fact, we in ugly China can't access any of the strategy service providers, but we have others like wechat.
So if it's necessary to ignore these configs, I'd like to fix it.

**Comment by lirantal** [comment]
@loulin do you mean local.example.js? there is no config.example.js and you're not supposed to 'copy' it anywhere... can you explain please?

**Comment by loulin** [comment]
yes, there is `a copy:localConfig` task that copies local.example.js to local.js. To get meanjs run `NODE_ENV=local grunt`, I have to add facebook, github config ...

**Comment by lirantal** [comment]
ok so local.example.js, not config.example.js, that's important :-)
you don't have to copy this config yourself, grunt will do it for you, and it's also not a must to create it/use it. By default, the local.js file is also commented entirely so none of the code there should be used.

can you explain the problem you are facing again?

**Comment by loulin** [comment]
I create an env file `stage.js` like this:
```js
module.exports = {
	db: {
		uri: 'mongodb://localhost/meanjs_stage',
	}
};
```
It throws error when I run `NODE_ENV=stage grunt`. What I mean is that it should run even if I do not config facebook or mailer, etc. Because we never use facebook, so that facebook html tag is also not necessary:
```html
	<!-- Facebook META -->
	<meta property="fb:app_id" content="{{facebookAppId}}">
	...
```
However, I can add all the config with fake data to get it running. So it's not a bug, maybe it's designed.

**Comment by loulin** [comment]
As it's a boilerplate, these configs are all good examples, so I can keep them and add new strategies.
Close for low priority.
