### ISSUE TITLE
when trying to create a new yo  meanjs application I'm getting this error.. 

### ISSUE THREAD

**Issue by taninme** [meanjs/mean#588]
Please help I'm trying to create a new 0.4 application using yo meanjs but giving me the following error. I'm on mac. I'm guessing I have installed everything because the regular meanjs is working for me and creating apps. Thanks  

darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/tanin/Documents/Node/mean3/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.1
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tanin/Documents/Node/mean3/npm-debug.log

**Comment by isotnikov** [comment]
Check requirements for mean.js. Your node is v0.12.4 but look here

> ##### MongoDB
> MongoDB version 2.4.x is supported.
> #####  Node.js
> Node version 0.10.x is supported.
> #####   npm
> npm version 1.3.x is supported.

**Comment by taninme** [comment]
Thanks :)

**Comment by codydaig** [comment]
Can this be closed?

**Comment by lirantal** [comment]
Yes, and should be moved to the generator branch in the future
