### ISSUE TITLE
Deploy question?

### ISSUE THREAD

**Issue by golmic** [meanjs/mean#589]
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   'server.js' ]
2 info using npm@2.9.1
3 info using node@v0.12.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart meanjs@0.3.3
6 info start meanjs@0.3.3
7 verbose unsafe-perm in lifecycle true
8 info meanjs@0.3.3 Failed to exec start script
9 verbose stack Error: meanjs@0.3.3 start: `grunt "server.js"`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:213:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid meanjs@0.3.3
11 verbose cwd /opt/mean
12 error Linux 2.6.32-504.12.2.el6.x86_64
13 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "server.js"
14 error node v0.12.3
15 error npm  v2.9.1
16 error code ELIFECYCLE
17 error meanjs@0.3.3 start: `grunt "server.js"`
17 error Exit status 1
18 error Failed at the meanjs@0.3.3 start script 'grunt "server.js"'.
18 error This is most likely a problem with the meanjs package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     grunt "server.js"
18 error You can get their info via:
18 error     npm owner ls meanjs
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by cdriscol** [comment]
@golmic, it looks like you're trying to start the project with
```bash
grunt "server.js"
```

try this instead
```bash
grunt
```
or
```bash
node server.js
```

**Comment by codydaig** [comment]
@golmic Are you still having any issues?

**Comment by golmic** [comment]
no.thanks~

**Comment by codydaig** [comment]
Close?
