### ISSUE TITLE
Core service sharing

### ISSUE THREAD

**Issue by skoold2003** [meanjs/mean#590]
I just made a change in my code so that core services can be shared among new modules. Since the loading was alphabetical any module name starting with A or B wouldn't recognize core services. I changed my code from this:
config/env/all.js-
ORIGINAL-
js: [
			'public/config.js',
			'public/application.js',
			'public/modules/*/*.js',
			'public/modules/*/*[!tests]*/*.js'
		]

NEW-
js: [
			'public/config.js',
			'public/application.js',
			'public/modules/core/*.js',
			'public/modules/*[!core]*/*.js',
			'public/modules/*/*[!tests]*/*.js'
		]

I'm not sure if this is the right way to make this suggestion as it is the first time posting to a git repo.

**Comment by codydaig** [comment]
I don't think this is an issue in 0.4.0.

Can anyone confirm?

**Comment by mleanos** [comment]
@codydaig You're right. This doesn't seem to be an issue in 0.4.0. 

I just tested this with a module that has A as the first letter in it's name. Everything loaded fine, including custom services I've added. 

Furthermore, the Chat would fail to recognize the Socket service if this was an issue.

**Comment by codydaig** [comment]
@mleanos Thanks!

@skoold2003 Can this issue be closed?

**Comment by skoold2003** [comment]
No problem..  Just wanted to share my experience in case anyone else ran into it. I'm not sure how to check what version I'm using otherwise I'd share it.

**Comment by codydaig** [comment]
@skoold2003 - It should say in the package.json file, but unless you specifically went to the 0.4.0 branch to download it, your most likely on 0.3.x.
