### ISSUE TITLE
img/profile/uploads directory overwritten on Heroku deploy

### ISSUE THREAD

**Issue by mleanos** [meanjs/mean#593]
I'm having an issue with the img/profile/uploads directory, when deploying to Heroku. During deployment, Heroku will destroy this uploads directory. Thus, deleting any profile pictures that users have uploaded. Adding it to .gitignore won't help this issue. It has to do with Heroku using slug, which destroys the application and rebuilds it.

Has anyone had any success with this, when deploying to Heroku? Or any advice on how to handle this issue, perhaps?

**Comment by simison** [comment]
Isn't this supposed to happen with Heroku? I've understood you should use Amazon S3 or similar to upload your files with Heroku...

**Comment by simison** [comment]
Yeah: https://devcenter.heroku.com/articles/dynos#ephemeral-filesystem

**Comment by mleanos** [comment]
Yea, this is definitely a desired feature of Heroku. However, was curious of what other's may be doing to combat this with the new uploads dir.

I'll check out your resource.. Thank you!

**Comment by mleanos** [comment]
Thank you for responding. I'll look at using Amazon S3. My other option will be to store them in my database. I was hoping to avoid that for the purpose of a profile picture. I'm already using mongo to store other file uploads from user's.

**Comment by simison** [comment]
Yeah, either way. S3 is neat.

You're welcome!
