### ISSUE TITLE
Can't install 

### ISSUE THREAD

**Issue by dinu88** [meanjs/mean#600]
gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1038:12)
gyp ERR! System Linux 3.13.0-54-generic
gyp ERR! command "/usr/local/bin/iojs" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/var/www/node/mean/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.9/node-v42-linux-x64/profiler.node" "--module_name=profiler" "--module_path=/var/www/node/mean/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.9/node-v42-linux-x64"
gyp ERR! cwd /var/www/node/mean/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
gyp ERR! node -v v1.0.2
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
node-pre-gyp ERR! build error 
...

Any suggestions?

**Comment by dinu88** [comment]
node v0.11.15
node-gyp v1.0.2

**Comment by isotnikov** [comment]
@dinu88 requirements: 

> ##### MongoDB
> MongoDB version 2.4.x is supported.
> #####  Node.js
> Node version 0.10.x is supported.
> #####   npm
> npm version 1.3.x is supported.

**Comment by dinu88** [comment]
@isotnikov thank you
