### ISSUE TITLE
Multiples views using ui-router

### ISSUE THREAD

**Issue by estvmachine** [meanjs/mean#602]
Hi, im trying to use multiples views using ui-router, the second view is charged inside the first view, so this way i dont alter the native 'index.html' from mean.js, that is i want... Here is my controller 

```javascript
angular.module('DTE').config(['$stateProvider',
	function($stateProvider) {
		// Articles state routing
		$stateProvider.
		state('list-docums', {
			url: '/DTE/docums',
			views:{
				'': {
					template:'modules/DTE/views/list-docums.client.view.html'
				},
				'searchbar': {
					template: 'modules/DTE/views/list-docums-searchbar.client.view.html'
				}
			}
		})
```

The index html: 

```html
{% block content %}
	<section data-ui-view></section>
{% endblock %}
```

I put 'data-ui-view" assuming unnamed, with this way in other aplications works, additionally i add the 'template" for angular, something like this:

```html
<script type="text/ng-template" id="../public/modules/DTE/views/list-documentos.client.view.html</script>
<script type="text/ng-template" id="../public/modules/DTE/views/list-documentos-searchbar.client.view.html"></script>
```

But this doesnt work, dont show nothing :(

**Comment by codydaig** [comment]
I don't quite understand what you're trying too do. However, at first glance I notice the syntax highlighting is off signifying an error.

You currently have:
<script type="text/ng-template" id="../public/modules/DTE/views/list-documentos.client.view.html</script>

It needs to be:
<script type="text/ng-template" id="../public/modules/DTE/views/list-documentos.client.view.html"></script>

Not sure if this will fix it, but that's a start.

**Comment by lirantal** [comment]
@estvmachine can you please explain?

**Comment by estvmachine** [comment]
Oh sorry. In the documentation of ui-router says you can use one state with multiples views (https://github.com/angular-ui/ui-router/wiki/Multiple-Named-Views). So my question is very nooby and its something like if i want to add this funcionality, the template or the structure of the app is still gonna working.  Well that is the question.

The code above i think is incorrect now i see it.

**Comment by lirantal** [comment]
ok, anything else to do here or you'll close this issue?

**Comment by estvmachine** [comment]
Its ok, im gonna close it. Thanks for the response.
