### ISSUE TITLE
`mongoose.connect` is treated as if it's synchronous

### ISSUE THREAD

**Issue by zbjornson** [meanjs/mean#603]
https://github.com/meanjs/mean/blob/master/server.js#L16 You're treating that call as if it's blocking, but it's not -- establishment of a connection(s) is async, and the rest of the initialization should only proceed after the callback is called without an error, right?

**Comment by ilanbiala** [comment]
@zbjornson take a look at 0.4.0 for the improved version.

**Comment by zbjornson** [comment]
@ilanbiala yes, it's correct in 0.4.0.

(Your branches are a bit confusing -- the readme gives instructions for checking out the "latest" version of the repository, but the instructions will check out master, not 0.4.0. From the number of commits in each branch, I was not sure if 0.4.0 was historical or future.)

**Comment by codydaig** [comment]
0.4.0 is future, but getting much closer to be merged into master.

I think this issue is resolved then.
