### ISSUE TITLE
What is the "secure" environment versus the "production" environment?

### ISSUE THREAD

**Issue by zbjornson** [meanjs/mean#604]
The [config docs](http://meanjs.org/docs.html#configuration) list development, production, test and travis, but the [git repo](https://github.com/meanjs/mean/tree/master/config/env) contains development, production, test and secure. Initially I wondered if "production" was a non-SSL production environment, but there is [at least one](https://github.com/meanjs/mean/blob/master/config/express.js#L77) instance where production does something different than secure.

This is only in master, not 0.4.0.

**Comment by lirantal** [comment]
scroll down on your original link for express and you'll find the reference to 'secure' config: https://github.com/meanjs/mean/blob/master/config/express.js#L148

**Comment by zbjornson** [comment]
Yeah, I saw that -- but my point was that "production" and "secure" do two different things. What if I want a secure (SSL) production (`app.locals.cache = 'memory';`) environment?

**Comment by lirantal** [comment]
The 'secure' config is not about adding security, it's simply about running the service in SSL mode (the name 'secure' might be confusing). If you want to run with the 'production' env settings and in SSL mode simply copy the production settings to the 'secure' env config.

**Comment by zbjornson** [comment]
Yeah, I understand what they do, but that's still not my point. Currently in order to get a production environment with SSL, you would have to modify express.js because this line:
https://github.com/meanjs/mean/blob/master/config/express.js#L77
is dependent on "production"
and the SSL stuff here:
https://github.com/meanjs/mean/blob/master/config/express.js#L148
is dependent on "secure". Copying the prod env settings into the secure env config would thus not be sufficient. Get what I'm saying? I'd recommend removing the secure config and changing L148 to "production" to force production to always use SSL, or changing L77 to be `process.env.NODE_ENV === 'production' || process.env.NODE_ENV === 'secure'`.

**Comment by lirantal** [comment]
@zbjornson since we have 0.4.0 going pretty well and going to release that soon then I don't think it's worth doing any changes o the 'master' branch for now related to this.
WDYT?

**Comment by zbjornson** [comment]
Good with me. (I'd change your readme though to clarify that "master" is not "latest," but is instead the "latest stable" and that future development goes on in separate release branches.) Cheers!

**Comment by lirantal** [comment]
@zbjornson hoping to see more from you on 0.4.0 items! :)
