### ISSUE TITLE
Update to grunt-nodemon 0.4.0

### ISSUE THREAD

**Issue by trainerbill** [meanjs/mean#612]
Can we update grunt-nodemon to 0.4.0 on the mean 0.4.0 branch?  It will fix the issue of watching too many files:

https://github.com/ChrisWren/grunt-nodemon/issues/46

Happens to us Ubuntu users.

**Comment by ilanbiala** [comment]
@trainerbill create a PR after 0.4 is officially released. This will probably have to wait about a week and it will be released as part of 0.4.1 or slightly after.

**Comment by lirantal** [comment]
right, it's there and we can probably close this issue thanks to @rhutchison PR.
