### ISSUE TITLE
Articles - How to add new field (rly is hard?)

### ISSUE THREAD

**Issue by michalmw** [meanjs/mean#614]
Hello,

i try add new field in articles.
e.x. 'data'
I try alone do this and working.. But rly is hard do this. You know how to fast add new field?

What i do?
1. add in public/controllers/articles.js:15
````
data: this.data
`````
2. in views/create.html add:
````
  <div class="form-group" ng-class="{ 'has-error' : submitted && articleForm.data.$invalid }">
      <label mean-token="'create-data'" class="col-md-3 control-label">Data</label>
      <div class="col-md-9">
        <input name="data" type="text" class="form-control" data-ng-model="data" id="data" placeholder="data" required>
        <div ng-show="submitted && articleForm.data.$invalid" class="help-block">
          <p ng-show="articleForm.data.$error.required">data is required</p>
        </div>
      </div>

    </div>
````
3. in server/models/article.s:28 add:
````
  data: {
    type: String,
    required: true,
    trim: true
  },
`````

and working..

really is so much work to add one field?

**Comment by codydaig** [comment]
@michalmw Are you having an issue or is your code working and just curious about the multiple places of adding a field?

**Comment by lirantal** [comment]
I think this can be closed, looks like @michalmw answered his own question :)

**Comment by codydaig** [comment]
@lirantal Marking this to be closed then! @michalmw Just reopen this is you have any specific questions!
