### ISSUE TITLE
Image Upload in meanjs 

### ISSUE THREAD

**Issue by taninme** [meanjs/mean#617]
Hi 

I'm trying to use the image upload feature in 0.4 in the 0.3 version of meanjs, but I'm not sure did they use nay package for image upload ? or just the code ? please let me know. Thanks a lot 

Ferdous

**Comment by lirantal** [comment]
@taninme wait a couple of weeks, hopefully even sooner, when we'll be rolling out 0.4.0 branch.

**Comment by Maniselvam006** [comment]
hi,

I am using meanjs in my `web portal` i want to do image upload functionality in my software like change profile image functionality in another module... is there any possible and solution is available?

I want to replicate change profile image functionality in another module.

I am new to meanjs so please suggest me how to do image upload functionality as inside of <form></form> in another module.
