### ISSUE TITLE
Regarding Invocation of authentication Service in mean js

### ISSUE THREAD

**Issue by AnilKumarSamal** [meanjs/mean#619]
Hi,
I am implementing a sample application using mean js However when i refresh the page the nav bar loses the autheticated user data so i get the login page back.I think the authentication.user is getting refresh. Can someone guide me when the Authentication service in mean js gets invoked and how to resolve the issue?The refresh of page should keep the nav bar displaying the autheticated user.

**Comment by pgrodrigues** [comment]
After logging in, refresh the page and do `console.log(Authentication.user);` in your home controller. If the value is `null` check wether or not you are injecting req.user when you serve your index view like this:

    exports.renderIndex = function(req, res) {
        res.render('modules/core/server/views/index', {
           user: req.user || null
        });
    };

If you are injecting req.user then you probably messed up with passport user configs and passport is not setting the req.user value correctly :x

**Comment by AnilKumarSamal** [comment]
Thanks.
