### ISSUE TITLE
CleanMean

### ISSUE THREAD

**Issue by sielay** [meanjs/mean#620]
Hi

As I said I do couple of projects basing on this awesome stack. I did many improvements that I needed for my project. I can't spend time creating PRs and sometimes I have to go in different direction. Anyhow I love this project and to enable you to pull best cherries of my work I created https://github.com/sielayltd/cleanmean . Feel free to pull form it, especially identity and testing. I will try to keep it up to date with upstream.

**Comment by lirantal** [comment]
@sielay thanks, sounds interesting. I will definitely have a look there.
