### ISSUE TITLE
initResize is not defined

### ISSUE THREAD

**Issue by estvmachine** [meanjs/mean#626]
I got this error in the minified version of my project:

![image](https://cloud.githubusercontent.com/assets/2062668/8524241/f4be7be0-23c7-11e5-9ec7-48a7278aa725.png)

Why happen this?

**Comment by lirantal** [comment]
@estvmachine 
1. can you rebuild your assets? (css, js, etc)
2. which version of MEAN.JS is this on?

**Comment by estvmachine** [comment]
1. Yes i can rebuild the assets, the server works and all, only gives me that error.

2. Sorry i delete the version in Package.json, exist other part where i can know that? :(

**Comment by simison** [comment]
@estvmachine From [package.json](https://github.com/meanjs/mean/blob/0.4.0/package.json#L4)

Or checking which branch you're at by typing `git branch`

**Comment by codydaig** [comment]
@estvmachine Are you still having issues or can this be closed?

**Comment by estvmachine** [comment]
Im still having issues, i dont know my version, only i know i using node v.0.10.25

**Comment by lirantal** [comment]
@estvmachine 
If you deleted the package.json that's a bit of an issue. How will you know MEAN.JS version? how will you re-install all of npm requirements?

If you manage to get it sorted maybe you should re-run `npm install` to make sure everything is up to date?

**Comment by estvmachine** [comment]
I dont delete the packaje.json, only i delete the version of MEAN.JS that appears in that file.

**Comment by lirantal** [comment]
Ok, please do some checks and ping back.

**Comment by codydaig** [comment]
@estvmachine Any luck?

**Comment by codydaig** [comment]
@lirantal @estvmachine Nothing heard in over a month, can we close?

**Comment by estvmachine** [comment]
Yeah closed it
