### ISSUE TITLE
Built with MeanJS

### ISSUE THREAD

**Issue by simison** [meanjs/mean#628]
I'd like to gather a list like this: https://github.com/linnovate/mean/wiki/Built-with-Mean

Feel free to drop links here!

Fine if start create a wiki page stub?

**Comment by lirantal** [comment]
Of course, go ahead.

**Comment by simison** [comment]
Volá! https://github.com/meanjs/mean/wiki/Built-with-Mean.js

**Comment by simison** [comment]
Wait, meanjs.org isn't built with meanjs. Silly. :-)

**Comment by lirantal** [comment]
lol, nice

**Comment by lirantal** [comment]
I'll leave it open a for a while, and then we can close but I'd suggest a more 'social' ways of doing this like simply asking in twitter :)

**Comment by codydaig** [comment]
@lirantal How long do you want to keep this open?

**Comment by lirantal** [comment]
We can close it.
If it weren't updated so far then no need.
