### ISSUE TITLE
module doesnt seem to load in production mode

### ISSUE THREAD

**Issue by amobrem** [meanjs/mean#64]
when I am in development mode my menu items show up, if I set the env=production my menu items disappear. I see no errors in the console or log. I have the same dependencies defined in all.js and production.js. What am I missing?

**Comment by hiteshvadlamudi** [comment]
I am new to MeanJS and started loving it. I still seem to have this issue. 
1. I created a MeanJS Project. Added a module. 
2. grunt lint and ran the application in development mode - Works Perfect. 
3. grunt build and deploy to heroku or run locally in production mode (after setting NODE_ENV=production) the module doesnt seem to be recognized. 

Can someone help ?
