### ISSUE TITLE
PassportJS - Facebook issue

### ISSUE THREAD

**Issue by kohbongchoi** [meanjs/mean#644]
Hi everyone,

We've used this stack for awhile now, and are familiar with the entire process of setting up social authentication, in this case, via facebook provider. Setup app on facebook, add keys to the env.config and setup domains / redirect uri etc on the facebook app settings.

However, I just did a fresh install npm install -g generator-meanjs then yo meanjs into a new app, and noticed that social login is not working. If the user has not authenticated, it goes to facecbook, but after the redirect, the user is not authenticated. Subsequent attempts do not even go to facebook, and rather just redirect to /.

I have followed the same process I always have in setting everything up. I am wondering if this is an issue with passport and the 2.4 facebook api, or something else.

I also posted this issue in the meanjs google group.

I thought maybe something odd may be at work in chrome / firefox on my laptop, but I checked in both browsers on my desktop as well and the issue replicated there.

Any thoughts or help would be appreciated. Thank you

**Comment by simison** [comment]
Which branch you are using? Master is currently using old version of passport-facebook npm module and 0.4.0 branch (going to be merged soon to master) has the new 2.0 version.

Details #202

**Comment by kohbongchoi** [comment]
I had attempted with both 0.4 and 0.3 generators, same issue. Could be the 0.4 generator hasn't been updated with the new passport-facebook?

Also, what is the status on the 0.4 generator? I noticed a few issues (for one, the routes are still referencing /auth/facebook/callback instead of the new api prefixed routes.

**Comment by simison** [comment]
Can be. Could you check the package version you have? `npm ls passport-facebook`

**Comment by kohbongchoi** [comment]
Hi again, thanks. Didn't expect someone to be up at this hour :)

I checked, didn't update npm. Now everything is good again :)

**Comment by simison** [comment]
Man, it's 2pm here in Eastern Europe. ;-) Cheers.
