### ISSUE TITLE
node v0.12 doesn't prompt for a PEM password when running grunt prod

### ISSUE THREAD

**Issue by jloveland** [meanjs/mean#646]
I get this error running with ssl after generating a cert with a password:
`Error: error:0906A068:PEM routines:PEM_do_header:bad password read`

my suspicion is that node is not asking me for the password when running `grunt prod`. I am running with node v0.12.5

to resolve, I needed to remove the password from the pem like so:
```
openssl rsa -in ./config/sslcerts/key.pem -out ./config/sslcerts/newkey.pem && mv ./config/sslcerts/newkey.pem ./config/sslcerts/key.pem
chmod 0600 ./config/sslcerts/key.pem ./config/sslcerts/cert.pem
```
not sure if anyone else has seen this, but I mentioned the a reference to another person solving this issue the same way:
http://blog.mgechev.com/2014/02/19/create-https-tls-ssl-application-with-express-nodejs/

**Comment by jloveland** [comment]
assignee: @lirantal

**Comment by jhkirkley** [comment]
I agree. I ran openssl rsa -in key.pem -out newkey.pem && mv newkey.pem key.pem inside sslcerts but it could be added to the script.

**Comment by lirantal** [comment]
I understand the issue but creating a the cert with a passphrase and then removing it doesn't make much sense. We should either have another script to remove the passphrase or somehow tell the user not to use a passphrase if that's even possible.

WDYT?

**Comment by codydaig** [comment]
@lirantal That's the way every server I worked on does it, where the server keys do not have a passphrase.

**Comment by grantgeorge** [comment]
I believe if you do not use the -aes256 option it will not prompt you for a password. The script can be updated as in this PR:

https://github.com/meanjs/mean/pull/651

**Comment by lirantal** [comment]
sounds great, thanks @grantgeorge 
@jloveland I merged #651  do you want to test it out and let us know if this works for you?

**Comment by jloveland** [comment]
Sure, looks like it will work! But I will test it tonight

**Comment by lirantal** [comment]
Great. For now I'm closing the issue.
