### ISSUE TITLE
ReferenceError: Can't find variable: angular

### ISSUE THREAD

**Issue by bgobi1991** [meanjs/mean#650]
Hi, 
when run this application through this error ReferenceError: Can't find variable: angular.

can anyone give the solution ?

**Comment by vaucouleur** [comment]
Hi,

Did you follow the full install procedure, including the  "npm install" step ?

Sebastien

**Comment by bgobi1991** [comment]
Hi,
i followed steps to installation but through this error,


D:\Projects\Examples\mean-master>npm install
npm WARN package.json meanjs@0.3.3 No license field.

> meanjs@0.3.3 postinstall D:\Projects\Examples\mean-master
> bower install --config.interactive=false

bower ENOGIT        git is not installed or not in the PATH

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! meanjs@0.3.3 postinstall: `bower install --config.interactive=false`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the meanjs@0.3.3 postinstall script 'bower install --config.i
nteractive=false'.
npm ERR! This is most likely a problem with the meanjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     bower install --config.interactive=false
npm ERR! You can get their info via:
npm ERR!     npm owner ls meanjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Projects\Examples\mean-master\npm-debug.log

**Comment by codydaig** [comment]
Do you have bower installed correctly on Windows? It requires an extra step than mac/unix users
https://www.npmjs.com/package/bower#windows-users

**Comment by karan-kapoor90** [comment]
The error clearly states that either git is not installed or is not in the
path. Can you confirm if you installed git?

**Comment by bgobi1991** [comment]
Hi,
Solved this issue, thank you very much..
