### ISSUE TITLE
description & keywords env var not display content in markup #0.4.0

### ISSUE THREAD

**Issue by lukekhamilton** [meanjs/mean#660]
The app.description and app.keywords content from ./config/env/defaults.js is not being rendered in the markup. 

Have tried to workout why this, however I cant seam to work it out.

**Comment by lirantal** [comment]
this seems very relevant and related to https://github.com/meanjs/mean/pull/536 so maybe we should close #536 and instead submit a new PR on the same topic for 0.4.0 branch

**Comment by codydaig** [comment]
@lukekhamilton @lirantal 

I actually just got an email this morning about this and the correct solution from @jdalton. I will submit the pull request shortly.

**Comment by lukekhamilton** [comment]
Confirmed #665 fixes this can be closed once merged. :)

**Comment by lirantal** [comment]
great, thanks @codydaig and @lukekhamilton
