### ISSUE TITLE
Issues upon following instructions

### ISSUE THREAD

**Issue by kpennell** [meanjs/mean#661]
Still pretty beginnerish.  Tried cloning and running npm install.  Still not sure if it worked.
Seems like a lot of errors after running it as instructed.

`localhost:desktop Test$ git clone https://github.com/meanjs/mean.git meanjs
Cloning into meanjs...
remote: Counting objects: 6057, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 6057 (delta 2), reused 0 (delta 0), pack-reused 6044
Receiving objects: 100% (6057/6057), 2.47 MiB | 674 KiB/s, done.
Resolving deltas: 100% (3082/3082), done.
localhost:desktop Test$ cd meanjs
localhost:meanjs Test$ npm install
npm WARN excluding symbolic link build/defs-config.json -> ../defs-config.json
 
> fsevents@0.3.6 install /Users/Test/Desktop/meanjs/node_modules/karma/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

Error: No developer directory found at /Developer. Run /usr/bin/xcode-select to update the developer directory path.

Error: No developer directory found at /Developer. Run /usr/bin/xcode-select to update the developer directory path.

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

  SOLINK_MODULE(target) Release/.node
  SOLINK_MODULE(target) Release/.node: Finished
  CXX(target) Release/obj.target/fse/fsevents.o
../fsevents.cc:10:43: error: CoreFoundation/CoreFoundation.h: No such file or directory
../fsevents.cc:11:39: error: CoreServices/CoreServices.h: No such file or directory
In file included from ../fsevents.cc:14:
../src/storage.cc:7: error: ‘UInt64’ does not name a type
../src/storage.cc:8: error: ‘UInt32’ does not name a type
../src/storage.cc:9: error: ‘CFStringRef’ does not name a type
../src/storage.cc:13: error: ‘CFAllocatorRef’ was not declared in this scope
../src/storage.cc:13: error: expected primary-expression before ‘const’
../src/storage.cc:13: error: initializer expression list treated as compound expression
../src/storage.cc:13: error: expected ‘,’ or ‘;’ before ‘{’ token
../src/storage.cc:22: error: variable or field ‘FSEventRelease’ declared void
../src/storage.cc:22: error: ‘CFAllocatorRef’ was not declared in this scope
../src/storage.cc:22: error: expected primary-expression before ‘const’
../src/storage.cc:27: error: ‘CFArrayCallBacks’ does not name a type
../fsevents.cc:37: error: ‘CFRunLoopRef’ does not name a type
../fsevents.cc:44: error: ‘UInt32’ has not been declared
../fsevents.cc:44: error: ‘UInt64’ has not been declared
../fsevents.cc:47: error: ‘CFArrayRef’ does not name a type
../fsevents.cc:48: error: ‘CFMutableArrayRef’ does not name a type
../fsevents.cc: In constructor ‘fse::FSEvents::FSEvents(const char*, NanCallback*)’:
../fsevents.cc:62: error: ‘CFStringRef’ was not declared in this scope
../fsevents.cc:62: error: expected `;' before ‘dirs’
../fsevents.cc:63: error: ‘paths’ was not declared in this scope
../fsevents.cc:63: error: ‘dirs’ was not declared in this scope
../fsevents.cc:63: error: ‘CFArrayCreate’ was not declared in this scope
../fsevents.cc:64: error: ‘events’ was not declared in this scope
../fsevents.cc:64: error: ‘FSEventArrayCallBacks’ was not declared in this scope
../fsevents.cc:64: error: ‘CFArrayCreateMutable’ was not declared in this scope
../fsevents.cc:65: error: ‘threadloop’ was not declared in this scope
../fsevents.cc: In destructor ‘virtual fse::FSEvents::~FSEvents()’:
../fsevents.cc:74: error: ‘paths’ was not declared in this scope
../fsevents.cc:74: error: ‘CFRelease’ was not declared in this scope
../fsevents.cc:75: error: ‘events’ was not declared in this scope
In file included from ../fsevents.cc:83:
../src/async.cc: In function ‘void async_propagate(uv_async_t*)’:
../src/async.cc:10: error: ‘CFIndex’ was not declared in this scope
../src/async.cc:10: error: expected `;' before ‘idx’
../src/async.cc:15: error: ‘cnt’ was not declared in this scope
../src/async.cc:15: error: ‘class fse::FSEvents’ has no member named ‘events’
../src/async.cc:15: error: ‘CFArrayGetCount’ was not declared in this scope
../src/async.cc:16: error: ‘idx’ was not declared in this scope
../src/async.cc:17: error: ‘class fse::FSEvents’ has no member named ‘events’
../src/async.cc:17: error: ‘CFArrayGetValueAtIndex’ was not declared in this scope
../src/async.cc:18: error: ‘struct fse_event’ has no member named ‘path’
../src/async.cc:18: error: ‘kCFStringEncodingUTF8’ was not declared in this scope
../src/async.cc:18: error: ‘CFStringGetCStringPtr’ was not declared in this scope
ent’ has no member named ‘path’uct fse_ev/
../src/async.cc:19: error: ‘CFStringGetCString’ was not declared in this scope
../src/async.cc:20: error: ‘struct fse_event’ has no member named ‘flags’
../src/async.cc:20: error: ‘struct fse_event’ has no member named ‘id’
../src/async.cc:22: error: ‘class fse::FSEvents’ has no member named ‘events’
../src/async.cc:22: error: ‘CFArrayRemoveAllValues’ was not declared in this scope
In file included from ../fsevents.cc:84:
../src/thread.cc: In member function ‘void fse::FSEvents::threadStart()’:
../src/thread.cc:32: error: ‘threadloop’ was not declared in this scope
../src/thread.cc: At global scope:
../src/thread.cc:36: error: variable or field ‘HandleStreamEvents’ declared void
../src/thread.cc:36: error: ‘ConstFSEventStreamRef’ was not declared in this scope
../src/thread.cc:36: error: expected primary-expression before ‘void’
../src/thread.cc:36: error: expected primary-expression before ‘numEvents’
../src/thread.cc:36: error: expected primary-expression before ‘void’
../src/thread.cc:36: error: expected primary-expression before ‘const’
../src/thread.cc:36: error: expected primary-expression before ‘const’
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 12.4.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/Test/Desktop/meanjs/node_modules/karma/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN optional dep failed, continuing fsevents@0.3.6
 
> phantomjs@1.9.17 install /Users/Test/Desktop/meanjs/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-macosx.zip
Saving to /var/folders/gf/nqy4g32j7jxcfscmn2ltjnbr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip
Receiving...
/ [=======================================-] 98% 0.0s-
Received 9187K total.
Extracting zip contents
Removing /Users/Test/Desktop/meanjs/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /var/folders/gf/nqy4g32j7jxcfscmn2ltjnbr0000gn/T/phantomjs/phantomjs-1.9.8-macosx.zip-extract-1437248663701/phantomjs-1.9.8-macosx -> /Users/Test/Desktop/meanjs/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/Test/Desktop/meanjs/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN optional dep failed, continuing readable-stream@2.0.2
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
 
> kerberos@0.0.11 install /Users/Test/Desktop/meanjs/node_modules/connect-mongo/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
  SOLINK_MODULE(target) Release/kerberos.node: Finished
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"0.10.35","npm":"1.4.28"})
npm WARN optional dep failed, continuing readable-stream@2.0.2
\
> bson@0.2.21 install /Users/Test/Desktop/meanjs/node_modules/connect-mongo/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished
 
> kerberos@0.0.11 install /Users/Test/Desktop/meanjs/node_modules/mongoose/node_modules/mongodb/node_modules/kerberos
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/kerberos/lib/kerberos.o
  CXX(target) Release/obj.target/kerberos/lib/worker.o
  CC(target) Release/obj.target/kerberos/lib/kerberosgss.o
  CC(target) Release/obj.target/kerberos/lib/base64.o
  CXX(target) Release/obj.target/kerberos/lib/kerberos_context.o
  SOLINK_MODULE(target) Release/kerberos.node
  SOLINK_MODULE(target) Release/kerberos.node: Finished

> bson@0.2.21 install /Users/Test/Desktop/meanjs/node_modules/mongoose/node_modules/mongodb/node_modules/bson
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bson/ext/bson.o
  SOLINK_MODULE(target) Release/bson.node
  SOLINK_MODULE(target) Release/bson.node: Finished
 
> ws@0.4.32 install /Users/Test/Desktop/meanjs/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
npm WARN optional dep failed, continuing default-browser-id@1.0.2

> v8-profiler@5.2.9 preinstall /Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
>  

> v8-debug@0.4.6 preinstall /Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
>  

 
> ws@0.4.32 install /Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished

> v8-debug@0.4.6 install /Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-debug/build/debug/v0.4.6/node-v11-darwin-x64/debug.node" is installed via remote

> v8-profiler@5.2.9 install /Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/Users/Test/Desktop/meanjs/node_modules/grunt-node-inspector/node_modules/node-inspector/node_modules/v8-profiler/build/profiler/v5.2.9/node-v11-darwin-x64/profiler.node" is installed via remote
npm ERR! Error: EACCES, mkdir '/Users/Test/.npm/on-finished/2.1.1'
npm ERR!  { [Error: EACCES, mkdir '/Users/Test/.npm/on-finished/2.1.1']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/Users/Test/.npm/on-finished/2.1.1',
npm ERR!   parent: 'body-parser' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/Test/Desktop/meanjs
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /Users/Test/.npm/on-finished/2.1.1
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, mkdir '/Users/Test/.npm/on-finished/2.1.1'
npm ERR! not ok code 0`

**Comment by kpennell** [comment]
I ran `grunt` and get this:


localhost:meanjs Test$ grunt
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?

Running "jshint:all" (jshint) task
>> 57 files lint free.

Running "csslint:all" (csslint) task
>> 2 files lint free.

Running "copy:localConfig" (copy) task
Copied 1 file

Running "concurrent:default" (concurrent) task
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?

Running "nodemon:dev" (nodemon) task

Running "watch" task
Waiting...
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
NODE_ENV is not defined! Using default development environment

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Test/Desktop/meanjs/config/express.js:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Test/Desktop/meanjs/server.js:29:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[nodemon] app crashed - waiting for file changes before starting...
^Clocalhost:meanjs Test$ npm install -g grunt-cli
npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/grunt-cli'
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/grunt-cli']
npm ERR!   errno: 3,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/grunt-cli' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Darwin 12.4.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "grunt-cli"
npm ERR! cwd /Users/Test/Desktop/meanjs
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! path /usr/local/lib/node_modules/grunt-cli
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, unlink '/usr/local/lib/node_modules/grunt-cli'
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/grunt-cli'
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/grunt-cli']
npm ERR! error rolling back   errno: 3,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/grunt-cli' }
npm ERR! not ok code 0
localhost:meanjs Test$ sudo npm install -g grunt-cli
Password:
/usr/local/bin/grunt -> /usr/local/lib/node_modules/grunt-cli/bin/grunt
grunt-cli@0.1.13 /usr/local/lib/node_modules/grunt-cli
├── resolve@0.3.1
├── nopt@1.0.10 (abbrev@1.0.7)
└── findup-sync@0.1.3 (lodash@2.4.2, glob@3.2.11)
localhost:meanjs Test$ grunt
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?

Running "jshint:all" (jshint) task
>> 58 files lint free.

Running "csslint:all" (csslint) task
>> 2 files lint free.

Running "copy:localConfig" (copy) task


Running "concurrent:default" (concurrent) task
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?

Running "watch" task
Waiting...

Running "nodemon:dev" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
NODE_ENV is not defined! Using default development environment

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Test/Desktop/meanjs/config/express.js:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Test/Desktop/meanjs/server.js:29:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[nodemon] app crashed - waiting for file changes before starting...
^Clocalhost:meanjs Test$ grunt
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?

Running "jshint:all" (jshint) task
>> 58 files lint free.

Running "csslint:all" (csslint) task
>> 2 files lint free.

Running "copy:localConfig" (copy) task


Running "concurrent:default" (concurrent) task
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?
>> Local Npm module "grunt-contrib-uglify" not found. Is it installed?
>> Local Npm module "grunt-contrib-cssmin" not found. Is it installed?

Running "watch" task
Waiting...

Running "nodemon:dev" (nodemon) task
[nodemon] v1.2.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: app/views/**/*.* gruntfile.js server.js config/**/*.js app/**/*.js
[nodemon] starting `node --debug server.js`
debugger listening on port 5858
NODE_ENV is not defined! Using default development environment

module.js:340
    throw err;
          ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Test/Desktop/meanjs/config/express.js:9:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/Test/Desktop/meanjs/server.js:29:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by mleanos** [comment]
@kpennell Have you tried running npm install again, after you installed grunt-cli?

Also, are you sure you're running the command window (I used cmd.exe since I'm on Windows) with the proper permissions; for me I run it as an Administrator.

**Comment by kpennell** [comment]
yeah, I did that but no luck.  Running this in terminal.

**Comment by codydaig** [comment]
What node and npm versions are you running?

**Comment by codydaig** [comment]
@kpennell Are you still having issues?

**Comment by kpennell** [comment]
I'm sorry. I just gave up on it when it didn't work.

**Comment by codydaig** [comment]
Can we close this issue then?

**Comment by lirantal** [comment]
@kpennell it's pretty clear from the error messages - express module couldn't be found so I assume you need to re-run `npm install`

**Comment by mondher25** [comment]
oading "grunt-karma.js" tasks...ERROR
>> TypeError: Cannot read property 'prototype' of undefined
>> Local Npm module "grunt-node-inspector" not found. Is it installed?
