### ISSUE TITLE
0.5.0 Coding Conventions

### ISSUE THREAD

**Issue by lirantal** [meanjs/mean#670]
- [ ] JSHint configuration to enforce more restrictions
- [x] Replacing Tab indentations with 2 spaces indent ( @ilanbiala @simison @codydaig  )
- [ ] Code Documentation (jsdoc/ngdoc/whatever you suggest) + every PR will be accompanied with another gh-pages PR to update the project documentation when relevant. ( @codydaig @ilanbiala @simison )

**Comment by simison** [comment]
I'd love to see one massive tabs => spaces change right after 0.4.0. Would make it easier later to track 0.5.0 changes.

Tabs/spaces seems to be a very common issue with PLs.

**Comment by ilanbiala** [comment]
+1 on that. 2 spaces or the tab equivalent is best.

**Comment by simison** [comment]
Otherwise this is total bikesheddig but I think [this](https://www.quora.com/Is-it-preferable-to-use-tabs-or-spaces-when-writing-code-Why/answer/Albert-Sheu) nails it:
>Spaces look the same everywhere. Tabs don't.

**Comment by simison** [comment]
By documentation do you mean documenting coding conventions or adding [jsdoc](http://usejsdoc.org/) (or even ngdoc)?

**Comment by lirantal** [comment]
Seems like there's no discussion required on the indentation type (thank god!) - we'll go with 2 spaces indent like the rest of the world (I'll update the item there)

I mean both code documentation as well as general documentation. Code docblock is self-explained. General documentation means that if we merge a PR that makes some change to how things work then it should be accompanied by another gh-pages PR that updated the documentation accordingly. Otherwise we get a big pile of technical debt in documentation.

**Comment by ilanbiala** [comment]
+1 on docs required to merge a PR as well.

**Comment by codydaig** [comment]
+1 on changed requiring an updates docs PR

+1 on spaces instead of tabs!

**Comment by simison** [comment]
+1 docs update requirement. A _CONTRIBUTING.md_ file would come handy. It would briefly explain all this and appear as a link on top the form when adding new issues/PL's. See [our page](https://github.com/Trustroots/trustroots/issues/new) for an example.

**Comment by lirantal** [comment]
@simison I've been wanting to add that CONTIRBUTING.md page for the past 2 weeks but haven't yet gotten to it, so you're welcome to PR it. Generally we need it as a documentation page on gh-pages as well as an actual file. 

Most importantly is what the contents of it will be and the guidelines there still need to be worked out. I have more than few already noted down but I'll close that list and we can definitely start with something..

**Comment by codydaig** [comment]
#690 i created an initial CONTRIBUTING.md file thats open for discussion!
@lirantal @simison @ilanbiala

**Comment by lirantal** [comment]
Yep, thanks.
I need to review it first and wanted to add some items to it too, we'll take it in the PR.

**Comment by vaucouleur** [comment]
Should there be a space between the keyword 'function' and the parameter list ?
I'm seeing some minor inconsistencies. Not a big deal, but it makes merging slightly more complicated when one use "auto-indentation" with his/her favorite code editor. 

**Random code examples without the space:**
* https://github.com/meanjs/mean/blob/a66c3fe5a7bf47acfa7a3748a5ca8fe143b58221/gulpfile.js#L178
* https://github.com/meanjs/mean/blob/a66c3fe5a7bf47acfa7a3748a5ca8fe143b58221/modules/core/tests/client/menus.client.service.tests.js#L4

**Random code examples  with the space:**
* https://github.com/meanjs/mean/blob/a66c3fe5a7bf47acfa7a3748a5ca8fe143b58221/gulpfile.js#L117
* https://github.com/meanjs/mean/blob/a66c3fe5a7bf47acfa7a3748a5ca8fe143b58221/modules/articles/client/controllers/articles.client.controller.js#L9


**For reference, the angular team seems to use the "no-space" option, see for example:**
* https://github.com/angular/angular/blob/7140c9cc341e477843423eeaebe264fe588338f4/tools/check-environment.js#L7
* https://github.com/angular/angular.js/blob/master/src/ngRoute/route.js#L236


**While the npm team seems to use a space, see for example**:
* https://github.com/npm/npm/blob/90ac6dc6eebde8cc4de14f194bb69d7d212913a0/lib/cache.js#L161
* https://github.com/npm/npm/blob/90ac6dc6eebde8cc4de14f194bb69d7d212913a0/lib/utils/git.js#L19

**Comment by mleanos** [comment]
@vaucouleur Personally, I like to have the space in these cases. It makes it easier for me to read. I agree that one way or the other must be used to avoid painful merges.

Perhaps, the settings in the editorconfig can be decided upon. Not sure if what is there, was previously decided. This file was recently updated to use spaces for indentation.
https://github.com/meanjs/mean/blob/0.4.0/.editorconfig

**Comment by lirantal** [comment]
+1 with @mleanos, I too also prefer to have spaces for function arguments.

**Comment by ilanbiala** [comment]
Didn't we take care of the tabs -> spaces? The JSHint stuff is currently being discussed in another issue. @lirantal @codydaig @mleanos I think what we should look at is moving the gh-pages branch to a separate repo and setting up a good system for every documentation with PR.

**Comment by mleanos** [comment]
@ilanbiala I'm all for moving the gh-pages to a new repo. It's difficult for me to manage switching back & forth between those branches; part of the reason why I've steered clear of the documentation contributions thus far (and that I'm on Windows). I think we can coordinate documentation syncing with PR's with this repo

I think we did figure out the spaces/tabs issue. If not, then we should definitely address it in the other issue that's being discussed right now.

**Comment by codydaig** [comment]
@ilanbiala That's what I've advocated before!!

Spaces have been addressed. We moved from 4 spaces too 2.

**Comment by ilanbiala** [comment]
@lirantal if you're not opposed, I think @codydaig might want (?) to take up creating a new repo for the docs and moving them there.

**Comment by codydaig** [comment]
@ilanbiala I'm down!

**Comment by ilanbiala** [comment]
@lirantal @codydaig I think this issue has been taken care of as far as we can right now, and we'll open new issues as we think of new stuff? Close?

**Comment by codydaig** [comment]
Close

**Comment by lirantal** [comment]
indeed, thanks guys.
