### ISSUE TITLE
Password required Validation error on user update

### ISSUE THREAD

**Issue by bluekrill** [meanjs/mean#672]
Hi,
I am using a standard meanjs base for my app, when I try to update an user, it gives me a save failed error :
Saving error is :

      { 
        [ValidationError: Validation failed]
        message: 'Validation failed',
        name: 'ValidationError',
        errors:
         { password:
           { [ValidatorError: Path `password` is required.]
               message: 'Path `password` is required.',
               name: 'ValidatorError',
               path: 'password',
               type: 'required',
               value: undefined } } }

I have tried both, retrieving the password for that particular user and then trying to save -> In this case the password is rehashed, making the old password obsolete and making the user incapable of logging in again.

Second, deleting password field using :

    delete user._doc.password;

before saving, in which case I get the same error. What could be the reason for this? I would really appreciate some help with this. The ONLY solution is for me to reload (window.location.reload) the edit profile page, after which everything seems to work just fine. But this is now a problem as I am trying to enable html5mode, which breaks on reload. More than a direct solution, I would love to know why this is happening? Why does a reload fix this? What is changing in the user object after a reload, only on this page, when I can access all the user fields on the display profile page already with ease, without reloading.

**Comment by lirantal** [comment]
Hi @bluekrill,

The changed password issue got resolved on branch 0.4.0 which will be soon released.
If you need to continue supporting the current version of MEAN.JS which you used then you can easily backport the fix (it's very focused) to your version and apply it.

**Comment by bluekrill** [comment]
Thanks @lirantal, I would like to backport the fix to my version. Just to be sure, I would have to perform a git cherry-pick master-0.4.0 to get this done right? If not, could you please tell me the right way to go about it, would really appreciate it.

**Comment by lirantal** [comment]
Or you could just take a look at the actual change in this PR https://github.com/meanjs/mean/pull/642 and copy&paste it to your code.

**Comment by bluekrill** [comment]
@lirantal Thanks, but I have already tried the isModified solution, in both cases -> without retrieving the password, in which case it still gives the Password validation error, and retrieving the password, and then trying to save, in which case it does not detect that the password is not modified and proceeds to rehash it.

I copied you code and tested it out again. No luck. Why would it not detect that the password is not modified?

**Comment by lirantal** [comment]
I assume you are working on the latest 'master' code? if so can you give us step by step instruction how to reproduce the problem you are facing?

**Comment by bluekrill** [comment]
@lirantal Hey, I am not using the latest master code. Will update and get back to you with the result. Hopefully that will fix it :). Thanks for the help.

**Comment by bluekrill** [comment]
@lirantal I found the problem, apparently I had set the password field in my user model as required. This was causing any updates to check for the password and hence the error. Though, the error would disappear after a page reload was forced, so I never thought this could be the problem. It all works fine now, so I guess the issue can be closed. Still can't understand what the page reload did to cause the Password required error to disappear. Thanks for your help.

**Comment by bluekrill** [comment]
@lirantal I have now the updated master version, and now the earlier problem of a Password validation error no longer exists. The user profile is successfully updated, but unfortunately now it either deletes the password field if it does not exists, or rewrites it, if it does. 

I am using the exact same server function to update as the master code, and retrieving the user from the exact same authentication service as the master code. No changes here except the additions to the User model to suit my app. Everything is updating correctly, unfortunately including the password which was removed by Passport at the time of retrieval. I still have the isModified function in place in my pre save method.

The password retrieval error was due to the fact that I had set my password field as required. Once I changed that, it is now overwriting my password, or deleting the field entirely, depending on how I send it across.

**Comment by lirantal** [comment]
@bluekrill 2 things:
1. can you submit a PR for master branch which fixes this problem?
2. can I ask you to try out the 0.4.0 branch of meanjs where this issue has been resolved?

**Comment by bluekrill** [comment]
@lirantal Sorry for the late response. I can definitely do those things. Thanks.

**Comment by lirantal** [comment]
Great, thanks.
