### ISSUE TITLE
DIgital ocean Mean droplet

### ISSUE THREAD

**Issue by Valonix** [meanjs/mean#674]
Hello, i am new in MEAN.js, angular, node and angular :)) but i want learn that stack.
I install mean stack in digitalocean droplet after i wrote grunt command i see that 
![image](https://cloud.githubusercontent.com/assets/8511169/8783427/6fec0afa-2f24-11e5-9aa1-dc64be372c8f.png)

it is normal errors? 

and where i can find mongo config and storage data after registration and other? i want see that code and learn how mongo db works.
I am PHP developer who learn JS and i have big experience in jquery.

**Comment by lirantal** [comment]
@Valonix welcome to the gang.
My most significant recommendation for you is to clone and checkout the 0.4.0 branch for the MEAN.JS project because it is quite the re-write of the project (files structure, etc) and will be released soon. This will guarantee that what you learn won't be wasted away with the new 0.4.0 release.

The issue there seems to be related to a non-compatible executable, not sure why.

**Comment by danaronoff** [comment]
@Valonix That js-bson error is in my DO image as well, but the app still runs. I imagine as @lirantal said the binaries for that module need to be updated or recompiled. 

I see you are using port 80 directly -- did you change that? Are you running the program as root? There are security implications with that. See here for a workaround: http://stackoverflow.com/questions/16573668/best-practices-when-running-node-js-with-port-80-ubuntu-linode

For configuration details on the 0.4.0 branch check out the config folder. Files in the end/ folder are where connection details are specified and the lib/ folder has a lot of the application startup logic.

**Comment by Valonix** [comment]
@danaronoff yeah, i change port from 3000 to 80. fot see site without :3000 in url . is this mistake? 

@lirantal you can tell me what i need to do in steps? i am really novice in all of this:) 
I understand I need to wait for a while and set all over again only this new version?

**Comment by codydaig** [comment]
@Valonix https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-14-04

It's generalized for any node.js application, but a great tutorial on running a node.js application in production.

**Comment by Valonix** [comment]
@codydaig ok, but  I just think that it is putting the stack where everything is already set up and including Mongo DB, I'll see what it looks like normally :)

**Comment by Valonix** [comment]
i paste this code in console 
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000 
and my site work withour :3000 is this bad idea?

**Comment by danaronoff** [comment]
As far as I know there are two ways to do it. The first is with a reverse proxy like ngnix (described in the link from @codydaig) and the other is through firewall rules like the one you just implemented. For a small website or a development environment, I don't see any issue with the firewall solution. For bigger websites needing to scale horizontally, the ngnix method is probably preferable.

**Comment by Valonix** [comment]
this is mt first step:) i think i didn`t need 100 firewalls and other security :)

**Comment by Valonix** [comment]
@lirantal how i can install branch https://github.com/meanjs/mean/tree/0.4.0 by readme file?

**Comment by codydaig** [comment]
To use grunt, you have to run 
```
npm install -g grunt-cli
```

**Comment by Valonix** [comment]
maybe i am stupid:) but i can`t understand how i must install 0,40 branch on new ubuntu server.
maybe i can some change after i install mean on digitalocean?
edit some file and write smth - file update and he download all needed file :)

http://188.166.108.124:3000/#!/ that is works , just install mean on 14.04 in digitalocean.

**Comment by codydaig** [comment]
For a bare bone ubuntu server, Digital Ocean has some great tutorials on how to get a server-up for Node. At minimum, the server needs to have Node and MongoDB installed.

To Use MEAN on a server with Node and MongoDB installed:
1.) Download the 0.4.0 branch: https://github.com/meanjs/mean/archive/0.4.0.zip
2.) Extract the files
3.) npm install
4.) grunt
5.) You should be good to go. You may have to open port 3000, or forward port 80 to port 3000 but that's dependent upon your server configuration.

**Comment by Valonix** [comment]
okay, thank, i try this later :)

**Comment by codydaig** [comment]
@Valonix Any more issues or can this issue be closed?
