### ISSUE TITLE
Proposal with working code:  separate core from boilerplate.  Adopt contrib module system.

### ISSUE THREAD

**Issue by MichaelJCole** [meanjs/mean#68]
Hi,

This is a proposal to add a core and plugin system to MEAN.JS

My motivation for this is:

1) To get an awesome clean boilerplate for new projects
2) Get updates to core code easily through npm
3) Get new features through modules from an open and thriving community
# The TLDR;

Here is a MEAN.JS boilerplate app using a new core and contrib plugin system implemented via npm.

To see the code in action:

```
git clone git@github.com:MichaelJCole/mean.git
cd mean
git checkout meanjs-core
npm install
grunt build
grunt
```

Notice package.json has two modules: meanjs-core and meanjs-module

In action:
1. Signup a new user and you should get an email.
2. Click [a confirmation link](http://localhost:3000/auth/confirm/adsfasdfasdf) and check your server console.
# Proposal

The proposal is to adopt a framework for boilerplate, core, and contrib code.

To move forward, I propose we: 

1) start to refactor core code out of the boilerplate and into meanjs-core
2) add new features (email verification and lost password) to meanjs-core
3) refine the boilerplate for the best end-developer experience
4) experiment with contrib modules and configuration, propose some best practices
5) adjust core best practices as we go

Please send any suggestions or comments!  What do you think?
# The details

I wanted to add three features to my MEAN.JS app:
1. email verification
2. lost passwords
3. subscription to an email list at MailChimp on signup.

1) & 2) seemed like 'core' functionality.  Something MEAN.JS would probably want to maintain 

3) is very custom.  Probably not maintained by MEAN.JS, but something I could share with other developers.

I created a plugin system in the MEAN.JS boilerplate forked [here](https://github.com/MichaelJCole/mean) that uses it's package.json to import modules [meanjs-core](https://github.com/MichaelJCole/mean-core) and [meanjs-module](https://github.com/MichaelJCole/mean-module).
## In action:  Signup email

1) Sign up as a new user.  An email should be sent to the address you used.

This email came from Mandrill email service account (I'll change the keys shortly).
You can config your own email transport in config/env/development.js 'emailTransactional'

The core function sendConfirmEmail is called from the boilerplate in app/controller/users.server.controller.js:

```
/**
 * Signup
 */
exports.signup = function(req, res) {
  // ...  

  // Then save the user 
  user.save(function(err) {
    if (err) {
      // ...
    } else {
      // ...
      req.login(user, function(err) {
        // ...
      });

      var templateData = {
        user: user
      };
      // Send confirmation email
      req.core.users.sendConfirmEmail(req, user, 'confirmation.email', templateData);
    }
  });
};
```

In the console you should see:

```
meanjs-core - users.server.controller.js - sendConfirmEmail...
---> about to send to: test23@michaelcole.com
---> email sent
POST /auth/signup 200 46ms - 254b
Message sent: 250 2.0.0 Ok: queued as 0801A20024B
```
## In action: confirmation link and custom contrib module

2) Click a confirmation link:
[](http://localhost:3000/auth/confirm/adsfasdfasdf)

This has two requirements:
1. Mark the user's email as confirmed in meanjs-core
2. Sign user up for MailChimp email list in contrib meanjs-module

The route is configured in the boilerplate users.server.routes.js like this:

```
  // Confirm user's email
  app.route('/auth/confirm/:confirmationCode')
    .get(app.core.users.checkEmailVerification)
    .get(app.core.users.processEmailVerification)
    .get(app.mean.myModule.subscribeMarketingEmails)
    .get(app.core.users.completeEmailVerification);
```

There are 4 controllers here:
1. Core: checkEmailVerification checks the link.  Not ok => go to error page.  Ok => call next()
2. Core: processEmailVerification.  Update db. Call next()
3. Contrib: subscribeMarketingEmails.  Use MailChimp API.  Call next()
4. Core: completeEmailVerification.  Return 'ok' to client

This let's the end-developer:
- add/remove/remix these controllers to get the functionality they want.  
- Get bug fixes through npm. 
- Have an ecosystem for contributed modules.
### To add your own custom module

Add a contributed module in your boilerplate's server.js:

```
// after mongoose initializes db
var meanModules = {
  'myModule': require('meanjs-module')(db, config) // edit config files if needed.
  // add your module here.
};
```
### How it works

meanModules, core, and config are automatically attached to app and req in /config/express.js so they can be used like this:

```
// Config
app.config
req.config
// Core functionality
app.core.[submodule].[export]
req.core.[submodule].[export]
// Contributed modules
app.mean.[export]
req.mean.[export]
```

For technical details, the meanjs-core/README.md was my coding plan and notes.

meanjs-core and meanjs-module are pretty simplistic right now.  I implemented just enough to demonstrate how core and contrib modules would interact with the boilerplate.
### Results of clicking the link

Clicking the link should reply with 'ok'.  So clearly I didn't fully implement this yet.  But check your server console to see what happened.

```
[nodemon] starting `node --debug server.js`
debugger listening on port 5858

 NODE_ENV is not defined! Using default development environment

Failed to load c++ bson extension, using pure JS version
meanjs-module - requiring...
meanjs-module - configuring...
Failed to load c++ bson extension, using pure JS version
meanjs-core - requiring...
meanjs-core - configuring...
meanjs-core - users.server.controller.js - requiring...
setting up email
MEAN.JS application started on port 3000
meanjs-core - users.server.controller.js - checkEmailVerification...
checking.  Success!
meanjs-core - users.server.controller.js - processEmailVerification...
updating user object
meanjs-module - subscribeMarketingEmails controller...
meanjs-core - users.server.controller.js - getCurrentUser...
meanjs-module - User subscribed to marketing emails
meanjs-core - users.server.controller.js - completeEmailVerification...
GET /auth/confirm/adsfasdfasdf 304 15ms
```

You can see console messages of when the different functions are being called.
# Comments

So, it's not fully baked, but it's enough to move in a direction.  

Todo:  
- Core Client-side AngularJS code.  My background is server side, but I'll need to find a way to get the email list functionality to work.  Symfony2 in php used symlinks to pull in client code from modules.
- Mongoose data models.  It would be nice to factor this out of boilerplate and into core.  

You read this far, thanks!  Click reply and tell me what you think?

**Comment by sreemohan003** [comment]
i am getting error while cloning i have added 

git clone git@github.com:MichaelJCole/mean.git
Cloning into 'mean'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
