### ISSUE TITLE
errorHandler.getErrorMessage(err) in the Article middleware 0.4 branch

### ISSUE THREAD

**Issue by vaucouleur** [meanjs/mean#680]
Hi,

I noticed something which looks suspicious, although it should probably have been discovered by now, so I might have missed something. It's on the current 0.4 branch, can someone double check this please ?

- At the following line, we're using the err variable:

https://github.com/meanjs/mean/blob/52fe4434290aebc152a561287966701ef9b61410/modules/articles/server/controllers/articles.server.controller.js#L103

- .. although the previous if statement "if (err) return next(err);" seems to ensure that the call to getErrorMessage will only get called, from this method, with a null err argument. 

If this is indeed the case, it seems dangerous because the following line in getErrorMessage is trying to access a 'code' property, possibly on a null variable:

https://github.com/meanjs/mean/blob/52fe4434290aebc152a561287966701ef9b61410/modules/core/server/controllers/errors.server.controller.js#L26

Thanks,
Sebastien

**Comment by vaucouleur** [comment]
Following up on this, there is indeed, I believe a small issue. The issue was hidden by the test, that is mixing two (related but distinct) aspects:

* Use of an invalid Id (in the sense: "a badly formed Id", one that does not follow Mongodb conventions)

* Use of an non existent Id (in the sense: "a non existing document")

Separating those two issues in two distinct tests exposes the issue:

https://github.com/vaucouleur/mean/commit/d35fd5f2836c2412cd5fb0884215880bd8799119

I will issue a PR for the test fix. This commit only contains the fix for the test, I guess it's better to isolate the test-fix and the middleware-fix; but I could combine both of them if you prefer.

**Comment by lirantal** [comment]
@vaucouleur I see your point, thanks, let's take it in the PR discussion.

**Comment by vaucouleur** [comment]
New PR
https://github.com/meanjs/mean/pull/720

**Comment by codydaig** [comment]
Should this be closed now that #720 has been merged?

**Comment by lirantal** [comment]
yes, thanks @codydaig
