### ISSUE TITLE
Minor issue: Unused local variable passport in express.js branch 0.4.0

### ISSUE THREAD

**Issue by vaucouleur** [meanjs/mean#694]
Hi,

A minor issue: Unused local variable passport in express.js branch 0.4.0, probably left over after a recent refactoring.

https://github.com/meanjs/mean/blob/00a4c0603aa6a2c785361a37cff6e5ae153b5688/config/lib/express.js#L18

**Comment by lirantal** [comment]
Thanks @vaucouleur , I have a PR for that.

**Comment by lirantal** [comment]
closing this due to PR https://github.com/meanjs/mean/pull/699 to fix it
