### ISSUE TITLE
Socket.io won't connect after redirect from Chat client controller 0.4.0

### ISSUE THREAD

**Issue by mleanos** [meanjs/mean#696]
I've been working with the Chat feature of the 0.4.0 branch, and I've identified an issue with the client Socket service instantiation. I think the current implementation of the Socket service, and Chat module can be refactored with minimal changes. I've done this within my own app, but the implementation is slightly different. 

To reproduce the issue.. Try to access the /chat route when you're not logged in. Then go through the login process, and go to the Chat module. The Socket isn't connected, and since the service has already been instantiated (when the user wasn't logged in), then the user can't send messages.

I can create a PR for this. Let me know, and I'll be more than happy.

**Comment by mleanos** [comment]
Perhaps, the issue that is causing #482?

**Comment by lirantal** [comment]
Woah, that's quite a bug. Good catch @mleanos a PR for that would be blessed, thank you.

**Comment by mleanos** [comment]
I submitted PR #701 for this.
