### ISSUE TITLE
Minor issue in config/config.js

### ISSUE THREAD

**Issue by L1CH** [meanjs/mean#702]
I'm new to mean.js and I'm going through configs and codes.

I found in the config.js
https://github.com/meanjs/mean/blob/0.4.0/config/config.js#L82-83
Should it be "console.log(chalk.red(..."  instead of "chalk.red(console.log(..."?

Thanks

**Comment by lirantal** [comment]
@L1CH good one, even though it works, we should change it even for consistency reasons across the project
