### ISSUE TITLE
Travis CI Improvements

### ISSUE THREAD

**Issue by cdriscol** [meanjs/mean#717]
I've had a few thoughts/suggestions on improving our current (0.4.0 branch) CI and wanted to get community input:

* **jshint should fail the build**
 * This can help catch some simple mistakes.
* **test errors should fail the build**
 * otherwise, what's the point of tests?
* **Can we run Travis CI on all commits?  Or force PRs?**
 * [This commit](https://github.com/meanjs/mean/commit/9fc88e6e5b5bd05c1e532246356725a3fa16a223) is what introduced some breaking tests, but CI didn't run on it because it wasn't a PR.

Mistakes happen, by everyone, and that's why we have a CI build that runs jshint, tests, etc.. now we just need it to tell us when things aren't okay.

FYI - [Here](https://travis-ci.org/meanjs/mean/jobs/72572487) is an example from Travis CI where **jshint and karma tests failed** but Travis marked this as **Passed**.

**Comment by codydaig** [comment]
@cdriscol Agreed!

**Comment by ilanbiala** [comment]
@cdriscol I'd love to see these changes. Any idea of what we can do?

**Comment by lirantal** [comment]
@cdriscol I've already started working on those changes exactly (apart from your last item on travis-ci configuration), although I was quite busy the last week so if you have anything to submit a PR for go ahead, otherwise I'll just get to it within a couple of days.

**Comment by cdriscol** [comment]
@lirantal - good enough for me!  thanks!
