### ISSUE TITLE
EADDRINUSE when running in debug

### ISSUE THREAD

**Issue by craigxgibbons** [meanjs/mean#721]
When attempting to run a newly generated site with no modifications the grunt task reports the following error:

Running "concurrent:default" (concurrent) task
Error: listen EADDRINUSE

My IDE (WebStorm) generates the following command:
/usr/local/bin/node --debug-brk=50956 /usr/local/lib/node_modules/grunt-cli/bin/grunt --gruntfile /Users/MyName/Documents/Dev/MEANJSSite/gruntfile.js

I know this error message means the port is already in use, but I can't seem to find any way around the issue.

EDIT: The full error stacktrace is as follows:

Running "concurrent:default" (concurrent) task
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Agent.Server.listen (net.js:1267:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Agent.Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Agent.Server.listen (net.js:1267:5)
    at Object.start (_debugger_agent.js:20:9)
    at startup (node.js:86:9)
    at node.js:814:3

**Comment by simison** [comment]
Do you have this running double or something else running at the background? (e.g. Rails or Node app...)

**Comment by craigxgibbons** [comment]
Absolutely nothing else is running in the background. I have tried this with a new app after a reboot and it produces the same error.

I have also spent about 2 hours Googling this problem. There is a long thread from about 2 years ago which doesn't seem relevant anymore. Other than that I can't find anything.

**Comment by simison** [comment]
or firewall blocking some ports perhaps?

**Comment by craigxgibbons** [comment]
I'm on a standard Mac working locally, the firewall is turned off. If I do: lsof -i | grep LISTEN

I can see nothing is listening on any port which WebStore or node uses. It's just my local MongoDB, my email and the WebStorm IDE. I'm going to bootcamp back to Windows and see if there result is the same but I suspect the grunt task is inadvertently hooking 2 processes to the same port

**Comment by simison** [comment]
Nah, Grunt is fine; just pulled fresh and tested both master and 0.4.0 branches. I'm also on also on OSX and node v0.12.7.

How about user rights, no special restrictions with the user your running it with?

Could you try and run express sample app? http://expressjs.com/starter/hello-world.html

**Comment by craigxgibbons** [comment]
I restarted in Windows, created a brand new meanjs app using the generator, opened it up in WebStorm and tried to debug using grunt again - the same issue occurs. Running with just 'grunt' works fine, but the debug commands cause the issue. I don't have any specific user running, just my default logins.

I did also try the basic barebones express app you mentioned and that works just fine. I'm not sure where to go from here, I'm new to node so it's quite possible something I'm doing wrong. Thanks for helping out with this.

**Comment by simison** [comment]
>Running with just 'grunt' works fine, but the debug commands cause the issue.

Hmm, what debug command you're referring to?

**Comment by craigxgibbons** [comment]
WebStorm executed the following command when running in Debug vs just a 'Run' ('grunt' command:

/usr/local/bin/node --debug-brk=50956 /usr/local/lib/node_modules/grunt-cli/bin/grunt --gruntfile /Users/MyName/Documents/Dev/MEANJSSite/gruntfile.js

The port is arbitrary and changes on each launch

**Comment by simison** [comment]
Ahaa, I see. Grunt file already [launches the app with node](https://github.com/meanjs/mean/blob/master/gruntfile.js#L91-L100) so doing so from the command line you end up running it double.

'grunt' is already debug mode command and you'll have for instance [node-inspector](https://github.com/meanjs/mean/blob/master/gruntfile.js#L101-L113) running there. Perhaps your IDE can hook into that.

**Comment by craigxgibbons** [comment]
Aah, ok that makes sense - I do believe you've cracked it. It's unfortunate this is the default option in WebStorm. I'll have to have a dig to see if I can find what config works for setting up WebStorm with a generated meanjs site.

Thanks again, much obliged.

**Comment by simison** [comment]
No prob. I believe this could now be closed?

**Comment by lirantal** [comment]
thanks @simison
