### ISSUE TITLE
how to run code coverage for this project

### ISSUE THREAD

**Issue by abhijt-zanak** [meanjs/mean#739]
I have mentioned 'coverage' in karma.conf.js , however after running the grunt test , after opening the index.html under coverage folder , it shows nothing ,

**Comment by codydaig** [comment]
@abhijt-zanak Currently we don't support test coverage, however, it is in the works, and there's a pull request that get's it prepped for the coverage that's coming soon.

**Comment by lirantal** [comment]
indeed, I'll push that soon enough, it's already working for the client side here, just need to tied things up, stay tuned!

**Comment by abhijt-zanak** [comment]
thanks for the info, I am looking forward.
@lirantal : as you mentioned it is working for client side, please let me know how to run for client side.

**Comment by lirantal** [comment]
Code coverage has been addressed as part of MEAN.JS in this PR: https://github.com/meanjs/mean/pull/811
