### ISSUE TITLE
Minor issue: ng-binding to article.content in user-list.client.view.html (0.4 branch)

### ISSUE THREAD

**Issue by vaucouleur** [meanjs/mean#741]
@rhutchison 

Ryan,

There is a ng-binding to article.content in user-list.client.view.html. Probably a leftover from a copy-and-paste. It's a minor issue, it might be too late to fix before the 0.4 release ?

https://github.com/meanjs/mean/blob/0.4.0/modules/users/client/views/admin/user-list.client.view.html#L15

Sebastien

**Comment by rhutchison** [comment]
Thank you @vaucouleur!

**Comment by codydaig** [comment]
@vaucouleur Good catch! Thanks for submitting a PR for that!

**Comment by lirantal** [comment]
@vaucouleur we wanted to move fast with the 0.4.0 release so we appreciate the PR!
Merged https://github.com/meanjs/mean/pull/744 which addresses this issue.
