### ISSUE TITLE
how to configure meanjs app for openshift deploy

### ISSUE THREAD

**Issue by iamnizzam** [meanjs/mean#749]

**Comment by lirantal** [comment]
Hi @iamnizzam 

There's this issue https://github.com/meanjs/mean/issues/477 which discusses Openshift integration.
I'm not sure what is the requirement for that, but if you come up with the way to do it you're welcome to submit some PRs to our documentation area and possibly a code PR if it requires something special so we can review.

**Comment by codydaig** [comment]
Can this issue be closed since it's currently up for discussion in #447?
@iamnizzam If you have specific questions or run into snags along the way, we'd be happy to help if you can provide us with more information! :-D

**Comment by lirantal** [comment]
yeah I guess so, let's take the discussion to #477 anyway.
