### ISSUE TITLE
Grunt issue

### ISSUE THREAD

**Issue by ilanbiala** [meanjs/mean#761]
Grunt's --force option seems to make a lot of our builds that shouldn't pass pass. For example, this build https://travis-ci.org/meanjs/mean/jobs/74211973 should have failed since 1 test failed, but --force made it continue. Is there a reason we are using --force @lirantal @rhutchison? Have either of you noticed this issue in any of your builds?

**Comment by lirantal** [comment]
@ilanbiala glad you're back :)
I'm submitting a PR for that

**Comment by ilanbiala** [comment]
@lirantal only for a little bit while I'm on vacation so the notifications don't pile up. I ran into it while I'm looking into adding Coveralls to visualize our coverage. @lirantal on that note, did you have coverage set up and did you already start looking into setting up a service such as Coveralls or Codecov?

**Comment by lirantal** [comment]
Yes I already have a pending PR for the coverage, which I was working on for a while and I actually refactored the app.js / server.js especially to make that work :)

I didn't address the coveralls though and some other items so if you want I can submit my PR and you can add your coveralls and other changes to it.

**Comment by ilanbiala** [comment]
@lirantal yeah if you submit your PR, I'll work on adding Coveralls to it, which I started doing in #760 just to make it available to anyone who may have had something.

**Comment by lirantal** [comment]
Cool.

with regards to the job you were referring to (https://travis-ci.org/meanjs/mean/jobs/74211973) and about grunt error handling - so in that case jshint doesn't fail (although if it does it doesn't fail grunt at all), and I do see an error there too which doesn't fail the grunt either.

My PR is a change to grunt's 'force' option to default it to false so it fails on any other task that fails, this way we can be sure that we are catching any kind of issue, whether these are tests, or jshint conventions. Is that what you were referring to?

**Comment by ilanbiala** [comment]
Yes.

**Comment by codydaig** [comment]
@lirantal Fixed in #762?

**Comment by lirantal** [comment]
Yes, thanks @codydaig
