### ISSUE TITLE
User Model tests

### ISSUE THREAD

**Issue by rmlopes** [meanjs/mean#770]
Hi,

I am trying out the 0.4.0 branch. The user model unit test for the email is failing (should not be able to save different user with the same email address).

**Comment by lirantal** [comment]
I noticed issues with that too, actually the test for that specific is a false positive, I've got a PR to send later this evening.

In the meanwhile, can you show me the output of the errors you got?

**Comment by rmlopes** [comment]
Running "server" task

MEAN.JS - Test Environment
Environment:                    test
Port:                           3001
Database:                               mongodb://localhost/mean-test

Running "mochaTest:src" (mochaTest) task


  Article Model Unit Tests:
    Method Save
      √ should be able to save without problems
      √ should be able to show an error when try to save without title

  Article CRUD tests
    √ should be able to save an article if logged in (127ms)
    √ should not be able to save an article if not logged in
    √ should not be able to save an article if no title is provided (55ms)
    √ should be able to update an article if signed in (81ms)
    √ should be able to get a list of articles if not signed in
    √ should be able to get a single article if not signed in
    √ should return proper error for single article with an invalid Id, if not s
igned in
    √ should return proper error for single article which doesnt exist, if not s
igned in
    √ should be able to delete an article if signed in (70ms)
    √ should not be able to delete an article if not signed in

  User Model Unit Tests:
    Method Save
      √ should begin with no users
      √ should be able to save without problems (43ms)
      √ should fail to save an existing user again (45ms)
      √ should be able to show an error when try to save without first name
      √ should confirm that saving user model doesnt change the password
      √ should be able to save 2 different users (51ms)
      1) should not be able to save different user with the same email address

  User CRUD tests
    √ should not be able to retrieve a list of users if not admin (57ms)
    √ should be able to retrieve a list of users if admin (59ms)


  20 passing (3s)
  1 failing

  1) User Model Unit Tests: Method Save should not be able to save different user with the same email address:
     Error: timeout of 2000ms exceeded at null.<anonymous> (C:\Users\rmlopes\meanprojects\meancegi\node_modules\mocha\lib\runnable.js:139:19)
      at Timer.listOnTimeout (timers.js:119:15)


The remaining PhantomJS tests are all marked with SUCCESS

**Comment by lirantal** [comment]
@rmlopes is this the latest version of master branch? can you pull please?

**Comment by rmlopes** [comment]
I just pulled the master in OS X and all the tests pass.

**Comment by lirantal** [comment]
Great, thanks.

**Comment by codydaig** [comment]
@rmlopes Was your issue resolved? If so, can this issue be closed?

**Comment by rmlopes** [comment]
All the user model  tests on the master are passing both in Windows and OS X.

**Comment by lirantal** [comment]
Great, thanks @codydaig  and @rmlopes
