### ISSUE TITLE
Integrate MEAN.JS with RequireJS?

### ISSUE THREAD

**Issue by kitz17** [meanjs/mean#775]
While using third-party libraries, I need to arrange the order of JS files in config file's `assets.lib.js[]` manually.

For example, I am using jQuery and some jQuery plugins, such as jQuery.linkify.js, I must put jQuery before all jQuery plugins' JS files and double check the order to make sure the dependencies are ready. Not only because of jQuery plugins, I am also using many angular modules that may not just only depend on angular.

Are there any workarounds that help me to handle the libraries' dependencies issue? So that I don't have to worry about the order of JS files in the config file.

**Comment by codydaig** [comment]
@kitz17 From my understanding of Javascript in the browser, you have to define the order that JS files are loaded in. I think even if you use RequireJS, you still have load items in the right order.

**Comment by kitz17** [comment]
Yea, it is actually the way I am doing now, there is a right order in my config file's  `assets.lib.js[]`.

But it would be a great idea if I could just specify (or register) the dependencies for each JS libraries without specific order, after all the needed JS libraries are defined, then the application would load the JS files in correct order for me, depends on their dependencies.

Something like:
````
require({
    'angular': {
      'src': 'angular/lib/angular'
    },
    'angular-jwplayer': {
      'src': 'angular-jwplayer/lib/angular-jwplayer',
      'dependencies': ['angular', 'jwplayer']
    },
    'jwplayer': {
      'src' : 'jwplayer-mirror/lib/jwplayer'
    }
});
```
(I am not sure the correct syntax of RequireJS, it is just the concept by the way)

**Comment by codydaig** [comment]
@kitz17 That's unfamiliar territory too me. One solution I found is (https://oclazyload.readme.io/). Hope that helps, that's all I got. Hopefully someone else here, who experienced this before has a solution for you!

**Comment by trainerbill** [comment]
@kitz17 Start a fork/branch and try out requireJS.  If you get it working with MEAN and its a better alternative submit a PR and we will discuss it!

**Comment by ilanbiala** [comment]
@kitz17 RequireJS is just another abstraction (and also complication) when developing. Before even making a PR, please justify why it would be better than simply keeping the order like we do now.

**Comment by codydaig** [comment]
@kitz17 Im going to close this issue for now. Feel free to reopen if you want to discuss why this should be added to the project. Thanks!
