### ISSUE TITLE
Possible initialization issue - model isn't being loaded in time for application

### ISSUE THREAD

**Issue by h3xc0ntr0l** [meanjs/mean#782]
So, I [posted] in the google groups an issue I was having extending Articles. I discovered that one of my errors was not *really* an error as much as JSHint just using 'Comment' as a reserved word. So, I added the lines 

    /* jshint:ignore start */
    var Comment = mongoose.model('Comment');
    /* jshint:ignore end */

and hacked together a way to get my code to keep running even though JSHint wanted to throw errors at every mention I make of `Comment` elsewhere in my code. However, I still get the error 

`MissingSchemaError: Schema hasn't been registered for model "comments".`

when I try to populate the 'comments' field of my Articles model. 

I am having trouble believing that this is an error with anything on your guys' side, as in with the initialization and whatnot, but I *can not* find my bug in my code. Besides this being a bug in my code, I can only guess that if it IS caused by resources not being loaded on time, then the bug would probably lie somewhere in the configuration. I'm currently porting a project from Rails to a MEAN stack and chose MeanJS to be my base, so I'm very very against hacking together a solution on my end when there is possibly a bug in the code somewhere. Any help is greatly appreciated

[posted]:https://groups.google.com/forum/#!topic/meanjs/E72kgtxyox8

**Comment by codydaig** [comment]
@h3xc0ntr0l Can you post the code where you define the Comment Schema?

**Comment by codydaig** [comment]
@h3xc0ntr0l I'm closing this issue. however, feel free to reopen if it's still an issue.
