### ISSUE TITLE
Shoud .jshintrc use space-2 to keep consistency?

### ISSUE THREAD

**Issue by QiyuLi** [meanjs/mean#783]
In the
https://github.com/meanjs/mean/blob/master/.jshintrc#L33
it use 4 space as ident.

However, in the
https://github.com/meanjs/mean/blob/master/.editorconfig#L18
it use 2 space as ident.

Is there any conflicts between these?

**Comment by codydaig** [comment]
@QiyuLi #766 address this and actually removes it from the jshint file. Nice catch though!

**Comment by QiyuLi** [comment]
Oh, didn't check that. Thanks!

**Comment by codydaig** [comment]
@QiyuLi Np. Thanks for pointing that out!
