### ISSUE TITLE
"Grunt build" command not build as expected

### ISSUE THREAD

**Issue by aralroca** [meanjs/mean#784]
I executed `grunt build` and created `dist` directory with: ***application.js*, *application.min.css* and application.min.js**

The **NODE_ENV** varibale is `development`.

I repeat now the process, and the new  `grunt build` that I did don't generate the files `.js`with the new code that I programmed. Again generates the old code before the new modifications... 

*Why?*

*How can I solve this problem?*

**gruntfile.js**
    
    'use strict';

    module.exports = function(grunt) {
	// Unified Watch Object
	var watchFiles = {
		serverViews: ['app/views/**/*.*'],
		serverJS: ['gruntfile.js', 'server.js', 'config/**/*.js', 'app/**/*.js'],
		clientViews: ['public/modules/**/views/**/*.html'],
		clientJS: ['public/js/*.js', 'public/modules/**/*.js'],
		clientCSS: ['public/modules/**/*.css'],
		mochaTests: ['app/tests/**/*.js']
	};

	// Project Configuration
	grunt.initConfig({
		pkg: grunt.file.readJSON('package.json'),
		watch: {
			serverViews: {
				files: watchFiles.serverViews,
				options: {
					livereload: true
				}
			},
			serverJS: {
				files: watchFiles.serverJS,
				tasks: ['jshint'],
				options: {
					livereload: true
				}
			},
			clientViews: {
				files: watchFiles.clientViews,
				options: {
					livereload: true,
				}
			},
			clientJS: {
				files: watchFiles.clientJS,
				tasks: ['jshint'],
				options: {
					livereload: true
				}
			},
			clientCSS: {
				files: watchFiles.clientCSS,
				tasks: ['csslint'],
				options: {
					livereload: true
				}
			}
		},
		jshint: {
			all: {
				src: watchFiles.clientJS.concat(watchFiles.serverJS),
				options: {
					jshintrc: true
				}
			}
		},
		csslint: {
			options: {
				csslintrc: '.csslintrc',
			},
			all: {
				src: watchFiles.clientCSS
			}
		},
		uglify: {
			production: {
				options: {
					mangle: false
				},
				files: {
					'public/dist/application.min.js': 'public/dist/application.js'
				}
			}
		},
		cssmin: {
			combine: {
				files: {
					'public/dist/application.min.css': '<%= applicationCSSFiles %>'
				}
			}
		},
		nodemon: {
			dev: {
				script: 'server.js',
				options: {
					nodeArgs: ['--debug'],
					ext: 'js,html',
					watch: watchFiles.serverViews.concat(watchFiles.serverJS)
				}
			}
		},
		'node-inspector': {
			custom: {
				options: {
					'web-port': 1337,
					'web-host': 'localhost',
					'debug-port': 5858,
					'save-live-edit': true,
					'no-preload': true,
					'stack-trace-limit': 50,
					'hidden': []
				}
			}
		},
		ngAnnotate: {
			production: {
				files: {
					'public/dist/application.js': '<%= applicationJavaScriptFiles %>'
				}
			}
		},
		concurrent: {
			default: ['nodemon', 'watch'],
			debug: ['nodemon', 'watch', 'node-inspector'],
			options: {
				logConcurrentOutput: true,
				limit: 10
			}
		},
		env: {
			test: {
				NODE_ENV: 'test'
			},
			secure: {
				NODE_ENV: 'secure'
			}
		},
		mochaTest: {
			src: watchFiles.mochaTests,
			options: {
				reporter: 'spec',
				require: 'server.js'
			}
		},
		karma: {
			unit: {
				configFile: 'karma.conf.js'
			}
		}
	});

	// Load NPM tasks
	require('load-grunt-tasks')(grunt);

	// Making grunt default to force in order not to break the project.
	grunt.option('force', true);

	// A Task for loading the configuration object
	grunt.task.registerTask('loadConfig', 'Task that loads the config into a grunt option.', function() {
		var init = require('./config/init')();
		var config = require('./config/config');

		grunt.config.set('applicationJavaScriptFiles', config.assets.js);
		grunt.config.set('applicationCSSFiles', config.assets.css);
	});

	// Default task(s).
	grunt.registerTask('default', ['lint', 'concurrent:default']);

	// Debug task.
	grunt.registerTask('debug', ['lint', 'concurrent:debug']);

	// Secure task(s).
	grunt.registerTask('secure', ['env:secure', 'lint', 'concurrent:default']);

	// Lint task(s).
	grunt.registerTask('lint', ['jshint', 'csslint']);

	// Build task(s).
	grunt.registerTask('build', ['lint', 'loadConfig', 'ngAnnotate', 'uglify', 'cssmin']);

	// Test task.
	grunt.registerTask('test', ['env:test', 'mochaTest', 'karma:unit']);
    };

*Thanks!*

**Comment by lirantal** [comment]
when did you last update your 'master' repository? it looks like the previous version of mean.js
can you check by cloning mean.js's master branch?

**Comment by aralroca** [comment]
Yes, it's old version of mean.js sorry. I started the university project in december and I didn't updated yet... my fault...  Is an issue from old version? is it solved?  Thanks. I want to start to update my project but I can't do a "git pull" because I have a lot of new code and the new version of mean have a lot of changes and I don't know how... If I did a clone of master and execute `grunt build`of new version works well :+1:  But I need to solve this issue in my project, do you know what is happen? Thank you again!

**Comment by lirantal** [comment]
do you remember if you cloned back then the 0.4.0 branch or the master branch of mean.js?
maybe you can easily check by peaking in your package.json?

**Comment by aralroca** [comment]
I cloned the day 2014-12-09, the version is 0.3.3, just this: https://github.com/meanjs/mean/tree/daa124a4f3b9ca5e8aaeef3f5a9457298c160ae5

**Comment by lirantal** [comment]
Sorry but there's not much I can help out here.
With that said, I remember there was an issue opened in the past about the problem that the grunt jobs don't always use css/js files from other (possibly custom/new) locations. So I highly recommend you to vigorously search for that in the issues in hope that you can find the fix there.

**Comment by aralroca** [comment]
Ok! Thanks for answer it :+1:
