### ISSUE TITLE
Best practice to communicate REST API with SocketIO?

### ISSUE THREAD

**Issue by aralroca** [meanjs/mean#792]
I have a question...

I want to call the methods "*leave*" and "*join*" in **socketIO** from  **REST API**  methods (server controllers) .

* What is the best practice to do that? 
* How can I get the current socket in the REST API?

*Thank you a lot!*

**Comment by mleanos** [comment]
@aralroca Can you give any more info on what your requirements are?

Is there a need to access these REST API methods externally, from your application? If so, how are you handling User authentication? 

If this will be used solely from your application, I would recommend using the Socket service to emit an event to a *core* socket config listener on the server. Similar to the Chat listeners in `chat.server.socket.config`. From there you can `require` your server controller. It's not going through the API, but if this will serve your needs, then it seems like the cleanest.

If you *MUST* access the Socket.IO server from the API methods, then you would need to expose it to your server controllers via a `require('./config/socket.io')`. I'm not sure how you would *obtain* the requesting user's Socket. I haven't really looked at that. It could be that you need to extract the socket that is associated with the user's Session..?

If you come up with a solution, please do share. I'm interested in this type of implementation.

**Comment by aralroca** [comment]
Sorry, finally I used `emit` in client to call the server, just that you recommend it :+1:

**Comment by codydaig** [comment]
@aralroca Sounds like this issue has been resolved. I'm closing this issue, but feel free to reopen if it hasn't been resolved.
