### ISSUE TITLE
How to do that session expiring automatically?

### ISSUE THREAD

**Issue by aralroca** [meanjs/mean#802]
I want that the session expires after 72 hours. What part of the MEAN.JS code I need to modify to do that? I'm not very familiar with ExpressJS. Thank you so much!

**Comment by pgrodrigues** [comment]
I believe you are looking to set a maxAge for session cookie, something like this: http://stackoverflow.com/questions/10429557/whats-the-correct-way-to-use-maxage-with-express-js.

In MEAN.JS you just have to add `cookie: {maxAge: 259200}` to the "Configure Express session" block in `config/lib/express.js`.

**Comment by aralroca** [comment]
Thank you a lot!

**Comment by lirantal** [comment]
Hi @aralroca,
I created a PR to address this problem: https://github.com/meanjs/mean/pull/803

**Comment by lirantal** [comment]
Updated PR https://github.com/meanjs/mean/pull/804 has been merged so this is already available to you in `master` branch @aralroca 
Thanks for letting us know!
