### ISSUE TITLE
Modules organization

### ISSUE THREAD

**Issue by bojanbass** [meanjs/mean#818]
Hi guys!

First of all I have to say you are writing awesome stuff!! 

I have a small question regarding code organization when using new vertical modules structure in 0.4 version. There's already a User module defined in meanjs which handles user profile, login and other stuff on client and server side. Let's say I have another module inside my application called Configuration, which allows some website admin to add new users, edit roles and make some other system settings. From the client side perspective, all logic and views belong to Configuration module, but there's a catch on server side, because APIs for User model already exists in Users module, and beside that I also reuse some of the existing APIs from Users module. 

So, is it better to have all the logic that I need on the client side also written in the same module on server side (in my case Configuration module), even if some code is duplicated from Users module? In this case there's also a problem on client side, because Users angular $resource service already exists and I can't just add a new one with the same name. Or is it better to include all client side logic that handles user management to Users module? But in this case I still need to specify routes in Configuration section. It sounds like in each case there's a mess in the code, maybe there is a better solution to solve this one?

Thank you in advance!

**Comment by lirantal** [comment]
Hi @bojanbass,

MEAN.JS is somewhere between a boilerplate and a framework, but it's definitely not a fully fledged platform so this means that there is a method you need to adopt for working on top of it once you choose it.

One suggestion is to keep the core users/ directories as they are and maybe treat them carefully with security concerns such as remove some routes if you deem them as something you wouldn't want to expose. Then, you can have your own users's module implementation in your Configurations module and just copy whatever is added on the users module from the framework to your own. Worst case you'll have duplication in that area. We're not going to add 10 more modules for the fun of it, so I don't expect new modules rising up anytime soon.

**Comment by bojanbass** [comment]
Ok, I will try to implement it like you said. Tnx.
