### ISSUE TITLE
CSRF protection middleware for the app?

### ISSUE THREAD

**Issue by sparshy** [meanjs/mean#828]
are there any plans to implement CSRF protection as the app uses cookie based authentication?

**Comment by pgrodrigues** [comment]
This should indeed be addressed. You can follow the guidelines [here](http://charandeepmatta.com/2014/06/04/csrfxsrf-protection-express-angular/), which suggests to use csurf express middleware.

You dont need to do anything in the frontend as long as you keep things within the Angular way, because Angular will deal with it by itself, as meantioned in the docs:

> Angular provides a mechanism to counter XSRF. When performing XHR requests, the $http service reads a token from a cookie (by default, XSRF-TOKEN) and sets it as an HTTP header (X-XSRF-TOKEN). Since only JavaScript that runs on your domain could read the cookie, your server can be assured that the XHR came from JavaScript running on your domain. The header will not be set for cross-domain requests.

**Comment by codydaig** [comment]
@sparshy https://github.com/expressjs/csurf would be my recommendation to start. :-D Happy Hacking!

**Comment by lirantal** [comment]
I would also look into PayPal's Lusca project which as a candidate

**Comment by pgrodrigues** [comment]
Didn't know lusca, it seems like a mix between csurf and helmet.

**Comment by codydaig** [comment]
@sparshy Did that answer your question?

**Comment by sparshy** [comment]
Yes @codydaig, thanks I will try to implement CSRF tokens on my branch as soon as I get time. Yo guys do have a future plan to implement it in the main branch?

**Comment by lirantal** [comment]
@sparshy indeed, security is also something we're investing efforts in (specifically I've been working on this front as well with my previous PRs about session security/cookies, etc).

Would be great to see a PR for that whenever you have time to work on it

**Comment by trainerbill** [comment]
If we go with Lusca, I will volunteer to do it.  I am biased here :)

**Comment by lirantal** [comment]
@sparshy I assume no update on this topic?
@trainerbill be my guest - can you quickly research lusca vs csurf / helmet? and let's start working on this PR

**Comment by codydaig** [comment]
https://www.npmjs.com/package/lusca

**Comment by codydaig** [comment]
A PR has been submitted #995
