### ISSUE TITLE
Password is being stored in clear text if length is 6

### ISSUE THREAD

**Issue by sparshy** [meanjs/mean#829]
Password is being stored in clear text if length is 6, just an equal sign is required here, or make sure min length for password is 7

    /**
     * Hook a pre save method to hash the password
     */
    UserSchema.pre('save', function (next) {
      if (this.password && this.isModified('password') && this.password.length >6) {
        this.salt = crypto.randomBytes(16).toString('base64');
        this.password = this.hashPassword(this.password);
      }
    
      next();
    });

**Comment by codydaig** [comment]
@sparshy I will look into this and verify on my end.
