### ISSUE TITLE
Article Refactoring

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#831]
This issue is too coordinate the outstanding PR related to the refactoring of the Articles and get them merged in.

My current proposal for the order of priority of the PRs:
#807 - Articles Admin Feature by @mleanos 
#800 - Articles refactor by @trainerbill 
#823 - Renaming of Files by @vaucouleur 

My reasoning:
#800 should wait until after #807 since #800 is changing portions of files that will no longer exist after #807 is merged. Also, #807 introduces additional areas to be refactored to match the desired format. #823 should either be taken care of in the first two, or afterwards to make merging easier for all contributors. 

I would love to see these get merged in within the next week! :-D
Let's get hacking! 

@lirantal @trainerbill @ilanbiala @rhutchison @mleanos @vaucouleur

**Comment by mleanos** [comment]
@codydaig I agree with your assessment. 

I think #823 should be it's own PR @vaucouleur can rebase & modify once the other two are merged. Seems like the path of least resistance, IMO.

**Comment by mleanos** [comment]
@codydaig @rhutchison I relinquish my stance on the order of #800 & #807. I'm fine with #800 going in first. We need to discuss #807 more anyways.

**Comment by vaucouleur** [comment]
@mleanos @codydaig  :+1:
