### ISSUE TITLE
能不能不使用grunt做工程自动化，使用gulp呢？

### ISSUE THREAD

**Issue by xiaoyang2022** [meanjs/mean#834]
能不能不使用grunt做工程自动化，使用gulp呢？

**Comment by codydaig** [comment]
Translation: Can you use gulp instead of grunt for automation?

**Comment by codydaig** [comment]
@xiaoyang2022 Yes! 对

**Comment by xiaoyang2022** [comment]
yes,i like gulp,grunt not easy!

**Comment by xiaoyang2022** [comment]
gulp is better than grunt to use,yours mean-stack will be use it?

**Comment by codydaig** [comment]
@xiaoyang2022 Currently the project uses both! We have plans to switch over to gulp, but for now, both work.

**Comment by xiaoyang2022** [comment]
very good! gulp is very good,grunt don't to use that is more works for develper and it more profile.thanks

**Comment by codydaig** [comment]
@xiaoyang2022 If you have any more questions, feel free to ask, otherwise go ahead and close the issue and Happy Hacking!
