### ISSUE TITLE
maybe to use "express-restify-mongoose" in project?

### ISSUE THREAD

**Issue by xiaoyang2022** [meanjs/mean#838]
https://github.com/florianholzapfel/express-restify-mongoose

maybe to use "express-restify-mongoose" in project? it will be easy to modules of angular,i hear your suggests to me!

**Comment by xiaoyang2022** [comment]
i see your's works! thanks! if you drop the grunt and it's plugins that will be better! i hope!

**Comment by lirantal** [comment]
Hi @xiaoyang2022,

Unfortunately I don't really follow up on what you're trying to say.
As for express-restify-mongoose it isn't on our agenda.
