### ISSUE TITLE
Option to require stronger passwords

### ISSUE THREAD

**Issue by jloveland** [meanjs/mean#848]
We should considering adding an option to allow developers to set the password strength and have the client and server test for this. A good option would be to follow OWASP password length & complexity. This could leverage libs such as:
https://www.npmjs.com/package/owasp-password-strength-test

**Comment by lirantal** [comment]
I vote for not making this an option but rather part of the framework.
I like it that we're making sure the framework is following secure guidelines and so we should adopt it.

@jloveland care to PR it?

**Comment by jloveland** [comment]
sure, I will work it this week.

**Comment by pgrodrigues** [comment]
:+1:

**Comment by codydaig** [comment]
:+1:

**Comment by 0xNacho** [comment]
:+1:

**Comment by jloveland** [comment]
Just and update on this: I got the server side working and accompanying unit tests this weekend. I am now working in the client side.

**Comment by lirantal** [comment]
Nice!

**Comment by jloveland** [comment]
@lirantal assuming you can close this issue.

**Comment by lirantal** [comment]
Great, thanks, I updated the milestone too.

**Comment by codydaig** [comment]
@lirantal Any reason in particular we're keeping this open?

**Comment by jloveland** [comment]
you can close this issue..resolved in #878
