### ISSUE TITLE
User Password is stored in clear text on 0.4.0

### ISSUE THREAD

**Issue by daskreativ** [meanjs/mean#849]
The username on my installation is stored in the mongodb as clear text under password.
Should that not be hashed out of the box?
I tested with dev and with prod config.

**Comment by codydaig** [comment]
@daskreativ Are you using the latest master version? We came across this bug recently but it's been fixed.

https://github.com/meanjs/mean/pull/830

**Comment by daskreativ** [comment]
i use the Branch 0.4.0
i think the latest master is still on 0.3.3 and there it works as far as i know (did not try now but a while ago). 
But not in the Branch

**Comment by pgrodrigues** [comment]
Branch 0.4.0 was merged into master a few weeks ago and the fix was only applied to master.

**Comment by lirantal** [comment]
@daskreativ check again with the master branch and let us know, this issue should be fixed.

**Comment by daskreativ** [comment]
Works on Master, missed the merge of 0.4.0 to master.
Sorry and thanks
