### ISSUE TITLE
Sign in page header (minor issue)

### ISSUE THREAD

**Issue by vaucouleur** [meanjs/mean#855]
The sign in page shows "Or with your account".  "Or" seems to be a typo. 

The whole title could simply be "Sign in" or anything similar.

https://github.com/meanjs/mean/blob/3bf07fe4ec54f640e07ad9b656a267e0dc4ef3e8/modules/users/client/views/authentication/signin.client.view.html#L2

**Comment by codydaig** [comment]
@vaucouluer why does "Or" seem like a typo? 
![capture](https://cloud.githubusercontent.com/assets/2314748/9523579/ee85203c-4c97-11e5-9d7c-b4e04567c612.PNG)

**Comment by vaucouleur** [comment]
@codydaig  My apologies, the social accounts integration was removed a long time ago from working directory, and I simply forgot about this. Using the default view the header makes sense, naturally.

**Comment by lirantal** [comment]
Thanks
