### ISSUE TITLE
grunt wont let running

### ISSUE THREAD

**Issue by ironheartbj18** [meanjs/mean#856]
I followed the instruction the steps 
unfortunately, it wont let running on localhost:3000

it said
$ grunt --force
>> Local Npm module "grunt-contrib-less" not found. Is it installed?
>> Local Npm module "grunt-node-inspector" not found. Is it installed?

why? What did I missing?

**Comment by codydaig** [comment]
@ironheartbj18 Sounds like you need to run `npm install`

**Comment by francisdaigle** [comment]
I am also experiencing this very problem when executing ```npm install``` (build error with "grunt-node-inspector"). A problem compiling one of it's dependencies perhaps?

```
npm ERR! v8-debug@0.4.6 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
```

Using:

```
{ http_parser: '1.0',
  node: '0.10.28',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.27',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1g',
  npm: '1.4.28',
  meanjs: '0.4.0' }
```

**Comment by francisdaigle** [comment]
Argh. 

"grunt-node-inspector" lacks a pre-built binary for OS X so it has to compile one. 

Problem was in the copying of the files – "copy" was choking on spaces in the directory names.

**Comment by codydaig** [comment]
@francisdaigle To clarify, did you resolve your issue?

@ironheartbj18 Does that help answer your question?

**Comment by ironheartbj18** [comment]
Yes I got it work finally , because I did not install "npm install -g yo"  and "npm install -g generator-meanjs", "yo meanjs" and "grunt" from http://meanjs.org/generator.html. obviously... 
wondering keeping it said  
```
>> Local Npm module "grunt-node-inspector" not found. Is it installed?

```
I went to https://www.npmjs.com/package/grunt-node-inspector
trying 
```
npm install grunt-node-inspector --save-dev
```

the version currently is  "version": "0.2.0",

it seems not working.

**Comment by ironheartbj18** [comment]
Uncaught ReferenceError: angular is not defined
When I run everything with grunt it seems that the server is running, but angular is not connecting. I cannot figure out what is going on. When I go to the locahost:3000 page the page is blank and the console reads: Uncaught ReferenceError: angular is not defined

I have tried doing a bower install and npm install bower several times, but nothing is working. Can someone help me out? What am I missing?

my github is https://github.com/ironheartbj18/jobfinder.

**Comment by codydaig** [comment]
@ironheartbj18 I just cloned your repo, ran `npm install` then `grunt` and the page loaded just fine with no errors.

**Comment by ironheartbj18** [comment]
@codydaig your different than mine hmm? it just showing as blank page.  I dont know which one the file to be back as normal showed as http://meanjs.herokuapp.com/ since I am very new with mean stack to get started. 

its just showing like this... 
![ashampoo_snap_2015 08 30_00h33m59s_001_](https://cloud.githubusercontent.com/assets/4556609/9565851/01d6819e-4eaf-11e5-8d3d-a2fb211f2c3b.png)

**Comment by codydaig** [comment]
What node and npm version are you running?

**Comment by codydaig** [comment]
@ironheartbj18 Also, did you use the generator or clone the master branch from the project?

**Comment by ironheartbj18** [comment]
@codydaig  I checked node -v its a 0.12.3 the currently is Current Version: v0.12.7. I m going to fork or clone the master branch from them.

**Comment by ironheartbj18** [comment]
I did not clone the master branch from the project. I solved it. When I looked at the '.bowerrc' 
```
{
	"directory": "public/lib"
}
```
so I created a new folder and type $bower install and $npm install -g bower (upgrade to : "1.5.2") it seem working now. just strange... maybe I did not create the folder as for lib. it was not existed.
