### ISSUE TITLE
how to use the consolidate package?

### ISSUE THREAD

**Issue by xiaoyang2022** [meanjs/mean#857]
the consolidate package is used to that server and client for swig? or no matter?

**Comment by codydaig** [comment]
The [colsolidate.js package](https://github.com/tj/consolidate.js) is used to make it easy to select a template engine to use. By default it's using swig, but if you want another engine, you can swap it out in the config (just be sure to also npm install that template engine).

**Comment by xiaoyang2022** [comment]
i　see  ,thanks!
