### ISSUE TITLE
ngRoute separate install

### ISSUE THREAD

**Issue by bobbyziom** [meanjs/mean#859]
I've had issues with ngRoute when running in production mode.

In angular documentation it says:

"In AngularJS 1.2.0 and later, ngRoute has been moved to its own module. If you are getting this error after upgrading to 1.2.x or later, be sure that you've installed ngRoute."

Installing ngRoute separately using bower fixed it. Thus it might be a good idea to update bower.json and default grunt build config to include loading ngRoute as a standard?

**Comment by ilanbiala** [comment]
We aren't using ngRoute, we are using ui-router. https://github.com/meanjs/mean/blob/master/bower.json#L13
