### ISSUE TITLE
Cloud Foundry deployment artifacts not part of 0.4.0 tag

### ISSUE THREAD

**Issue by jd-carroll** [meanjs/mean#862]
The necessary deployment artifacts are not part of the 0.4.0 tag.

It is missing files such as:
- .cfignore
- manifest.yml

**Comment by codydaig** [comment]
@jd-carroll Cloud Foundry was introduced right after 0.4. It's in the master branch right now and we should be releasing 0.4.1 in the near future.

**Comment by jd-carroll** [comment]
Cool thanks!
