### ISSUE TITLE
Optional persistent login

### ISSUE THREAD

**Issue by aralroca** [meanjs/mean#867]
Perhaps the optional persistent login is an interesting thing to implement in signIn, this is the typical checkbox **"Remember me"** in sign in view.

**Comment by lirantal** [comment]
@aralroca PR please?

**Comment by ilanbiala** [comment]
@lirantal don't we already have sessions that kind of take care of this?

**Comment by lirantal** [comment]
So actually the "Remember me" functionality is simply about the session expiration time.
We can decide that a login without the Remember me checkbox yields a session for only until the browser/tab closes, and then it dies. And when Remember me is toggled on then we can create a session with a longer time, say 24 hours.

**Comment by aralroca** [comment]
By default in the last version of MEAN.JS when I close the browser (Chrome or Safari) and open it again, the session is not persistent and I need to sign in again. If I open new browser tabs, is not necessary to sign in again... This is the normal flow? Or maybe is an issue?

**Comment by mleanos** [comment]
@aralroca I don't experience this behavior with Chrome or Firefox. I'm automatically logged in when I open the app in either browser, after previously closing it.

Are you up to date with the latest upstream?

**Comment by trainerbill** [comment]
Isn't this normally done with a browser cookie?  User object is typically encrypted into a browser cookine when remember me is checked and then decoded and server session initiated based off the cookie?

**Comment by ilanbiala** [comment]
Is this still an issue, or is @mleanos correct and remember me works?

**Comment by lirantal** [comment]
remember me works because we have an expiration time on cookies.
I guess we can close this unless someone will re-open
