### ISSUE TITLE
How unstable is 0.4

### ISSUE THREAD

**Issue by mikepc** [meanjs/mean#870]
I am starting a new project this week and I want to use meanjs, but I would like to use the new features only in 0.4, is 0.4 stable enough to start a new project with or is it really a trainwreck like the title says? 

The main reason I am questioning it is everywhere I look on the net folks are talking about 0.4 and even the video gives a tutorial using 0.4.

So is it stupid to use 0.4 or should I just stay with 0.3 now?

**Comment by codydaig** [comment]
@mikepc What title gives you the impression that it is a trainwreck?

**Comment by mikepc** [comment]
when I switch to the 0.4 branch it says "this branch is broken and highly unstable" on top of the readme in a desktop browser

**Comment by codydaig** [comment]
@mikepc Are you referring to the generator? If so, the generator is currently broken. I am in the process of making a working generator for it. 

If you want to use 0.4, clone the master branch of this repo to get started.

**Comment by mikepc** [comment]
ah yes right on! Cool man!

**Comment by codydaig** [comment]
@mikepc Let us know if you have any other questions!

If this answers your question, would you mind closing the issue? :-D

**Comment by mikepc** [comment]
Yepper! Installing the packages now, thank you very very much <3
