### ISSUE TITLE
jshint is failing 

### ISSUE THREAD

**Issue by suryasingh** [meanjs/mean#872]
hello,
 I run a grunt command and got the following response , although i'm able to run via ```grunt --force``` . Any clue why jshint is shouting for 'user' not defined.
 >> Running "jshint:all" (jshint) task
   modules/users/tests/server/user.server.model.tests.js
     89 |      var _user = new User(user);
                                    ^ 'user' is not defined.
    105 |      var _user = new User(user);
                                    ^ 'user' is not defined.
    121 |      var _user = new User(user);
                                    ^ 'user' is not defined.

>> 3 errors in 101 files

**Comment by codydaig** [comment]
@suryasingh Are you running the latest version from the master branch? I think this just got fixed in a recent PR.

**Comment by suryasingh** [comment]
@codydaig i pulled it 3 days back. Thanks , i'l pull the latest one.

**Comment by codydaig** [comment]
@suryasingh #863 Fixed it. You must have cloned right between the breaking commit and the fix.

**Comment by suryasingh** [comment]
@codydaig Awesome.. thanks.
