### ISSUE TITLE
gulp mocha/gulp karma hang on execution

### ISSUE THREAD

**Issue by mikepc** [meanjs/mean#873]
Clone the 0.4 branch,
cd into the directory
npm install
bower install
gulp test -> Mocha succeeds, karma hangs.

gulp mocha -> Hangs
  -- I was able to get gulp to exit by adding a done(err), to the mocha task to capture the error, which was a mongoose User model not being registered error.

gulp karma -> Hangs, don't know how to get around this one.

Switching back to grunt until we can get this figured out.

**Comment by mikepc** [comment]
I should add this is using test:server, test:client respectively.

**Comment by ilanbiala** [comment]
@mikepc Gulp support isn't finalized yet and Grunt should still be used. If you'd like, feel free to help us reach parity with Grunt so we can release Gulp support sooner.

**Comment by codydaig** [comment]
There is a known bug with gulp where it hangs for a bit after tests complete. I encountered this recently with another project. There's a hacky wordaround, but I don't really like it. It should stop hanging after a few seconds (<30), if it doesn't then there's something else funky with it.
