### ISSUE TITLE
How do i add Comments to an article Module?

### ISSUE THREAD

**Issue by vrohitk** [meanjs/mean#879]
i would like to add a commenting platform in the article module for a new app i am building. could someone suggest how i could proceed to do so.

**Comment by sparshy** [comment]
edit the article schema, to create a field comments[this should be array of objects]

Each object inside the array can be like
    {
        commentData:{
             type: String
         }
        user:{
            type : Schema.ObjectId,
            ref: 'User'
         }
    }

**Comment by vrohitk** [comment]
I want to create like an comments for a blog post, like an array by different users

**Comment by sparshy** [comment]
Yeah this should work, the array will be something like this
comments:[
{commentData:"abc", user:ObjectId(345),created:Date}.
{commentData:"cdf",user:ObjectId(129),created:Date}
]

**Comment by vrohitk** [comment]
after setting up on the back-end, how should the update on the angular side?

**Comment by sparshy** [comment]
the returned article object from the server will contain all the comments, you can simply use
//this should be inside ArticlesController
<div ng-repeat="comment in article.comments">
     <div>{{comment.commentData}} by {{comment.user.displayName}}</div>
</div>

remember to populate displayName on the server side before sending the response.

**Comment by ilanbiala** [comment]
Please move this to a separate forum such as StackOverflow or email correspondence unless there is a bug or request that requires the team's attention.
