### ISSUE TITLE
Warning - You need to have Ruby and Sass installed and in your PATH for this task to work.

### ISSUE THREAD

**Issue by italiancollectiveco** [meanjs/mean#880]
Hello guys just wanted to let you know that this warning comes up after cloning the repo, npm i, bower i and running grunt.

Has it not been added to the dependencies?

**Comment by ilanbiala** [comment]
@italiancollectiveco Grunt requires Sass to be installed. Try that and run Grunt again. Closing because that should be the solution, let me know if it doesn't work and we'll reopen.

**Comment by italiancollectiveco** [comment]
@ilanbiala :Thank you, could you or someone else update the installation requirements instructions?

**Comment by ilanbiala** [comment]
@italiancollectiveco feel free to submit a PR.

**Comment by italiancollectiveco** [comment]
@ilanbiala done.
