### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by ilanbiala** [meanjs/mean#881]
Let's get a CHANGELOG.md added for easy version comparison. Something along the lines of AngularJS's should be good.

**Comment by lirantal** [comment]
@ilanbiala I was thinking we can easily find some tool that will traverse the commit log and create a CHANGELOG out of it, no?

**Comment by ilanbiala** [comment]
@lirantal there is git-conventional-changelog, but I think it just is too explicit and we would need to tidy it up quite a bit or standardize our commit messages a lot. Even then, I think it would be too dense and wouldn't be much better than doing GitHub compare.

**Comment by lirantal** [comment]
@ilanbiala Ok then. What do you suggest? going manually through the commit log to dig up the data for CHANGELOG.MD?

**Comment by simison** [comment]
I recon it's fine to have this more fuzzy for the past and just keep it in order for the future.

Something along the lines: 
* pre 0.3; not so important as it's quite old
* 0.3—0.4; a log would be nice as there are probably quite some people with 0.3
* 0.4.x—future; detailed

**Comment by ilanbiala** [comment]
@simison I think we all agree on most of that, in fact I would say there's almost too much from 0.3 to 0.4 to actually include it, so I suggest we just start at 0.4. However, we're trying to figure out a way to create a concise changelog without much effort.

**Comment by simison** [comment]
IC, could changelog be updated with each PL? Mention it at CONTRIBUTE.md. Something like:

___Next up___
- People add a new line here each time they send a PL?

___v0.4.1___
- feature
- feature

thoughts?

**Comment by ilanbiala** [comment]
The sections is definitely part of the plan, but the continuous updating isn't my favorite strategy. Maybe we will have to standardize a commit message so we can use git-conventional-changelog and maybe a --skip-changelog or something will keep those out of the changelog?

**Comment by lirantal** [comment]
Guys, why not just use some tool like:
1. https://github.com/dylang/changelog
2. https://github.com/dylang/changelog

And manually generate/add to the CHANGELOG everytime we tag a new release?
I don't think we need to be very anal on the CHANGELOG. This is an open source project and anyone who wishes to find more about the history of the project can easily review the commits log, the issues queue, etc.
