### ISSUE TITLE
Socket io : extract the socket associated with user session

### ISSUE THREAD

**Issue by suryasingh** [meanjs/mean#889]
Hi ,
 I want to extract the socket associated with user session, i'm not getting a way to achieve that. As an example .. inside the create method i want to get an instance of socket associated with the current user session.
>>
exports.create = function (req, res) {
  var article = new Article(req.body);
  article.user = req.user;
  article.save(function (err) {
    if (err) {
      return res.status(400).send({
        message: errorHandler.getErrorMessage(err)
      });
    } else {
        ```get socket instance for this session , and send a message that article is created ```
      res.json(article);
    }
  });
};

**Comment by ilanbiala** [comment]
@suryasingh please use StackOverflow or another more appropriate forum for how-tos and other questions that don't involve bugs or features before coming here. If you still don't get an answer there, then feel free to come back with whatever progress you have made and we'll try to help.
