### ISSUE TITLE
livereload for sass files importing lib files not working

### ISSUE THREAD

**Issue by mmintel** [meanjs/mean#894]
hi there,

sass files that import a file from lib e.g. `@import 'angular-material/angular-material';` sort of disable livereload. if I remove that import and keep the other partial imports livereload works. This problem exists with grunt and gulp.
I also tried to add includePaths to grunt-sass settings but that doesn't change anything.

have any idea?

**Comment by ilanbiala** [comment]
@mmintel have you tried using it without a compass-dependent sass implementation, such as node-sass? I'm not sure if there will be a difference, but I know there are a few differences between the two implementations.

**Comment by mmintel** [comment]
@ilanbiala good idea! I only tested it with the default packages of meanjs 0.4.0.. so it's grunt-contrib-sass which is the ruby version. Which feels a bit strange to me. MEAN is the power of combining JS but then a ruby compiler is loaded instead of a javascript compiler.

I'll try to exchange these today evening if I find time and then i'll see if that works.

**Comment by mmintel** [comment]
its working with grunt-sass! But I cannot explain :D

**Comment by ilanbiala** [comment]
@mmintel then what was the problem?

**Comment by zeldar** [comment]
Try this:

In terminal, navigate to your project folder.
1. npm uninstall node-sass
2. npm uninstall gulp-sass
3. npm uninstall node-sass -g
4. npm uninstall gulp-sass -g
5. npm install node-sass -g
6. npm install node-sass --save-dev
7. npm install gulp-sass -g
8. npm install gulp-sass --save-dev

My node-sass and gulp-sass never seem to work without those steps. 

IF THAT FAILS, TRY THIS ALSO:

In gulpfile.js:

These requires should be in your module dependencies.
gulp = require('gulp'),
sass = require('gulp-sass'),

In gulp.task('watch'):
gulp.watch(defaultAssets.client.sass, ['sass', 'csslint']).on('change', plugins.livereload.changed);

// Sass task
gulp.task('sass', function () {
	return gulp.src(defaultAssets.client.sass)
		.pipe(plugins.sass())
		.pipe(plugins.rename(function (path) {
			path.dirname = path.dirname.replace('/scss','./css');
		}))
		.pipe(gulp.dest('./modules/'));
});

Make sure you have your SCSS folders properly set up in the task, as well as the default Assets folder, and in your modules. 

Let me know if any of this helps.

**Comment by codydaig** [comment]
@mmintel I'm going to close this issue. Feel free to reopen if this is still an issue. :-D
