### ISSUE TITLE
Restrict user role in ui-router

### ISSUE THREAD

**Issue by bobbyziom** [meanjs/mean#895]
Hello

Both in the express api and in the menu service it's possible to validate access via user roles. How can you allow/restrict access to certain pages using the ui-router? I imagine it to be much more convenient than using ng-hide in the view to validate whether a user have access or not?

**Comment by mleanos** [comment]
@bobbyziom If you look at this file, you can see the implementation of *restricting* certain roles to certain routes. If you notice the *view* & *list* routes don't have any restrictions.
https://github.com/meanjs/mean/blob/master/modules/articles/client/config/articles.client.routes.js#L21

Here is an example of restricting the route to only the *admin* role.
https://github.com/meanjs/mean/blob/master/modules/core/client/config/core-admin.client.routes.js#L11

And here you can see that the user must be *logged in* to access the Chat module.
https://github.com/meanjs/mean/blob/master/modules/chat/client/config/chat.client.routes.js#L11

You can play around with these route configurations, for the desired behavior. If you have any additional questions, I'd be more than happy to assist.

I'm a little unclear as to your concern over the Menu service. Can you clarify what you meant?

**Comment by bobbyziom** [comment]
@mleanos Thanks a lot for your answer! So if I understand correctly, I just have to put the data field in the state to limit access to certain roles? 

About the Menu service I saw that it was possible to show menu items according to user roles, so it wasn't really a question. But just hiding the menu, it was still accessible via URL - so I'll try the data field out :+1:

**Comment by mleanos** [comment]
@bobbyziom Yes. Just add something like the following to your module's route configurations..
```
data: {
  roles: ['user', 'admin', 'any-custom-user-role']
}
```

**Comment by bobbyziom** [comment]
@mleanos Thanks you very much! Easy and it works :)

**Comment by mleanos** [comment]
@bobbyziom Anytime. Glad it worked out.
