### ISSUE TITLE
UIRoute MenuService value syntax

### ISSUE THREAD

**Issue by bobbyziom** [meanjs/mean#900]
Hello

In the article example the menu will remain active if a user is creating an article. It uses
```
'/article(/create)?' 
```
as the argument for making the menu item active when both in /article and /article/create path.
I'm making a dashboard for different devices, and I want to have my menu item active for either of them. My path is /dash/:deviceId (deviceId is mongoDB reference id).

How can i make the menu item for every path with /dash, no matter what will come after? And could anyone give some common syntax guidelines for the UIRoute argument in MenuService - I can't find anything else than the article example which doesn't cover my current issue.

Thanks alot!

**Comment by ilanbiala** [comment]
@bobbyziom please use StackOverflow or another forum that is more appropriate for questions as GitHub is mainly for bug reports and feature requests.

**Comment by bobbyziom** [comment]
Could be an idea to enhance the documentation, but okay, I'll try. Thanks anyways.

**Comment by codydaig** [comment]
@bobbyziom Hit me up on Gitter! I wouldn't mind helping and figuring this out with ya.

**Comment by rhutchison** [comment]
@bobbyziom have you looked at ui-sref-active?
