### ISSUE TITLE
user profile picture render issue [bug]

### ISSUE THREAD

**Issue by rainings** [meanjs/mean#905]
![screenshot_1](https://cloud.githubusercontent.com/assets/7414544/9807324/224a9dd2-5884-11e5-9c3c-cd815c3d9934.png)
the user profile picture didn't show correctly. 

 on 78 in article.server.controller.js
remove 'displayName'
Article.find().sort('-created').populate('user', 'displayName').exec(function(err, articles)
Article.find().sort('-created').populate('user').exec(function(err, articles)

![screenshot_4](https://cloud.githubusercontent.com/assets/7414544/9807351/9884adda-5884-11e5-89de-ac22c2801c06.png)

special thanks to Geoff Oslund

**Comment by codydaig** [comment]
@rainings If you add `profileImageURL` to the list, does that also solve your issue instead of passing the entire user object?
`Article.find().sort('-created').populate('user', 'displayName', 'profileImageURL').exec(function(err, articles)`

**Comment by rainings** [comment]
@codydaig the app crashed after i added the 'profileImageURL'

**Comment by codydaig** [comment]
@rainings Sorry, slightly wrong syntax on my part:

`Article.find().sort('-created').populate('user', 'displayName profileImageURL').exec(function(err, articles)`

**Comment by rainings** [comment]
@codydaig it works as well by adding 'profileImageURL'

**Comment by codydaig** [comment]
@rainings So, by removing displayName and not passing in the second argument into populate, it's returning the entire user object with the article. By passing a second argument with a space separated list of fields only returns those fields from the user object.

**Comment by codydaig** [comment]
@rainings Let us know if you have any other questions or concerns, otherwise can this issue be closed?

**Comment by rainings** [comment]
@codydaig ya, the problem solved. i hope this issue can solve in the next version

**Comment by codydaig** [comment]
@rainings What problem is there to solve? The addition of the profile photo is a case by case basis. Since the base application doesn't use it, I don't think that it should be included.

**Comment by rainings** [comment]
@codydaig  all right, got it. just close it. Thank you

**Comment by codydaig** [comment]
@lirantal @ilanbiala Go ahead and close.
