### ISSUE TITLE
Change jshintrc latedef to exclude function definitions

### ISSUE THREAD

**Issue by trainerbill** [meanjs/mean#912]
Can we change to

"latedef": "nofunc"

to allow us to follow the john papa style guide and allow function definitions to be defined later?

**Comment by ilanbiala** [comment]
@trainerbill how is that better and not as confusing? The point of us referring to John Papa's style guide isn't just to blindly follow it but to do what we also think makes sense. You have to justify a better reason than it being in someone else's style guide. I'm not opposed to changes, but there needs to be evidence behind why it would be better.

**Comment by trainerbill** [comment]
@ilanbiala I meant to have this as a discussion.  If we are going to follow that style guide then this jshint rule needs to change.  I had to change it in my project so I figured I would bring it up for discussion here.  That is all.  My only point is that we reference this style guide and so we should probably be able to support writing code that validates against it.  Yes, they can google and find the fix and add the exclusion themselves, but is that what we really want to do?  Can you provide any evidence on why it would not be better?

If anything hopefully this thread will help someone looking for the answer in the future.

**Comment by ilanbiala** [comment]
@trainerbill isn't it more confusing to have a function defined after it's used when you are reading over someone else's code? Also, as I mentioned in another issue, the style guide isn't strictly our rulebook, it's a guide. If that's unclear, feel free to submit a PR with a style guide doc and we'll publicly provide our own rules.

**Comment by trainerbill** [comment]
@ilanbiala Well I support using john papas style guide as a rulebook.  It leaves out any gray areas and gives us something to reference when code does not meet requirements.  Obviously you are against it, so as Owner of the project maybe you should put together a style guide that collaborators should stick to.  I am fine with using our own style guide, but it needs to be defined.  Otherwise we end up arguing over everything and PR's take forever in the review process.

**Comment by codydaig** [comment]
@ilanbiala I'm completley in favor on John Papa's style guide. The only rule I don't like in the style guide is IIFEs. But if we need to keep them for ease of understanding and usability, let's just leave them in.

**Comment by mleanos** [comment]
I think using John Papa's style guide is important. However, we should not strictly adhere to everything he suggests. Rather we should look at the benefit of a specific suggestion, and weigh it against how well it fits into this project. For me, the use of IIFE's is clearly outside the bounds of this project's current implementation. That's one example of something we don't *need* to follow.

As for the `latedef` setting, I think we should use this. Allowing us to use a function before it is declared, makes the code a lot more readable. If we only took one aspect of the John Papa style guide, I'd vote for this one. 

He explains it pretty well here..
https://github.com/johnpapa/angular-styleguide#style-y034
https://github.com/johnpapa/angular-styleguide#style-y035
http://www.johnpapa.net/angular-function-declarations-function-expressions-and-readable-code/

I've included this in my project & it's been a life-saver. My code feels much more serene.

**Comment by codydaig** [comment]
Here's an example of a project that I'm currently working on. We've addapted the John Papa style guide almost to the T, except for IIFEs. https://github.com/nobsjs/nobsjs

**Comment by mleanos** [comment]
I took Cody's lead & have been converting my server controllers to adhere to this style as well. Working with promises is a lot cleaner & more straightforward; the code is a lot easier to read/manage.

**Comment by lirantal** [comment]
@trainerbill am I missing something? current jshint is already set to ` "latedef": "nofunc"`: 
https://github.com/meanjs/mean/blob/master/.jshintrc#L10

**Comment by mleanos** [comment]
@lirantal That's a good point :)

**Comment by trainerbill** [comment]
@lirantal haha.  Yeah it is...  I cloned down right after 0.4.0 when it was not.  Didn't look at recent master.  my bad.
