### ISSUE TITLE
node 4.0 is publish，will be Influence mean project?

### ISSUE THREAD

**Issue by xiaoyang2022** [meanjs/mean#913]
node 4.0 is publish，will be Influence mean project?

**Comment by codydaig** [comment]
@xiaoyang2022 Currently the mean project does not support Node 4.0. But we hope to work towards supporting it in the future! If you want to help, feel free!

**Comment by xiaoyang2022** [comment]
thanks ,very much!

**Comment by lirantal** [comment]
@xiaoyang2022 you can follow up on the build status for node v4 on travis-ci here: https://travis-ci.org/meanjs/mean

We will add the v4 support to travis in a couple of days and you can see it there on the main page.

**Comment by xiaoyang2022** [comment]
thanks, in the /mean/modules/core/client/app/ 's files,i tink put it into /config/lib/ 's  will be better  ?
