### ISSUE TITLE
this file would be input under "mean/config/lib/ " will be better?

### ISSUE THREAD

**Issue by xiaoyang2022** [meanjs/mean#914]
mean/modules/core/client/app/ ,this file would be input under "mean/config/lib/ " will be better?

If you can, how to do?Can you help me!

**Comment by xiaoyang2022** [comment]
if the angular project is more modules,will be more clear in the framework

**Comment by codydaig** [comment]
@xiaoyang2022 Sorry for the delay, did you figure this out or does this still need to be addressed?
