### ISSUE TITLE
Missing angular js files in lib

### ISSUE THREAD

**Issue by AswathyRaju** [meanjs/mean#919]
Hi,

I have done a gilt clone , git clone https://github.com/meanjs/mean.git meanjs , ( v : 0.4.1)
but the  sample application is not working. Missing angular js files in lib folder.

Is there any maintenance work is going on ? or I have to do anything else to run the application ?

Please help me.

Thanks

**Comment by simison** [comment]
Did you run `npm install` and did that then run `bower install` at the end of it?
