### ISSUE TITLE
RESTful API tests

### ISSUE THREAD

**Issue by s-oravec** [meanjs/mean#92]
I would like to see out of box support for RESTful API tests.
Currently it isn't possible without some initial hacking as express is initialized asynchronously and session store is not ready yet when the tests start (or maybe it is my lack of js coding skills ;)) or by running mocha tests in separate grunt task.

**Comment by FREEZX** [comment]
Can we get a generator for this in https://github.com/meanjs/generator-meanjs/ ?

**Comment by FREEZX** [comment]
Added in my fork: https://github.com/FREEZX/generator-meanjs/blob/master/express-test/templates/_.server.routes.test.js
