### ISSUE TITLE
Allow for session.secret to be read from local env config

### ISSUE THREAD

**Issue by jloveland** [meanjs/mean#926]
enhancement: put the `sessionSecret` as a `local.js` env config so we can configure it without accidentally committing to code.
`sessionSecret: process.env.SESSION_SECRET || 'MEAN',`
https://github.com/meanjs/mean/blob/master/config/env/default.js#L25

**Comment by codydaig** [comment]
@jloveland Seems like this was resolved wth #927. If not, feel free to reopen! :-D
