### ISSUE TITLE
Protractor issue (App Already Bootstrapped with this Element 'document')

### ISSUE THREAD

**Issue by naando-araujo** [meanjs/mean#930]
I'm trying to integrate protractor in a stack.
Have someone faced this error while testing?

"App Already Bootstrapped with this Element 'document'"

It happens when the ui-router states changes during the tests.
If I test "/" and "#!/a" it's ok, but if then I go to "#!/b" crashes.

So I research and found out ```browser.ignoreSynchronization = true;``` to mask this error in protractor config, but it's messing my tests when change between ui-router states.

Thanks!

**Comment by codydaig** [comment]
@jloveland Has this been resolved with the latest changes?

**Comment by jloveland** [comment]
@codydaig and @naando-araujo I think we can close this.

**Comment by lirantal** [comment]
@naando-araujo any comments?

**Comment by naando-araujo** [comment]
I discovered an approach, just use ```beforeEach(function() { browser.get(''); });```. Using this I resolved the error, I just don't know if it's the best way.

BTW I asked here:
 - http://stackoverflow.com/q/32722948/2913704

Thanks

**Comment by codydaig** [comment]
@naando-araujo Have you checkout the latest changes that were made to the protractor tests in the master branch by @jloveland? I'm not quite sure what the issues are getting mean, but that may be a great place to start.

**Comment by naando-araujo** [comment]
@codydaig and @jloveland I agree, we can close it. I finish my tasks on that project, it was started over 3 months so I guess it was used with the first release and nowadays (probably already resolved) so
I would start at the master branch, as you said.
I'll try to checkout as soon as possible. Thanks!
