### ISSUE TITLE
Node-pre-gyp package?

### ISSUE THREAD

**Issue by ilanbiala** [meanjs/mean#938]
@lirantal Where are we using the node-pre-gyp package?

**Comment by lirantal** [comment]
@ilanbiala maybe you should ask Cody:
```bash
5d5d1b7b (Cody Daig       2015-07-17 01:09:08 -0700  50)     "node-pre-gyp": "0.6.4",
```

**Comment by ilanbiala** [comment]
@codydaig do you know what the node-pre-gyp package is doing? I don't see it being required anywhere.

**Comment by simison** [comment]
Running `npm ls` shows it being required in a couple of places, notably:

```
├─┬ connect-mongo@0.8.1
│ ├─┬ debug@2.2.0
│ │ └── ms@0.7.1
│ ├── depd@1.0.1
│ └─┬ mongodb@2.0.31
│   ├─┬ mongodb-core@1.1.26
│   │ ├─┬ bson@0.3.2
│   │ │ └─┬ bson-ext@0.1.6
│   │ │   ├── nan@1.8.4
│   │ │   └─┬ node-pre-gyp@0.6.4
```

**Comment by ilanbiala** [comment]
@simison that's fine that it is depended on, but there is no reason to have it as a top level dependency of our app.

**Comment by codydaig** [comment]
@ilanbiala Sorry for the delay. That came a PR I did to get rid of the npm warnings for the future upgrade of npm 3. It had something to do with dependency resolution.

**Comment by ilanbiala** [comment]
It's not used anywhere though, do you remember the PR?

**Comment by lirantal** [comment]
@ilanbiala just submit a PR to remove it and we'll see if it fails or not in the CI :)

**Comment by ilanbiala** [comment]
#1001
