### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by devypt** [meanjs/mean#945]
in the documentation http://meanjs.org/docs/0.4.x/#troubleshooting it's saying 

`git checkout 0.4.0`

which should be 

`git checkout v0.4.0`

**Comment by codydaig** [comment]
@devypt Do you want to submit a PR for this?

**Comment by devypt** [comment]
@codydaig  yes

**Comment by devypt** [comment]
@codydaig where is the docs repo?

**Comment by codydaig** [comment]
@devypt It's the gh-pages branch of this repo.
