### ISSUE TITLE
Build Error at `npm install`. Issue with node installed via nvm (node version manager)?

### ISSUE THREAD

**Issue by cdnadmin** [meanjs/mean#946]
Does meanjs not work when node is installed via NVM (Node Version Manager)?  

Tried w/node versions 0.12.0 and 4.1.1 via (NPM) and respective npm versions 2.5.1 and 3.3.4.

I cloned meanjs v0.3.3 (`git clone --depth 1 --origin meanorigin  --branch v0.3.3 https://github.com/meanjs/mean.git .`) and and did an `npm install`, failed with this: 

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 69
gyp ERR! stack     at ChildProcess.onExit (/Users/collaborare/.nvm/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/collaborare/.nvm/v4.1.1/bin/node" "/Users/collaborare/.nvm/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users/collaborare/monico/work/source/wbe/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node" "--module_name=debug" "--module_path=/Users/collaborare/monico/work/source/wbe/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64"
gyp ERR! cwd /Users/collaborare/monico/work/source/wbe/node_modules/v8-debug
gyp ERR! node -v v4.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/collaborare/.nvm/v4.1.1/bin/node /Users/collaborare/.nvm/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/collaborare/monico/work/source/wbe/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/collaborare/monico/work/source/wbe/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/collaborare/monico/work/source/wbe/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:87:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:817:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
node-pre-gyp ERR! System Darwin 14.5.0
node-pre-gyp ERR! command "/Users/collaborare/.nvm/v4.1.1/bin/node" "/Users/collaborare/monico/work/source/wbe/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/collaborare/monico/work/source/wbe/node_modules/v8-debug
node-pre-gyp ERR! node -v v4.1.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.11
node-pre-gyp ERR! not ok 
Failed to execute '/Users/collaborare/.nvm/v4.1.1/bin/node /Users/collaborare/.nvm/v4.1.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/collaborare/monico/work/source/wbe/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64/debug.node --module_name=debug --module_path=/Users/collaborare/monico/work/source/wbe/node_modules/v8-debug/build/debug/v0.4.6/node-v46-darwin-x64' (1)

**Comment by codydaig** [comment]
I use Node via nvm, so I know it's not an issue with that. and we don't have a 0.3.3 branch.

**Comment by cdnadmin** [comment]
Thx, @codydaig.  Incidentally, also tried it with latest out there --> v0.4.1.

**Comment by cdnadmin** [comment]
File for above comment...and for thoroughness of issue description.

[Terminal Saved Output.txt | uploaded via ZenHub](https://files.zenhub.io/560bb9b2d7a4f68e2d4f0b0a)

**Comment by cdnadmin** [comment]
Tried by nvm installing v0.12.7 (latest of v0.12.x), per these lines in the error output:

`gyp ERR! node -v v0.12.0`
`gyp ERR! node-gyp -v v1.0.2`
`gyp ERR! not ok`

...to no avail...same error.

**Comment by cdnadmin** [comment]
Got past above error by referencing this [npm issue](https://github.com/npm/npm/issues/3932).  Basically, it's an issue with current (Sept 2015) updates to xcode.  Have to `sudo xcodebuild -license` then 'agree' to it at the command line, per @inexplicable 's instructions.

Buuut, now we get a `Error: 'make' failed with exit code: 2`  See attached file. 

[TerminalOutput.MakeErrorCode2.txt | uploaded via ZenHub](https://files.zenhub.io/560bc1acd7a4f68e2d4f0b46)

**Comment by codydaig** [comment]
@cdnadmin Glad you got it working!
