### ISSUE TITLE
404 error on Generator Repo link

### ISSUE THREAD

**Issue by dfdumaresq** [meanjs/mean#952]
On http://meanjs.org/docs.html#getting-started the link to Generator Repo is wrong. The issue is also on the 0.4.1 documentation page: http://meanjs.org/docs/0.4.x/#getting-started

<p>The generator is still in development. See the <a href="https://github.com/meanjs/generator-meanjs/tree/0.4-dev">Generator Repo</a> for information on how to use the development version.
  </p>

Thanks,
Dave

**Comment by codydaig** [comment]
https://github.com/meanjs/mean/blob/gh-pages/_includes/docs/0.4.x/gettingstarted.html#L42
