### ISSUE TITLE
Documentation mistake

### ISSUE THREAD

**Issue by devypt** [meanjs/mean#953]
version number is wrong in the download link which cause 404

this 

`$ wget https://github.com/meanjs/mean/archive/0.4.0.zip -O meanjs.zip; unzip meanjs.zip; rm meanjs.zip`

should be 

`$ wget https://github.com/meanjs/mean/archive/v0.4.0.zip -O meanjs.zip; unzip meanjs.zip; rm meanjs.zip`

I will submit pull request for it.

**Comment by lirantal** [comment]
Correct, thanks please do.

**Comment by lirantal** [comment]
Thanks @devypt I've created a PR for it.
