### ISSUE TITLE
[solved] remove Article Error

### ISSUE THREAD

**Issue by Meistercoach83** [meanjs/mean#958]
Hi,
I´m using a not modified version (current stable). When I click on the delete button for one article, all my articles are deleted. The request sent to the server is looking ok: 
DELETE /api/articles/560cd6624a69c22833f25918 200

where can i search for occuring errors?

**Comment by mleanos** [comment]
@Meistercoach83 I can't reproduce this issue on the master branch. Can you check to see what version of the project you're running?

Does your package.json file have this setting? 
https://github.com/meanjs/mean/blob/master/package.json#L5

If not, then is this the "current stable" version that you're referring to?
https://github.com/meanjs/mean/releases/tag/v0.3.3

**Comment by Meistercoach83** [comment]
Hi,

yes - there´s a line with "meanjs-version": "0.4.1" in package.json

**Comment by mleanos** [comment]
I'm not experiencing that behavior. Could there be other contributing factors? 

And the articles code hasn't been modified at all? What browser are you using? 

Also, could you provide screen shots, and/or the contents of your articles server/client controller?

**Comment by Meistercoach83** [comment]
It´s the current Firefox in version 41.0.1. 
I downloaded the zip from master branch again manually => same problem

**Comment by mleanos** [comment]
I just updated my Firefox to 41.0.1. And still I can't reproduce. There has to be some other factor involved. 

Are you experiencing any other database issues? Any problems with Chat, or user profile updates?

**Comment by Meistercoach83** [comment]
Could there be sth. wrong with my versions of node / mongodb?

By the way. A grunt:test gets me an error with logout:

    User CRUD tests should be able to login successfully and logout successfully:

      Uncaught AssertionError: expected 'Found. Redirecting to /' to be 'Moved Temporarily. Redirecting to /'
      + expected - actual
      +"Moved Temporarily. Redirecting to /"
      -"Found. Redirecting to /"
      ......
      at Test.<anonymous> (/modules/users/tests/server/user.server.routes.tests.js:98:36)

**Comment by mleanos** [comment]
I can't think of anything that could cause that type of behavior. Everything else seems to be behaving correctly?

Out of curiosity, what versions of node, npm, and mongodb do you have installed?

**Comment by simison** [comment]
Old Mongo could indeed cause such errors. A friend had issues with MeanJS and Mongo 2.2 (rather old).

**Comment by Meistercoach83** [comment]
my versions:
mongodb: 3.0.6
node: 0.12.7
npm : 2.11.3

**Comment by simison** [comment]
Did anyone test this with new Mongo before? @ilanbiala @mleanos @rhutchison @lirantal @codydaig 

It _should_ be just a drop in replacement...

**Comment by Meistercoach83** [comment]
I dropped my complete vm and reinstalled everything. now it seems to work. I don´t know why. but issue can be closed

**Comment by mleanos** [comment]
I'm using mongodb 3.0.6 as well.

**Comment by codydaig** [comment]
@Meistercoach83 Glad you got it figured out!

@ilanbiala Can we close?

**Comment by lirantal** [comment]
@Meistercoach83 keep a close eye and let us know if this happens again.

**Comment by codydaig** [comment]
@simison I'm using mongo version 3.0.5
