### ISSUE TITLE
Using socket from controllers in mean 3.0

### ISSUE THREAD

**Issue by karan-kapoor90** [meanjs/mean#963]
We've been working on quite a big project using mean 3.0 as the base now and I picked up the socket functionality from an intermediate 4.0 code and brought it into our 3.0 with the entire globbing mechanism. 
Is there a way I can use socket to send out notifications from my controllers? Something that maybe includes configuring socket with app such that I can just require it in any controller and just use it?

I know this is kind of abstract but I'm really in the dark here.

**Comment by ilanbiala** [comment]
@karan-kapoor90 this question is better suited on another forum. GitHub is appropriate for feature requests, bug fixes, etc. but not help as we cannot help the whole community. If you still haven't had any luck after asking around, come back with whatever progress you have made and we'll try to help.

**Comment by karan-kapoor90** [comment]
I understand that @ilanbiala but this is really urgent for me which is why I posted it here directly. I understand thats not how questions are taken up here, but if you do have any clue on how it can be done, it'll be much appreciated.

**Comment by mleanos** [comment]
@karan-kapoor90 I've worked quite a bit with socket.io in my own app based off the 0.4.0 version. I'm on Gitter if you'd like to talk about it there.

**Comment by karan-kapoor90** [comment]
Found a solution at https://vexxhost.com/resources/tutorials/mean-socket-io-integration-tutorial/ :)

**Comment by karan-kapoor90** [comment]
Thanks for offering @mleanos

**Comment by GPnow** [comment]
@mleanos @karan-kapoor90   I am porting my app from 3.0 to 4.0 ,where i used it in my controllers,like
        var socketio = req.app.get('socketio');
and then  in the CRUD functions like socketio.sockets.emit(id,message);
If you offer a similar solutions,it will save a lot of time for me,thanks in advance.
