### ISSUE TITLE
Sub-generators not working, always trying to scaffold a new app

### ISSUE THREAD

**Issue by ClaasM** [meanjs/mean#970]
Using Windows 8.1. Its the same with other sub-generators. Why could that be?

![image](https://cloud.githubusercontent.com/assets/9898462/10351295/176992cc-6d49-11e5-924c-7fafe1ab99c2.png)

**Comment by mleanos** [comment]
@ClaasM Currently, the sub-generators do not work for the newest meanjs version. The sub-generators are being worked on at the moment. The easiest way to add a new module, is by adding the files & folders manually.

https://github.com/meanjs/generator-meanjs/blob/master/README.md#application-generator
Read the bottom of that section.

**Comment by ClaasM** [comment]
Thanks for the info, you may want to add that in the docs on meanjs.org.
