### ISSUE TITLE
forgot-password | Server hits error "ECONNREFUSED" (500)

### ISSUE THREAD

**Issue by aviadhahami** [meanjs/mean#976]
Hey,
For some reason I can not use the "forgot password" functionality.

In order to test it I've generated couple of MEAN projects via `yo` and in all of them (and doesn't matter where they run) one can not use the "Forgot Password" section.
From my debug I've realized it has to do with the `nodemailer` usage at line *68* on `users.password.server.controller.js` .

The server returns the following error 
`Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
POST /auth/forgot 500 29.845 ms - -
`

Any idea on what's going on or how to solve ?
I ran into this since I have users reporting this on one of my projects.

Thanks !

**Comment by codydaig** [comment]
@aviadhahami My initial thoughts are telling me that you don't have a mail transporter set-up properly.

**Comment by mleanos** [comment]
@aviadhahami I'm not having any issues with this feature on the *master* branch. My guess is the same as Cody's. Do you have the `mailer` settings set for the environment the app is running in?

**Comment by aviadhahami** [comment]
Hey guys,
Thanks for the quick response.
Will dig into `mailer` later on today and post update

**Comment by aviadhahami** [comment]
Ok guys, solved it.

Issue was indeed with the mailer config. thx !
