### ISSUE TITLE
XMLHttpRequest cannot load error on accessing MEAN.js API through IONIC app

### ISSUE THREAD

**Issue by vrohitk** [meanjs/mean#977]
I am developing an ionic application, trying to access API of MEAN.JS application which is as below which is a link to encoded JSON

https://damp-dawn-2579.herokuapp.com/api/foods
The factory service of my application accesses the above link but gets an error

XMLHttpRequest cannot load http://localhost:3000/api/foods. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8100' is therefore not allowed access.
Factory Service

.factory('Foods', ['$resource',
  function($resource) {
    return $resource('https://damp-dawn-2579.herokuapp.com/api/foods/:foodId', { foodId: '@_id'
    }, {
      update: {
        method: 'PUT'
      }
    });
  }
])
How do i overcome this? Thank you

**Comment by codydaig** [comment]
You need to enable cors. 
https://www.npmjs.com/package/cors
