### ISSUE TITLE
Moving gh-pages to own repo

### ISSUE THREAD

**Issue by codydaig** [meanjs/mean#992]
@lirantal @ilanbiala 

Could we move the gh-pages branch to it's own repo `meanjs.github.io` to make it easier to work on and submit PRs? It's pretty hidden where it's at now.

**Comment by ilanbiala** [comment]
I like the idea, but I think having docs updates will be harder since it's in a different repo and keeping track of 2 PRs on different repos will be tougher. Any thoughts on that?

**Comment by codydaig** [comment]
@ilanbiala I think it will be easier for people to submit PRs, but I also see your point keeping track of PRs on two different repos. However, the generator does are buried in the gh-pages repo of the mean project which was my biggest reasoning for suggesting to move it. 

I hosted an open source hackathon today and that was the piece of feedback that I received that the docs for the generator are hard to find.

**Comment by ilanbiala** [comment]
@codydaig let's get some more feedback on it, because I'm not opposed to it, but I don't want the docs to take a step back because they end up in a separate repo.

**Comment by lirantal** [comment]
@codydaig what do you mean by the docs are hard to find?
It's quite common that repositories have gh-pages branch for documentation.

Maybe we should make it more obvious in the website docs or in the wiki/README of where to find the docs and how to work with them? That seems like a much easier approach.

**Comment by codydaig** [comment]
@lirantal The issue they had was they were looking for a gh-pages branch in the generator, which doesn't exist. There's just the gh-pages in the mean repo. I'm fine with either, I just figured I'd bring it up too see what other people's thought were. If stick to the same method, we need to put something about where the docs are located in the generator repo `readme.md`.

**Comment by lirantal** [comment]
In this case I think a much quicker and easier approach is simply to make the information more available if it is through the README or on the main sections of the website itself.
Moving around repos and all that just seems some overhead that we don't want to start focusing on.

**Comment by codydaig** [comment]
Fair. I'll find a way to make that more clear and submit a PR. 

@ilanbiala @lirantal Thanks for the feedback! :-D

**Comment by lirantal** [comment]
Welcome :)

**Comment by codydaig** [comment]
@lirantal @ilanbiala Can one of you guys create a repo meanjs.github.io for me too move the documentation over too?

**Comment by lirantal** [comment]
@codydaig do we want to call the repo meanjs? or be more specific?
currently these are the existing repositories under meanjs organization: https://github.com/meanjs

**Comment by codydaig** [comment]
the repo should be called `meanjs.github.io` That's the common practice and preferred method of creating a github pages website for an organization.

**Comment by lirantal** [comment]
Got it.
Have fun: https://github.com/meanjs/meanjs.github.io

**Comment by codydaig** [comment]
@lirantal Thanks!

**Comment by ilanbiala** [comment]
@codydaig @lirantal has everything been moved? If so, can we make whatever else changes regarding Heroku that are necessary so we can delete gh-pages from this repo?

**Comment by codydaig** [comment]
@ilanbiala Everything has been moved. The new repo is live on github pages. I believe that it is safe to delete the gh-pages branch from this (meanjs/mean) repo. I made a small change to the docs (the updated date) only in the other meanjs.github.io repo and that change is displayed on the website.

**Comment by codydaig** [comment]
We're using github pages, not heroku.

**Comment by ilanbiala** [comment]
Yeah I noticed the gh-pages is up, so we should be good. @lirantal any reason not to?

**Comment by lirantal** [comment]
yep, @codydaig go for it.
